SSAnne_2F_Room5_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room5_EventScript_Gentleman::
	msgbox SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone, MSGBOX_NPC
	end

SSAnne_2F_Room5_EventScript_LittleBoy::
	msgbox SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
	.string "Du kannst den PC in der Ecke dort\n"
	.string "drüben benutzen!\p"
	.string "Darauf hat man mich am Empfang\n"
	.string "freundlicherweise hingewiesen.$"

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
	.string "Im POKéMON-CENTER kannst du müde,\n"
	.string "verletzte und besiegte POKéMON\l"
	.string "heilen!$"

