SSAnne_2F_Room5_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room5_EventScript_Gentleman::
	msgbox SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone, MSGBOX_NPC
	end

SSAnne_2F_Room5_EventScript_LittleBoy::
	msgbox SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
	.string "Hast du die Safari-Zone in\n"
	.string "FUCHSANIA City schon besucht?\p"
	.string "Es gibt dort sehr seltene Pokémon!$"

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
	.string "Mein Papa war mit mir in der\n"
	.string "SAFARI-Zone! Es war aufregend!$"

