SafariZone_North_Frlg_MapScripts::
	.byte 0

SafariZone_North_EventScript_RestHouseSign::
	msgbox SafariZone_North_Text_RestHouse, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips1::
	msgbox SafariZone_North_Text_SecretHouseStillAhead, MSGBOX_SIGN
	end

SafariZone_North_EventScript_AreaSign::
	msgbox SafariZone_North_Text_Area2, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips2::
	msgbox SafariZone_North_Text_ZigzagThroughTallGrass, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips3::
	msgbox SafariZone_North_Text_WinFreeHMFindSecretHouse, MSGBOX_SIGN
	end

SafariZone_North_Text_RestHouse::
	.string "RASTHAUS$"

SafariZone_North_Text_SecretHouseStillAhead::
	.string "TIPPS FÜR TRAINER\p"
	.string "Bis zum GEHEIMEN HAUS ist es nicht\n"
	.string "mehr weit!$"

SafariZone_North_Text_Area2::
	.string "AREAL 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
	.string "TIPPS FÜR TRAINER\p"
	.string "POKéMON verstecken sich in hohem\n"
	.string "Gras!\p"
	.string "Laufe durch das hohe Gras und\n"
	.string "scheuche sie auf!$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
	.string "TIPPS FÜR TRAINER\p"
	.string "Finde das GEHEIME HAUS.\n"
	.string "Dann gewinnst du eine VM!$"

