SafariZone_North_Frlg_MapScripts::
	.byte 0

SafariZone_North_EventScript_RestHouseSign::
	msgbox SafariZone_North_Text_RestHouse, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips1::
	msgbox SafariZone_North_Text_SecretHouseStillAhead, MSGBOX_SIGN
	end

SafariZone_North_EventScript_AreaSign::
	msgbox SafariZone_North_Text_Area2, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips2::
	msgbox SafariZone_North_Text_ZigzagThroughTallGrass, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips3::
	msgbox SafariZone_North_Text_WinFreeHMFindSecretHouse, MSGBOX_SIGN
	end

SafariZone_North_Text_RestHouse::
	.string "Rasthaus$"

SafariZone_North_Text_SecretHouseStillAhead::
	.string "Tipps für Trainer\p"
	.string "Bis zum Geheimen Haus ist es nicht\n"
	.string "mehr weit!$"

SafariZone_North_Text_Area2::
	.string "Areal 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
	.string "Tipps für Trainer\p"
	.string "Pokémon verstecken sich in hohem\n"
	.string "Gras!\p"
	.string "Laufe durch das hohe Gras und\n"
	.string "scheuche sie auf!$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
	.string "Tipps für Trainer\p"
	.string "Finde das Geheime Haus.\n"
	.string "Dann gewinnst du eine VM!$"

