BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "Was braucht ein Trainer?\p"
	.string "Kenntnis… Strategie…\l"
	.string "Ein glückliches Los…\l"
	.string "Einen groben Überblick…\l"
	.string "Seele…\l"
	.string "Bravur…\l"
	.string "Und eine gute Anlage…\p"
	.string "Nun, das bringe ich alles mit!\n"
	.string "Ich werde überall einfach unschlagbar\l"
	.string "sein!\p"
	.string "Was? Pokémon?!?\n"
	.string "Was ist das denn? Kann man das essen?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Hast du schon mal was über die\n"
	.string "Kampfkoryphäen gehört?\p"
	.string "So nennt Scott die sieben Trainer,\n"
	.string "die die sieben Einrichtungen der\l"
	.string "Kampfzone leiten.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "Im Duellturm hat mir ein älteres\n"
	.string "Mädchen gesagt, dass ich sehr viel\l"
	.string "Talent für’s Kämpfen habe!\p"
	.string "Ich mag aber lieber Pokémon\n"
	.string "Wettbewerbe!\p"
	.string "Aber bei den Wettbewerben schneide\n"
	.string "ich nie so sonderlich gut ab.\p"
	.string "Ob man auch für etwas Talent haben\n"
	.string "kann, obwohl man was anderes lieber\l"
	.string "mag?$"

