SaffronCity_Mart_hns_MapScripts::
	.byte 0

SafronMart_EventScript_CooltrainerM::
	msgbox SaffronMart_Text_CooltrainerM, MSGBOX_NPC
	end
SafronMart_EventScript_CooltrainerF::
	msgbox SaffronMart_Text_CooltrainerF, MSGBOX_NPC
	end
SaffronMart_Text_CooltrainerM:
	.string "In LAVANDIA ist ein großer RADIOTURM.$"

SaffronMart_Text_CooltrainerF:
	.string "Ich will stärker werden, aber\n"
	.string "es klappt nicht so richtig…\p"
	.string "Könntest du mir nicht ein paar\n"
	.string "Tricks und Kniffe zeigen?$"
