SevenIsland_TanobyRuins_Frlg_MapScripts::
	.byte 0

SevenIsland_TanobyRuins_Text_BrandonIntro::
	.string "Weißt du irgendetwas über diese\n"
	.string "Steinkammer?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
	.string "Das war überraschend. Du\n"
	.string "hättest nicht so grob sein müssen.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
	.string "Die Tanibo-ruinen sind mindestens\n"
	.string "1500 Jahre alt.\p"
	.string "Aber zunächst ist es ein Geheimnis,\n"
	.string "warum sie überhaupt gebaut wurden.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
	.string "Man sagt, dass hier ein mystisches\n"
	.string "Pokémon schlafen soll.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
	.string "Ich bin nicht gut beim Kämpfen.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
	.string "Ich habe gehört, dass es noch\n"
	.string "andere Ruinen wie diese geben\l"
	.string "soll.\l"
	.string "Vielleicht sind sie die Ruhestätten\l"
	.string "anderer, mystischer Pokémon.$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
	.string "Tom bringt mir das Malen bei!$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
	.string "Wir könnten Ärger bekommen, wenn\n"
	.string "wir hier so viel Lärm machen.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
	.string "Ich sagte, dass ich ein altes\n"
	.string "Gebäude malen wollte.\p"
	.string "Also hat Tom mich hierher\n"
	.string "gebracht.$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
	.string "Heute hat er mir im Anschluss an\n"
	.string "die Unterrichtsstunde die Kammer\l"
	.string "gezeigt.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
	.string "Oh, wie außergewöhnlich.$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
	.string "Ah, du studierst also ganz alleine\n"
	.string "Pokémon…\p"
	.string "Ja, du bist wirklich eine außer-\n"
	.string "ordentliche Persönlichkeit.$"
