OneIsland_House1_Frlg_MapScripts::
	.byte 0

OneIsland_House1_EventScript_OldMan::
	msgbox OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays, MSGBOX_NPC
	end

OneIsland_House1_EventScript_OldWoman::
	msgbox OneIsland_House1_Text_LastTimeMtEmberErupted, MSGBOX_NPC
	end

OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays::
	.string "Die diamantförmigen Felder sind\n"
	.string "Teleporter!\p"
	.string "Eine Art Hi-Tech-Transportsystem!$"

OneIsland_House1_Text_LastTimeMtEmberErupted::
	.string "Die SILPH CO. und das TEAM ROCKET\n"
	.string "werden demnächst fusionieren!$"

