OneIsland_House1_Frlg_MapScripts::
	.byte 0

OneIsland_House1_EventScript_OldMan::
	msgbox OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays, MSGBOX_NPC
	end

OneIsland_House1_EventScript_OldWoman::
	msgbox OneIsland_House1_Text_LastTimeMtEmberErupted, MSGBOX_NPC
	end

OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays::
	.string "Wenn die Sonne scheint,\n"
	.string "gehe ich hinaus und betrachte\l"
	.string "den Vulkan!\l"
	.string "Das ist meine tägliche Routine!$"

OneIsland_House1_Text_LastTimeMtEmberErupted::
	.string "Lass mich nachdenken…\n"
	.string "Wann ist der Glutberg zum\l"
	.string "letzten Mal ausgebrochen?$"

