BlackthornCity_Mart_hns_MapScripts::
	.byte 0

BlackthornMart_EventScript_CoolTrainerM::
	msgbox BlackthornMart_Text_CooltrainerM, MSGBOX_NPC
	end

BlackthornMart_EventScript_BlackBelt::
	msgbox BlackthornMart_Text_BlackBelt, MSGBOX_NPC
	end

BlackthornMart_Text_CooltrainerM:
	.string "Top-Beleber füllt die KP bewusstloser\n"
	.string "Pokémon wieder vollständig auf.\l"
	.string "Im Pokémon-Supermarkt gibt es sie\l"
	.string "aber leider nicht zu kaufen…\p"
	.string "Oh, und Vorsicht! Die AP des jeweiligen\n"
	.string "Pokémon werden von Top-Beleber\l"
	.string "nicht mit aufgefüllt!$"

BlackthornMart_Text_BlackBelt:
	.string "Top-Schutz hält dir schwache Pokémon\n"
	.string "vom Leib.\p"
	.string "Von allen Schutzsprays hält die Wirkung\n"
	.string "von Top-Schutz am längsten an.$"
