PewterCity_Mart_hns_MapScripts::
	.byte 0

PewterCity_Mart_EventScript_Youngster::
	msgbox PewterCity_Mart_Text_Youngster, MSGBOX_NPC
	end

PewterCity_Mart_EventScript_Nerd::
	msgbox PewterCity_Mart_Text_SuperNerd, MSGBOX_NPC
	end

PewterCity_Mart_Text_Youngster:
	.string "Hi! Mach doch Bekanntschaft\n"
	.string "mit meinem Garados!\p"
	.string "Ich habe es als Karpador\n"
	.string "aufgezogen. Kaum zu\l"
	.string "glauben, wie stark es geworden ist.$"

PewterCity_Mart_Text_SuperNerd:
	.string "Es gab mal einen\n"
	.string "komischen, alten Mann, der Karpador\l"
	.string "verkaufte.\p"
	.string "Er sagte immer, die Karpador im\n"
	.string "See des Zorns seien außergewöhnlich.$"

