Route21_South_Frlg_MapScripts::
	.byte 0

Route21_South_Text_JackIntro::
	.string "Ich habe alle meine Pokémon auf\n"
	.string "See gefangen!$"

Route21_South_Text_JackDefeat::
	.string "Platsch!$"

Route21_South_Text_JackPostBattle::
	.string "Wo hast du deine Pokémon gefangen?$"

Route21_South_Text_JeromeIntro::
	.string "Ich nehme an einem Triathlon teil!$"

Route21_South_Text_JeromeDefeat::
	.string "Ächz, schnauf...$"

Route21_South_Text_JeromePostBattle::
	.string "Du hast gewonnen!\n"
	.string "Aber ich kann noch beim Marathon\l"
	.string "und im Radrennen siegen!$"

Route21_South_Text_RolandIntro::
	.string "Ahh!\n"
	.string "Genieße die Sonne und den Wind!$"

Route21_South_Text_RolandDefeat::
	.string "Ups!\n"
	.string "Ich hab verloren!$"

Route21_South_Text_RolandPostBattle::
	.string "Die Sonne hat mich wie ein\n"
	.string "Hähnchen geröstet!$"

Route21_South_Text_ClaudeIntro::
	.string "Heh, du verjagst die Fische!$"

Route21_South_Text_ClaudeDefeat::
	.string "Entschuldigung, ich wollte nicht so\n"
	.string "barsch sein!$"

Route21_South_Text_ClaudePostBattle::
	.string "Ich war nur sauer, weil ich noch\n"
	.string "nichts gefangen habe.$"

Route21_South_Text_NolanIntro::
	.string "Leiste mir Gesellschaft, bis etwas\n"
	.string "anbeißt!$"

Route21_South_Text_NolanDefeat::
	.string "Na ja, wenigstens ist etwas Zeit\n"
	.string "vergangen!$"

Route21_South_Text_NolanPostBattle::
	.string "Juchhu!\n"
	.string "Etwas hat angebissen!$"

Route21_North_Text_LilIntro::
	.string "Ewe: Häh? Ein Kampf? Tobi,\n"
	.string "schaffst du das nicht alleine?$"

Route21_North_Text_LilDefeat::
	.string "Ewe: Oh, na ja!\n"
	.string "Wir haben verloren. Zufrieden?$"

Route21_North_Text_LilPostBattle::
	.string "Ewe: Ich bin müde.\n"
	.string "Können wir nicht schon nach Hause?$"

Route21_North_Text_LilNotEnoughMons::
	.string "Ewe: Häh? Ein Kampf? Ich kann\n"
	.string "ihn nicht alleine bestreiten.\l"
	.string "Bring zwei Pokémon, o.k.?$"

Route21_North_Text_IanIntro::
	.string "Tobi: Meine Schwester trainiert\n"
	.string "nicht genug, daher habe ich sie\l"
	.string "gezwungen hierher zu kommen.$"

Route21_North_Text_IanDefeat::
	.string "Tobi: Argh, Schwesterherz!\n"
	.string "Bemüh dich doch!$"

Route21_North_Text_IanPostBattle::
	.string "Tobi: Komm schon, Schwesterlein!\p"
	.string "So wirst du nie Gewicht verlieren!$"

Route21_North_Text_IanNotEnoughMons::
	.string "Tobi: Wir verlangen einen Zwei-\n"
	.string "gegen-Zwei-Kampf. Bring doch zwei\l"
	.string "Pokémon mit!$"
