RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "Die Trainerschule ist hervorragend.\p"
	.string "Wenn du dort lernst, kannst du später\n"
	.string "sogar Arenaleiter werden.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "Felizia, die Arenaleiterin, weiß\n"
	.string "wirklich eine Menge über Pokémon.\p"
	.string "Und sie ist sehr stark!$"

