SafariZone_West_Frlg_MapScripts::
	.byte 0

SafariZone_West_EventScript_RestHouseSign::
	msgbox SafariZone_West_Text_RestHouse, MSGBOX_SIGN
	end

SafariZone_West_EventScript_LostTeethNotice::
	msgbox SafariZone_West_Text_PleaseFindWardensLostTeeth, MSGBOX_SIGN
	end

SafariZone_West_EventScript_TrainerTips::
	msgbox SafariZone_West_Text_SearchForSecretHouse, MSGBOX_SIGN
	end

SafariZone_West_EventScript_AreaSign::
	msgbox SafariZone_West_Text_AreaSign, MSGBOX_SIGN
	end

SafariZone_West_Text_RestHouse::
	.string "Rasthaus$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
	.string "Belohnung!\p"
	.string "Wer die Goldzähne des Parkwächters\n"
	.string "der Safari-Zone findet, erhält\l"
	.string "eine Belohnung!\p"
	.string "Finder melden sich bitte beim\n"
	.string "Parkwächter!$"

SafariZone_West_Text_SearchForSecretHouse::
	.string "Tipps für Trainer\p"
	.string "Erforsche die Safari-Zone!\n"
	.string "Finde das Geheime Haus!$"

SafariZone_West_Text_AreaSign::
	.string "Areal 3\n"
	.string "Osten: Zentrum$"

