CeladonCity_DepartmentStore_1F_Frlg_MapScripts::
	.byte 0

CeladonCity_DepartmentStore_1F_EventScript_Receptionist::
	msgbox CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_1F_EventScript_LayoutSign::
	msgbox CeladonCity_DepartmentStore_1F_Text_FloorDescriptions, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_1F_EventScript_FloorSign::
	msgbox CeladonCity_DepartmentStore_1F_Text_ServiceCounter, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
	.string "Willkommen im EINKAUFSZENTRUM von\n"
	.string "PRISMANIA CITY!\p"
	.string "Auf der Tafel rechts findest du\n"
	.string "eine Übersicht.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
	.string "EG: KUNDENINFORMATION\p"
	.string "1S: ZUBEHÖR FÜR TRAINER\p"
	.string "2S: VIDEOSPIELE-SHOP\p"
	.string "3S: GESCHENKARTIKEL\p"
	.string "4S: DROGERIE\p"
	.string "DACHGARTEN: AUTOMATEN$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
	.string "EG: KUNDENINFORMATION$"

