VermilionCity_Mart_hns_MapScripts::
	.byte 0

VermilionCity_Mart_EventScript_BirdMan::
	msgbox VermilionMart_Text_SuperNerd, MSGBOX_NPC
	end

VermilionCity_Mart_EventScript_Woman::
	msgbox VermilionMart_Text_Beauty, MSGBOX_NPC
	end

VermilionMart_Text_SuperNerd:
	.string "Team Rocket hat Kanto verlassen. Das\n"
	.string "allein ist schon ein Grund zum Feiern!$"

VermilionMart_Text_Beauty:
	.string "Ich habe vor, in\n"
	.string "SAFFRONIA CITY einkaufen zu gehen.$"
