SafariZone_West_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_West_RestHouse_EventScript_Man::
	msgbox SafariZone_West_Text_BaitMakesMonStickAround, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_Scientist::
	msgbox SafariZone_West_Text_RocksMakeMonRunButEasierCatch, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_CooltrainerF::
	msgbox SafariZone_West_Text_HikedLotsDidntSeeMonIWanted, MSGBOX_NPC
	end

SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
	.string "Die SAFARI-ZONE ist riesig, nicht?\p"
	.string "Der ARENALEITER von FUCHSANIA\n"
	.string "CITY, KOGA, hält hier gelegentlich\l"
	.string "Wache.\p"
	.string "Dank ihm können wir hier in\n"
	.string "Sicherheit spielen.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
	.string "Wenn auf dem PC eine POKéMON-BOX\n"
	.string "voll ist, wechsle einfach zu einer\l"
	.string "anderen BOX!$"

SafariZone_West_Text_BaitMakesMonStickAround::
	.string "Wenn du ihnen KÖDER zuwirfst,\n"
	.string "bleiben die POKéMON eher an\l"
	.string "einem Ort, da sie mit dem Fressen\l"
	.string "beschäftigt sind!$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
	.string "Die POKéMON eines TRAINERs sind\n"
	.string "stärker als wildlebende!$"

