Route8_Frlg_MapScripts::
	.byte 0

Route8_EventScript_UndergroundPathSign::
	msgbox Route8_Text_UndergroundPathSign, MSGBOX_SIGN
	end

Route8_Text_AidanIntro::
	.string "Du weißt viel über Pokémon!\n"
	.string "Doch wie sieht es mit Chemie aus?$"

Route8_Text_AidanDefeat::
	.string "Au!\n"
	.string "Eine Kernschmelze!$"

Route8_Text_AidanPostBattle::
	.string "Meine schulischen Leistungen sind\n"
	.string "besser!$"

Route8_Text_StanIntro::
	.string "O.k.!\n"
	.string "Die Spiele mögen beginnen!$"

Route8_Text_StanDefeat::
	.string "Knapp vorbei ist auch daneben!$"

Route8_Text_StanPostBattle::
	.string "Man kann nicht immer gewinnen!$"

Route8_Text_GlennIntro::
	.string "Um zu gewinnen, benötigst du eine\n"
	.string "gute Strategie!$"

Route8_Text_GlennDefeat::
	.string "Ich habe verloren!\n"
	.string "Das ist nicht logisch!$"

Route8_Text_GlennPostBattle::
	.string "SLEIMA kämpft als Erstes... und...\n"
	.string "und... dann...$"

Route8_Text_PaigeIntro::
	.string "Ich mag alle Nidoran sehr gerne!\n"
	.string "Deshalb sammle ich sie!$"

Route8_Text_PaigeDefeat::
	.string "Warum?\n"
	.string "Warum nur?$"

Route8_Text_PaigePostBattle::
	.string "Wenn Pokémon sich entwickeln,\n"
	.string "werden sie groß und hässlich! Sie\l"
	.string "sollten klein und goldig bleiben!$"

Route8_Text_LeslieIntro::
	.string "Die Schule macht Spaß! Pokémon zu\n"
	.string "trainieren aber auch!$"

Route8_Text_LeslieDefeat::
	.string "O.k., ich gehe lieber zur Schule!$"

Route8_Text_LesliePostBattle::
	.string "Wir sitzen hier fest, weil\n"
	.string "SAFFRONIA CITY abgeriegelt wird.$"

Route8_Text_AndreaIntro::
	.string "Mauzi ist so süß!\n"
	.string "Miau, miauz!$"

Route8_Text_AndreaDefeat::
	.string "Miauz!$"

Route8_Text_AndreaPostBattle::
	.string "Aber Taubsi und Rattfratz sind\n"
	.string "auch niedlich!$"

Route8_Text_MeganIntro::
	.string "Es muss ziemlich blöd aussehen, wie\n"
	.string "wir hier herumstehen!$"

Route8_Text_MeganDefeat::
	.string "Schau was du getan hast!$"

Route8_Text_MeganPostBattle::
	.string "Der Wachtposten von Saffronia\n"
	.string "City ist so gemein!\p"
	.string "Er lässt uns nicht in die Stadt!$"

Route8_Text_RichIntro::
	.string "Ich bin ein weit herumgekommener\n"
	.string "Glücksspieler!$"

Route8_Text_RichDefeat::
	.string "Den Jackpot habe ich noch nicht\n"
	.string "geknackt...$"

Route8_Text_RichPostBattle::
	.string "Glücksspiele und Pokémon haben\n"
	.string "eines gemeinsam: Man kann nicht\l"
	.string "damit aufhören!$"

Route8_Text_JuliaIntro::
	.string "Welches Pokémon ist süß, pummelig\n"
	.string "und kuschlig?$"

Route8_Text_JuliaDefeat::
	.string "Hör auf!\p"
	.string "Sei nicht so gemein zu Piepi!$"

Route8_Text_JuliaPostBattle::
	.string "Ich habe gehört, Piepi entwickelt\n"
	.string "sich, wenn man ihm einen Mondstein\l"
	.string "gibt.$"

Route8_Text_UndergroundPathSign::
	.string "TUNNELPFAD\n"
	.string "PRISMANIA CITY - LAVANDIA$"

Route8_Text_EliIntro::
	.string "Nora: Die Kraft von Zwillingen ist\n"
	.string "fantastisch. Wusstest du das?$"

Route8_Text_EliDefeat::
	.string "Nora: Aber…\n"
	.string "Wir nutzten unsere Zwillings-Kraft.$"

Route8_Text_EliPostBattle::
	.string "Nora: Ich habe mein Pokémon mit\n"
	.string "JO gefangen!$"

Route8_Text_EliNotEnoughMons::
	.string "NORA: Wir können nicht kämpfen,\n"
	.string "wenn du keine zwei POKéMON hast.$"

Route8_Text_AnneIntro::
	.string "JO: Wir überrumpeln dich mit\n"
	.string "unserer Zwillings-Kraft.$"

Route8_Text_AnneDefeat::
	.string "JO: Unsere Zwillings-Kraft…$"

Route8_Text_AnnePostBattle::
	.string "JO: Ich trainiere Pokémon mit\n"
	.string "Nora!$"

Route8_Text_AnneNotEnoughMons::
	.string "JO: Hallo! Lass uns kämpfen!\n"
	.string "Aber bring zwei POKéMON mit!$"

Route8_Text_RicardoIntro::
	.string "Mein Motorrad spielt verrückt!$"

Route8_Text_RicardoDefeat::
	.string "Argh!\n"
	.string "Das kann ich einfach nicht!$"

Route8_Text_RicardoPostBattle::
	.string "Mir ist Gras in die Speichen\n"
	.string "gekommen.$"

Route8_Text_JarenIntro::
	.string "Mach den Weg frei oder ich über-\n"
	.string "fahre dich!$"

Route8_Text_JarenDefeat::
	.string "Du hast es drauf, Kiddie!$"

Route8_Text_JarenPostBattle::
	.string "Denk bloß nicht, dass du etwas\n"
	.string "Besonderes bist, nur weil du\l"
	.string "gewonnen hast.$"
