Route11_Frlg_MapScripts::
	.byte 0

Route11_EventScript_DiglettsCaveSign::
	msgbox Route11_Text_DiglettsCave, MSGBOX_SIGN
	end

Route11_Text_HugoIntro::
	.string "Versuche dein Glück gegen mich!$"

Route11_Text_HugoDefeat::
	.string "Das Glück hat mich verlassen!$"

Route11_Text_HugoPostBattle::
	.string "Das ganze Leben ist ein\n"
	.string "Glücksspiel!$"

Route11_Text_JasperIntro::
	.string "Wettkämpfe!\n"
	.string "Ich kann ihnen nicht widerstehen!$"

Route11_Text_JasperDefeat::
	.string "Immerhin hatte ich eine Chance!$"

Route11_Text_JasperPostBattle::
	.string "Feiglinge haben in der Welt der\n"
	.string "Pokémon keine Chance!$"

Route11_Text_EddieIntro::
	.string "Hast du Lust mit mir zu kämpfen?$"

Route11_Text_EddieDefeat::
	.string "Hä?\n"
	.string "Das ist gemein!$"

Route11_Text_EddiePostBattle::
	.string "Immerhin habe ich es versucht!\n"
	.string "Ich schäme mich nicht!$"

Route11_Text_BraxtonIntro::
	.string "Vorsicht!\n"
	.string "Ich verlege hier gerade Kabel!$"

Route11_Text_BraxtonDefeat::
	.string "Das war ein Stromschlag!$"

Route11_Text_BraxtonPostBattle::
	.string "Schone die Umwelt und spare\n"
	.string "Energie!$"

Route11_Text_DillonIntro::
	.string "Ich habe gerade erst angefangen,\n"
	.string "Pokémon zu trainieren!$"

Route11_Text_DillonDefeat::
	.string "Mist!\n"
	.string "Ich hasse schwache Pokémon!$"

Route11_Text_DillonPostBattle::
	.string "Was willst du noch?\n"
	.string "Lass mich endlich allein!$"

Route11_Text_DirkIntro::
	.string "Haha!\n"
	.string "Bisher habe ich noch nie verloren!$"

Route11_Text_DirkDefeat::
	.string "Es gibt immer ein erstes Mal...$"

Route11_Text_DirkPostBattle::
	.string "Das war purer Zufall!\n"
	.string "Nichts als Glück!$"

Route11_Text_DarianIntro::
	.string "Ich habe noch nie gewonnen...$"

Route11_Text_DarianDefeat::
	.string "Das habe ich kommen sehen!$"

Route11_Text_DarianPostBattle::
	.string "Das war nichts als Glück.\n"
	.string "Purer Zufall!$"

Route11_Text_YasuIntro::
	.string "In meiner Klasse bin ich der Beste!$"

Route11_Text_YasuDefeat::
	.string "Ich muss meine Pokémon mehr\n"
	.string "trainieren!$"

Route11_Text_YasuPostBattle::
	.string "Aus den Bergen steigt manchmal ein\n"
	.string "dickes Pokémon herab.\p"
	.string "Es ist sehr stark!\n"
	.string "Versuche es zu fangen!$"

Route11_Text_BernieIntro::
	.string "Nimm dich vor Hochspannung in\n"
	.string "Acht!$"

Route11_Text_BernieDefeat::
	.string "Au!\n"
	.string "Der Funke ist übergesprungen!$"

Route11_Text_BerniePostBattle::
	.string "Ich mache mich besser wieder an\n"
	.string "die Arbeit.$"

Route11_Text_DaveIntro::
	.string "Meine Pokémon müssten bereit sein!$"

Route11_Text_DaveDefeat::
	.string "Das war schwach!$"

Route11_Text_DavePostBattle::
	.string "Ich muss ein paar stärkere fangen!$"

Route11_Text_DiglettsCave::
	.string "Digdas Höhle$"

