
#if IS_HNS
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Willkommen im Kampfcamp!\p"
	.string "Ich begleite dich zu dem K.O.-\n"
	.string "Teamturnier.$"
#else
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Willkommen im Kampfcamp von\n"
	.string "Laubwechselfeld!\p"
	.string "Ich begleite dich zu dem K.O.-\n"
	.string "Teamturnier.$"
#endif

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Möchtest du dich der Herausforderung\n"
	.string "des K.O.-Kampfturniers stellen?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Wir freuen uns auf deine nächste\n"
	.string "Herausforderung.$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "Im Kampfcamp von Laubwechselfeld\n"
	.string "findet das K.O.-Teamturnier statt.\p"
	.string "Jeder Teilnehmer darf drei Pokémon\n"
	.string "in den Kampf mitnehmen.\p"
	.string "Diese müssen in der Reihenfolge\n"
	.string "angeordnet werden, in der sie kämpfen\l"
	.string "sollen.\p"
	.string "Diese Reihenfolge wird im Kampf strikt\n"
	.string "eingehalten.\p"
	.string "Ein Pokémon bleibt solange im Kampf,\n"
	.string "bis der Kampf entschieden ist.\p"
	.string "Wenn ein Kampf nach drei Runden noch\n"
	.string "nicht entschieden ist, wird der Sieger\l"
	.string "durch ein richterliches Urteil bestimmt.\p"
	.string "Wenn du deine Herausforderung\n"
	.string "unterbrechen möchtest, speichere\l"
	.string "bitte dein Spiel.\p"
	.string "Wenn du ohne Speichern unterbrichst,\n"
	.string "ist die Herausforderung beendet.\p"
	.string "Besiegst du drei Trainer in Folge,\n"
	.string "gewinnst du einen fantastischen Preis.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Bevor du das Kampfcamp betrittst,\n"
	.string "musst du dein Spiel speichern. Okay?$"

FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Jedes Turnier bietet zwei Kategorien\n"
	.string "an: Level 50 und Offene Kämpfe. Wofür\l"
	.string "entscheidest du dich?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Sehr schön! Dann bestimme jetzt bitte\n"
	.string "deine drei Pokémon.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Verehrter Herausforderer!\p"
	.string "Leider besitzt du keine drei Pokémon,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "Eier{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Verehrter Herausforderer!\p"
	.string "Leider besitzt du keine drei Pokémon,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Du brauchst drei verschiedene Pokémon.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "Eier{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Ich werde dich nun zum Kampfcamp\n"
	.string "begleiten.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Verehrter Herausforderer!\p"
	.string "Du hast, bevor du die Herausforderung\n"
	.string "abgebrochen hast, nicht gespeichert.\p"
	.string "Daher wirst du leider für diese\n"
	.string "Herausforderung disqualifiziert.\l"
	.string "Schade!\p"
	.string "Natürlich kannst du dich einer neuen\n"
	.string "Herausforderung stellen!$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Hervorragend! Du hast drei Trainer in\n"
	.string "Folge besiegt!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Dein Erfolg wird gespeichert.\n"
	.string "Bitte warten.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "In Anerkennung deines dreifachen\n"
	.string "Sieges überreichen wir dir diesen Preis.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} gewinnt\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh, dein Beutel ist voll.\p"
	.string "Bitte schaffe Platz in deinem Beutel\n"
	.string "und komme dann wieder.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Vielen Dank für die Teilnahme!\p"
	.string "Das Ergebnis wird gespeichert.\n"
	.string "Bitte warten.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Wir freuen uns auf deine nächste\n"
	.string "Herausforderung.$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Wir haben schon auf dich gewartet!\p"
	.string "Bevor du das Kampfcamp betrittst,\n"
	.string "wird dein Spiel gespeichert.\l"
	.string "Bitte warten.$"

#if IS_HNS
VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Willkommen im Kampfcamp!\p"
	.string "Hier wird das Vertrauen der Trainer in\n"
	.string "ihre Pokémon getestet.$"
#else
VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Willkommen im Kampfcamp von\n"
	.string "Wiesenflur!\p"
	.string "Hier wird das Vertrauen der Trainer in\n"
	.string "ihre Pokémon getestet.$"
#endif
VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Möchtest du dich der Herausforderung\n"
	.string "des Wiesenflur Kampfcamps stellen?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "Im Kampfcamp von Wiesenflur gibt es\n"
	.string "eine entscheidende Regel, die beachtet\l"
	.string "werden muss.\p"
	.string "Trainer dürfen ihre Pokémon lediglich\n"
	.string "in den Kampf rufen und zurückziehen.\p"
	.string "Ansonsten ist es ihnen nicht erlaubt,\n"
	.string "in den Kampf einzugreifen.\p"
	.string "Die Pokémon sollen sich gemäß ihres\n"
	.string "Wesens verhalten und kämpfen.\p"
	.string "Du musst deinen Pokémon vertrauen und\n"
	.string "sie beobachten.\p"
	.string "Wenn du es schaffst, drei Trainer in\n"
	.string "Folge zu besiegen, bekommst du einen\l"
	.string "Preis von uns.\p"
	.string "Wenn du deine Herausforderung\n"
	.string "unterbrechen willst, speichere bitte\l"
	.string "dein Spiel.\p"
	.string "Brichst du die Herausforderung ohne zu\n"
	.string "speichern ab, wirst du disqualifiziert.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Hast du dein Herz gestärkt und deine\n"
	.string "Pokémon, dann komm wieder.$"

VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Es gibt zwei Schwierigkeitsgrade: Level\n"
	.string "50 und Offene Kämpfe. Wofür\l"
	.string "entscheidest du dich?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Seufz…\p"
	.string "Leider besitzt du keine drei Pokémon,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Du brauchst drei verschiedene Pokémon.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "Eier{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Seufz…\p"
	.string "Leider besitzt du keine drei Pokémon,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Du brauchst drei verschiedene Pokémon.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "Eier{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Gut. Dann bestimme jetzt deine drei\n"
	.string "Pokémon.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Bevor du das Kampfcamp betrittst,\n"
	.string "musst du dein Spiel speichern. Okay?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Gut. Dann folge mir.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Ich fühle mich geehrt, dass ich deinen\n"
	.string "Pokémon zuschauen durfte.\p"
	.string "Das Ergebnis wird gespeichert.\n"
	.string "Bitte warte einen Moment.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Drei Siege in Folge…\p"
	.string "Das Band zwischen dir und deinen\n"
	.string "Pokémon ist wirklich stark.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Dein Erfolg wird gespeichert.\n"
	.string "Bitte warte einen Moment.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Für deinen dreifachen Sieg bekommst du\n"
	.string "von uns diesen Preis überreicht.$"


#if IS_HNS
SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Willkommen im Kampfcamp!\p"
	.string "Ich begleite dich zum Wechselkampf-\n"
	.string "Turnier.$"
#else
SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Willkommen im Kampfcamp von\n"
	.string "Graphitport City.\p"
	.string "Ich begleite dich zum Wechselkampf-\n"
	.string "Turnier.$"
#endif

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Möchtest du am Wechselkampf\n"
	.string "teilnehmen?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Hier im Kampfcamp von Graphitport City\n"
	.string "halten wir Wechselkampf-Turniere ab,\l"
	.string "die mit Leih-Pkmn ausgetragen werden.\p"
	.string "Als Erstes leihst du dir drei Pokémon.\p"
	.string "Mit diesen kannst du an einem\n"
	.string "Einzelkampf teilnehmen.\p"
	.string "Gewinnst du, darfst du ein Leih-\n"
	.string "Pokémon tauschen.\p"
	.string "Wiederhole diese Folge von Siegen und\n"
	.string "Tausch. Gewinnst du drei Mal in Folge,\l"
	.string "erhältst du einen Preis.\p"
	.string "Wenn du die Herausforderung abbrechen\n"
	.string "willst, speichere dein Spiel.\p"
	.string "Wenn du ohne zu speichern abbrichst,\n"
	.string "wirst du disqualifiziert.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Wir freuen uns auf deine nächste\n"
	.string "Herausforderung.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "An welcher Stufe möchtest du teil-\n"
	.string "nehmen? Level 50 oder Offene Kämpfe?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Bevor du dich der Herausforderung\n"
	.string "stellst, speichere ich dein Spiel. Okay?$"

SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Gut, ich werde deine Pokémon sicher für\n"
	.string "dich aufbewahren, während du\l"
	.string "teilnimmst.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Bitte hier entlang.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Vielen Dank für deine Teilnahme!\p"
	.string "Ich gebe dir nun deine Pokémon\n"
	.string "zurück.\p"
	.string "Ich werde das Ergebnis speichern.\n"
	.string "Bitte warte einen Moment.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Ich gebe dir deine Pokémon zurück und\n"
	.string "nehme dafür unsere Leih-Pokémon\l"
	.string "entgegen.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Herzlichen Glückwunsch!\n"
	.string "Du hast drei Kämpfe in Folge gewonnen!\p"
	.string "Ich gebe dir nun deine Pokémon\n"
	.string "zurück.\p"
	.string "Ich werde deinen Erfolg speichern.\n"
	.string "Bitte warte einen Moment.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "Für deinen dreifachen Sieg bekommst du\n"
	.string "von uns diesen Preis überreicht.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh, dein Beutel ist voll.\p"
	.string "Bitte schaffe Platz in deinem Beutel\n"
	.string "und komme dann wieder.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Wir haben auf dich gewartet!\p"
	.string "Bevor du die Herausforderung\n"
	.string "fortsetzt, speichere ich dein Spiel.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Entschuldigung!\p"
	.string "Du hast, bevor du die Herausforderung\n"
	.string "abgebrochen hast, nicht gespeichert.\p"
	.string "Daher wirst du für diese Herausforde-\n"
	.string "rung disqualifiziert. Schade!$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Wir geben dir nun deine eigenen\n"
	.string "Pokémon zurück.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} gewinnt {STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Die Regeln des Wechselkampfes hängen\n"
	.string "öffentlich aus.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Wähle bitte ein Themengebiet aus.$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "In einem Wechselkampf darfst du\n"
	.string "nur drei Pokémon einsetzen.\p"
	.string "Egal, ob du sie dir ausleihst oder\n"
	.string "tauschst, du darfst keine zwei gleichen\l"
	.string "Pokémon in deinem Team haben.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Du kannst mit dem Trainer Pokémon\n"
	.string "tauschen, den du besiegt hast.\p"
	.string "Allerdings nur die Pokémon, die dieser\n"
	.string "im Kampf eingesetzt hat. Ein genereller\l"
	.string "Tausch ist nicht möglich.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Nach jedem gewonnenen Kampf kannst du\n"
	.string "eines deiner Pokémon gegen das deines\l"
	.string "Gegners tauschen.\p"
	.string "Du kannst mit dem dritten Trainer\n"
	.string "allerdings keine Pokémon tauschen.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Beim Pokémon-Tausch musst du auf zwei\n"
	.string "Dinge achten!\p"
	.string "Du kannst den Status des Pokémon, das\n"
	.string "du haben möchtest, vor dem Tausch\l"
	.string "nicht überprüfen.\p"
	.string "Denk daran, dass deine Pokémon in einer\n"
	.string "bestimmten Reihenfolge angeordnet\l"
	.string "sind.\p"
	.string "Diese bleibt auch nach dem Tausch\n"
	.string "unverändert.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Die Pokémon im Kampfcamp von\n"
	.string "Graphitport City sind alle\l"
	.string "Leih-Pokémon.\p"
	.string "Diese stehen auf Level 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Die Regeln des Wiesenflur Kampfcamps\n"
	.string "hängen öffentlich aus.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Wähle bitte ein Themengebiet aus.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Hier müssen die Pokémon selbständig\n"
	.string "handeln und kämpfen.\p"
	.string "Anders als wilde Pokémon reagieren\n"
	.string "Pokémon, die mit Menschen zusammen-\l"
	.string "leben, abhängig von ihrem Wesen.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Je nach Wesenheit wird ein Pokémon\n"
	.string "eventuell angreifen, egal, was passiert.\p"
	.string "Ein anderes wird sich vielleicht seinem\n"
	.string "Wesen entsprechend unter allen\p"
	.string "Umständen schützen wollen. Ein anderes\n"
	.string "irritiert oder verwirrt seinen Gegner.\p"
	.string "Abhängig von seinem Wesen wird ein\n"
	.string "Pokémon Lieblingsattacken haben, die\l"
	.string "es hervorragend beherrscht.\p"
	.string "Auf der anderen Seite wird es Attacken\n"
	.string "kennen, die es nicht mag und die ihm\l"
	.string "Schwierigkeiten machen.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Es gibt offensive Attacken, die dem\n"
	.string "Gegner Schaden zufügen.\p"
	.string "Es gibt defensive Attacken, die auf\n"
	.string "gegnerische Attacken vorbereiten oder\l"
	.string "aber KP wiederherstellen können.\p"
	.string "Und es gibt Attacken, die den Gegner\n"
	.string "schwächen, indem sie Statusprobleme\l"
	.string "verursachen, wie Vergiftungen oder\l"
	.string "Paralyse.\p"
	.string "Pokémon werden diese 3 Kategorien mit\n"
	.string "Sicherheit im Kampf in Betracht ziehen!$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Gibt ein Trainer seinem Pokémon keine\n"
	.string "Anweisungen, wird es vielleicht nicht in\l"
	.string "der Lage sein, bestimmte Attacken\p"
	.string "einzusetzen. Ein Pokémon hat\n"
	.string "Schwierigkeiten mit Attacken, die es\l"
	.string "nicht mag.\p"
	.string "Kennt ein Pokémon nur Attacken, die\n"
	.string "seinem Wesen widersprechen, so kann es\l"
	.string "nicht immer sein ganzes Können zeigen.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Abhängig von seinem Wesen, wird ein\n"
	.string "Pokémon vielleicht auch Attacken ein-\l"
	.string "setzen, die seinem Wesen widersprechen.\p"
	.string "Benimmt es sich in bestimmten\n"
	.string "Situationen merkwürdig, beobachte es\l"
	.string "genau.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "In diesem Kampfcamp werden die Level\n"
	.string "der gegnerischen Pokémon an die Level\l"
	.string "deiner Pokémon angepasst.\p"
	.string "Trotzdem wird kein Trainer, auf den du\n"
	.string "triffst, Pokémon unter Level 30 haben.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Die Regeln des Wiesenflur Kampfcamps\n"
	.string "hängen öffentlich aus.$"

