Text_PictureBookShelf:
	.string "Eine Sammlung von Pokémon-Büchern.$"

Text_BookShelf:
	.string "Hier stehen jede Menge Bücher.$"

Text_PokemonCenterBookShelf:
	.string "Pokémon-Magazine!\n"
	.string "Der Pokémon Freund…\p"
	.string "Pokémon Handbuch…\n"
	.string "Geliebte Pokémon…$"

Text_Vase:
	.string "Diese Vase sieht sehr teuer aus…\n"
	.string "Schauen wir mal hinein…\p"
	.string "Och, sie ist leer.$"

Text_EmptyTrashCan:
	.string "Leer…$"

Text_ShopShelf:
	.string "Die Regale biegen sich unter dem\n"
	.string "Gewicht von Pokémon-Artikeln.$"

Text_Blueprint:
	.string "Sind das Blaupausen?\n"
	.string "Die sind zu kompliziert zu lesen.$"

