@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "Ich bin der PENSIONSLEITER.\p"
	.string "Ich kümmere mich um die wertvollen\n"
	.string "POKéMON der TRAINER.\p"
	.string "Wenn ich eines deiner POKéMON auf-\n"
	.string "ziehen soll, sprich mit meiner Frau.$"

DayCare_Text_DoYouWantEgg::
	.string "Ach, du bist es!\p"
	.string "Wir haben deine POKéMON aufgezogen\n"
	.string "und wurden überrascht!\p"
	.string "Deine POKéMON haben nun ein EI!\p"
	.string "Wir wissen nicht, wie das passiert ist,\n"
	.string "aber deine POKéMON haben es.\p"
	.string "Möchtest du es haben?$"

DayCare_Text_YourMonIsDoingFine::
	.string "Ach, du bist es! Schön, dich zu sehen.\n"
	.string "Deinem {STR_VAR_1} geht es sehr gut.$"

DayCare_Text_IllKeepIt::
	.string "Well then, I'll keep it.\n"
	.string "Thanks!$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "Du hast keinen Platz dafür… Komm\n"
	.string "wieder, wenn du Platz geschafft hast.$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER} erhält das EI vom\n"
	.string "PENSIONSLEITER.$"

DayCare_Text_TakeGoodCareOfIt::
	.string "Kümmere dich gut darum.$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "ポケモンを　ひきとりたい　ときは\n"
	.string "ばさんに　いって　おくれ$"

DayCare_Text_YourMonsAreDoingFine::
	.string "Ah, du bist es! Deine POKéMON\n"
	.string "{STR_VAR_1} und {STR_VAR_2} entwickeln\l"
	.string "sich prächtig.$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "Ich werde es behalten.\n"
	.string "Oder möchtest du es haben?$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "Ich bin die PENSIONSLEITERIN.\p"
	.string "Wir ziehen POKéMON für dich auf.\p"
	.string "Sollen wir eins für dich aufziehen?$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "Welches POKéMON sollen wir für dich\n"
	.string "aufziehen?$"

DayCare_Text_WellRaiseYourMon::
	.string "Fein, dann nehmen wir dein {STR_VAR_1}\n"
	.string "für eine Weile in Pflege.\p"
	.string "Schau später mal nach ihm.$"

DayCare_Text_WeCanRaiseOneMore::
	.string "Wir können zwei deiner POKéMON\n"
	.string "nehmen. Möchtest du noch eines in\l"
	.string "Pflege geben?$"

DayCare_Text_HusbandWasLookingForYou::
	.string "Mein Mann hat dich schon gesucht.$"

DayCare_Text_FineThenComeAgain::
	.string "Oh, fine, then.\n"
	.string "Come again.$"

DayCare_Text_NotEnoughMoney::
	.string "Du hast nicht genug Geld…$"

DayCare_Text_TakeOtherOneBackToo::
	.string "Möchtest du das andere auch wieder\n"
	.string "mitnehmen?$"

DayCare_Text_ComeAgain::
	.string "Fine.\n"
	.string "Come again.$"

DayCare_Text_GoodToSeeYou::
	.string "Ach, du bist es! Schön, dich zu sehen.\n"
	.string "Deinen POKéMON kann es einfach\l"
	.string "nur gut gehen!$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "Dein {STR_VAR_1} ist um {STR_VAR_2} Level\n"
	.string "gewachsen.$"

DayCare_Text_YourPartyIsFull::
	.string "Dein POKéMON-Team ist vollzählig.\n"
	.string "Schaffe Platz und komm dann\l"
	.string "wieder.$"

DayCare_Text_TakeBackWhichMon::
	.string "どっちの　ポケモンを　ひきとるかい？$"

DayCare_Text_ItWillCostX::
	.string "Wenn du dein {STR_VAR_1}\n"
	.string "mitnehmen willst, kostet das ¥{STR_VAR_2}.$"

DayCare_Text_HeresYourMon::
	.string "Sehr schön!\n"
	.string "Hier ist dein POKéMON!$"

DayCare_Text_TookBackMon::
	.string "{PLAYER} hat {STR_VAR_1} von der\n"
	.string "PENSIONSLEITERIN zurückerhalten.$"

DayCare_Text_YouHaveJustOneMon::
	.string "Oh! Du hast aber nur ein POKéMON.\p"
	.string "Komm einfach später wieder.$"

DayCare_Text_TakeYourMonBack::
	.string "Möchtest du dein POKéMON wieder\n"
	.string "mitnehmen?$"

DayCare_Text_WhatWillYouBattleWith::
	.string "Wenn du das POKéMON hier lässt, womit\n"
	.string "willst du denn dann kämpfen?\p"
	.string "Komm einfach später wieder.$"

DayCare_Text_Huh::
	.string "Huh?$"
