Trade_Text_LookingForMonWannaTradeForMon::
	.string "Ich suche nach {STR_VAR_1}!\p"
	.string "Tauschst du es gegen {STR_VAR_2}?$"

Trade_Text_AwwOhWell::
	.string "Awww!\n"
	.string "Oh, well…$"

Trade_Text_WhatThatsNoMon::
	.string "What?\n"
	.string "That's no {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "Hey, thanks!$"

Trade_Text_IsntMyOldMonGreat::
	.string "Ist {STR_VAR_2} nicht cool?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "Hallo!\p"
	.string "Willst du dein {STR_VAR_1} nicht\n"
	.string "gegen ein {STR_VAR_2} tauschen?$"

Trade_Text_WellIfYouDontWantTo::
	.string "Wenn du nicht magst, kann man\n"
	.string "nichts machen!$"

Trade_Text_ThisIsntMon::
	.string "Hm?\n"
	.string "Das ist kein {STR_VAR_1}!\p"
	.string "Denk an mich, wenn du eins\n"
	.string "gefangen hast!$"

Trade_Text_Thanks::
	.string "Thanks!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "Das {STR_VAR_2}, das ich\n"
	.string "mit dir getauscht habe -\l"
	.string "ist es stärker geworden?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "Besitzt du ein {STR_VAR_1}?\p"
	.string "Willst du es gegen {STR_VAR_2}\n"
	.string "tauschen?$"

Trade_Text_ThatsTooBad::
	.string "That's too bad.$"

Trade_Text_ThisIsNoMon::
	.string "Das ist kein {STR_VAR_1}!\p"
	.string "Komm wieder, wenn du eines besitzt!$"

Trade_Text_ThanksYoureAPal::
	.string "Thanks, you're a pal!$"

Trade_Text_HowIsMyOldMon::
	.string "Wie geht es {STR_VAR_2}?\p"
	.string "Mein {STR_VAR_1} fühlt sich super!$"
