Trade_Text_LookingForMonWannaTradeForMon::
	.string "Ich suche nach {VAR}!\p"
	.string "Tauschst du es gegen {VAR}?$"

Trade_Text_AwwOhWell::
	.string "Awww!\n"
	.string "Oh, well…$"

Trade_Text_WhatThatsNoMon::
	.string "What?\n"
	.string "That's no {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "Hey, thanks!$"

Trade_Text_IsntMyOldMonGreat::
	.string "Ist {VAR} nicht cool?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "Hallo!\p"
	.string "Willst du dein {VAR} nicht\n"
	.string "gegen ein {VAR} tauschen?$"

Trade_Text_WellIfYouDontWantTo::
	.string "Wenn du nicht magst, kann man\n"
	.string "nichts machen!$"

Trade_Text_ThisIsntMon::
	.string "Hm?\n"
	.string "Das ist kein {VAR}!\p"
	.string "Denk an mich, wenn du eins\n"
	.string "gefangen hast!$"

Trade_Text_Thanks::
	.string "Thanks!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "Das {VAR}, das ich\n"
	.string "mit dir getauscht habe -\l"
	.string "ist es stärker geworden?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "Besitzt du ein {VAR}?\p"
	.string "Willst du es gegen {VAR}\n"
	.string "tauschen?$"

Trade_Text_ThatsTooBad::
	.string "That's too bad.$"

Trade_Text_ThisIsNoMon::
	.string "Das ist kein {VAR}!\p"
	.string "Komm wieder, wenn du eines besitzt!$"

Trade_Text_ThanksYoureAPal::
	.string "Thanks, you're a pal!$"

Trade_Text_HowIsMyOldMon::
	.string "Wie geht es {VAR}?\p"
	.string "Mein {VAR} fühlt sich super!$"
