@ Crystal-accurate phone dialogue for HnS rematch trainers
@ Greetings from Crystal callee/caller files prepended to each text

@ Joey - Knirps, Route 30
MatchCall_HNS_Joey_General1::
	.string "Yo, {PLAYER}! Wie geht es dir?\p"
	.string "Wie geht es deinen Pokémon?\p"
	.string "Mein {STR_VAR_3} ist nicht zu\n"
	.string "halten, wie immer.\p"
	.string "Es ist mein Ein und Alles. Ich werde\n"
	.string "mit ihm ein toller Trainer sein!$"

MatchCall_HNS_Joey_General2::
	.string "Yo, {PLAYER}! Hast du Zeit?\p"
	.string "Mein {STR_VAR_3} sieht\n"
	.string "entschlossener aus!\p"
	.string "Ich bezweifle, dass du auch so ein\n"
	.string "cooles Pokémon in deinem Team\l"
	.string "hast!$"

MatchCall_HNS_Joey_General3::
	.string "Yo, {PLAYER}! Wie geht es dir?\p"
	.string "Ich experimentiere gerade mit den\n"
	.string "Attacken von {STR_VAR_3}, um\l"
	.string "eine Strategie zu finden.\p"
	.string "Finde ich eine gute, dann müssen\n"
	.string "wir kämpfen!$"

MatchCall_HNS_Joey_Battle::
	.string "Yo, {PLAYER}!\p"
	.string "Treffen wir uns für einen Kampf!\p"
	.string "Ich verspreche, es wird anders!$"

@ Wade - Käfersammler, Route 31
MatchCall_HNS_Wade_General1::
	.string "{PLAYER}, alles senkrecht?\p"
	.string "Wie geht es deinen Pokémon?\p"
	.string "Meine Pokémon haben zu viel\n"
	.string "Energie.\p"
	.string "Das ist ein Problem.\p"
	.string "Von all meinen Pokémon ist\n"
	.string "{STR_VAR_3} am schwierigsten.\p"
	.string "Mit ihm zu arbeiten ist ermüdend.$"

MatchCall_HNS_Wade_General2::
	.string "{PLAYER}, alles senkrecht? Schön\n"
	.string "heute, oder?\p"
	.string "Wachsen deine Pokémon?\p"
	.string "Meine Pokémon wachsen mir zu\n"
	.string "schnell. Es ist überwältigend!\p"
	.string "{STR_VAR_3} wächst besonders\n"
	.string "schnell.\p"
	.string "Ich denke, es wird stark.$"

MatchCall_HNS_Wade_General3::
	.string "{PLAYER}, alles senkrecht?\p"
	.string "Yo, wir haben ein wildes\n"
	.string "{STR_VAR_3} mit nur einem Schlag\l"
	.string "besiegt.\p"
	.string "Es ging so hart zu Boden, dass ich\n"
	.string "fast schon Mitleid hatte.$"

MatchCall_HNS_Wade_FoundItem::
	.string "{PLAYER}, alles senkrecht?\p"
	.string "Ich habe alle möglichen Beeren\n"
	.string "gefunden.\p"
	.string "Wenn du willst, teile ich mit dir.\p"
	.string "Ich warte auf\n"
	.string "Route 31.$"

MatchCall_HNS_Wade_Battle::
	.string "{PLAYER}, alles senkrecht?\p"
	.string "Lust auf einen Pokémon-Kampf?\p"
	.string "Es wird nicht so wie das letzte Mal!$"

@ Ralph - Angler, Route 32
MatchCall_HNS_Ralph_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Wie läuft’s Angeln?\p"
	.string "Versorgst du deine Pokémon auch\n"
	.string "gut?\p"
	.string "Behandle sie gut, sie sind deine\n"
	.string "Kameraden!$"

MatchCall_HNS_Ralph_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Ich habe mehr Zeit mit meinem\n"
	.string "{STR_VAR_3} verbracht, als mit\l"
	.string "meinen Kindern.\p"
	.string "Das ist in der Tat schade.$"

MatchCall_HNS_Ralph_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hör dir das an!\p"
	.string "Ich besiegte ein wildes\n"
	.string "{STR_VAR_3}.\p"
	.string "Ich erzählte es meinem Sohn, aber\n"
	.string "er sagte, er könne das auch leicht\l"
	.string "tun.\p"
	.string "Er ist sehr aufsässig geworden…$"

MatchCall_HNS_Ralph_Battle::
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Liz - Picknicker, Route 32
MatchCall_HNS_Liz_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Ich hatte etwas Zeit, also\l"
	.string "hab ich dich angerufen.\p"
	.string "Wie geht es deinen Pokémon?\p"
	.string "Ich bringe mein {STR_VAR_3}\n"
	.string "jeden Tag ins Pokémon\l"
	.string "Center in Violet,\p"
	.string "also geht’s ihm\n"
	.string "fantastisch!\p"
	.string "Die Rezeptionistin ist eine\n"
	.string "Freundin!$"

MatchCall_HNS_Liz_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Du musst dir das anhören.\p"
	.string "Mein {STR_VAR_3} ist so\n"
	.string "bezaubernd!\p"
	.string "Es kuschelt sich ständig an mich!$"

MatchCall_HNS_Liz_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Hör mal, hör mal!\p"
	.string "Denkst du nicht auch, dass Falk,\n"
	.string "der Arenaleiter von Viola City, cool\l"
	.string "und schön ist?\p"
	.string "Aber, man sagt, dass sein Vater, der\n"
	.string "im Freien trainiert, noch cooler und\l"
	.string "schöner als Falk ist.\p"
	.string "Ich würde ihn gerne kennen lernen!$"

MatchCall_HNS_Liz_Battle::
	.string "Hi, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Anthony - Wanderer, Route 33
MatchCall_HNS_Anthony_General1::
	.string "Hey, {PLAYER}!\p"
	.string "Sind deine Pokémon immer noch wild?\p"
	.string "Mein {STR_VAR_3} und ich, wir\n"
	.string "strotzen vor Energie.\p"
	.string "Wir wandern täglich in den Bergen,\n"
	.string "um so Energie abzubauen.$"

MatchCall_HNS_Anthony_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Neulich hab ich zugesehen,\n"
	.string "wie mein {STR_VAR_3}\l"
	.string "Beeren gegessen hat.\p"
	.string "Es sah so aus, als würde es\n"
	.string "das Essen genießen, also\l"
	.string "hab ich auch probiert.\p"
	.string "Ich weiß nicht, ob Menschen\n"
	.string "das essen sollten, aber\l"
	.string "es war lecker!$"

MatchCall_HNS_Anthony_General3::
	.string "Hey, {PLAYER}!\p"
	.string "In letzter Zeit sind mir viele wilde\n"
	.string "{STR_VAR_3} begegnet.\p"
	.string "Sie sind kein großes Problem.$"

MatchCall_HNS_Anthony_Battle::
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Todd - Camper, Route 34
MatchCall_HNS_Todd_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Was geht?\p"
	.string "Wie ziehst du deine\n"
	.string "Pokémon groß?\p"
	.string "Ich mach so allerlei,\n"
	.string "wie sie in die\l"
	.string "Kinderkrippe geben und\p"
	.string "sie mit Items\n"
	.string "abhärten.$"

MatchCall_HNS_Todd_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Was geht?\p"
	.string "Mein {STR_VAR_3} wird mir immer\n"
	.string "ähnlicher.\p"
	.string "Es wird immer niedlicher!$"

MatchCall_HNS_Todd_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Was geht?\p"
	.string "Und, pass auf!\p"
	.string "Jetzt besiegen wir\n"
	.string "{STR_VAR_3} mühelos.\p"
	.string "Ich sollte die\n"
	.string "Rosalia-Arena fordern.$"

MatchCall_HNS_Todd_Battle::
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Gina - Picknicker, Route 34
MatchCall_HNS_Gina_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Wie geht’s dir?\p"
	.string "Sind deine Pokémon noch immer\n"
	.string "stark?\p"
	.string "Ich trainiere mein {STR_VAR_3}\n"
	.string "täglich.$"

MatchCall_HNS_Gina_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Wie geht’s dir?\p"
	.string "Mein {STR_VAR_3} und ich stimmen\n"
	.string "uns immer besser aufeinander ab.$"

MatchCall_HNS_Gina_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Wie geht’s dir?\p"
	.string "Wir kämpften gegen ein wildes\n"
	.string "{STR_VAR_3} und gewannen knapp.\p"
	.string "Wir kommen jetzt in Schwung!$"

MatchCall_HNS_Gina_Battle::
	.string "Hi, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Irwin - Jongleur, Route 35
MatchCall_HNS_Irwin_General1::
	.string "Äh, hallo, {PLAYER}?\n"
	.string "Hier ist dein Kumpel Erich!\p"
	.string "Ich hab neulich den\n"
	.string "erstaunlichsten Kampf gesehen!\p"
	.string "Ich wünschte, ich könnte so\n"
	.string "kämpfen.\p"
	.string "Ach halt, ich kann! Ich\n"
	.string "brauch nur jemanden zum Kämpfen!$"

MatchCall_HNS_Irwin_General2::
	.string "Äh, hallo, {PLAYER}?\n"
	.string "Hier ist dein Kumpel Erich!\p"
	.string "Hehe, ich habe gleich angerufen!\p"
	.string "Ich denke, wir werden sehr gute\n"
	.string "Kameraden!$"

MatchCall_HNS_Irwin_General3::
	.string "Äh, hallo, {PLAYER}?\n"
	.string "Hier ist dein Kumpel Erich!\p"
	.string "Als ich deine Geschichten hörte,\n"
	.string "weinte meine Seele!\p"
	.string "Wirklich!$"

MatchCall_HNS_Irwin_Battle::
	.string "Äh, hallo, {PLAYER}?\n"
	.string "Hier ist dein Kumpel Erich!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Arnie - Käfersammler, Route 35
MatchCall_HNS_Arnie_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Wie läuft’s?\p"
	.string "Ich wette, deine Pokémon sind viel\n"
	.string "stärker als zuvor.$"

MatchCall_HNS_Arnie_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Wie läuft’s?\p"
	.string "Mein {STR_VAR_3} ist immer dabei!\p"
	.string "Es ist so süß! Ich liebe es!$"

MatchCall_HNS_Arnie_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Wie läuft’s?\p"
	.string "Um mal das Thema zu wechseln,\n"
	.string "ich hab dieses {STR_VAR_3}\l"
	.string "zum ersten Mal gesehen.\p"
	.string "Es war leicht zu besiegen,\n"
	.string "ehrlich gesagt.$"

MatchCall_HNS_Arnie_Battle::
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Alan - Schulkind, Route 36
MatchCall_HNS_Alan_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "{PLAYER}, trainierst du deine\n"
	.string "Pokémon richtig?\p"
	.string "Ich habe gelesen, dass man die\n"
	.string "Pokémon, die man fängt mit Liebe\l"
	.string "und Umsicht trainieren soll.$"

MatchCall_HNS_Alan_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "Mein {STR_VAR_3} wird immer\n"
	.string "stärker, womit ich gerechnet habe!$"

MatchCall_HNS_Alan_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "Apropos, wir besiegten neulich ein\n"
	.string "wildes {STR_VAR_3}.\p"
	.string "Die richtige Vorbereitung lohnt!$"

MatchCall_HNS_Alan_FoundItem::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "Hehehe, ich fand etwas Schönes!\p"
	.string "Es gehört dir!\p"
	.string "Wieso kommst du nicht zu\n"
	.string "Route 36 und holst es ab?$"

MatchCall_HNS_Alan_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Dana - Göre, Route 38
MatchCall_HNS_Dana_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Mein {STR_VAR_3} strotzt vor\n"
	.string "Energie, das macht mir ein wenig\l"
	.string "Angst.\p"
	.string "Wie geht es deinen Pokémon?$"

MatchCall_HNS_Dana_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Mein {STR_VAR_3} wird immer\n"
	.string "süßer!\p"
	.string "Ich habe schon viele Fotos\n"
	.string "gemacht!$"

MatchCall_HNS_Dana_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Im Handumdrehen war das wilde\n"
	.string "{STR_VAR_3} K.O.\p"
	.string "Das kommt bestimmt davon, dass du\n"
	.string "mir Kampftipps gegeben hast.$"

MatchCall_HNS_Dana_FoundItem::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Weißt du was?\n"
	.string "Ich hab ein tolles Geschenk!\p"
	.string "Wie versprochen, gehört es dir!\n"
	.string "Ich bin sicher, es gefällt dir.\p"
	.string "Komm es dir holen! Ich warte\n"
	.string "auf Route 38!$"

MatchCall_HNS_Dana_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Chad - Schulkind, Route 38
MatchCall_HNS_Chad_General1::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Lutz!\p"
	.string "Wie geht’s deinen Pokémon\n"
	.string "so?\p"
	.string "Du kennst Prof. Eich, also\n"
	.string "geht’s deinen Pokémon\l"
	.string "natürlich gut!\p"
	.string "Meinen Pokémon geht’s auch\n"
	.string "gut.\p"
	.string "Aber ich versuche ja auch,\n"
	.string "ein Pokémon-Professor zu\l"
	.string "werden.$"

MatchCall_HNS_Chad_General2::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Lutz!\p"
	.string "Ich beobachte neuerdings\n"
	.string "wilde {STR_VAR_3}.\p"
	.string "Ich lerne allerlei neue\n"
	.string "Dinge durch meine\l"
	.string "Beobachtungen.\p"
	.string "Ich wünschte, ich könnte\n"
	.string "bald ein Pokémon-Forscher\l"
	.string "wie Prof. Eich werden.$"

MatchCall_HNS_Chad_General3::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Lutz!\p"
	.string "Ich lerne fleißig, damit\n"
	.string "Prof. Eich mich zu seinem\l"
	.string "Assistenten macht!$"

MatchCall_HNS_Chad_Battle::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Lutz!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Derek - Pokéfan M, Route 39
MatchCall_HNS_Derek_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Das musst du hören!\p"
	.string "Mein liebenswürdiges {STR_VAR_3}\n"
	.string "sah mich an und lachte!\p"
	.string "Es muss daran liegen, weil unsere\n"
	.string "Herzen im Einklang schlagen!$"

MatchCall_HNS_Derek_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Hör genau zu.\p"
	.string "Mein {STR_VAR_3} lächelt\n"
	.string "fröhlich, wenn ich es in die Wangen\l"
	.string "zwicke.\p"
	.string "Aber es lacht nur bei mir.\p"
	.string "Ich bin etwas Besonderes.$"

MatchCall_HNS_Derek_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Wie geht es deinem Pikachu?\p"
	.string "Lass uns zusammenkommen und mit\n"
	.string "unseren Pikachu angeben!$"

MatchCall_HNS_Derek_FoundItem::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Ich möchte, dass du dieses Nugget\n"
	.string "bekommst.\p"
	.string "Ich bin auf Route 39.\n"
	.string "Komm es dir holen!$"

MatchCall_HNS_Derek_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Tully - Angler, Route 42
MatchCall_HNS_Tully_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Wie läuft es mit deinem Abenteuer?\p"
	.string "Ich kann mich über das Angeln\n"
	.string "nicht beschweren!$"

MatchCall_HNS_Tully_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Mein {STR_VAR_3} ist erneut\n"
	.string "gewachsen.\p"
	.string "Es war groß, als ich es fing, aber\n"
	.string "jetzt ist es noch größer.$"

MatchCall_HNS_Tully_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Oh yo, ich schlug ein wildes\n"
	.string "{STR_VAR_3} K.O.\p"
	.string "Es war riesig, ungefähr soo groß.\p"
	.string "He, ich glaube, man kann das am\n"
	.string "Telefon nicht beschreiben…$"

MatchCall_HNS_Tully_FoundItem::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Ich fand etwas Kleines am Ufer.\p"
	.string "Wie versprochen, es gehört dir.\p"
	.string "Ich warte auf\n"
	.string "Route 42.$"

MatchCall_HNS_Tully_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Brent - Pokémaniac, Route 43
MatchCall_HNS_Brent_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Taro!\p"
	.string "Ach ja, ich hab dich neulich\n"
	.string "aus einem Pokémon Center\l"
	.string "kommen sehen.\p"
	.string "Du heilst deine Pokémon\n"
	.string "regelmäßig, oder?\l"
	.string "Ich bin beeindruckt.\p"
	.string "Heh, mein {STR_VAR_3} ist\n"
	.string "so zäh, es muss nicht oft\l"
	.string "zu Pokémon Centern\l"
	.string "gehen. Heheh!$"

MatchCall_HNS_Brent_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Taro!\p"
	.string "Oh yo, ich habe vor geraumer Zeit\n"
	.string "ein sehr seltenes Pokémon in einem\l"
	.string "Tausch erhalten.\p"
	.string "Möchtest du wissen welches?\p"
	.string "Hehe, das verrate ich dir nicht!$"

MatchCall_HNS_Brent_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Taro!\p"
	.string "Wusstest du…?\p"
	.string "Bill kommt ursprünglich aus Dukatia\n"
	.string "City.\p"
	.string "Offenbar ist Bill kein wirklich\n"
	.string "guter Kämpfer.$"

MatchCall_HNS_Brent_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Taro!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Tiffany - Picknicker, Route 43
MatchCall_HNS_Tiffany_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ilona!\p"
	.string "Sind deine Pokémon in Ordnung?\p"
	.string "Ich hoffe, du bringst sie täglich in\n"
	.string "ein Pokémon-Center.\p"
	.string "Übertreib es nicht.\p"
	.string "Mein {STR_VAR_3} ist süß und\n"
	.string "lebhaft, weil ich es täglich in ein\l"
	.string "Pokémon-Center bringe.$"

MatchCall_HNS_Tiffany_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ilona!\p"
	.string "Mein {STR_VAR_3} ist so\n"
	.string "bezaubernd, nicht wahr?\p"
	.string "Ich schlafe immer mit ihm - es ist\n"
	.string "so weich und warm!$"

MatchCall_HNS_Tiffany_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ilona!\p"
	.string "Oh, wir mussten vor kurzem gegen\n"
	.string "ein wildes {STR_VAR_3} kämpfen…\p"
	.string "Mein Piepi war fast besiegt!\p"
	.string "Schrecklich, oder? Ich hasse diese\n"
	.string "{STR_VAR_3}!$"

MatchCall_HNS_Tiffany_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ilona!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Vance - Vogelfänger, Route 44
MatchCall_HNS_Vance_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Arno!\p"
	.string "Geht es dir und deinen Pokémon\n"
	.string "gut?\p"
	.string "Mein {STR_VAR_3} sieht aus,\n"
	.string "als würde es stark genug\p"
	.string "um es mit den legendären\n"
	.string "Vogel-Pokémon aufzunehmen!$"

MatchCall_HNS_Vance_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Arno!\p"
	.string "Mein {STR_VAR_3} wurde stärker.\p"
	.string "Wir sind abgehoben!$"

MatchCall_HNS_Vance_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Arno!\p"
	.string "Wir können {STR_VAR_3} leicht\n"
	.string "besiegen!\p"
	.string "…Huh? Du auch? Das ist doch toll?$"

MatchCall_HNS_Vance_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Arno!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Wilton - Angler, Route 44
MatchCall_HNS_Wilton_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Sind deine Pokémon gewachsen?\p"
	.string "Mein {STR_VAR_3} ist ein bisschen\n"
	.string "gewachsen.$"

MatchCall_HNS_Wilton_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Mein {STR_VAR_3} ist sehr\n"
	.string "gewachsen!\p"
	.string "Meine Angelfähigkeiten haben sich\n"
	.string "auch verbessert!$"

MatchCall_HNS_Wilton_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Wir besiegten ein wildes\n"
	.string "{STR_VAR_3}…\p"
	.string "Du weißt, dass mir Angeln mehr Spaß\n"
	.string "macht, als wilde Pokémon zu\l"
	.string "besiegen.$"

MatchCall_HNS_Wilton_FoundItem::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Ich habe beim Angeln ein Item\n"
	.string "gefunden.\p"
	.string "Komm es dir holen auf\n"
	.string "Route 44.$"

MatchCall_HNS_Wilton_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Kenji - Schwarzgurt, Route 45
MatchCall_HNS_Kenji_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Timon!\p"
	.string "{PLAYER}! Schönes Wetter, oder?$"

MatchCall_HNS_Kenji_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Timon!\p"
	.string "Bist du noch auf Reisen?\p"
	.string "Ich bin meinem Training treu\n"
	.string "geblieben.\p"
	.string "Oooooaaarrrgh!$"

MatchCall_HNS_Kenji_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Timon!\p"
	.string "Ich trainiere gerade.\p"
	.string "Entschuldige, aber rufe mich\n"
	.string "später noch mal an.\p"
	.string "Oooooaaarrrgh!$"

MatchCall_HNS_Kenji_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Timon!\p"
	.string "Ich mach gerade Pause!\p"
	.string "Komm vorbei, wenn du Zeit hast!$"

MatchCall_HNS_Kenji_FoundItem::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Timon!\p"
	.string "Ich mach gerade Pause vom\n"
	.string "Training.\p"
	.string "Ich hab was Gutes gefunden.\n"
	.string "Komm es dir holen, wenn du willst!$"

@ Parry - Wanderer, Route 45
MatchCall_HNS_Parry_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Günter!\p"
	.string "Sehen deine Pokémon gut aus?\p"
	.string "Mein {STR_VAR_3} und ich, wir\n"
	.string "sehen hervorragend aus! Hahaha!$"

MatchCall_HNS_Parry_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Günter!\p"
	.string "Nichts kann es mit meinem\n"
	.string "{STR_VAR_3} aufnehmen.$"

MatchCall_HNS_Parry_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Günter!\p"
	.string "Ja, wir haben ein wildes\n"
	.string "{STR_VAR_3} besiegt!\p"
	.string "Das war ok, aber ich wollte\n"
	.string "es eigentlich fangen…$"

MatchCall_HNS_Parry_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Günter!\p"
	.string "Du kämpfst wieder gegen mich,\n"
	.string "oder?$"

@ Erin - Picknicker, Route 46
MatchCall_HNS_Erin_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Nanette!\p"
	.string "Trainierst du deine Pokémon?\p"
	.string "Mein {STR_VAR_3} sieht\n"
	.string "gut aus!$"

MatchCall_HNS_Erin_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Nanette!\p"
	.string "Mein {STR_VAR_3} ist viel\n"
	.string "stärker als zuvor!$"

MatchCall_HNS_Erin_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Nanette!\p"
	.string "Und, und… Ich habe gerade ein\n"
	.string "{STR_VAR_3} besiegt!\p"
	.string "Ich trainiere meine Pokémon\n"
	.string "intensiv!$"

MatchCall_HNS_Erin_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Nanette!\p"
	.string "Ich arbeite hart an meinen\n"
	.string "Pokémon!\p"
	.string "Komme für einen Rückkampf zurück!$"

@ Jack - Schulkind, National Park
MatchCall_HNS_Jack_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Julius!\p"
	.string "Wie geht’s deinen Pokémon\n"
	.string "so?\p"
	.string "Mein {STR_VAR_3} ist so\n"
	.string "neugierig, das wird zum Problem.\p"
	.string "Vielleicht ist es wie ich…$"

MatchCall_HNS_Jack_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Julius!\p"
	.string "Die Intelligenz von meinem\n"
	.string "{STR_VAR_3} steigt und steigt.\p"
	.string "Es könnte intelligenter als deines\n"
	.string "sein!$"

MatchCall_HNS_Jack_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Julius!\p"
	.string "Hast du gewusst?\p"
	.string "Wenn es regnet, gibt es bestimmt\n"
	.string "auch Donner.\p"
	.string "Mein Kamerad erhielt einige gute\n"
	.string "Tipps. Wenn er sie mir sagt, rufe ich\l"
	.string "dich sofort an.$"

MatchCall_HNS_Jack_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Julius!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Beverly - Pokéfan F, National Park
MatchCall_HNS_Beverly_General1::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Sorgst du gut für deine Pokémon?\p"
	.string "Meinem {STR_VAR_3} geht es gut.\n"
	.string "Es frisst viel.$"

MatchCall_HNS_Beverly_General2::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Ich habe mein {STR_VAR_3}\n"
	.string "verschönert und es ist somit noch\l"
	.string "süßer als zuvor!$"

MatchCall_HNS_Beverly_General3::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Sind deine Pokémon in Top-Form?\p"
	.string "Lass uns mal wieder über Pokémon\n"
	.string "plaudern.$"

MatchCall_HNS_Beverly_FoundItem::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Mein Mann hat einige Nuggets.\p"
	.string "Wenn du möchtest, gebe ich dir\n"
	.string "einen dafür, dass du mir geholfen\l"
	.string "hast.\p"
	.string "Ich bin im Nationalpark.\n"
	.string "Komm bitte vorbei, wenn\l"
	.string "du kannst.$"

MatchCall_HNS_Beverly_Battle::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Huey - Matrose, Olivine Lighthouse
MatchCall_HNS_Huey_General1::
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Nepomuk!\p"
	.string "Wie geht es dir?$"

MatchCall_HNS_Huey_General2::
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Nepomuk!\p"
	.string "Wir müssen irgendwann wieder\n"
	.string "kämpfen.\p"
	.string "Ich werde dich herausfordern, bis\n"
	.string "ich gewinne, darauf kannst du\l"
	.string "wetten.$"

MatchCall_HNS_Huey_Battle::
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Nepomuk!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Gaven - Ass-Trainer M, Route 26
MatchCall_HNS_Gaven_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Maik!\p"
	.string "Wie geht es deinen Pokémon?\p"
	.string "Meinem {STR_VAR_3} geht es wie\n"
	.string "immer hervorragend.\p"
	.string "Lass uns am Ball bleiben und\n"
	.string "Pokémon-Champs werden!$"

MatchCall_HNS_Gaven_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Maik!\p"
	.string "Mein {STR_VAR_3} könnte stärker\n"
	.string "sein, als ich dachte.\p"
	.string "Ich bezweifle, dass ich je ein\n"
	.string "Pokémon sehe, das besser\l"
	.string "ist als meins.$"

MatchCall_HNS_Gaven_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Maik!\p"
	.string "Ich bin davon besessen, dich zu\n"
	.string "besiegen.$"

MatchCall_HNS_Gaven_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Maik!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Beth - Ass-Trainer F, Route 26
MatchCall_HNS_Beth_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Dea!\p"
	.string "Gehörst du zu den Menschen, die\n"
	.string "oft in Pokémon-Center gehen?\p"
	.string "Ich gehe täglich. Sich um das\n"
	.string "Wohlergehen seiner Pokémon zu\l"
	.string "kümmern, gehört zu den Grundlagen\l"
	.string "eines Pokémon -Trainers.$"

MatchCall_HNS_Beth_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Dea!\p"
	.string "Erinnerst du dich an mein süßes\n"
	.string "{STR_VAR_3}?\p"
	.string "{STR_VAR_3} rennt sehr schnell.\p"
	.string "Es ist wahrlich berauschend auf\n"
	.string "ihm zu reiten, wenn es loslegt.$"

MatchCall_HNS_Beth_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Dea!\p"
	.string "Lass uns wieder mal kämpfen!$"

MatchCall_HNS_Beth_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Dea!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Jose - Vogelfänger, Route 27
MatchCall_HNS_Jose_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Geht es deinen Pokémon gut?\p"
	.string "Mein {STR_VAR_3} strotzt vor\n"
	.string "Energie.\p"
	.string "Hebt es ab, kommt es für eine Weile\n"
	.string "nicht wieder.$"

MatchCall_HNS_Jose_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Sperr die Ohren auf, die Stange\n"
	.string "meines {STR_VAR_3}s riecht\l"
	.string "verlockend.\p"
	.string "Der Duft bringt meine\n"
	.string "Geschmacksnerven in Ekstase!$"

MatchCall_HNS_Jose_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Vor geraumer Zeit schlug mein\n"
	.string "Porenta ein {STR_VAR_3} K.O.\p"
	.string "Du hättest sehen sollen, wie grazil\n"
	.string "Porenta mit seiner Stange umgeht!\p"
	.string "Einfach unfassbar!$"

MatchCall_HNS_Jose_FoundItem::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Mein Porenta hatte etwas Schönes\n"
	.string "im Schnabel.\p"
	.string "Wie versprochen, gehört es dir.\p"
	.string "Hol mich auf Route 27\n"
	.string "ein, und ich lass es\l"
	.string "dich haben.$"

MatchCall_HNS_Jose_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Reena - Ass-Trainer F, Route 27
MatchCall_HNS_Reena_General1::
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Bea.\p"
	.string "Sag mal, wie geht’s deinen\n"
	.string "Pokémon?\p"
	.string "Was? Toll? Ach so…\p"
	.string "Was? Meine Pokémon?\p"
	.string "Natürlich geht’s ihnen\n"
	.string "gut! Was für eine Frage\l"
	.string "ist das denn?$"

MatchCall_HNS_Reena_General2::
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Bea.\p"
	.string "Hör zu…\p"
	.string "Erinnerst du dich an mein\n"
	.string "{STR_VAR_3}?\p"
	.string "Ja, genau. Das süße {STR_VAR_3}.\p"
	.string "Meinst du nicht auch, dass es\n"
	.string "perfekt zu mir passt?$"

MatchCall_HNS_Reena_General3::
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Bea.\p"
	.string "Sei nicht zu stolz, dass du mich\n"
	.string "zufällig geschlagen hast…\p"
	.string "Das war Dusel!$"

MatchCall_HNS_Reena_Battle::
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Bea.\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Alex - Kämpferin, Route 13
MatchCall_HNS_Alex_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Johann!\p"
	.string "Meine stolzen Pokémon\n"
	.string "werden von Tag zu Tag schärfer.\p"
	.string "{STR_VAR_3} wird\n"
	.string "richtig stark!$"

MatchCall_HNS_Alex_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab gehört, andere\n"
	.string "Regionen haben Könige und\l"
	.string "Königinnen. Wieso hat\p"
	.string "Kanto keine Königsfamilie?$"

MatchCall_HNS_Alex_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Johann!\p"
	.string "Meine stolzen Pokémon sind bereit\n"
	.string "für einen Rückkampf! Komm zu Route\l"
	.string "13!$"

@ Riley - Rowdy, Route 17
MatchCall_HNS_Riley_General1::
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Hannes.\p"
	.string "Die Radstrecke ist die beste.\n"
	.string "Nichts geht über den Wind\l"
	.string "im Gesicht.\p"
	.string "{STR_VAR_3} liebt das\n"
	.string "Tempo auch!$"

MatchCall_HNS_Riley_General2::
	.string "Yo, {PLAYER}!\p"
	.string "Ihr Johto-Kids sind gar nicht so\n"
	.string "übel. Hab euch wohl unterschätzt.\p"
	.string "Aber lass es dir nicht zu\n"
	.string "Kopf steigen!$"

MatchCall_HNS_Riley_Battle::
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Hannes.\p"
	.string "Komm runter zur Radstrecke!\n"
	.string "Ich will einen Rückkampf!$"

@ Trevor - Jongleur, Route 14
MatchCall_HNS_Trevor_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Reinhold.\p"
	.string "Wusstest du, dass Pokémon\n"
	.string "freundlicher werden, wenn man\l"
	.string "an denkwürdigen Orten trainiert?\p"
	.string "{STR_VAR_3} scheint es\n"
	.string "hier zu mögen.$"

MatchCall_HNS_Trevor_General2::
	.string "Hi, {PLAYER}!\p"
	.string "Manche Pokémon-Attacken\n"
	.string "sind stärker, wenn dein\p"
	.string "Pokémon dir gegenüber\n"
	.string "freundlicher ist!$"

MatchCall_HNS_Trevor_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Reinhold.\p"
	.string "Meine Freunde sind bereit zum\n"
	.string "Kampf! Schau vorbei auf Route 14!$"

@ Kyle - Angler, Route 12
MatchCall_HNS_Kyle_General1::
	.string "Wer ist da dran?!\n"
	.string "Hab ich dich angerufen?\p"
	.string "Hier ist Alain. Vergiss das nicht!$"

MatchCall_HNS_Kyle_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Erinnerst du dich?\n"
	.string "An die Geheimnisse des Angelns?$"

MatchCall_HNS_Kyle_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alain.\p"
	.string "Ich hab ein paar starke\n"
	.string "neue Pokémon geangelt!\p"
	.string "Komm zu Route 12 für\n"
	.string "einen Kampf!$"

@ Carter - Pokéfan, Route 14
MatchCall_HNS_Carter_General1::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Ernst.\p"
	.string "Ich sammle seltene\n"
	.string "Starter-Pokémon.\p"
	.string "Mein {STR_VAR_3} ist mein\n"
	.string "neuester Stolz!$"

MatchCall_HNS_Carter_General2::
	.string "Hi, {PLAYER}!\p"
	.string "Wusstest du, dass es Starter-\n"
	.string "Pokémon aus vielen\l"
	.string "verschiedenen Regionen gibt?\p"
	.string "Ich will sie alle\n"
	.string "sammeln!$"

MatchCall_HNS_Carter_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ernst.\p"
	.string "Ich hab neue Starter zum\n"
	.string "Vorzeigen! Komm zu\l"
	.string "Route 14!$"

@ Hillary - Expertin, Route 15
MatchCall_HNS_Hillary_General1::
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Lehrerin Sylvia.\p"
	.string "Wieso bist du nicht in der Schule?$"

MatchCall_HNS_Hillary_General2::
	.string "Hallo, {PLAYER}.\p"
	.string "Spielst du Spiele, statt\n"
	.string "Hausaufgaben zu machen?$"

MatchCall_HNS_Hillary_Battle::
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Sylvia.\p"
	.string "Meine Pokémon haben die\n"
	.string "nächste Stufe erreicht!\p"
	.string "Komm uns auf Route 15 testen!$"

@ Rob - Käfersammler, Route 2
MatchCall_HNS_Rob_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Götz!\p"
	.string "Der Vertania-Wald ist voller\n"
	.string "cooler Käfer!$"

MatchCall_HNS_Rob_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab einen Käfer-Arena-\n"
	.string "leiter im Vertania-Wald gesehen!$"

MatchCall_HNS_Rob_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Götz!\p"
	.string "Mein Käfer-Team ist stärker\n"
	.string "als je zuvor!\p"
	.string "Komm zu Route 2 für einen\n"
	.string "Rückkampf!$"

@ Nicole - Schwimmerin, Route 20
MatchCall_HNS_Nicole_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Elke!\p"
	.string "Die Wellen sind heute toll!\n"
	.string "Meine Pokémon schwimmen gern\l"
	.string "im offenen Meer.\p"
	.string "{STR_VAR_3} wird\n"
	.string "so schnell!$"

MatchCall_HNS_Nicole_General2::
	.string "Hi, {PLAYER}!\p"
	.string "Schwimmen mit Pokémon ist\n"
	.string "die beste Übung.$"

MatchCall_HNS_Nicole_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Elke!\p"
	.string "Meine Wasser-Pokémon wollen\n"
	.string "unbedingt kämpfen!\p"
	.string "Komm zu Route 20!$"

@ Billy - Schulkind, Route 15
MatchCall_HNS_Billy_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Sandro.\p"
	.string "Ich hab im Unterricht\n"
	.string "Kampfstrategien gelernt.\p"
	.string "{STR_VAR_3} und ich haben\n"
	.string "sie geübt!$"

MatchCall_HNS_Billy_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Bald sind Prüfungen, aber\n"
	.string "ich würde lieber kämpfen.\p"
	.string "Buchwissen ist nicht\n"
	.string "alles, oder?$"

MatchCall_HNS_Billy_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Sandro.\p"
	.string "Ich hab neue Tricks gelernt!\n"
	.string "Komm zu Route 15!$"

@ Kenny - Wanderer, Route 13
MatchCall_HNS_Kenny_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Hilmar.\p"
	.string "Wurden wirklich alle Berge\n"
	.string "von Ozeanen und Flüssen geformt?$"

MatchCall_HNS_Kenny_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Hier ist Hilmar.\n"
	.string "Ich war im Marmoria-Museum!\p"
	.string "Wusstest du, dass ganz Kanto\n"
	.string "einst unter Wasser stand?$"

MatchCall_HNS_Kenny_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Hilmar.\p"
	.string "Ich hab hart in den Bergen\n"
	.string "trainiert!\p"
	.string "Komm zu Route 13 für\n"
	.string "einen Kampf!$"

@ Joel - Rowdy, Route 17
MatchCall_HNS_Joel_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Manuel.\p"
	.string "Ich arbeite daran, im\n"
	.string "Kampf cool auszusehen.\p"
	.string "{STR_VAR_3} hat ein paar\n"
	.string "schicke neue Attacken!$"

MatchCall_HNS_Joel_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Hier ist Manuel.\p"
	.string "Es gab einen Unfall auf der\n"
	.string "Radstrecke.\p"
	.string "Sicher zu sein, ist das\n"
	.string "Coolste, was man sein kann.$"

MatchCall_HNS_Joel_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Manuel.\p"
	.string "Ich seh cool aus und kämpfe\n"
	.string "cool! Komm zur Radstrecke!$"

@ Charles - Rowdy, Route 17
MatchCall_HNS_Charles_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Fridolin.\p"
	.string "Ich war so etwas wie ein\n"
	.string "Herzensbrecher in Einall.\p"
	.string "Jetzt bin ich ein Highway-Star!$"

MatchCall_HNS_Charles_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Die Radstrecke bei Nacht ist\n"
	.string "etwas ganz Besonderes.\p"
	.string "Die Straßenlaternen und der\n"
	.string "Wind… das ist Freiheit!$"

MatchCall_HNS_Charles_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Fridolin.\p"
	.string "Die Highway-Stars wollen\n"
	.string "Rache! Komm zur\l"
	.string "Radstrecke!$"
