@ Crystal-accurate phone dialogue for HnS rematch trainers
@ Greetings from Crystal callee/caller files prepended to each text

@ Joey - Knirps, Route 30
MatchCall_HNS_Joey_General1::
	.string "Yo, {PLAYER}!\n"
	.string "Wie geht’s dir?\p"
	.string "Wie geht’s deinen Pokémon?\p"
	.string "Mein {STR_VAR_3} brennt drauf\n"
	.string "loszulegen, wie immer.\p"
	.string "Es ist das einzige, das ich\n"
	.string "habe. Ich werde ein großer\l"
	.string "Trainer mit ihm!$"

MatchCall_HNS_Joey_General2::
	.string "Yo, {PLAYER}!\n"
	.string "Hast du ’ne Minute?\p"
	.string "Mein {STR_VAR_3} sieht\n"
	.string "schärfer aus als zuvor!\p"
	.string "Ich bezweifle, dass es ein\n"
	.string "Pokémon gibt, das so cool\l"
	.string "ist wie er!$"

MatchCall_HNS_Joey_General3::
	.string "Yo, {PLAYER}!\n"
	.string "Wie geht’s dir?\p"
	.string "Ich schau mir gerade\n"
	.string "{STR_VAR_3}s Attacken an\l"
	.string "und plane Strategien.\p"
	.string "Wenn mir was Gutes einfällt,\n"
	.string "lass uns kämpfen!$"

MatchCall_HNS_Joey_Battle::
	.string "Yo, {PLAYER}!\p"
	.string "Lass uns treffen und\n"
	.string "kämpfen!\p"
	.string "Ich verspreche, es wird\n"
	.string "anders sein!$"

@ Wade - Käfersammler, Route 31
MatchCall_HNS_Wade_General1::
	.string "{PLAYER}, hallo!\p"
	.string "Wie geht’s deinen Pokémon?\p"
	.string "Meine Pokémon haben zu\n"
	.string "viel Energie übrig.\p"
	.string "Das wird langsam zum Problem.\p"
	.string "Von all meinen Pokémon ist\n"
	.string "{STR_VAR_3} am schwersten\l"
	.string "zu bändigen.\p"
	.string "Mit ihm zu arbeiten ist\n"
	.string "anstrengend.$"

MatchCall_HNS_Wade_General2::
	.string "{PLAYER}, hallo!\n"
	.string "Ist das Wetter nicht schön?\p"
	.string "Wachsen deine Pokémon?\p"
	.string "Meine Pokémon wachsen mir\n"
	.string "ein bisschen zu schnell.\l"
	.string "Das ist überwältigend!\p"
	.string "{STR_VAR_3} wächst\n"
	.string "besonders schnell.\p"
	.string "Ich glaube, das wird hart.$"

MatchCall_HNS_Wade_General3::
	.string "{PLAYER}, hallo!\p"
	.string "Ach ja, wir haben ein wildes\n"
	.string "{STR_VAR_3} mit einem\l"
	.string "Treffer besiegt.\p"
	.string "Es ging so leicht unter,\n"
	.string "dass es mir fast leid tat\l"
	.string "für den Armen.$"

MatchCall_HNS_Wade_FoundItem::
	.string "{PLAYER}, hallo!\p"
	.string "Ich hab allerlei\n"
	.string "Beeren gefunden.\p"
	.string "Wenn du willst, teile ich\n"
	.string "welche mit dir.\p"
	.string "Ich warte auf\n"
	.string "Route 31.$"

MatchCall_HNS_Wade_Battle::
	.string "{PLAYER}, hallo!\p"
	.string "Hast du Lust auf einen\n"
	.string "Pokémon-Kampf?\p"
	.string "Es wird nicht wie letztes\n"
	.string "Mal!$"

@ Ralph - Angler, Route 32
MatchCall_HNS_Ralph_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Wie läuft’s Angeln?\p"
	.string "Kümmerst du dich gut um\n"
	.string "deine Pokémon?\p"
	.string "Man muss gut sein zu\n"
	.string "seinen Partnern!$"

MatchCall_HNS_Ralph_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Ich verbringe mehr Zeit\n"
	.string "mit meinem {STR_VAR_3}\l"
	.string "als mit meinen Kindern.\p"
	.string "Das ist irgendwie traurig,\n"
	.string "ehrlich gesagt.$"

MatchCall_HNS_Ralph_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hör dir das an!\p"
	.string "Ich hab gerade ein wildes\n"
	.string "{STR_VAR_3} besiegt.\p"
	.string "Ich hab’s meinem Kind erzählt,\n"
	.string "aber es meinte, das könnte\l"
	.string "es locker auch.\p"
	.string "Mann, ist der frech\n"
	.string "geworden…$"

MatchCall_HNS_Ralph_Battle::
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Liz - Picknicker, Route 32
MatchCall_HNS_Liz_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Ich hatte etwas Zeit, also\l"
	.string "hab ich dich angerufen.\p"
	.string "Wie geht’s denn deinen\n"
	.string "Pokémon?\p"
	.string "Ich bringe mein {STR_VAR_3}\n"
	.string "jeden Tag ins Pokémon\l"
	.string "Center in Violet,\p"
	.string "also geht’s ihm\n"
	.string "fantastisch!\p"
	.string "Ich bin mit der\n"
	.string "Empfangsdame befreundet!$"

MatchCall_HNS_Liz_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Du musst dir das anhören.\p"
	.string "Mein {STR_VAR_3} ist so\n"
	.string "niedlich!\p"
	.string "Es will sich immer an\n"
	.string "mich schmiegen!$"

MatchCall_HNS_Liz_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Hör mal, hör mal!\p"
	.string "Findest du nicht, dass Falk\n"
	.string "von der Violet-Arena cool\l"
	.string "und gutaussehend ist?\p"
	.string "Aber man sagt, sein Vater,\n"
	.string "der auf Reisen trainiert,\l"
	.string "ist noch viel cooler und\l"
	.string "gutaussehender als Falk.\p"
	.string "Ich wünschte, ich könnte ihn treffen!$"

MatchCall_HNS_Liz_Battle::
	.string "Hi, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Anthony - Wanderer, Route 33
MatchCall_HNS_Anthony_General1::
	.string "Hey, {PLAYER}!\p"
	.string "Sind deine Pokémon noch so\n"
	.string "wild wie eh und je?\p"
	.string "Mein {STR_VAR_3} und ich, wir\n"
	.string "haben Energie im Überfluss.\p"
	.string "Wir wandern jeden Tag auf\n"
	.string "Berge, um unsere ganze\l"
	.string "Energie loszuwerden.$"

MatchCall_HNS_Anthony_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Neulich hab ich zugesehen,\n"
	.string "wie mein {STR_VAR_3}\l"
	.string "Beeren gegessen hat.\p"
	.string "Es sah so aus, als würde es\n"
	.string "das Essen genießen, also\l"
	.string "hab ich auch probiert.\p"
	.string "Ich weiß nicht, ob Menschen\n"
	.string "das essen sollten, aber\l"
	.string "es war lecker!$"

MatchCall_HNS_Anthony_General3::
	.string "Hey, {PLAYER}!\p"
	.string "In letzter Zeit begegne ich\n"
	.string "oft wilden {STR_VAR_3}\l"
	.string "ziemlich häufig.\p"
	.string "Die sind leicht zu\n"
	.string "bewältigen.$"

MatchCall_HNS_Anthony_Battle::
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Todd - Camper, Route 34
MatchCall_HNS_Todd_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Was geht?\p"
	.string "Wie ziehst du deine\n"
	.string "Pokémon groß?\p"
	.string "Ich mach so allerlei,\n"
	.string "wie sie in die\l"
	.string "Kinderkrippe geben und\p"
	.string "sie mit Items\n"
	.string "abhärten.$"

MatchCall_HNS_Todd_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Was geht?\p"
	.string "Mein {STR_VAR_3} sieht\n"
	.string "immer mehr aus wie ich.\p"
	.string "Es wird immer niedlicher!$"

MatchCall_HNS_Todd_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Was geht?\p"
	.string "Und, weißt du was?\p"
	.string "Jetzt besiegen wir\n"
	.string "{STR_VAR_3} mühelos.\p"
	.string "Ich sollte die\n"
	.string "Rosalia-Arena fordern.$"

MatchCall_HNS_Todd_Battle::
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Gina - Picknicker, Route 34
MatchCall_HNS_Gina_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Wie geht’s dir?\p"
	.string "Sind deine Pokémon noch\n"
	.string "stark?\p"
	.string "Ich trainiere jeden Tag\n"
	.string "mit {STR_VAR_3}.$"

MatchCall_HNS_Gina_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Wie geht’s dir?\p"
	.string "Mein {STR_VAR_3} und ich\n"
	.string "verstehen uns immer besser\l"
	.string "miteinander.$"

MatchCall_HNS_Gina_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Wie geht’s dir?\p"
	.string "Wir haben ein wildes\n"
	.string "{STR_VAR_3} bekämpft und\l"
	.string "es in einem knappen\l"
	.string "Kampf besiegt.\p"
	.string "Wir kommen langsam in\n"
	.string "Fahrt!$"

MatchCall_HNS_Gina_Battle::
	.string "Hi, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Irwin - Jongleur, Route 35
MatchCall_HNS_Irwin_General1::
	.string "Äh, hallo, {PLAYER}?\n"
	.string "Hier ist dein Kumpel Erich!\p"
	.string "Ich hab neulich den\n"
	.string "erstaunlichsten Kampf gesehen!\p"
	.string "Ich wünschte, ich könnte so\n"
	.string "kämpfen.\p"
	.string "Ach halt, ich kann! Ich\n"
	.string "brauch nur jemanden zum Kämpfen!$"

MatchCall_HNS_Irwin_General2::
	.string "Äh, hallo, {PLAYER}?\n"
	.string "Hier ist dein Kumpel Erich!\p"
	.string "Hehe, ich hab sofort angerufen!\p"
	.string "Ich glaube, wir können gute\n"
	.string "Freunde werden!$"

MatchCall_HNS_Irwin_General3::
	.string "Äh, hallo, {PLAYER}?\n"
	.string "Hier ist dein Kumpel Erich!\p"
	.string "Von deinen Abenteuern zu\n"
	.string "hören, rührt meine Seele!\p"
	.string "Ganz bestimmt!$"

MatchCall_HNS_Irwin_Battle::
	.string "Äh, hallo, {PLAYER}?\n"
	.string "Hier ist dein Kumpel Erich!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Arnie - Käfersammler, Route 35
MatchCall_HNS_Arnie_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Wie läuft’s?\p"
	.string "Ich wette, deine Pokémon sind\n"
	.string "viel stärker als vorher.$"

MatchCall_HNS_Arnie_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Wie läuft’s?\p"
	.string "Ich bin immer mit meinem\n"
	.string "{STR_VAR_3} zusammen!\p"
	.string "Es ist so niedlich!\n"
	.string "Ich liebe es einfach!$"

MatchCall_HNS_Arnie_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Wie läuft’s?\p"
	.string "Um mal das Thema zu wechseln,\n"
	.string "ich hab dieses {STR_VAR_3}\l"
	.string "zum ersten Mal gesehen.\p"
	.string "Es war leicht zu besiegen,\n"
	.string "ehrlich gesagt.$"

MatchCall_HNS_Arnie_Battle::
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Alan - Schulkind, Route 36
MatchCall_HNS_Alan_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "{PLAYER}, ziehst du deine\n"
	.string "Pokémon richtig groß?\p"
	.string "Ich hab in einem Buch gelesen,\n"
	.string "dass man jedes gefangene\l"
	.string "Pokémon mit Liebe und\l"
	.string "Sorgfalt aufziehen sollte.$"

MatchCall_HNS_Alan_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "Mein {STR_VAR_3} wird\n"
	.string "stärker, genau wie ich\l"
	.string "berechnet habe!$"

MatchCall_HNS_Alan_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "Übrigens, wir haben neulich\n"
	.string "ein wildes {STR_VAR_3}\l"
	.string "besiegt.\p"
	.string "Das Vorab-Büffeln hat sich\n"
	.string "gelohnt!$"

MatchCall_HNS_Alan_FoundItem::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "Hehehe, ich hab was\n"
	.string "Schönes gefunden!\p"
	.string "Du kannst es haben!\p"
	.string "Wieso kommst du nicht zu\n"
	.string "Route 36 und holst es ab?$"

MatchCall_HNS_Alan_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Dana - Göre, Route 38
MatchCall_HNS_Dana_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Mein {STR_VAR_3} steckt so\n"
	.string "voller Energie, es ist ein\l"
	.string "bisschen unheimlich.\p"
	.string "Wie geht’s deinen Pokémon\n"
	.string "so?$"

MatchCall_HNS_Dana_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Mein {STR_VAR_3} wird\n"
	.string "immer hübscher!\p"
	.string "Ich hab schon jede Menge\n"
	.string "Fotos gemacht!$"

MatchCall_HNS_Dana_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Es dauerte nur einen Moment,\n"
	.string "ein wildes {STR_VAR_3} zu besiegen.\p"
	.string "Das liegt bestimmt daran, dass\n"
	.string "du mir letztes Mal ein paar\l"
	.string "Kampftipps gegeben hast.$"

MatchCall_HNS_Dana_FoundItem::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Weißt du was?\n"
	.string "Ich hab ein tolles Geschenk!\p"
	.string "Wie versprochen, gehört es dir!\n"
	.string "Ich bin sicher, es gefällt dir.\p"
	.string "Komm es dir holen! Ich warte\n"
	.string "auf Route 38!$"

MatchCall_HNS_Dana_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Chad - Schulkind, Route 38
MatchCall_HNS_Chad_General1::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Lutz!\p"
	.string "Wie geht’s deinen Pokémon\n"
	.string "so?\p"
	.string "Du kennst Prof. Eich, also\n"
	.string "geht’s deinen Pokémon\l"
	.string "natürlich gut!\p"
	.string "Meinen Pokémon geht’s auch\n"
	.string "gut.\p"
	.string "Aber ich versuche ja auch,\n"
	.string "ein Pokémon-Professor zu\l"
	.string "werden.$"

MatchCall_HNS_Chad_General2::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Lutz!\p"
	.string "Ich beobachte neuerdings\n"
	.string "wilde {STR_VAR_3}.\p"
	.string "Ich lerne allerlei neue\n"
	.string "Dinge durch meine\l"
	.string "Beobachtungen.\p"
	.string "Ich wünschte, ich könnte\n"
	.string "bald ein Pokémon-Forscher\l"
	.string "wie Prof. Eich werden.$"

MatchCall_HNS_Chad_General3::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Lutz!\p"
	.string "Ich lerne fleißig, damit\n"
	.string "Prof. Eich mich zu seinem\l"
	.string "Assistenten macht!$"

MatchCall_HNS_Chad_Battle::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Lutz!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Derek - Pokéfan M, Route 39
MatchCall_HNS_Derek_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Du musst dir das anhören!\p"
	.string "Mein liebenswertes {STR_VAR_3}\n"
	.string "hat mich angeschaut und gegrinst!\p"
	.string "Das liegt bestimmt daran, dass\n"
	.string "unsere Herzen im Gleichklang\l"
	.string "schlagen!$"

MatchCall_HNS_Derek_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Hör dir das an.\p"
	.string "Mein {STR_VAR_3} grinst\n"
	.string "glücklich, wenn ich seine\l"
	.string "Wange kneife.\p"
	.string "Aber es grinst für niemand\n"
	.string "sonst.\p"
	.string "Ich muss was Besonderes sein.$"

MatchCall_HNS_Derek_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Wie geht’s deinem Pikachu\n"
	.string "so?\p"
	.string "Lass uns treffen und mit\n"
	.string "unseren Pikachu angeben!$"

MatchCall_HNS_Derek_FoundItem::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Ich würde dir gern ein\n"
	.string "Nugget geben.\p"
	.string "Ich bin auf Route 39.\n"
	.string "Komm es dir holen!$"

MatchCall_HNS_Derek_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Tully - Angler, Route 42
MatchCall_HNS_Tully_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Wie läuft deine Reise\n"
	.string "so voran?\p"
	.string "Ich kann mich beim Angeln\n"
	.string "nicht beklagen!$"

MatchCall_HNS_Tully_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Mein {STR_VAR_3} ist wieder\n"
	.string "gewachsen.\p"
	.string "Es war nur so groß, als ich\n"
	.string "es gefangen hab, aber jetzt\l"
	.string "ist es viel größer.$"

MatchCall_HNS_Tully_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Ach ja, ich hab ein wildes\n"
	.string "{STR_VAR_3} besiegt.\p"
	.string "Es war riesig, ungefähr so\n"
	.string "groß sogar.\p"
	.string "Heh, ich schätze, man sieht\n"
	.string "das am Telefon nicht…$"

MatchCall_HNS_Tully_FoundItem::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Ich hab was Schönes am\n"
	.string "Wasser gefunden.\p"
	.string "Wie versprochen, gehört\n"
	.string "es dir.\p"
	.string "Ich warte auf\n"
	.string "Route 42.$"

MatchCall_HNS_Tully_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Brent - Pokémaniac, Route 43
MatchCall_HNS_Brent_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Taro!\p"
	.string "Ach ja, ich hab dich neulich\n"
	.string "aus einem Pokémon Center\l"
	.string "kommen sehen.\p"
	.string "Du heilst deine Pokémon\n"
	.string "regelmäßig, oder?\l"
	.string "Ich bin beeindruckt.\p"
	.string "Heh, mein {STR_VAR_3} ist\n"
	.string "so zäh, es muss nicht oft\l"
	.string "zu Pokémon Centern\l"
	.string "gehen. Heheh!$"

MatchCall_HNS_Brent_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Taro!\p"
	.string "Ach ja, ich hab vor einer\n"
	.string "Weile ein extrem seltenes\l"
	.string "Pokémon getauscht.\p"
	.string "Willst du wissen, was\n"
	.string "das ist?\p"
	.string "Hehe, das bleibt mein\n"
	.string "Geheimnis!$"

MatchCall_HNS_Brent_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Taro!\p"
	.string "Wusstest du schon…?\p"
	.string "Bill kommt ursprünglich aus\n"
	.string "Rosalia City.\p"
	.string "Bill ist offenbar nicht\n"
	.string "sehr gut im Kämpfen.$"

MatchCall_HNS_Brent_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Taro!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Tiffany - Picknicker, Route 43
MatchCall_HNS_Tiffany_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ilona!\p"
	.string "Geht’s deinen Pokémon\n"
	.string "gut?\p"
	.string "Ich hoffe, du bringst sie\n"
	.string "jeden Tag ins Pokémon Center.\p"
	.string "Überfordere sie nicht zu sehr.\p"
	.string "Mein {STR_VAR_3} ist niedlich\n"
	.string "und quirlig, genau weil ich\l"
	.string "es jeden Tag ins Pokémon\l"
	.string "Center bringe.$"

MatchCall_HNS_Tiffany_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ilona!\p"
	.string "Mein {STR_VAR_3} ist doch\n"
	.string "goldig, findest du nicht?\p"
	.string "Ich schlaf immer mit ihm…\n"
	.string "es ist so flauschig und warm!$"

MatchCall_HNS_Tiffany_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ilona!\p"
	.string "Ach, und wir mussten vor\n"
	.string "einer Weile gegen ein wildes\l"
	.string "{STR_VAR_3} kämpfen…\p"
	.string "Mein Pixi wär beinahe\n"
	.string "ohnmächtig geworden!\p"
	.string "Ist das nicht schrecklich?\n"
	.string "Ich hasse diese fiesen\l"
	.string "{STR_VAR_3}!$"

MatchCall_HNS_Tiffany_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ilona!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Vance - Vogelfänger, Route 44
MatchCall_HNS_Vance_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Arno!\p"
	.string "Geht’s dir und deinen Pokémon\n"
	.string "gut?\p"
	.string "Mein {STR_VAR_3} sieht aus,\n"
	.string "als würde es stark genug\p"
	.string "um es mit den legendären\n"
	.string "Vogel-Pokémon aufzunehmen!$"

MatchCall_HNS_Vance_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Arno!\p"
	.string "Mein {STR_VAR_3} ist\n"
	.string "stärker geworden.\p"
	.string "Wir sind endlich abgehoben!$"

MatchCall_HNS_Vance_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Arno!\p"
	.string "Wir können {STR_VAR_3}\n"
	.string "locker besiegen!\p"
	.string "…Wie? Du auch?\n"
	.string "Ist das nicht toll?$"

MatchCall_HNS_Vance_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Arno!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Wilton - Angler, Route 44
MatchCall_HNS_Wilton_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Sind deine Pokémon\n"
	.string "gewachsen?\p"
	.string "Mein {STR_VAR_3} ist ganz\n"
	.string "schön gewachsen.$"

MatchCall_HNS_Wilton_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Mein {STR_VAR_3} ist\n"
	.string "beeindruckend gewachsen!\p"
	.string "Meine Angelkünste haben\n"
	.string "sich auch verbessert!$"

MatchCall_HNS_Wilton_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Wir haben ein wildes\n"
	.string "{STR_VAR_3} besiegt…\p"
	.string "Weißt du, Angeln macht mir\n"
	.string "mehr Spaß als wilde Pokémon\l"
	.string "zu besiegen.$"

MatchCall_HNS_Wilton_FoundItem::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Ich hab beim Angeln ein\n"
	.string "Item geschnappt.\p"
	.string "Komm es dir holen auf\n"
	.string "Route 44.$"

MatchCall_HNS_Wilton_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Kenji - Schwarzgurt, Route 45
MatchCall_HNS_Kenji_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Udo!\p"
	.string "{PLAYER}! Schönes Wetter,\n"
	.string "was?$"

MatchCall_HNS_Kenji_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Udo!\p"
	.string "Bist du noch auf\n"
	.string "deiner Reise?\p"
	.string "Ich bleibe meinem Training\n"
	.string "treu ergeben.\p"
	.string "Oooooaaarrrgh!$"

MatchCall_HNS_Kenji_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Udo!\p"
	.string "Ich trainiere gerade.\p"
	.string "Tut mir leid, ruf mich ein\n"
	.string "anderes Mal wieder an.\p"
	.string "Oooooaaarrrgh!$"

MatchCall_HNS_Kenji_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Udo!\p"
	.string "Ich mach gerade Pause!\p"
	.string "Wieso schaust du nicht vorbei,\n"
	.string "wenn du Zeit hast?$"

MatchCall_HNS_Kenji_FoundItem::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Udo!\p"
	.string "Ich mach gerade Pause vom\n"
	.string "Training.\p"
	.string "Ich hab was Gutes gefunden.\n"
	.string "Komm es dir holen, wenn du willst!$"

@ Parry - Wanderer, Route 45
MatchCall_HNS_Parry_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Günter!\p"
	.string "Sehen deine Pokémon gut\n"
	.string "aus?\p"
	.string "Mein {STR_VAR_3} und ich…\n"
	.string "wir sehen ziemlich schick\l"
	.string "aus! Hahahah!$"

MatchCall_HNS_Parry_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Günter!\p"
	.string "Nichts kommt an mein\n"
	.string "{STR_VAR_3} jetzt ran.$"

MatchCall_HNS_Parry_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Günter!\p"
	.string "Ja, wir haben ein wildes\n"
	.string "{STR_VAR_3} besiegt!\p"
	.string "Das war ok, aber ich wollte\n"
	.string "es eigentlich fangen…$"

MatchCall_HNS_Parry_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Günter!\p"
	.string "Du kämpfst doch wieder\n"
	.string "mit mir, oder?$"

@ Erin - Picknicker, Route 46
MatchCall_HNS_Erin_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Lotte!\p"
	.string "Ziehst du deine\n"
	.string "Pokémon groß?\p"
	.string "Mein {STR_VAR_3} sieht\n"
	.string "gut aus!$"

MatchCall_HNS_Erin_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Lotte!\p"
	.string "Mein {STR_VAR_3} ist viel\n"
	.string "stärker als zuvor!$"

MatchCall_HNS_Erin_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Lotte!\p"
	.string "Und, und… ich hab gerade\n"
	.string "{STR_VAR_3} besiegt!\p"
	.string "Ich hab mein Pokémon\n"
	.string "richtig großgezogen!$"

MatchCall_HNS_Erin_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Lotte!\p"
	.string "Ich arbeite hart daran, mein\n"
	.string "Pokémon großzuziehen!\p"
	.string "Komm zurück für einen\n"
	.string "weiteren Kampf!$"

@ Jack - Schulkind, National Park
MatchCall_HNS_Jack_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Julius!\p"
	.string "Wie geht’s deinen Pokémon\n"
	.string "so?\p"
	.string "Mein {STR_VAR_3} ist so\n"
	.string "neugierig, das wird zum Problem.\p"
	.string "Vielleicht ist es wie ich…$"

MatchCall_HNS_Jack_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Julius!\p"
	.string "Die Intelligenz meines\n"
	.string "{STR_VAR_3} steigt stetig.\p"
	.string "Es könnte klüger sein\n"
	.string "als deins!$"

MatchCall_HNS_Jack_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Julius!\p"
	.string "Wusstest du schon?\p"
	.string "Wenn es regnet, schlägt\n"
	.string "sicher ein Donner ein.\p"
	.string "Mein Freund hat tolle Tipps\n"
	.string "gehört. Wenn er sie mir sagt,\l"
	.string "ruf ich dich sofort an und\l"
	.string "erzähl es dir.$"

MatchCall_HNS_Jack_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Julius!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Beverly - Pokéfan F, National Park
MatchCall_HNS_Beverly_General1::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Hältst du deine Pokémon\n"
	.string "glücklich?\p"
	.string "Mein {STR_VAR_3} ist gesund.\n"
	.string "Es isst jeden Tag eine Menge.$"

MatchCall_HNS_Beverly_General2::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Ich hab mein {STR_VAR_3}\n"
	.string "aufgehübscht und noch\l"
	.string "niedlicher gemacht!$"

MatchCall_HNS_Beverly_General3::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Sind deine Pokémon in\n"
	.string "Topform?\p"
	.string "Lass uns wieder über\n"
	.string "Pokémon quatschen.$"

MatchCall_HNS_Beverly_FoundItem::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Mein Mann hat ein paar\n"
	.string "Nuggets bekommen.\p"
	.string "Wenn du magst, kannst du\n"
	.string "eins als Dank haben, weil\l"
	.string "du mir geholfen hast.\p"
	.string "Ich bin im Nationalpark.\n"
	.string "Komm bitte vorbei, wenn\l"
	.string "du kannst.$"

MatchCall_HNS_Beverly_Battle::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Huey - Matrose, Olivine Lighthouse
MatchCall_HNS_Huey_General1::
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Nepomuk!\p"
	.string "Wie läuft’s?$"

MatchCall_HNS_Huey_General2::
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Nepomuk!\p"
	.string "Wir müssen irgendwann\n"
	.string "wieder kämpfen.\p"
	.string "Du kannst drauf wetten, dass\n"
	.string "ich dich weiter herausfordere,\l"
	.string "bis ich gewinne.$"

MatchCall_HNS_Huey_Battle::
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Nepomuk!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Gaven - Ass-Trainer M, Route 26
MatchCall_HNS_Gaven_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Maik!\p"
	.string "Wie geht’s deinen Pokémon\n"
	.string "so?\p"
	.string "Meinem {STR_VAR_3} geht’s so\n"
	.string "gut wie eh und je.\p"
	.string "Lass uns dranbleiben und\n"
	.string "Pokémon-Champions werden!$"

MatchCall_HNS_Gaven_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Maik!\p"
	.string "Mein {STR_VAR_3} ist\n"
	.string "vielleicht stärker, als ich dachte.\p"
	.string "Ich bezweifle, dass ich je ein\n"
	.string "Pokémon sehe, das besser\l"
	.string "ist als meins.$"

MatchCall_HNS_Gaven_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Maik!\p"
	.string "Ich grüble ständig darüber,\n"
	.string "wie ich dich schlagen kann.$"

MatchCall_HNS_Gaven_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Maik!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Beth - Ass-Trainer F, Route 26
MatchCall_HNS_Beth_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Dea!\p"
	.string "Bist du der Typ Mensch, der\n"
	.string "oft ins Pokémon Center\l"
	.string "geht?\p"
	.string "Ich geh jeden Tag. Auf die\n"
	.string "Gesundheit deiner Pokémon zu\l"
	.string "achten, gehört einfach dazu,\l"
	.string "ein Pokémon-Trainer zu sein.$"

MatchCall_HNS_Beth_General2::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Dea!\p"
	.string "Erinnerst du dich an mein\n"
	.string "süßes {STR_VAR_3}?\p"
	.string "{STR_VAR_3} läuft sehr\n"
	.string "schnell.\p"
	.string "Es ist berauschend, auf\n"
	.string "seinem Rücken zu reiten, wenn\l"
	.string "es richtig loslegt.$"

MatchCall_HNS_Beth_General3::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Dea!\p"
	.string "Lass uns irgendwann wieder\n"
	.string "kämpfen!$"

MatchCall_HNS_Beth_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Dea!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Jose - Vogelfänger, Route 27
MatchCall_HNS_Jose_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Sind deine Pokémon noch\n"
	.string "in Bestform?\p"
	.string "Mein {STR_VAR_3} hat zu\n"
	.string "viel Energie.\p"
	.string "Wenn es erstmal abhebt,\n"
	.string "kommt es eine ganze Weile\l"
	.string "nicht zurück.$"

MatchCall_HNS_Jose_General2::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Hör mal zu, mein\n"
	.string "{STR_VAR_3} hat einen\l"
	.string "wirklich köstlich\l"
	.string "duftenden Stock.\p"
	.string "Der Duft weckt meinen\n"
	.string "Appetit!$"

MatchCall_HNS_Jose_General3::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Vor einer Weile besiegte\n"
	.string "Porenta dieses {STR_VAR_3}.\p"
	.string "Du hättest sehen sollen, wie\n"
	.string "Porenta diesen Stock\l"
	.string "geschwungen hat.\p"
	.string "Erstaunliches Zeug!$"

MatchCall_HNS_Jose_FoundItem::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Mein Porenta hatte etwas\n"
	.string "Hübsches in seinem\l"
	.string "Schnabel.\p"
	.string "Wie versprochen, kannst\n"
	.string "du es haben.\p"
	.string "Hol mich auf Route 27\n"
	.string "ein, und ich lass es\l"
	.string "dich haben.$"

MatchCall_HNS_Jose_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Reena - Ass-Trainer F, Route 27
MatchCall_HNS_Reena_General1::
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Bea.\p"
	.string "Sag mal, wie geht’s deinen\n"
	.string "Pokémon?\p"
	.string "Was? Toll? Ach so…\p"
	.string "Was? Meine Pokémon?\p"
	.string "Natürlich geht’s ihnen\n"
	.string "gut! Was für eine Frage\l"
	.string "ist das denn?$"

MatchCall_HNS_Reena_General2::
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Bea.\p"
	.string "Hör zu, Schätzchen…\p"
	.string "Erinnerst du dich an\n"
	.string "mein {STR_VAR_3}?\p"
	.string "Ja, genau. Dieses\n"
	.string "reizende {STR_VAR_3}.\p"
	.string "Findest du nicht, es passt\n"
	.string "perfekt zu mir?$"

MatchCall_HNS_Reena_General3::
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Bea.\p"
	.string "Sei nicht so stolz, nur\n"
	.string "weil du mich zufällig\l"
	.string "besiegt hast…\p"
	.string "Das war ein Glückstreffer!$"

MatchCall_HNS_Reena_Battle::
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Bea.\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"

@ Alex - Kämpferin, Route 13
MatchCall_HNS_Alex_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Susanne!\p"
	.string "Meine stolzen Pokémon\n"
	.string "werden von Tag zu Tag schärfer.\p"
	.string "{STR_VAR_3} wird\n"
	.string "richtig stark!$"

MatchCall_HNS_Alex_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab gehört, andere\n"
	.string "Regionen haben Könige und\l"
	.string "Königinnen. Wieso hat\p"
	.string "Kanto keine Königsfamilie?$"

MatchCall_HNS_Alex_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Susanne!\p"
	.string "Meine stolzen Pokémon sind\n"
	.string "bereit für einen Rückkampf! Komm zu Route 13!$"

@ Riley - Rowdy, Route 17
MatchCall_HNS_Riley_General1::
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Urs.\p"
	.string "Die Radstrecke ist die beste.\n"
	.string "Nichts geht über den Wind\l"
	.string "im Gesicht.\p"
	.string "{STR_VAR_3} liebt das\n"
	.string "Tempo auch!$"

MatchCall_HNS_Riley_General2::
	.string "Yo, {PLAYER}!\p"
	.string "Ihr Johto-Kids sind gar nicht\n"
	.string "so übel. Hab euch wohl unterschätzt.\p"
	.string "Aber lass es dir nicht zu\n"
	.string "Kopf steigen!$"

MatchCall_HNS_Riley_Battle::
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Urs.\p"
	.string "Komm runter zur Radstrecke!\n"
	.string "Ich will einen Rückkampf!$"

@ Trevor - Jongleur, Route 14
MatchCall_HNS_Trevor_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Achim.\p"
	.string "Wusstest du, dass Pokémon\n"
	.string "freundlicher werden, wenn man\l"
	.string "an denkwürdigen Orten trainiert?\p"
	.string "{STR_VAR_3} scheint es\n"
	.string "hier zu mögen.$"

MatchCall_HNS_Trevor_General2::
	.string "Hi, {PLAYER}!\p"
	.string "Manche Pokémon-Attacken\n"
	.string "sind stärker, wenn dein\p"
	.string "Pokémon dir gegenüber\n"
	.string "freundlicher ist!$"

MatchCall_HNS_Trevor_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Achim.\p"
	.string "Meine Freunde sind bereit zum Kampf!\n"
	.string "Schau vorbei auf Route 14!$"

@ Kyle - Angler, Route 12
MatchCall_HNS_Kyle_General1::
	.string "Wer ist da dran?!\n"
	.string "Hab ich dich angerufen?\p"
	.string "Hier ist Alain. Vergiss das nicht!$"

MatchCall_HNS_Kyle_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Erinnerst du dich?\n"
	.string "An die Geheimnisse des Angelns?$"

MatchCall_HNS_Kyle_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alain.\p"
	.string "Ich hab ein paar starke\n"
	.string "neue Pokémon geangelt!\p"
	.string "Komm zu Route 12 für\n"
	.string "einen Kampf!$"

@ Carter - Pokéfan, Route 14
MatchCall_HNS_Carter_General1::
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Torben.\p"
	.string "Ich sammle seltene\n"
	.string "Starter-Pokémon.\p"
	.string "Mein {STR_VAR_3} ist mein\n"
	.string "neuester Stolz!$"

MatchCall_HNS_Carter_General2::
	.string "Hi, {PLAYER}!\p"
	.string "Wusstest du, dass es Starter-\n"
	.string "Pokémon aus vielen\l"
	.string "verschiedenen Regionen gibt?\p"
	.string "Ich will sie alle\n"
	.string "sammeln!$"

MatchCall_HNS_Carter_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Torben.\p"
	.string "Ich hab neue Starter zum\n"
	.string "Vorzeigen! Komm zu\l"
	.string "Route 14!$"

@ Hillary - Expertin, Route 15
MatchCall_HNS_Hillary_General1::
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Lehrerin Sylvia.\p"
	.string "Wieso bist du nicht in der Schule?$"

MatchCall_HNS_Hillary_General2::
	.string "Hallo, {PLAYER}.\p"
	.string "Spielst du Spiele, statt\n"
	.string "Hausaufgaben zu machen?$"

MatchCall_HNS_Hillary_Battle::
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Sylvia.\p"
	.string "Meine Pokémon haben die\n"
	.string "nächste Stufe erreicht!\p"
	.string "Komm uns auf Route 15 testen!$"

@ Rob - Käfersammler, Route 2
MatchCall_HNS_Rob_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Götz!\p"
	.string "Der Vertania-Wald ist voller\n"
	.string "cooler Käfer!$"

MatchCall_HNS_Rob_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab einen Käfer-Arena-\n"
	.string "leiter im Vertania-Wald gesehen!$"

MatchCall_HNS_Rob_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Götz!\p"
	.string "Mein Käfer-Team ist stärker\n"
	.string "als je zuvor!\p"
	.string "Komm zu Route 2 für einen\n"
	.string "Rückkampf!$"

@ Nicole - Schwimmerin, Route 20
MatchCall_HNS_Nicole_General1::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Gabrysia!\p"
	.string "Die Wellen sind heute toll!\n"
	.string "Meine Pokémon schwimmen gern\l"
	.string "im offenen Meer.\p"
	.string "{STR_VAR_3} wird\n"
	.string "so schnell!$"

MatchCall_HNS_Nicole_General2::
	.string "Hi, {PLAYER}!\p"
	.string "Schwimmen mit Pokémon ist\n"
	.string "die beste Übung.$"

MatchCall_HNS_Nicole_Battle::
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Gabrysia!\p"
	.string "Meine Wasser-Pokémon wollen\n"
	.string "unbedingt kämpfen!\p"
	.string "Komm zu Route 20!$"

@ Billy - Schulkind, Route 15
MatchCall_HNS_Billy_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Sandro.\p"
	.string "Ich hab im Unterricht\n"
	.string "Kampfstrategien gelernt.\p"
	.string "{STR_VAR_3} und ich haben\n"
	.string "sie geübt!$"

MatchCall_HNS_Billy_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Bald sind Prüfungen, aber\n"
	.string "ich würde lieber kämpfen.\p"
	.string "Buchwissen ist nicht\n"
	.string "alles, oder?$"

MatchCall_HNS_Billy_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Sandro.\p"
	.string "Ich hab neue Tricks gelernt!\n"
	.string "Komm zu Route 15!$"

@ Kenny - Wanderer, Route 13
MatchCall_HNS_Kenny_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Hilmar.\p"
	.string "Wurden wirklich alle Berge\n"
	.string "von Ozeanen und Flüssen geformt?$"

MatchCall_HNS_Kenny_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Hier ist Hilmar.\n"
	.string "Ich war im Marmoria-Museum!\p"
	.string "Wusstest du, dass ganz Kanto\n"
	.string "einst unter Wasser stand?$"

MatchCall_HNS_Kenny_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Hilmar.\p"
	.string "Ich hab hart in den Bergen\n"
	.string "trainiert!\p"
	.string "Komm zu Route 13 für\n"
	.string "einen Kampf!$"

@ Joel - Rowdy, Route 17
MatchCall_HNS_Joel_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Jonas.\p"
	.string "Ich arbeite daran, im\n"
	.string "Kampf cool auszusehen.\p"
	.string "{STR_VAR_3} hat ein paar\n"
	.string "schicke neue Attacken!$"

MatchCall_HNS_Joel_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Hier ist Jonas.\p"
	.string "Es gab einen Unfall auf der\n"
	.string "Radstrecke.\p"
	.string "Sicher zu sein, ist das\n"
	.string "Coolste, was man sein kann.$"

MatchCall_HNS_Joel_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Jonas.\p"
	.string "Ich seh cool aus und kämpfe\n"
	.string "cool! Komm zur Radstrecke!$"

@ Charles - Rowdy, Route 17
MatchCall_HNS_Charles_General1::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Karl.\p"
	.string "Ich war so etwas wie ein\n"
	.string "Herzensbrecher in Einall.\p"
	.string "Jetzt bin ich ein Highway-Star!$"

MatchCall_HNS_Charles_General2::
	.string "Hey, {PLAYER}!\p"
	.string "Die Radstrecke bei Nacht ist\n"
	.string "etwas ganz Besonderes.\p"
	.string "Die Straßenlaternen und der\n"
	.string "Wind… das ist Freiheit!$"

MatchCall_HNS_Charles_Battle::
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Karl.\p"
	.string "Die Highway-Stars wollen\n"
	.string "Rache! Komm zur\l"
	.string "Radstrecke!$"
