gText_Oak_Welcome::
	.string "Hi! Entschuldige die Verspätung!\p"
	.string "Willkommen in der Welt der Pokémon!\p"
	.string "Mein Name ist Eich!\n"
	.string "Man nennt mich den Pokémon-Professor.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "Diese Welt wird von Wesen bewohnt,\n"
	.string "die man Pokémon nennt.\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "Menschen und Pokémon leben\n"
	.string "zusammen und helfen einander.\p"
	.string "Für manche Leute sind Pokémon\n"
	.string "Haustiere, andere tragen Kämpfe\l"
	.string "mit ihnen aus.\p"
	.string "Leider wissen wir noch nicht alles\n"
	.string "über Pokémon.\p"
	.string "Es gibt noch viele Geheimnisse\n"
	.string "zu lüften.\p"
	.string "Darum studiere ich Pokémon\n"
	.string "tagaus, tagein!\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "Und wer bist du?$"

gText_Oak_BoyOrGirl::
	.string "Bist du ein Junge?\n"
	.string "Oder bist du ein Mädchen?$"

gText_Oak_WhatChallenge::
	.string "Aha…\p"
	.string "Und… wie, denkst du,\n"
	.string "wird das Abenteuer werden?$"

gText_Oak_ChallengeSelected::
	.string "Hört sich gut an,\n"
	.string "eine nette Herausforderung!$"

gText_Oak_WhatsYourName::
	.string "Wie lautet dein Name?$"

gText_Oak_SoItsPlayer::
	.string "Ah, du bist also {PLAYER}{KUN}?$"

gText_Oak_YourePlayer::
	.string "Ah, okay!\p"
	.string "Jetzt habe ich es! Du heißt {PLAYER}{KUN}\n"
	.string "und bist gerade nach Neuborkia\l"
	.string "gezogen, schöner Ort.\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "{PLAYER}{KUN}, bist du bereit?\p"
	.string "Dein eigenes Pokémon-Abenteuer\n"
	.string "erwartet dich.\p"
	.string "Dich erwarten tolle Dinge,\n"
	.string "aber auch harte Zeiten.\p"
	.string "Eine Welt voller Träume und\n"
	.string "aufregender Pokémon-Abenteuer\l"
	.string "erwartet dich! Mach dich bereit!\p"
	.string "Komm später in mein Pokémon-Labor,\n"
	.string "ich erwarte dich dort.\p"
	.string "$"
