gText_Oak_Welcome::
	.string "Entschuldige das du warten musstest.\p"
	.string "Willkommen in der Welt der POKéMON!\p"
	.string "Mein Name ist EICH.\p"
	.string "Aber jeder nennt mich nur\n"
	.string "den POKéMON-PROFESSOR.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "Das hier nennen wir “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "Auf dieser Welt leben Wesen,\n"
	.string "die uns als POKéMON bekannt sind.\p"
	.string "Wir Menschen leben Seite an Seite\n"
	.string "mit ihnen, als Freunde oder als\l"
	.string "Arbeitskollegen.\p"
	.string "Und manchmal schließen wir uns mit\n"
	.string "ihnen zusammen und tragen Kämpfe\l"
	.string "gegen andere von uns aus.\p"
	.string "Doch obwohl wir den POKéMON so\n"
	.string "nahe stehen, wissen wir noch nicht\l"
	.string "alles über sie.\p"
	.string "Es gibt noch viele, viele Geheim-\n"
	.string "nisse um die POKéMON.\p"
	.string "Um die Mysterien der POKéMON\n"
	.string "aufzudecken, widme ich mich der\l"
	.string "Forschung. Genau das tue ich.\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "Und wer bist du?$"

gText_Oak_BoyOrGirl::
	.string "Bist du ein Junge?\n"
	.string "Oder bist du ein Mädchen?$"

gText_Oak_WhatChallenge::
	.string "Aha…\p"
	.string "Und… wie denkst du,\n"
	.string "wird das Abenteuer werden?$"

gText_Oak_ChallengeSelected::
	.string "Hört sich gut an,\n"
	.string "eine nette Herausforderung!$" 

gText_Oak_WhatsYourName::
	.string "Fein!\n"
	.string "Und wie heißt du?$"

gText_Oak_SoItsPlayer::
	.string "Ah, du bist also {PLAYER}{KUN}?$"

gText_Oak_YourePlayer::
	.string "Ah, okay!\p"
	.string "Jetzt habe ich es! Du heißt {PLAYER}{KUN}\n"
	.string "und bist gerade nach NEUBORKIA,\l"
	.string "gezogen, schöner Ort.\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "Gut, bist du bereit?\p"
	.string "Dein eigenes Abenteuer wird\n"
	.string "nun beginnen.\p"
	.string "Hab nur Mut und stürze dich in die\n"
	.string "Welt der POKéMON, wo Abenteuer,\l"
	.string "Träume und Freundschaft warten.\p"
	.string "Komm später in mein POKéMON-LABOR,\n"
	.string "ich erwarte dich dort.\p"
	.string "$"
