gText_ObtainedTheItem::
	.string "{STR_VAR_2} erhalten!$"

gText_TheBagIsFull::
	.string "Der BEUTEL ist voll…$"

gText_PutItemInPocket::
	.string "{PLAYER} packt {STR_VAR_2} in die\n"
	.string "{STR_VAR_3}-TASCHE.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} hat {STR_VAR_2} gefunden!$"

gText_TooBadBagIsFull::
	.string "Zu schade!\n"
	.string "Der BEUTEL ist voll…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} packt {STR_VAR_2} in den\n"
	.string "PYRABEUTEL.$"

gText_ObtainedTheDecor::
	.string "{STR_VAR_2} erhalten.$"

gText_NoRoomLeftForAnother::
	.string "Zu schade! Es ist kein Platz für\n"
	.string "{STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} wurde auf den PC\n"
	.string "übertragen.$"

gText_ObtainedTheItems::
	.string "Erhält {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "{PLAYER} findet {STR_VAR_1} {STR_VAR_2}!$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} put the COINS away in\n"
	.string "the COIN CASE.$"

gText_FoundXCoins::
	.string "{PLAYER} findet\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "{PLAYER} findet\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

gText_CoinCaseIsFull::
	.string "Schade!\n"
	.string "MÜNZKORB ist voll…$"

gText_NothingToPutThemIn::
	.string "Schade!\n"
	.string "Ich habe nichts zum aufbewahren…$"
