Text_BootUpPC:
	.string "{PLAYER} schaltet den PC ein.$"

gText_WhichPCShouldBeAccessed::
	.string "Zugriff auf wessen PC?$"

gText_AccessedSomeonesPC::
	.string "Verbindung zu Jemandes PC hergestellt.$"

gText_StorageSystemOpened::
	.string "Pokémon-Lagerungs-System geöffnet.$"

gText_AccessedPlayersPC::
	.string "Verbindung mit PC von {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Verbindung zu Lanettes PC hergestellt.$"

gText_AccessedBillsPC::
	.string "Verbindung zu Bills PC hergestellt.$"
