gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} wurde auf Jemandes PC\n"
	.string "übertragen.\p"
	.string "Es wurde in Box\n"
	.string "“{STR_VAR_1}” abgelegt.$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} wurde zu\n"
#if IS_FRLG
	.string "Bill'S PC gesendet.\p"
#else
	.string "Lanette'S PC gesendet.\p"
#endif
	.string "Es wurde in\n"
	.string "Box “{STR_VAR_1} abgelegt.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "Box “{STR_VAR_3}” in\n"
	.string "Jemandes PC ist voll.\p"
	.string "{STR_VAR_2} wurde in Box\n"
	.string "“{STR_VAR_1}” übertragen.$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "Box “{STR_VAR_3}” auf\n"
#if IS_FRLG
	.string "Bill'S PC war voll.\p"
#else
	.string "Lanette'S PC war voll.\p"
#endif
	.string "{STR_VAR_2} wurde zu\n"
	.string "Box “{STR_VAR_1} transferiert.”$"

gText_PkmnSentToPCAfterCatch::
	.string "{STR_VAR_2} wurde zu\n"
	.string "{B_PC_CREATOR_NAME} PC.\p"
	.string "gesendet in \n"
	.string "Box “{STR_VAR_1}”.$"

gText_PlayerObtainedTheMon::
	.string "{PLAYER} erhält\n"
	.string "das {STR_VAR_1}!$"

gText_NoMoreRoomForPokemon::
	.string "Es ist kein Platz mehr für Pokémon\n"
	.string "vorhanden!\p"
	.string "Die Pokémon Boxen sind voll und\n"
	.string "es kann kein Pokémon mehr\l"
	.string "abgelegt werden!$"

gText_NicknameThisPokemon::
	.string "Möchtest du {STR_VAR_1} einen\n"
	.string "Spitznamen geben?$"
