gText_WouldYouLikeToRestYourPkmn::
	.string "Willkommen im Pokémon-Center!\p"
	.string "Wir heilen deine Pokémon und\n"
	.string "machen sie wieder fit.\p"
	.string "O.K. Wir benötigen deine Pokémon.$"

gText_IllTakeYourPkmn::
	.string "Okay, ich nehme deine Pokémon für einen\n"
	.string "Moment in meine Obhut.$"

gText_RestoredPkmnToFullHealth::
	.string "Danke!\p"
	.string "Deine Pokémon sind wieder topfit!$"

gText_WeHopeToSeeYouAgain::
	.string "Komm jederzeit wieder vorbei!$"

gText_WelcomeCutShort::
	.string "Willkommen im Pokémon-Center!\p"
	.string "Wir heilen deine Pokémon und\n"
	.string "machen sie wieder fit.\p"
	.string "O.K. Wir benötigen deine Pokémon.$"

gText_NoticesGoldCard::
	.string "Di-dieser Pass…\n"
	.string "Ist das der… Goldpass?!?\p"
	.string "Diese goldene Farbe ist brillant!\n"
	.string "Die vier Sterne funkeln richtig!\p"
	.string "Ich habe schon viele Trainer mit einem\n"
	.string "Silberpass gesehen, aber, {PLAYER},\l"
	.string "du bist der erste Trainer mit einem\l"
	.string "Goldpass!\p"
	.string "Okay, {PLAYER}, bitte gib mir die Ehre,\n"
	.string "mich um deine Pokémon kümmern\l"
	.string "zu dürfen!$"

gText_YouWantTheUsual::
	.string "Ich freue mich, dich zu sehen, {PLAYER}!\n"
	.string "Das Übliche, nicht wahr?$"

gText_IllTakeYourPkmn2::
	.string "Okay, ich nehme deine Pokémon für einen\n"
	.string "Moment in meine Obhut.$"

gText_ThankYouForWaiting::
	.string "Danke!$"

gText_WeHopeToSeeYouAgain2::
	.string "Komm bald wieder!$"

gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge
    .string "Sorry, du spielst mit\n"
    .string "der Pokécenter-Challenge!\p"
    .string "Viel Glück!{PAUSE_UNTIL_PRESS}$"
