gBirchDexRatingText_AreYouCurious::
	.string "Prof. Birk: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte\n"
	.string "mit dem Pokédex zeigen?$"

gBirchDexRatingText_Cancel::
	.string "Ach? Du hast erst so wenige\n"
	.string "Pokémon gefangen, dass es sich\l"
	.string "nicht lohnt, ihn mir zu zeigen?$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "Oh, du hast {STR_VAR_1} Pokémon gesehen\n"
	.string "und {STR_VAR_2} Pokémon gefangen…$"

gBirchDexRatingText_LessThan10::
	.string "Du solltest mehr ins hohe Gras\n"
	.string "gehen und mehr auf Pokémon\l"
	.string "achten.$"

gBirchDexRatingText_LessThan20::
	.string "So langsam bekommst du den Bogen\n"
	.string "raus. Aber es wird immer schwieriger\l"
	.string "werden!$"

gBirchDexRatingText_LessThan30::
	.string "Einige Pokémon tauchen nur in be-\n"
	.string "stimmten Regionen auf.\l"
	.string "Hab nur Geduld.$"

gBirchDexRatingText_LessThan40::
	.string "Nun, er könnte mehr Einträge\n"
	.string "enthalten, aber es sieht schon\l"
	.string "eher nach einem Pokédex aus.$"

gBirchDexRatingText_LessThan50::
	.string "Das läuft doch wunderbar.\n"
	.string "Mach weiter so.$"

gBirchDexRatingText_LessThan60::
	.string "Verwendest du irgendwelche\n"
	.string "Angeln?\l"
	.string "Hier gibt es viele Pokémon im Meer.$"

gBirchDexRatingText_LessThan70::
	.string "Statt die Pokémon nur zu fangen,\n"
	.string "wie wäre es, sie sich entwickeln zu\l"
	.string "lassen?$"

gBirchDexRatingText_LessThan80::
	.string "Der Pokédex wird einfach\n"
	.string "fantastisch.\l"
	.string "Das habe ich im Gefühl…$"

gBirchDexRatingText_LessThan90::
	.string "Du hast so viele gefangen…\n"
	.string "Du hast ein außergewöhnliches\l"
	.string "Talent!$"

gBirchDexRatingText_LessThan100::
	.string "Warst du schon mal in der\n"
	.string "Safari-Zone?\p"
	.string "Ich habe gehört, es gibt Pokémon,\n"
	.string "die man nur dort finden kann.$"

gBirchDexRatingText_LessThan110::
	.string "Du hast die 100er-Marke\n"
	.string "überschritten!\p"
	.string "Das ist ein beeindruckender\n"
	.string "Pokédex!$"

gBirchDexRatingText_LessThan120::
	.string "Es gibt auch Pokémon, die man\n"
	.string "durch den Einsatz von\l"
	.string "Zertrümmerer findet.$"

gBirchDexRatingText_LessThan130::
	.string "Du solltest einige Pokémon fangen\n"
	.string "und sie mit anderen tauschen.$"

gBirchDexRatingText_LessThan140::
	.string "Ich habe von Pokémon gehört, die\n"
	.string "sich entwickeln, wenn sie ihren\l"
	.string "Trainer sehr lieben.$"

gBirchDexRatingText_LessThan150::
	.string "Ich hatte keine Ahnung, dass es in\n"
	.string "der Hoenn-Region so viele\l"
	.string "verschiedene Pokémon-Arten gibt.$"

gBirchDexRatingText_LessThan160::
	.string "Manchmal erscheinen einige\n"
	.string "Pokémon in großer Anzahl\p"
	.string "wie bei einem Ausbruch.\n"
	.string "Das solltest du nicht verpassen!$"

gBirchDexRatingText_LessThan170::
	.string "Dein Pokédex liefert einen\n"
	.string "erstaunlich guten Einblick in die\l"
	.string "Pokémon der Hoenn-Region!$"

gBirchDexRatingText_LessThan180::
	.string "Ich sage, du hast dich bereits als\n"
	.string "guter Pokémon-Professor\l"
	.string "qualifiziert.$"

gBirchDexRatingText_LessThan190::
	.string "Mit diesem Pokédex, der schon so\n"
	.string "weit gediehen ist, bist du ein\l"
	.string "echter Profi.$"

gBirchDexRatingText_LessThan200::
	.string "Du bist sehr nahe dran, den\n"
	.string "Pokédex zu vervollständigen.\l"
	.string "Das fühle ich einfach.$"

gBirchDexRatingText_DexCompleted::
	.string "Herzlichen Glückwunsch!\n"
	.string "Dein Pokédex ist vollständig!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "Auf nationaler Ebene…\p"
	.string "hast du {STR_VAR_1} Pokémon gesehen\n"
	.string "und {STR_VAR_2} Pokémon gefangen…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "Prof. Eich: Ich freue mich, dich\n"
	.string "zu sehen! Was macht dein Pokédex?\p"
	.string "Zeig ihn mir!$"

PokedexRating_Text_SeenXOwnedY::
	.string "In deinem Pokédex steht:\p"
	.string "Gesehen: {STR_VAR_1} Pokémon\n"
	.string "  Besitz: {STR_VAR_2} Pokémon\p"
	.string "Prof. Eichs Bewertung:$"

PokedexRating_Text_LessThan10::
	.string "Du hast noch eine Menge Arbeit vor dir.\p"
	.string "Suche in hohem Gras nach Pokémon!$"

PokedexRating_Text_LessThan20::
	.string "Das sieht schon ganz gut aus!\p"
	.string "Hole dir bei meinem Assistenten die VM\n"
	.string "Blitz ab!$"

PokedexRating_Text_LessThan30::
	.string "Du benötigst noch weitere!\p"
	.string "Fange also die verschiedensten\n"
	.string "Pokémon!$"

PokedexRating_Text_LessThan40::
	.string "Sehr gut! Du gibst dir sehr viel Mühe!\p"
	.string "Hole dir bei meinem Assistenten einen\n"
	.string "Detektor ab!$"

PokedexRating_Text_LessThan50::
	.string "Dein Pokédex macht gute Fortschritte!\p"
	.string "Ich habe einem meiner Assistenten ein\n"
	.string "Münzamulett gegeben. Hol es dir!$"

PokedexRating_Text_LessThan60::
	.string "Ah, nun hast du mehr als 50!\p"
	.string "Ich habe einem meiner Assistenten\n"
	.string "einen EP-Teiler gegeben. Hol in dir!$"

PokedexRating_Text_LessThan70::
	.string "Heh! Es wird immer besser!$"

PokedexRating_Text_LessThan80::
	.string "Fantastisch!\p"
	.string "Du solltest dir Wasser-Pokémon angeln!$"

PokedexRating_Text_LessThan90::
	.string "Wundervoll! Du bist ein\n"
	.string "leidenschaftlicher Sammler!$"

PokedexRating_Text_LessThan100::
	.string "Ich bin wirklich beeindruckt! Das war\n"
	.string "sicher eine Menge Arbeit!$"

PokedexRating_Text_LessThan110::
	.string "Du hast bereits 100 verschiedene\n"
	.string "Pokémon! Du leistest hervorragende\l"
	.string "Arbeit!$"

PokedexRating_Text_LessThan120::
	.string "Super! Einige deiner Pokémon haben sich\n"
	.string "sogar entwickelt!$"

PokedexRating_Text_LessThan130::
	.string "Ausgezeichnet! Tausche Pokémon mit\n"
	.string "Freunden, um weitere zu erhalten!$"

PokedexRating_Text_LessThan140::
	.string "Überragend! Du hast dich zu einem\n"
	.string "echten Profi gemausert!$"

PokedexRating_Text_LessThan150::
	.string "Ich bin sprachlos!\p"
	.string "Von nun an giltst du als Autorität für\n"
	.string "Pokémon!$"

PokedexRating_Text_Complete::
	.string "Dein Pokédex ist komplett fertig\n"
	.string "gestellt! Herzlichen Glückwunsch!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "In deinem Nationalen Pokédex\n"
	.string "steht:\p"
	.string "Gesehen: {STR_VAR_1} Pokémon\n"
	.string "Besitz: {STR_VAR_2} Pokémon.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "Ich bin gespannt, ob du den\n"
	.string "Nationalen Pokédex füllen kannst.$"

PokedexRating_Text_YouveCompletedDex::
	.string "Endlich…\p"
	.string "Dein Pokédex ist komplett!\p"
	.string "Das ist traumhaft!\n"
	.string "Wirklich fantastisch!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Danke, {PLAYER}!\n"
	.string "Meinen aufrichtigen Dank!\l"
	.string "Du hast meinen Traum erfüllt.$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "Eich: Ah, willkommen!\p"
	.string "Wie ist es um deinen Pokédex\n"
	.string "bestellt?\p"
	.string "Wow!\p"
	.string "Ich weiß es natürlich, aber ich\n"
	.string "liebe es trotzdem!\p"
	.string "Zeig ihn mir…$"

@ HnS (mostly directly copied from HGSS)

gElmDexRatingText_AreYouCurious::
	.string "Prof. Lind: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte\n"
	.string "mit dem Pokédex zeigen?$"

gElmDexRatingText_AreYouCuriousNational::
	.string "Prof. Lind: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte\n"
	.string "mit dem nationalen Pokédex zeigen?$"

gJohtoDexRatingText_LessThan10::
	.string "Du solltest mehr ins hohe Gras\n"
	.string "gehen und mehr auf Pokémon\l"
	.string "achten.$"

gJohtoDexRatingText_LessThan20::
	.string "So langsam bekommst du den Bogen\n"
	.string "raus. Aber es wird immer schwieriger\l"
	.string "werden!$"

gJohtoDexRatingText_LessThan35::
	.string "Einige Pokémon tauchen nur in be-\n"
	.string "stimmten Regionen auf.\l"
	.string "Hab nur Geduld.$"

gJohtoDexRatingText_LessThan50::
	.string "Das läuft doch wunderbar.\n"
	.string "Mach weiter so.$"

gJohtoDexRatingText_LessThan65::
	.string "Verwendest du irgendwelche\n"
	.string "Angeln?\l"
	.string "Hier gibt es viele Pokémon im Meer.$"

gJohtoDexRatingText_LessThan80::
	.string "Der Pokédex wird einfach\n"
	.string "fantastisch.\l"
	.string "Das habe ich im Gefühl…$"

gJohtoDexRatingText_LessThan95::
	.string "Du hast so viele gefangen…\n"
	.string "Du hast ein außergewöhnliches\l"
	.string "Talent!$"

gJohtoDexRatingText_LessThan110::
	.string "Du hast die 100er-Marke\n"
	.string "überschritten!\p"
	.string "Das ist ein beeindruckender\n"
	.string "Pokédex!$"

gJohtoDexRatingText_LessThan125::
	.string "Du kannst manchen Pokémon nur zu\n"
	.string "gewissen Tageszeiten begegnen!$"

gJohtoDexRatingText_LessThan140::
	.string "Die Zahl deiner registrierten Pokémon\n"
	.string "ist ja ziemlich gewachsen! Mach weiter\l"
	.string "so!$"

gJohtoDexRatingText_LessThan155::
	.string "Beeindruckend! Du fängst Pokémon\n"
	.string "nicht nur, sondern sorgst auch dafür,\l"
	.string "dass sie sich entwickeln!$"

gJohtoDexRatingText_LessThan170::
	.string "Wenn du Kurts Pokébälle mit Bedacht\n"
	.string "einzusetzen verstehst, dürfte die Zahl\l"
	.string "deiner gefangenen Pokémon in die Höhe\l"
	.string "schnellen!$"

gJohtoDexRatingText_LessThan185::
	.string "Wenn du Pokémon fangen möchtest, ist\n"
	.string "es von Vorteil, Informationen mit\l"
	.string "deinen Freunden auszutauschen!$"

gJohtoDexRatingText_LessThan200::
	.string "Tauschst du deine Pokémon mit\n"
	.string "Freunden? Alleine ist das sehr\l"
	.string "schwierig!$"

gJohtoDexRatingText_LessThan215::
	.string "Die 200-Marke ist erreicht! Dein\n"
	.string "Pokédex entwickelt sich ja prächtig!$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan230::
	.string "Schon über 225,\n"
	.string "weiter so.$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan245::
	.string "Schon über 240,\n"
	.string "weiter so.$"

gJohtoDexRatingText_LessThan260::
	.string "Du hast so viele Pokémon gefunden!\n"
	.string "Dank deiner Hilfe kommt meine\l"
	.string "Forschung gut voran!$"

gJohtoDexRatingText_LessThan275::
	.string "Fantastisch! Was soll ich mehr sagen?\n"
	.string "Du hast das Zeug, ein ganz großer\l"
	.string "Pokémon-Professor zu werden!$"

gJohtoDexRatingText_LessThanMaxDex::
	.string "Dein Pokédex ist glatter Wahnsinn! Du\n"
	.string "wirst noch ein echter Profi!$"

gJohtoDexRatingText_Complete::
	.string "Oh!\n"
	.string "Der Johto-Pokédex ist ja vollständig!\p"
	.string "Und das nur dank dir, {PLAYER}!!!\n"
	.string "Das ist wirklich eine außergewöhnliche\l"
	.string "Leistung!$"

gNationalDexRatingText_LessThan100::
	.string "Es ist noch ein weiter Weg bis zum Ziel,\n"
	.string "aber lass dich davon nicht entmutigen!$"

gNationalDexRatingText_LessThan150::
	.string "Unter 150.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan200::
	.string "Unter 200.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan250::
	.string "Unter 250.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan300::
	.string "Unter 300.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan350::
	.string "Unter 350.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan400::
@	.string "Musik im Radio könnte\n"
@	.string "Pokémon herauslocken$"
	.string "Es gibt überall versteckte\n"
	.string "Orte, überall auf der Welt.$"

gNationalDexRatingText_LessThan435::
	.string "Unter 435.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan465::
	.string "Unter 465.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan475::
	.string "Unter 475.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThanMaxDex::
	.string "Ich habe noch nie einen so\n"
	.string "herausragenden Trainer wie dich\l"
	.string "getroffen!$"

gNationalDexRatingText_Complete::
	.string "Ausgezeichnet! Der Nationale Pokédex\n"
	.string "ist ja vollständig!\p"
	.string "Ich habe mich nicht in dir getäuscht,\n"
	.string "als wir uns zum ersten Mal getroffen\l"
	.string "haben. Meine Entscheidung war\l"
	.string "goldrichtig!\p"
	.string "Ach, was sage ich! Du hast meine\n"
	.string "Erwartungen bei Weitem übertroffen,\l"
	.string "{PLAYER}! Dank dir!!!$"
