gBirchDexRatingText_AreYouCurious::
	.string "Prof. Birk: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte\n"
	.string "mit dem Pokédex zeigen?$"

gBirchDexRatingText_Cancel::
	.string "Ach? Du hast erst so wenige\n"
	.string "Pokémon gefangen, dass es sich\l"
	.string "nicht lohnt, ihn mir zu zeigen?$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "Oh, du hast {STR_VAR_1} Pokémon gesehen\n"
	.string "und {STR_VAR_2} Pokémon gefangen…$"

gBirchDexRatingText_LessThan10::
	.string "Du solltest mehr ins hohe Gras\n"
	.string "gehen und mehr auf Pokémon\l"
	.string "achten.$"

gBirchDexRatingText_LessThan20::
	.string "So langsam bekommst du den Bogen\n"
	.string "raus. Aber es wird immer schwieriger\l"
	.string "werden!$"

gBirchDexRatingText_LessThan30::
	.string "Einige Pokémon tauchen nur in be-\n"
	.string "stimmten Regionen auf.\l"
	.string "Hab nur Geduld.$"

gBirchDexRatingText_LessThan40::
	.string "Nun, er könnte mehr Einträge\n"
	.string "enthalten, aber es sieht schon\l"
	.string "eher nach einem Pokédex aus.$"

gBirchDexRatingText_LessThan50::
	.string "Das läuft doch wunderbar.\n"
	.string "Mach weiter so.$"

gBirchDexRatingText_LessThan60::
	.string "Verwendest du irgendwelche\n"
	.string "Angeln?\l"
	.string "Hier gibt es viele Pokémon im Meer.$"

gBirchDexRatingText_LessThan70::
	.string "Statt die Pokémon nur zu fangen,\n"
	.string "wie wäre es, sie sich entwickeln zu\l"
	.string "lassen?$"

gBirchDexRatingText_LessThan80::
	.string "Der Pokédex wird einfach\n"
	.string "fantastisch.\l"
	.string "Das habe ich im Gefühl…$"

gBirchDexRatingText_LessThan90::
	.string "Du hast so viele gefangen…\n"
	.string "Du hast ein außergewöhnliches\l"
	.string "Talent!$"

gBirchDexRatingText_LessThan100::
	.string "Warst du schon mal in der\n"
	.string "Safari-Zone?\p"
	.string "Ich habe gehört, es gibt Pokémon,\n"
	.string "die man nur dort finden kann.$"

gBirchDexRatingText_LessThan110::
	.string "Du hast die 100er-Marke\n"
	.string "überschritten!\p"
	.string "Das ist ein beeindruckender\n"
	.string "Pokédex!$"

gBirchDexRatingText_LessThan120::
	.string "Es gibt auch Pokémon, die man\n"
	.string "durch den Einsatz von\l"
	.string "Zertrümmerer findet.$"

gBirchDexRatingText_LessThan130::
	.string "Du solltest einige Pokémon fangen\n"
	.string "und sie mit anderen tauschen.$"

gBirchDexRatingText_LessThan140::
	.string "Ich habe von Pokémon gehört, die\n"
	.string "sich entwickeln, wenn sie ihren\l"
	.string "Trainer sehr lieben.$"

gBirchDexRatingText_LessThan150::
	.string "Ich hatte keine Ahnung, dass es in\n"
	.string "der Hoenn-Region so viele\l"
	.string "verschiedene Pokémon-Arten gibt.$"

gBirchDexRatingText_LessThan160::
	.string "Manchmal erscheinen einige\n"
	.string "Pokémon in großer Anzahl\p"
	.string "wie bei einem Ausbruch.\n"
	.string "Das solltest du nicht verpassen!$"

gBirchDexRatingText_LessThan170::
	.string "Dein Pokédex liefert einen\n"
	.string "erstaunlich guten Einblick in die\l"
	.string "Pokémon der Hoenn-Region!$"

gBirchDexRatingText_LessThan180::
	.string "Ich sage, du hast dich bereits als\n"
	.string "guter Pokémon-Professor\l"
	.string "qualifiziert.$"

gBirchDexRatingText_LessThan190::
	.string "Mit diesem Pokédex, der schon so\n"
	.string "weit gediehen ist, bist du ein\l"
	.string "echter Profi.$"

gBirchDexRatingText_LessThan200::
	.string "Du bist sehr nahe dran, den\n"
	.string "Pokédex zu vervollständigen.\l"
	.string "Das fühle ich einfach.$"

gBirchDexRatingText_DexCompleted::
	.string "Herzlichen Glückwunsch!\n"
	.string "Dein Pokédex ist vollständig!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "Auf nationaler Ebene…\p"
	.string "hast du {STR_VAR_1} Pokémon gesehen\n"
	.string "und {STR_VAR_2} Pokémon gefangen…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "Prof. Eich: Ich freue mich, dich\n"
	.string "zu sehen! Was macht dein Pokédex?\p"
	.string "Zeig ihn mir!$"

PokedexRating_Text_SeenXOwnedY::
	.string "In deinem Pokédex steht:\p"
	.string "Gesehen: {STR_VAR_1} Pokémon\n"
	.string "  Besitz: {STR_VAR_2} Pokémon\p"
	.string "Prof. Eichs Bewertung:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for Pokémon!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my Aides a Flash\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your Pokédex could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "Pokémon!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my Aides an\n"
	.string "Itemfinder. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your Pokédex is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my Aides an\n"
	.string "Amulet Coin. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my Aides an EXP.\n"
	.string "Share. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable Pokédex!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "Pokémon by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of Pokémon! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the Pokémon Professor now!$"

PokedexRating_Text_Complete::
	.string "Your Pokédex is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "In deinem Nationalen Pokédex\n"
	.string "steht:\p"
	.string "Gesehen: {STR_VAR_1} Pokémon\n"
	.string "Besitz: {STR_VAR_2} Pokémon.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "Ich bin gespannt, ob du den\n"
	.string "Nationalen Pokédex füllen kannst.$"

PokedexRating_Text_YouveCompletedDex::
	.string "Endlich…\p"
	.string "Dein Pokédex ist komplett!\p"
	.string "Das ist traumhaft!\n"
	.string "Wirklich fantastisch!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Danke, {PLAYER}!\n"
	.string "Meinen aufrichtigen Dank!\l"
	.string "Du hast meinen Traum erfüllt.$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "Eich: Ah, willkommen!\p"
	.string "Wie ist es um deinen Pokédex\n"
	.string "bestellt?\p"
	.string "Wow!\p"
	.string "Ich weiß es natürlich, aber ich\n"
	.string "liebe es trotzdem!\p"
	.string "Zeig ihn mir…$"

@ HnS (mostly directly copied from HGSS)

gElmDexRatingText_AreYouCurious::
	.string "Prof. Lind: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte\n"
	.string "mit dem Pokédex zeigen?$"

gElmDexRatingText_AreYouCuriousNational::
	.string "Prof. Lind: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte\n"
	.string "mit dem nationalen Pokédex zeigen?$"

gJohtoDexRatingText_LessThan10::
	.string "Du solltest mehr ins hohe Gras\n"
	.string "gehen und mehr auf Pokémon\l"
	.string "achten.$"

gJohtoDexRatingText_LessThan20::
	.string "So langsam bekommst du den Bogen\n"
	.string "raus. Aber es wird immer schwieriger\l"
	.string "werden!$"

gJohtoDexRatingText_LessThan35::
	.string "Einige Pokémon tauchen nur in be-\n"
	.string "stimmten Regionen auf.\l"
	.string "Hab nur Geduld.$"

gJohtoDexRatingText_LessThan50::
	.string "Das läuft doch wunderbar.\n"
	.string "Mach weiter so.$"

gJohtoDexRatingText_LessThan65::
	.string "Verwendest du irgendwelche\n"
	.string "Angeln?\l"
	.string "Hier gibt es viele Pokémon im Meer.$"

gJohtoDexRatingText_LessThan80::
	.string "Der Pokédex wird einfach\n"
	.string "fantastisch.\l"
	.string "Das habe ich im Gefühl…$"

gJohtoDexRatingText_LessThan95::
	.string "Du hast so viele gefangen…\n"
	.string "Du hast ein außergewöhnliches\l"
	.string "Talent!$"

gJohtoDexRatingText_LessThan110::
	.string "Du hast die 100er-Marke\n"
	.string "überschritten!\p"
	.string "Das ist ein beeindruckender\n"
	.string "Pokédex!$"

gJohtoDexRatingText_LessThan125::
	.string "Schon über 120,\n"
	.string "weiter so.$"

gJohtoDexRatingText_LessThan140::
	.string "Schon über 135,\n"
	.string "weiter so.$"

gJohtoDexRatingText_LessThan155::
	.string "Schon über 150,\n"
	.string "weiter so.$"

gJohtoDexRatingText_LessThan170::
	.string "Schon über 165,\n"
	.string "weiter so.$"

gJohtoDexRatingText_LessThan185::
	.string "Schon über 180,\n"
	.string "weiter so.$"

gJohtoDexRatingText_LessThan200::
	.string "Schon über 195,\n"
	.string "weiter so.$"

gJohtoDexRatingText_LessThan215::
	.string "Schon über 210,\n"
	.string "weiter so.$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan230::
	.string "Schon über 225,\n"
	.string "weiter so.$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan245::
	.string "Schon über 240,\n"
	.string "weiter so.$"

gJohtoDexRatingText_LessThan260::
	.string "Schon über 255,\n"
	.string "weiter so.$"

gJohtoDexRatingText_LessThan275::
	.string "Schon über 270,\n"
	.string "weiter so.$"

gJohtoDexRatingText_LessThanMaxDex::
	.string "Super Pokédex!\n"
	.string "Wird richtig professionell!$"

gJohtoDexRatingText_Complete::
	.string "Oh!\n"
	.string "Der Johto-Pokédex ist ja vollständig!\p"
	.string "Und das nur dank dir, {PLAYER}!!!\n"
	.string "Das ist wirklich eine außergewöhnliche\l"
	.string "Leistung!$"

gNationalDexRatingText_LessThan100::
	.string "Weniger als Hundert.\n"
	.string "Nicht aufgeben!$"

gNationalDexRatingText_LessThan150::
	.string "Unter 150.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan200::
	.string "Unter 200.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan250::
	.string "Unter 250.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan300::
	.string "Unter 300.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan350::
	.string "Unter 350.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan400::
@	.string "Musik im Radio könnte\n"
@	.string "Pokémon herauslocken$"
	.string "Es gibt überall versteckte\n"
	.string "Orte, überall auf der Welt.$"

gNationalDexRatingText_LessThan435::
	.string "Unter 435.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan465::
	.string "Unter 465.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThan475::
	.string "Unter 475.\n"
	.string "Weiter so!$"

gNationalDexRatingText_LessThanMaxDex::
	.string "Ich habe noch nie zuvor einen\n"
	.string "so tollen Trainer gesehen!$"

gNationalDexRatingText_Complete::
	.string "Exzellent! Ein fantastischer\n"
	.string "Nationaler Pokédex!\p"
	.string "Wow...{PAUSE 10}\p"
	.string "Du hast meine kühnsten\n"
	.string "Erwartungen übertroffen!\p"
	.string "Wirklich toll gemacht!\p"
	.string "Danke, {PLAYER}!$"
