ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Hast du vor, tiefer hineinzugehen?\p"
	.string "Würdest du mir bitte Küstensalz\n"
	.string "und Küstenschalen mitbringen?\p"
	.string "Ich kann dir daraus etwas Wunderbares\n"
	.string "anfertigen.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Wenn du mir jeweils viermal Küstensalz\n"
	.string "und Küstenschale mitbringst, fertige\l"
	.string "ich dir Seegesang daraus an.\p"
	.string "Jeder Tag ist ein guter Tag, die Zutaten\n"
	.string "dafür zu finden…$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh, hey! Küstensalz und Küstenschale!\n"
	.string "Und davon auch noch so viele!\p"
	.string "Soll ich dir daraus Seegesang\n"
	.string "anfertigen?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Sehr schön! Ich werde dir sofort\n"
	.string "Seegesang anfertigen.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Fertig! Bitte schön!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Gib das einem Pokémon zum Tragen.\n"
	.string "Es wird das lieben, das garantiere ich!\p"
	.string "Der Klang von Seegesang…\n"
	.string "Er ist einfach vollendet!\p"
	.string "Die Zutaten kannst du jeden Tag finden,\n"
	.string "daher kann ich dir mehrere machen.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… Wirklich?\n"
	.string "Ich wollte Seegesang anfertigen…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "In deinem Beutel ist nicht genügend\n"
	.string "Platz für das neue Item.\p"
	.string "Schaffe Platz und hole dir dann\n"
	.string "Seegesang bei mir ab.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Hier gab es mal Küstensalz.\n"
	.string "Aber jetzt ist nichts mehr davon da.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Hier gab es mal eine Küstenschale.\n"
	.string "Aber jetzt gibt es keine mehr.$"
