LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Du hast an einem Pokémon Wettbewerb\n"
	.string "teilgenommen, stimmt’s?\p"
	.string "Da kannst du mir doch etwas über\n"
	.string "dein Pokémon erzählen.\p"
	.string "Ich bin Reporter. Ich arbeite an einer\n"
	.string "Geschichte über Pokémon Wettbewerbe.\p"
	.string "Würdest du mir wohl einige Fragen\n"
	.string "beantworten?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Oh, das machst du?\n"
	.string "Herzlichen Dank.\p"
	.string "Beschreibe mir doch kurz den Wettbe-\n"
	.string "werb, an dem du gerade teilgenommen\l"
	.string "hast.$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Ah, ich verstehe.\n"
	.string "Das ist ein bewegender Kommentar.\p"
	.string "Man bekommt ein gutes Bild davon,\n"
	.string "wie dieser Wettbewerb war.\p"
	.string "Ich habe eine letzte Frage.\p"
	.string "Wenn du das Wort “{STR_VAR_2}” hörst,\n"
	.string "was für ein Bild hast du dann vor Augen?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Oh, hm.\p"
	.string "Das stellst du dir also unter dem\n"
	.string "Begriff “{STR_VAR_2}” vor.\p"
	.string "Danke schön!\n"
	.string "Du hast mir einige gute Ideen geliefert.\p"
	.string "Jetzt kann ich eine gute Geschichte\n"
	.string "über die Pokémon Wettbewerbe\l"
	.string "schreiben.\p"
	.string "Vielleicht, aber nur vielleicht, findet\n"
	.string "sie auch ihren Weg ins Fernsehen.\l"
	.string "Ich hoffe, du schaltest dann ein!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Oh, das ist wirklich schade…\p"
	.string "Nun, wenn du eine gute Geschichte auf\n"
	.string "Lager hast, melde dich wieder bei mir.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Ich freue mich schon auf deinen\n"
	.string "nächsten Pokémon Wettbewerb.$"

gTVBravoTrainerText00::
	.string "Yeah!\n"
	.string "Es ist Bravo Trainer Zeit!\p"
	.string "Heute stellen wir ein Pokémon vor,\n"
	.string "das zu {STR_VAR_1} gehört.\p"
	.string "Dieses Pokémon hat eine {STR_VAR_2}-\n"
	.string "Wertung in der {STR_VAR_3}-Klasse\l"
	.string "bekommen.$"

gTVBravoTrainerText01::
	.string "Begrüßt {STR_VAR_2},\n"
	.string "das {STR_VAR_1}!\p"
	.string "Der Kosename {STR_VAR_2}…\p"
	.string "Selbst dieser Kosename strahlt die\n"
	.string "Aura von “{STR_VAR_3}” aus!$"

gTVBravoTrainerText02::
	.string "Als der Trainer {STR_VAR_1} sein Pokémon\n"
	.string "in einem Wettbewerb antreten ließ,\l"
	.string "haben wir es geschafft, einige leiden-\l"
	.string "schaftliche Aussagen zu erhalten.$"

gTVBravoTrainerText03::
	.string "Als {STR_VAR_1} nach dem Wettbewerb über\n"
	.string "diesen befragt wurde, bekamen wir ein\l"
	.string "breites Grinsen und folgende Antwort:\l"
	.string "“{STR_VAR_2}!”\p"
	.string "Nun, sicher, das Pokémon von {STR_VAR_1}\n"
	.string "kam auf Platz {STR_VAR_3} im Wettbewerb.\p"
	.string "Die Aussage passt absolut zu {STR_VAR_1},\n"
	.string "das ist meine Meinung!$"

gTVBravoTrainerText04::
	.string "Als {STR_VAR_1} nach dem Wettbewerb über\n"
	.string "diesen befragt wurde, bekamen wir die\l"
	.string "bittere Antwort: “{STR_VAR_2}!”\p"
	.string "Nun, sicher, das Pokémon von {STR_VAR_1}\n"
	.string "kam auf Platz {STR_VAR_3} im Wettbewerb.\p"
	.string "Die Enttäuschung von {STR_VAR_1} wird hier\n"
	.string "mehr als deutlich, das ist meine\l"
	.string "Meinung.$"

gTVBravoTrainerText05::
	.string "Möchtet ihr auch wissen, was {STR_VAR_1}\n"
	.string "sich unter {STR_VAR_2} vorstellt?\p"
	.string "Ihr könnt darauf wetten, dass wir\n"
	.string "danach gefragt haben! Natürlich!\p"
	.string "Die Antwort war klipp und klar:\n"
	.string "“{STR_VAR_3}!”\p"
	.string "Das ist es, was {STR_VAR_2} für {STR_VAR_1}\n"
	.string "repräsentiert!$"

gTVBravoTrainerText06::
	.string "Die letzte Attacke, {STR_VAR_2}, die\n"
	.string "von {STR_VAR_1} eingesetzt wurde,\l"
	.string "ist ganz klar “{STR_VAR_3}!”$"

gTVBravoTrainerText07::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Wir hoffen, dass {STR_VAR_1} noch höhere\n"
	.string "Gipfel erklimmen wird!\p"
	.string "Unsere Zeit ist mal wieder abgelaufen!\n"
	.string "Bis zum nächsten Mal! Tschüss!$"

gTVBravoTrainerText08::
	.string "Wir stellen vor: Trainers {STR_VAR_1}!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Hallo! Du bist der Trainer, der gerade\n"
	.string "gekämpft hat, richtig?\p"
	.string "Ich interviewe Trainer in der ganzen\n"
	.string "Welt.\p"
	.string "Würdest du mir deine Eindrücke über\n"
	.string "das Kämpfen schildern?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Ja? Wirklich?\n"
	.string "Danke schön!\l"
	.string "Dann, äh…\p"
	.string "Wie war es heute im Duellturm?\p"
	.string "Warst du mit dem Kampf zufrieden?\n"
	.string "Oder bist du unzufrieden?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh…\n"
	.string "Tut mir Leid, dich zu stören.\p"
	.string "Bitte gib uns ein Interview, wenn du\n"
	.string "wieder im Duellturm kämpfst.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Ja, natürlich!\p"
	.string "Da ist dieser untrügliche Ausdruck der\n"
	.string "Zufriedenheit auf deinem Gesicht…\p"
	.string "Ganz offensichtlich hattest du einen\n"
	.string "großartigen Kampf!$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, ich verstehe…\p"
	.string "Nun, es ist immer schwer, den Kampf so\n"
	.string "zu beeinflussen, wie man es möchte.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Darf ich dir noch eine Frage stellen?\p"
	.string "Wenn du deine Eindrücke über diesen\n"
	.string "Kampf beschreiben müsstest, was\l"
	.string "würdest du dann sagen?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Das ist erstaunlich cool!\p"
	.string "Eine großartige Sache! Ich wünsche dir\n"
	.string "im nächsten Kampf genauso viel Glück!\p"
	.string "Ich hoffe, wir treffen uns bald wieder!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, ich verstehe…\p"
	.string "Nun, auch die ruhigen Typen sind cool,\n"
	.string "nicht wahr?\p"
	.string "Ich hoffe, du gibst mir bald wieder die\n"
	.string "Möglichkeit, deine Eindrücke\l"
	.string "festzuhalten!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "Ich freue mich schon auf deinen\n"
	.string "nächsten Kampf!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Yeah!\n"
	.string "Es ist Bravo Trainer Zeit!\p"
	.string "Heute stellen wir {STR_VAR_1} vor. {STR_VAR_1}\n"
	.string "hat sich der Herausforderung im\l"
	.string "Duellturm gestellt!\p"
	.string "Bei dieser Begegnung hatte {STR_VAR_1}\n"
	.string "das listige {STR_VAR_2} mitgebracht.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "Das Paar stellte einen neuen Rekord von\n"
	.string "{STR_VAR_2} Siegen in Folge in einer\l"
	.string "{STR_VAR_1}-Konkurrenz auf!\l"
	.string "Bravo, Trainer!$"

BravoTrainerBattleTower_Text_Lost::
	.string "Die beiden scheiterten schließlich an\n"
	.string "{STR_VAR_1} im Kampf Nummer {STR_VAR_2}.\l"
	.string "Netter Versuch, Trainer!\p"
	.string "Es war einfach nur großes Pech, so\n"
	.string "früh während dieser Herausforderung\l"
	.string "auf {STR_VAR_1} zu treffen.\p"
	.string "Wir fragten den Trainer nach den\n"
	.string "Eindrücken, die der Kampf gegen\l"
	.string "{STR_VAR_1} hinterlassen hat.$"

BravoTrainerBattleTower_Text_Won::
	.string "Die beiden haben gewonnen, indem sie\n"
	.string "{STR_VAR_2} von {STR_VAR_1} klar\l"
	.string "besiegt haben. Bravo, Trainer!\p"
	.string "Sogar {STR_VAR_1} wurde besiegt…\n"
	.string "Das ist unglaublich! Einfach\l"
	.string "unglaublich!\p"
	.string "Wir haben den Trainer nach den\n"
	.string "Eindrücken im Moment des Sieges\l"
	.string "gefragt.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Nach einer Reihe von Siegen musste sich\n"
	.string "das Paar schließlich doch {STR_VAR_2}\l"
	.string "von {STR_VAR_1} geschlagen geben.\p"
	.string "Netter Versuch, Trainer!\p"
	.string "Man sieht nicht oft so ein wunderbares\n"
	.string "Team wie {STR_VAR_1} und\l"
	.string "{STR_VAR_2}. Das könnt ihr glauben!\p"
	.string "Wir haben den Trainer gefragt, wie es\n"
	.string "war, gegen dieses Super-Paar zu\l"
	.string "kämpfen.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Und das hat uns der Trainer gesagt:\n"
	.string "“Ich bin zufrieden!”\p"
	.string "Ist das nicht eine erfrischend offene\n"
	.string "Antwort? Bravo, Trainer!\p"
	.string "Aber ist ein so eingefleischter Trainer\n"
	.string "überhaupt in der Lage, mit einem Kampf\l"
	.string "zufrieden zu sein?\p"
	.string "Ich habe herausgefunden, wie zufrieden\n"
	.string "der Trainer war, als ich diese Worte\l"
	.string "hörte:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Und das hat uns der Trainer verraten:\n"
	.string "“Ich bin nicht zufrieden…”\p"
	.string "Unser Trainer war wohl gerade etwas\n"
	.string "niedergeschlagen, als er das sagte.\p"
	.string "Und es ist nicht immer leicht, nach\n"
	.string "einem Kampf voll zufrieden zu sein,\l"
	.string "richtig?\p"
	.string "Nun, wir haben nachgehakt und heraus-\n"
	.string "gefunden, wie unzufrieden der Trainer\l"
	.string "tatsächlich war:$"

BravoTrainerBattleTower_Text_None1::
	.string "Nichts$"

BravoTrainerBattleTower_Text_None2::
	.string "Nichts$"

BravoTrainerBattleTower_Text_None3::
	.string "Nichts$"

BravoTrainerBattleTower_Text_None4::
	.string "Nichts$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}”.$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}”.\n"
	.string "Ist das nicht großartig?\p"
	.string "Das drückt wahrhaftig die Freude von\n"
	.string "{STR_VAR_2} aus. Das würde ich doch sagen!\p"
	.string "Am Ende noch der Kampf gegen\n"
	.string "{STR_VAR_3}… Das war wirklich das, was\l"
	.string "man “{STR_VAR_1}” nennt!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}”.\n"
	.string "Eine treffende Aussage!\p"
	.string "Das Ende des Kampfes gegen\n"
	.string "{STR_VAR_3}… Man kann es nur\l"
	.string "“{STR_VAR_1}” nennen!\p"
	.string "Ich finde, die Enttäuschung von\n"
	.string "{STR_VAR_2} wird mehr als deutlich.$"

BravoTrainerBattleTower_Text_Outro::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Ich hoffe, wir sehen {STR_VAR_1} noch\n"
	.string "höhere Gipfel erklimmen!\p"
	.string "Das war’s für den Moment!\n"
	.string "Bis zur nächsten Sendung!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Wow!\p"
	.string "Es ist ganz offensichtlich, dass du\n"
	.string "deine Liebe {STR_VAR_1} schenkst.\p"
	.string "Okay, es heißt {STR_VAR_2}.\p"
	.string "Darf ich dich um einen Gefallen bitten?\p"
	.string "Ich bin TV-Reporter und mache eine\n"
	.string "Umfrage zum Thema Pokémon.\p"
	.string "Würdest du mir bitte ein paar einfache\n"
	.string "Fragen beantworten?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Großartig! Danke schön!\p"
	.string "Okay, los geht’s. Ich brauche\n"
	.string "kurze, knappe Antworten, okay?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Als du {STR_VAR_1} zum ersten Mal ge-\n"
	.string "sehen hast, was war das für\l"
	.string "ein Gefühl?\p"
	.string "Wie würdest du die Gefühle zu dem\n"
	.string "Zeitpunkt beschreiben?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Du kümmerst dich liebevoll um\n"
	.string "{STR_VAR_1}.\p"
	.string "Wenn du es mit etwas vergleichen\n"
	.string "würdest, das du magst, was wäre das?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Diese Frage bezieht sich auch auf dein\n"
	.string "geliebtes {STR_VAR_1}.\p"
	.string "Was hat dich an {STR_VAR_1} angezogen?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Okay, das ergibt einen Sinn.\p"
	.string "Diese Frage mag vielleicht etwas schwer\n"
	.string "sein, um sie kurz zu beantworten.\p"
	.string "Also…\p"
	.string "Was bedeuten Pokémon für dich?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Ich verstehe!\p"
	.string "Hmhm…\p"
	.string "Das war’s! Danke, dass du mir deine\n"
	.string "Zeit zur Verfügung gestellt hast!\p"
	.string "Es hat mir viel Spaß gemacht, mich mit\n"
	.string "dir zu unterhalten.\p"
	.string "Vielleicht kannst du dieses Interview\n"
	.string "bald im Fernsehen sehen. Achte darauf!\p"
	.string "Okay, das ist alles.\n"
	.string "Vielen Dank und leb wohl.$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, okay…\p"
	.string "Nun, wenn du mir doch etwas über\n"
	.string "Pokémon erzählen willst, ich bin hier.$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "Ich liebe meinen Job - ich lerne so viel\n"
	.string "über Pokémon während der Interviews.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Hallo, du scheinst deinem {STR_VAR_1}\n"
	.string "sehr nahe zu stehen.\p"
	.string "Weißt du was?\n"
	.string "Ich bin ein TV-Reporter.\p"
	.string "Ich reise herum und interviewe Leute,\n"
	.string "befrage sie zu Pokémon.\p"
	.string "Darf ich dich auch etwas über dein\n"
	.string "{STR_VAR_1} fragen?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Wow, danke schön!\p"
	.string "Dann erzähl mir doch einfach alles, was\n"
	.string "dir an {STR_VAR_1} gefällt.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Wow…\n"
	.string "Das ist ja ein interessanter Bericht.\p"
	.string "Du stehst deinem {STR_VAR_1} sehr nahe,\n"
	.string "nicht wahr?\p"
	.string "Ich denke, dein Bericht wird sich\n"
	.string "großartig im Fernsehen machen.\p"
	.string "Ich verspreche, ich mache daraus eine\n"
	.string "unterhaltsame Sendung. Die darfst\l"
	.string "du nicht verpassen!\p"
	.string "Okay, das war’s.\n"
	.string "Danke und leb wohl.$"

gTVFanClubOpinionsText00::
	.string "Wir sind der Pokémon-Fanclub.\p"
	.string "Wir sind live auf Sendung!\p"
	.string "Hier ist eure Meinung gefragt und ich\n"
	.string "spreche sie öffentlich laut für euch\l"
	.string "aus. Ist das nicht fantastisch?\p"
	.string "Heute bringen wir euch eine Reportage\n"
	.string "unseres Reporters ins Haus, der im Auf-\l"
	.string "trag des Pokémon-Fanclubs unter-\l"
	.string "wegs war.\p"
	.string "Wer ist heute der glückliche\n"
	.string "Pokémon-Fan, den wir hier vorstellen?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "So, was hat uns {STR_VAR_1} wohl über\n"
	.string "{STR_VAR_3}, das {STR_VAR_2},\l"
	.string "zu sagen?\p"
	.string "Und ich… Ich werde die Worte der Zu-\n"
	.string "neigung laut im Fernsehen herausrufen!\p"
	.string "Huuh-haa!\p"
	.string "Lasst uns alle laut rufen!$"

gTVFanClubOpinionsText01::
	.string "Wir haben {STR_VAR_1} gefragt: “Als du\n"
	.string "{STR_VAR_2} das erste Mal gesehen hast,\l"
	.string "was war das für ein Gefühl?”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Juhuhuu! Das ist eine super Aussage!\p"
	.string "Bringt sie euch nicht auch Erinnerungen\n"
	.string "an längst vergangene Zeiten wieder?$"

gTVFanClubOpinionsText02::
	.string "Wir haben {STR_VAR_1} gefragt: “Wenn du\n"
	.string "{STR_VAR_2} mit etwas vergleichen\l"
	.string "würdest, das du magst, was wäre das?”\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Huhuhuuu! Was für ein origineller\n"
	.string "Vergleich!\p"
	.string "Man spürt gleich das intensive Gefühl,\n"
	.string "das der Trainer für {STR_VAR_2}\l"
	.string "empfindet!$"

gTVFanClubOpinionsText03::
	.string "Sehen wir mal weiter…\n"
	.string "Und was genau findet {STR_VAR_1} so\l"
	.string "anziehend an {STR_VAR_2}?\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Heiaaa! Was für eine spektakuläre\n"
	.string "Erklärung!\p"
	.string "Die Liebe dieses Trainers zu seinem\n"
	.string "{STR_VAR_2} wird mehr als deutlich!$"

gTVFanClubOpinionsText04::
	.string "Hm? Oh, da gibt es noch mehr.\n"
	.string "Dem müssen wir mal nachgehen.\p"
	.string "Lasst uns mal sehen…\p"
	.string "Wir haben {STR_VAR_1} gefragt: “Was be-\n"
	.string "deuten dir Pokémon?”\p"
	.string "… … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Bravo!\p"
	.string "Das ist das Beste des heutigen Tages!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Man will das immer und immer wieder\n"
	.string "laut herausrufen!\p"
	.string "Nach diesem großartigen Ausruf ist es\n"
	.string "auch schon wieder Zeit, sich zu\l"
	.string "verabschieden!\p"
	.string "Also rufen wir jetzt zum Abschluss\n"
	.string "alle zusammen…\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "Wir sind der Pokémon-Fanclub.\p"
	.string "Wir sind live auf Sendung!\p"
	.string "Heute steht unsere Sendung ganz im\n"
	.string "Zeichen unserer Pokémon-Umfrage. \p"
	.string "Welcher der Geschichten, die Trainer\n"
	.string "und Pokémon uns liefern, wird heute\l"
	.string "unsere Aufmerksamkeit gehören?\p"
	.string "Mal sehen…\p"
	.string "Diese hier!\p"
	.string "Wir fangen mit diesem Brief an!\p"
	.string "Dies ist ein Brief von {STR_VAR_1} über\n"
	.string "ein geliebtes {STR_VAR_2}.\p"
	.string "Mal sehen, wie leidenschaftlich der\n"
	.string "Schreiber seine Liebe zu {STR_VAR_2}\l"
	.string "ausdrückt! Hmhm…$"

gTVFanClubText01::
	.string "Hui!\n"
	.string "Was für ein wunderbarer Brief!$"

gTVFanClubText02::
	.string "Ich liebe ihn, ich muss ihn nochmal\n"
	.string "lesen!$"

gTVFanClubText03::
	.string "Ein großartiger Brief, den man immer und\n"
	.string "immer wieder lesen muss.$"

gTVFanClubText04::
	.string "Dieses kleine “{STR_VAR_3}!” zeigt\n"
	.string "die unglaublich emotionale Bindung!\p"
	.string "Ein großartiger Brief mit einer das Herz\n"
	.string "erwärmenden Tiefe!$"

gTVFanClubText05::
	.string "Besonders das kleine “{STR_VAR_3}”!\p"
	.string "Ich liebe es, wie “{STR_VAR_3}” hier\n"
	.string "gebraucht wird!$"

gTVFanClubText06::
	.string "Übrigens, auch wenn es nicht wirklich\n"
	.string "wichtig ist, “{STR_VAR_3}” ist\l"
	.string "eine super Aussage.\p"
	.string "Ich werde “{STR_VAR_3}” ab sofort in\n"
	.string "meiner Konversation einsetzen.$"

gTVFanClubText07::
	.string "Wenn ich diesen Brief bewerten müsste,\n"
	.string "bekäme er {STR_VAR_3} Punkte von mir.\p"
	.string "Und für das nächste Mal erwarte ich\n"
	.string "einen noch besseren Brief, {STR_VAR_1}!\p"
	.string "Hui je, schaut euch nur die Uhrzeit an!\n"
	.string "Für heute sage ich Tschüss. Bis zum\l"
	.string "nächsten Mal.$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Ach!\n"
	.string "Magst du vielleicht Pokémon?\p"
	.string "Ich habe einen Vertrag mit einem Fern-\n"
	.string "sehsender.\p"
	.string "Ich sammle aktuelle Geschichten von\n"
	.string "Pokémon und ihren Trainern.\p"
	.string "Hättest du Lust, mir etwas von dir zu\n"
	.string "erzählen?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Ich sammle aktuelle Geschichten von\n"
	.string "Pokémon und ihren Trainern.\p"
	.string "Hättest du Lust, mir etwas von dir zu\n"
	.string "erzählen?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, du hast Lust dazu?!?\n"
	.string "Wunderbar! Danke schön!\p"
	.string "Dann erzähl mir doch bitte von\n"
	.string "interessanten Begebenheiten, in denen\l"
	.string "Pokémon eine Rolle spielen.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Oh, ich versteh’ schon…\p"
	.string "Nun, wenn du mir eine interessante\n"
	.string "Geschichte erzählen kannst, sag es mir.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Hach, eine erhebende Geschichte!\p"
	.string "Ich bin sicher, deine Geschichte wird\n"
	.string "im Fernsehen ausgestrahlt.\p"
	.string "Irgendwann bestimmt. Also, verpasse\n"
	.string "sie nicht!$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hmmm… Da habe ich eine wirklich gute\n"
	.string "Geschichte für das Fernsehprogramm.\p"
	.string "Ich sollte sie schnell aufschreiben!$"

gTVRecentHappeningsText00::
	.string "Hallo, es ist Zeit für Interessante\n"
	.string "Geschichten.\p"
	.string "Für einen Pokémon-Trainer ist jeder\n"
	.string "Tag ein Tag voller Geschichten.\p"
	.string "Wir möchten heute einige dieser \n"
	.string "Pokémon-Geschichten erzählen.\p"
	.string "Heute erzählen wir die Geschichte von\n"
	.string "Trainer {STR_VAR_1}.\p"
	.string "Was mag {STR_VAR_1} wohl erlebt haben?\n"
	.string "Lasst es uns herausfinden.\p"
	.string "Mal sehen…$"

gTVRecentHappeningsText01::
	.string "War das nicht aufschlussreich?\p"
	.string "Diese Geschichte gibt genau wieder, was\n"
	.string "{STR_VAR_1} vor kurzem erlebt hat. So, als\l"
	.string "hätten wir es selber erlebt.$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.” Das gibt\n"
	.string "der Geschichte Akzente und Tiefe.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.” Das gibt\n"
	.string "uns einen Eindruck von dem Schauplatz.\l"
	.string "Wir können uns alles besser vorstellen.$"

gTVRecentHappeningsText04::
	.string "“{STR_VAR_3}” war die\n"
	.string "eindrucksvollste Stelle der Geschichte.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} hat uns eine wundervolle Ge-\n"
	.string "schichte mit Pokémon erzählt.\p"
	.string "Und nun hat sich diese Geschichte tief\n"
	.string "in unsere Seelen eingebrannt.\p"
	.string "Das war es für heute. Bitte schaltet\n"
	.string "auch nächstes Mal wieder ein.$"

gTVMassOutbreakText00::
	.string "Guten Tag, meine Damen und Herren!\n"
	.string "Hier sind die Pokémon Nachrichten.\p"
	.string "Wir haben soeben von einem sehr\n"
	.string "seltenen Ereignis erfahren.\p"
	.string "Es wird berichtet, dass es in der Umge-\n"
	.string "bung von {STR_VAR_1} zu einem Massen-\l"
	.string "aufkommen von {STR_VAR_2} kam.\p"
	.string "{STR_VAR_2}, das ist bestimmt jedem be-\n"
	.string "kannt, ist ein seltenes Pokémon,\l"
	.string "das nur sehr schwer zu finden ist.\p"
	.string "Das scheint eine seltene Gelegenheit\n"
	.string "zu sein, den Ausbruch von wilden\l"
	.string "{STR_VAR_2} zu beobachten.\p"
	.string "Das waren die Pokémon Nachrichten.$"

gTV3CheersForPokeblocksText00::
	.string "MC: Ich hoffe, ihr seid in Topstimmung!\n"
	.string "“3 Hochs für die {POKEBLOCK}!”\p"
	.string "Heute untersuchen wir {POKEBLOCK}, die\n"
	.string "von {STR_VAR_1} und Freunden\l"
	.string "hergestellt wurden.\p"
	.string "Und ohne weitere Verzögerung werden\n"
	.string "wir sie meinem Schluppuck, einem\l"
	.string "wahren Feinschmecker, geben.\p"
	.string "… … … … …\n"
	.string "…\l"
	.string "… … … … …\l"
	.string "…$"

gTV3CheersForPokeblocksText01::
	.string "Schluppuck: Schlupp! Puck!\p"
	.string "MC: Er scheint sehr {STR_VAR_1} zu sein.\n"
	.string "Schluppuck meint, er schmeckt\l"
	.string "“{STR_VAR_2}!”\p"
	.string "Vielen Dank, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "Das Talent von {STR_VAR_1} beim\n"
	.string "Beerenmixen könnte besser sein.\p"
	.string "Wäre dieser Trainer besser, würden\n"
	.string "auch die {POKEBLOCK} besser schmecken.$"

gTV3CheersForPokeblocksText03::
	.string "Schluppuck: Schlupp! Puck!\p"
	.string "MC: Er scheint sehr {STR_VAR_1} zu sein.\n"
	.string "Schluppuck meint, er schmeckt\l"
	.string "“{STR_VAR_2}!”\p"
	.string "{STR_VAR_3} hat Fehler gemacht, die die\n"
	.string "Qualität beeinflussen.$"

gTV3CheersForPokeblocksText04::
	.string "Schade, dass die Bemühungen von\n"
	.string "{STR_VAR_1} umsonst waren.\p"
	.string "Und auch {STR_VAR_2} sollte beim\n"
	.string "nächsten Mal eine bessere Leistung\l"
	.string "zeigen.$"

gTV3CheersForPokeblocksText05::
	.string "Freut euch auf die nächste Sendung!\n"
	.string "Unsere Devise lautet\l"
	.string "“3 Hochs für die {POKEBLOCK}!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Hey, du da!\p"
	.string "Ich bin ein großer Fan von {STR_VAR_1}.\n"
	.string "Was hältst du von {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Ah ha. Das ist also deine Meinung über\n"
	.string "diesen Trainer.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Du erinnerst dich gar nicht mehr an\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Ich bin ein großer Fan von {STR_VAR_1}.\n"
	.string "Was hältst du von {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Für wie stark würdest du {STR_VAR_1}\n"
	.string "auf einer Skala von 0 bis 100 halten?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Du erinnerst dich gar nicht mehr an\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Ach so! Ich hoffe, du triffst\n"
	.string "{STR_VAR_1} irgendwann mal. Dann wirst\l"
	.string "du bestimmt auch ein Fan.$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Ah ha.\p"
	.string "Vielen Dank!\n"
	.string "Das war interessant.\p"
	.string "Ich werde das anderen Fans von\n"
	.string "{STR_VAR_1} mitteilen und mit ihnen\l"
	.string "darüber diskutieren.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Im Fernsehen zeigen sie bald eine\n"
	.string "Sondersendung über {STR_VAR_1}.\p"
	.string "Die darf ich auf keinen Fall verpassen!$"

gTVTrainerFanClubSpecialText00::
	.string "Pokémon Trainer-Fanclub\n"
	.string "Sondersendung über {STR_VAR_1}!\p"
	.string "Heute bieten wir allen Fans in Hoenn, \n"
	.string "die {STR_VAR_1} bewundern, etwas\l"
	.string "Besonderes!\p"
	.string "Wir haben uns die Frage gestellt: “Was\n"
	.string "denken die Leute über {STR_VAR_1}?”\p"
	.string "Wir fragten repräsentativ den Trainer\n"
	.string "{STR_VAR_2}.\p"
	.string "Unsere Frage: “Wie würdest du\n"
	.string "{STR_VAR_1} mit einem Wort\l"
	.string "beschreiben?”\p"
	.string "Die Antwort: “{STR_VAR_3}.”\p"
	.string "Wunderbar, {STR_VAR_2}!\n"
	.string "Was für eine scharfsinnige Antwort.\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.”\n"
	.string "Eine treffende Beschreibung.\p"
	.string "{STR_VAR_2} legte die Stärke von\n"
	.string "{STR_VAR_1} auf einer Skala von\l"
	.string "1 bis 100 fest.$"

gTVTrainerFanClubSpecialText01::
	.string "Sie liegt bei {STR_VAR_3}!\n"
	.string "Eine sehr hohe Zahl!\p"
	.string "{STR_VAR_2} scheint {STR_VAR_1}\n"
	.string "sehr zu schätzen und zu bewundern.$"

gTVTrainerFanClubSpecialText02::
	.string "Sie liegt bei {STR_VAR_3}!\n"
	.string "Ein guter Wert!\p"
	.string "{STR_VAR_2} sieht in {STR_VAR_1}\n"
	.string "anscheinend einen Rivalen.$"

gTVTrainerFanClubSpecialText03::
	.string "Sie liegt bei {STR_VAR_3}!\n"
	.string "Nicht gerade beeindruckend.\p"
	.string "{STR_VAR_2} hält {STR_VAR_1}\n"
	.string "wohl für einen Trainer, der nur\l"
	.string "zufällig Kämpfe gewinnt.$"

gTVTrainerFanClubSpecialText04::
	.string "Sie liegt bei {STR_VAR_3}!\n"
	.string "Was für eine Blamage…\p"
	.string "{STR_VAR_2} scheint von {STR_VAR_1}\n"
	.string "gar nichts zu halten.$"

gTVTrainerFanClubSpecialText05::
	.string "Das war’s, Leute!\p"
	.string "Ich bin sicher, wir haben viel Neues \n"
	.string "über {STR_VAR_1} erfahren.\p"
	.string "Ich verabschiede mich mit den Worten\n"
	.string "von {STR_VAR_2}.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "Und nun ist es wieder Zeit für…\n"
	.string "Die Namenbewerter Show\p"
	.string "Ich sage die Zukunft eures Pokémon\n"
	.string "anhand seines Kosenamens vorher.\p"
	.string "Ratschläge habe ich zu geben und\n"
	.string "hilfreiche Ratschläge biete ich an.\p"
	.string "Heute basiert meine Prophezeiung auf\n"
	.string "dem Kosenamen {STR_VAR_3} des\l"
	.string "Pokémon {STR_VAR_2} von {STR_VAR_1}.\p"
	.string "Hmhm…\p"
	.string "Hmm…\n"
	.string "Dieser Kosename…$"

gTVNameRaterText01::
	.string "Ein Kosename, der auf ein vielfältiges\n"
	.string "Talent hindeutet.\p"
	.string "Ich rate dem Trainer, mutig zu sein\n"
	.string "und sich vielen Herausforderungen\l"
	.string "zu stellen.$"

gTVNameRaterText02::
	.string "Dieser Kosename passt perfekt\n"
	.string "zu {STR_VAR_1}, dem Namen des Trainers!\p"
	.string "Ich sehe eine starke Partnerschaft, in\n"
	.string "der das Timing perfekt ist.$"

gTVNameRaterText03::
	.string "Dieser Kosename betont die einzig-\n"
	.string "artige Persönlichkeit des Pokémon.\p"
	.string "Wird das Pokémon gut aufgezogen, ent-\n"
	.string "wickelt sich seine Einzigartigkeit voll.$"

gTVNameRaterText04::
	.string "Dieser Kosename zeigt die mitfühlende\n"
	.string "und fürsorgliche Seite der Pokémon.\p"
	.string "Wird dieses Pokémon gut aufgezogen,\n"
	.string "wird es sehr warmherzig sein!$"

gTVNameRaterText05::
	.string "Ein schöner Kosename, der auf die\n"
	.string "zukünftige Größe hindeutet.\p"
	.string "Mich würde es schon interessieren, was\n"
	.string "die Zukunft für dieses Pokémon bringt.$"

gTVNameRaterText06::
	.string "Dieser gute Kosename sollte das\n"
	.string "Pokémon kräftig und herzlich\l"
	.string "werden lassen!\p"
	.string "Dieses Pokémon wird für lange, lange\n"
	.string "Zeit gesund und fit sein.$"

gTVNameRaterText07::
	.string "Dieser gute Kosename sollte das\n"
	.string "Pokémon sehr aktiv machen!\p"
	.string "Ich denke, das Pokémon wird in\n"
	.string "Kämpfen stark auftreten.$"

gTVNameRaterText08::
	.string "Ein ansprechender Kosename, der dem\n"
	.string "Pokémon Charme verleihen wird!\p"
	.string "Ich bezweifle nicht, dass das Pokémon\n"
	.string "in einem Pokémon Wettbewerb alle\l"
	.string "mit seinem Charme betören wird!$"

gTVNameRaterText09::
	.string "Der Kosename {STR_VAR_1} wurzelt in\n"
	.string "dem Buchstaben “{STR_VAR_3}”.\p"
	.string "Der Buchstabe wird noch verstärkt\n"
	.string "durch den Anfangsbuchstaben “{STR_VAR_2}”,\p"
	.string "wodurch der Kosename eine starke\n"
	.string "Ausstrahlung bekommt.$"

gTVNameRaterText10::
	.string "Der Kosename {STR_VAR_1} ist auf \n"
	.string "ansprechende Weise wohlklingend.\p"
	.string "Die Ausstrahlung der Buchstaben “{STR_VAR_2}”\n"
	.string "und “{STR_VAR_3}” - einfach bemerkenswert!$"

gTVNameRaterText11::
	.string "Der Kosename {STR_VAR_1} - er strahlt\n"
	.string "ein sublimes, fließendes Gefühl aus.\p"
	.string "Der Fluss des ersten Buchstabens “{STR_VAR_2}”\n"
	.string "bis hin zum “{STR_VAR_3}” ist wunderbar.$"

gTVNameRaterText12::
	.string "Lasst uns weitere Beispiele für gute\n"
	.string "Kosenamen untersuchen.$"

gTVNameRaterText13::
	.string "Nehmen wir zum Beispiel einen Teil des\n"
	.string "Namens von Trainer {STR_VAR_1}. Wir er-\l"
	.string "halten den schönen Kosenamen {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "Natürlich wäre der Kosename {STR_VAR_2}{STR_VAR_3}\n"
	.string "genauso schön.$"

gTVNameRaterText15::
	.string "Der Name der Pokémon-Kategorie\n"
	.string "{STR_VAR_2} kann ebenfalls als Basis\l"
	.string "für den Kosenamen {STR_VAR_1}{STR_VAR_3} dienen.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} ist ebenfalls ein anziehender\n"
	.string "Kosename.$"

gTVNameRaterText17::
	.string "Man sollte niemals einem Pokémon die\n"
	.string "Kategoriebezeichnung eines anderen\l"
	.string "Pokémon als Kosenamen geben!\p"
	.string "Zum Beispiel sollte der Name von\n"
	.string "{STR_VAR_2} nicht für den Namen {STR_VAR_1}{STR_VAR_3}\l"
	.string "verwendet werden.$"

gTVNameRaterText18::
	.string "Aber ich gebe zu, {STR_VAR_1}\n"
	.string "ist wirklich ein guter Kosename.\p"
	.string "Und ich hoffe, dass der Trainer\n"
	.string "{STR_VAR_1} weiter liebevoll behandelt.\p"
	.string "Das war unsere heutige Show.\n"
	.string "Wir sehen uns hoffentlich bald wieder.$"

gTVPokemonAnglerText00::
	.string " {STR_VAR_2}-Angler\p"
	.string "Moderator: Hallo! Heute gibt es\n"
	.string "Tipps zum Angeln von {STR_VAR_2}.\p"
	.string "Guru, welchen Ratschlag haben\n"
	.string "Sie für uns?\p"
	.string "Guru: Hm? Ein {STR_VAR_2} fangen?\n"
	.string "Nun, zunächst sind Geduld und Ausdauer\l"
	.string "gefragt. Das ist das Wichtigste.\p"
	.string "Sehen Sie {STR_VAR_1} dort drüben?\n"
	.string "Dieser Trainer ist ein gutes Beispiel.\p"
	.string "Der Trainer hat bereits {STR_VAR_3}\n"
	.string "Pokémon entkommen lassen.\p"
	.string "Aber {STR_VAR_1} wartet ab. Gibt nicht auf.\n"
	.string "Das ist die erste Regel beim Angeln von\l"
	.string "{STR_VAR_2}.\p"
	.string "Moderator: Ich verstehe…\p"
	.string "Oh! {STR_VAR_1} hat endlich das extrem\n"
	.string "schnelle {STR_VAR_2} gefangen!\p"
	.string "Der Trainer ist den Tränen nahe vor\n"
	.string "Freude!\p"
	.string "Wenn ich diesen begeisterten Ausdruck\n"
	.string "sehe, möchte ich auch Angeln gehen.\p"
	.string "Zuschauer, warum nutzen Sie nicht die\n"
	.string "Chance, einige {STR_VAR_2} zu fischen?\p"
	.string "Bis zur nächsten Sendung leben Sie wohl\n"
	.string "und Petri heil!$"

gTVPokemonAnglerText01::
	.string " {STR_VAR_2}-Angler\p"
	.string "Moderator: Hallo! Heute gibt es\n"
	.string "Tipps zum Angeln von {STR_VAR_2}.\p"
	.string "Guru, welchen Ratschlag haben\n"
	.string "Sie für uns?\p"
	.string "Guru: Hm? {STR_VAR_2} fangen?\n"
	.string "Nun, setzen Sie Ihre Angel mit viel\l"
	.string "Kraft ein.\p"
	.string "Sehen Sie {STR_VAR_1} dort drüben?\n"
	.string "Wie hier die Angel gehandhabt wird?\p"
	.string "Der Trainer hat bereits {STR_VAR_3}\n"
	.string "fangen können.\p"
	.string "Moderator: Das ist unglaublich!\n"
	.string "Es wirkt wie ein Sturm…\p"
	.string "Wenn ich solche Techniken beobachte,\n"
	.string "möchte ich auch sofort Angeln gehen.\p"
	.string "Zuschauer, warum nutzen Sie nicht die\n"
	.string "Chance, einige {STR_VAR_2} zu fischen?\p"
	.string "Bis zur nächsten Sendung leben Sie wohl\n"
	.string "und Petri heil!$"

gTVPokemonTodayFailedText00::
	.string "Hallo!\p"
	.string "Willkommen bei Pokémon Heute!\p"
	.string "Schwester: Hallo! Alles gesund\n"
	.string "und munter?\p"
	.string "Heute werfen wir einen Blick auf das\n"
	.string "Pokémon {STR_VAR_2} von {STR_VAR_1}!\p"
	.string "Bruder: Yeah! Genau das werden wir tun!$"

gTVPokemonTodayFailedText01::
	.string "Oh!\n"
	.string "Da wir gerade über {STR_VAR_1} sprechen…\p"
	.string "Schwester, ich habe den Trainer mit\n"
	.string "eigenen Augen gesehen!\p"
	.string "Schwester: Und was hast du\n"
	.string "beobachtet?\p"
	.string "Bruder: Nun, ich war gerade unterwegs\n"
	.string "nach {STR_VAR_2}.\p"
	.string "Da sah ich, wie {STR_VAR_1} versuchte, das \n"
	.string "Pokémon {STR_VAR_3} zu fangen, aber…$"

gTVPokemonTodayFailedText02::
	.string "Das Pokémon konnte flüchten!\p"
	.string "Und wie viele Pokébälle wurden am Ende\n"
	.string "verbraucht? {STR_VAR_2}! Und das für nichts!\p"
	.string "Du hättest den frustrierten Ausdruck\n"
	.string "im Gesicht von {STR_VAR_1} sehen\p"
	.string "sollen, als das Pokémon sich aus dem\n"
	.string "Staub machte!$"

gTVPokemonTodayFailedText03::
	.string "Aber {STR_VAR_1} hat so lange daneben-\n"
	.string "geworfen, bis das Pokémon\l"
	.string "kampfunfähig wurde!\p"
	.string "Und wie viele Pokébälle wurden am Ende\n"
	.string "verbraucht? {STR_VAR_2}! Und das für nichts!\p"
	.string "Du hättest den Ausdruck fassungsloser\n"
	.string "Bestürzung auf dem Gesicht von\l"
	.string "{STR_VAR_1}\p"
	.string "sehen sollen, als das Pokémon plötzlich\n"
	.string "kampfunfähig wurde!$"

gTVPokemonTodayFailedText04::
	.string "Schwester: Hey, du da!\n"
	.string "Das ist aber nicht nett!\p"
	.string "Du solltest dich nicht über das Unglück\n"
	.string "anderer lustig machen!\p"
	.string "Oh, mir tut {STR_VAR_1} Leid.\n"
	.string "Was für eine Schande!\p"
	.string "Bruder: Da hast du Recht!\n"
	.string "Tut mir Leid, dass ich gelacht habe.$"

gTVPokemonTodayFailedText05::
	.string "Schwester: Räusper Haha Räusper Haha…\p"
	.string "Bruder: Hey!\n"
	.string "Du lachst ja!\p"
	.string "Schwester: Ich???\p"
	.string "Ich habe doch nicht gelacht!\n"
	.string "Ehrlich nicht!\p"
	.string "Mir tut {STR_VAR_1} echt Leid.\n"
	.string "Was für eine Schande!\p"
	.string "Bruder: …$"

gTVPokemonTodayFailedText06::
	.string "Schwester: Schluss jetzt mit dem\n"
	.string "Blödsinn! Lasst uns das heutige\l"
	.string "Pokémon betrachten…\p"
	.string "Wie?\n"
	.string "Wir haben keine Zeit mehr dafür?\p"
	.string "Oooh! Dann haben wir heute ja gar kein\n"
	.string "Pokémon vorgestellt!\p"
	.string "Bruder: Also, bis zum nächsten Mal!\p"
	.string "Schwester: Hey, du kannst die Show\n"
	.string "doch nicht einfach ohne mich beenden!$"

gTVPokemonTodaySuccessfulText00::
	.string "Hallo!\p"
	.string "Willkommen bei Pokémon Heute!\p"
	.string "Schwester: Hallo! Alles gesund\n"
	.string "und munter?\p"
	.string "Heute werfen wir einen Blick auf das\n"
	.string "Pokémon {STR_VAR_2} von {STR_VAR_1}!\p"
	.string "Bruder: Yeah! Genau das werden wir tun!$"

gTVPokemonTodaySuccessfulText01::
	.string "Schwester: {STR_VAR_1} hat {STR_VAR_2} den\n"
	.string "Kosenamen {STR_VAR_3} gegeben!\p"
	.string "{STR_VAR_3} scheint wirklich liebevoll\n"
	.string "behandelt zu werden.$"

gTVPokemonTodaySuccessfulText02::
	.string "Bruder: Und wie viele Bälle musste der\n"
	.string "Trainer werfen, um es zu fangen? {STR_VAR_3}!\p"
	.string "Ein {STR_VAR_2} brachte den\n"
	.string "gewünschten Erfolg!$"

gTVPokemonTodaySuccessfulText03::
	.string "Schwester: Wenn das Fangen so einfach\n"
	.string "war, wollte das Schicksal {STR_VAR_1} und\l"
	.string "{STR_VAR_2} wohl zusammenführen!$"

gTVPokemonTodaySuccessfulText04::
	.string "Schwester: Wow! Wie aufregend!\p"
	.string "Man sagt, dass ein Pokémon, das schwer\n"
	.string "zu fangen ist, die Liebe seines\l"
	.string "Trainers verdient!$"

gTVPokemonTodaySuccessfulText05::
	.string "Schwester: {STR_VAR_2} von {STR_VAR_1} ist\n"
	.string "ein bemerkenswertes Pokémon, da\p"
	.string "es nur mit dem unfehlbaren\n"
	.string "Meisterball gefangen werden konnte!\p"
	.string "Bruder: Wow! Das ist\n"
	.string "mega-beeindruckend!\p"
	.string "Schwester: {STR_VAR_1} muss {STR_VAR_2} \n"
	.string "wirklich gewollt haben! Mit Sicherheit!$"

gTVPokemonTodaySuccessfulText06::
	.string "Bruder: Und dann erhält {STR_VAR_2}\n"
	.string "auch noch den Kosenamen {STR_VAR_3}…\p"
	.string "Das ermöglicht einen guten Einblick in\n"
	.string "die Einstellung von Trainer {STR_VAR_1}.\p"
	.string "Schwester: Das sehe ich auch so!$"

gTVPokemonTodaySuccessfulText07::
	.string "Ich würde diesen Kosenamen einem\n"
	.string "{STR_VAR_3} geben!\p"
	.string "Bruder: Hui! Das wäre der Anfang von\n"
	.string "etwas ganz Neuem.$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2}, das {STR_VAR_1}?\n"
	.string "Hört sich das nicht einfach perfekt an?\p"
	.string "Die Buchstaben und alles - wie\n"
	.string "geschaffen für das Pokémon\l"
	.string "{STR_VAR_1}!\p"
	.string "Bruder: Yeah! Stimmt! Absolut!$"

gTVPokemonTodaySuccessfulText09::
	.string "Soweit ich weiß, hat noch kein Trainer\n"
	.string "jemals seinem {STR_VAR_1} den\l"
	.string "Kosenamen {STR_VAR_2} gegeben!\p"
	.string "Bruder: Das zeigt doch nur, welch einen\n"
	.string "hervorragenden Geschmack der Trainer\l"
	.string "bei der Wahl des Kosenamens bewies!$"

gTVPokemonTodaySuccessfulText10::
	.string "Mein nächstes Pokémon bekommt den\n"
	.string "Kosenamen {STR_VAR_2}.\p"
	.string "Bruder: Wie? Meines auch!\n"
	.string "Ich werde es auch {STR_VAR_2} nennen!$"

gTVPokemonTodaySuccessfulText11::
	.string "Schwester: Oh je!\n"
	.string "Schau dir nur die Uhrzeit an!\p"
	.string "Nun, Freunde, das war es für heute.\n"
	.string "Wir sehen uns das nächste Mal wieder!\p"
	.string "Bruder: Denkt daran, es könnte euer\n"
	.string "Pokémon sein, das wir hier vorstellen!$"

SmartShopper_Text_Intro::
	.string "Hallo!\p"
	.string "Zeit für den heutigen Cleverkauf!\p"
	.string "Interviewer: Wie geht es euch?\p"
	.string "Heute besuchen wir ein Geschäft\n"
	.string "in {STR_VAR_2}.\p"
	.string "Schauen wir doch mal, welche Artikel\n"
	.string "dort besonders begehrt sind.$"

SmartShopper_Text_ClerkNormal::
	.string "Fragen wir doch einfach den Verkäufer\n"
	.string "hier.\p"
	.string "Hallo, wie läuft das Geschäft?\p"
	.string "Verkäufer: Oh, ausgezeichnet!\p"
	.string "Im Moment verkaufen wir {STR_VAR_2}\n"
	.string "besonders gut.\p"
	.string "Und gerade hat ein Trainer namens\n"
	.string "{STR_VAR_1} {STR_VAR_3} gekauft.$"

SmartShopper_Text_RandomComment1::
	.string "Interviewer: Der Trainer hat {STR_VAR_3}-mal\n"
	.string "{STR_VAR_2} gekauft? Wow!\p"
	.string "Mir scheint es, als ob {STR_VAR_1} sich\n"
	.string "für eine längere Reise rüstet.\p"
	.string "Auf Reisen ist {STR_VAR_2} einfach\n"
	.string "unverzichtbar.$"

SmartShopper_Text_RandomComment2::
	.string "Interviewer: Da wir gerade von\n"
	.string "{STR_VAR_2} sprechen…\l"
	.string "Ich habe {STR_VAR_3} gekauft.\p"
	.string "{STR_VAR_2} ist ein großartiges Item!$"

SmartShopper_Text_RandomComment3::
	.string "Interviewer: {STR_VAR_2}?!?\n"
	.string "Und gleich {STR_VAR_3} davon?!?\p"
	.string "Ich hätte nicht gedacht, dass jemand\n"
	.string "so viel davon kauft.\p"
	.string "Meine Güte, ich könnte mir höchstens\n"
	.string "ein oder zwei auf einmal davon leisten…$"

SmartShopper_Text_RandomComment4::
	.string "Interviewer: Ich habe erst ein Mal\n"
	.string "sehr viel gekauft. Eine große\l"
	.string "Stückzahl des Items {STR_VAR_2}.\p"
	.string "Aber schließlich war auch das zu viel.\n"
	.string "Ich habe es hinterher echt bereut…\p"
	.string "Seitdem kaufe ich grundsätzlich nur\n"
	.string "noch das, was ich wirklich brauche…\p"
	.string "Huups!\p"
	.string "Wir wollen doch hier nicht über mich\n"
	.string "reden!$"

SmartShopper_Text_SecondItem::
	.string "Verkäufer: {STR_VAR_1} hat auch von dem\n"
	.string "Item {STR_VAR_2} gleich {STR_VAR_3}\l"
	.string "Exemplare gekauft.\p"
	.string "Interviewer: Oh, das ist clever.\n"
	.string "{STR_VAR_2} ist ein sehr gutes Item…$"

SmartShopper_Text_ThirdItem::
	.string "Verkäufer: Und der Trainer kaufte\n"
	.string "von dem Item {STR_VAR_2} {STR_VAR_3}\l"
	.string "Exemplare.$"

SmartShopper_Text_DuringSale::
	.string "Verkäufer: Und zwar als es im Sonder-\n"
	.string "angebot war. Clever!!!$"

SmartShopper_Text_OutroNormal::
	.string "Interviewer: Hmm… {STR_VAR_1} scheint ein\n"
	.string "richtiger Schnäppchenjäger zu sein!\p"
	.string "{STR_VAR_1} brauchte also für alles nur…\p"
	.string "¥{STR_VAR_2} zu bezahlen?!?\n"
	.string "Wie unglaublich günstig!\p"
	.string "Oh! Wir sind am Ende unserer Sendung!\n"
	.string "Bis zum nächsten Mal! Auf Wiedersehen!$"

SmartShopper_Text_IsVIP::
	.string "Verkäufer: {STR_VAR_1} ist ein VIP-Kunde,\n"
	.string "daran besteht kein Zweifel.$"

SmartShopper_Text_ClerkMax::
	.string "Fragen wir doch mal den Verkäufer.\p"
	.string "Hallo, wie läuft das Geschäft?\p"
	.string "Verkäufer: Oh, es ist einfach un-\n"
	.string "glaublich. Einfach überwältigend.\p"
	.string "Vor kurzem hat ein Trainer namens\n"
	.string "{STR_VAR_1} das Item {STR_VAR_2}\l"
	.string "in großer Stückzahl gekauft.\p"
	.string "Er hat fast das ganze Regal mit\n"
	.string "{STR_VAR_2} leergeräumt.\p"
	.string "Ich hätte nie gedacht, dass es einen\n"
	.string "Trainer gibt, der {STR_VAR_2} \l"
	.string "in so großen Mengen benötigt!\p"
	.string "Interviewer: Das waren dann ja 100\n"
	.string "oder 200 Exemplare!?!\p"
	.string "Verkäufer: Oh, nein. Viel, viel mehr!\p"
	.string "Interviewer: Du meine Güte! {STR_VAR_1}\n"
	.string "muss ein ganz besonderer Kunde sein!\p"
	.string "Verkäufer: {STR_VAR_1} ist ein VIP-Kunde,\n"
	.string "daran besteht gar kein Zweifel!$"

SmartShopper_Text_OutroMax::
	.string "Interviewer: Hmm…\n"
	.string "Das ist unglaublich.\p"
	.string "Aber warum hat der Trainer wohl gleich\n"
	.string "so viel auf einmal gekauft?\p"
	.string "… …\p"
	.string "Ein Mysterium… Aber leider haben wir\n"
	.string "keine Zeit mehr, hinter das Geheimnis\l"
	.string "zu kommen. Bis zur nächsten Sendung!\p"
	.string "{STR_VAR_1} muss ein Rätsel bleiben…$"

gTVWorldOfMastersText00::
	.string "Die Welt der Meister\p"
	.string "Hallo, liebe Zuschauer.\p"
	.string "Vielleicht ist Ihnen schon einmal der\n"
	.string "Trainer {STR_VAR_1} begegnet.\p"
	.string "{STR_VAR_1} ist berühmt als Meister im\n"
	.string "Fangen von Pokémon.\p"
	.string "Der Erfolg von {STR_VAR_1} im Fangen von\n"
	.string "Pokémon basiert auf einer gründlichen\l"
	.string "Suche, die zu Fuß stattfindet.\p"
	.string "Eines denkwürdigen Tages machte\n"
	.string "der Trainer  {STR_VAR_2} Schritte.\p"
	.string "Die Gesamtzahl der an diesem Tag\n"
	.string "gefangenen Pokémon betrug {STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Diese bemerkenswerte Leistung war nur\n"
	.string "möglich, weil zwischen dem Trainer und\l"
	.string "{STR_VAR_1} tiefes Vertrauen besteht.$"

gTVWorldOfMastersText02::
	.string "Der Meister hat das letzte {STR_VAR_3}\n"
	.string "an diesem Tage in der Nähe von\l"
	.string "{STR_VAR_2} gefangen.\p"
	.string "Dieses Pokémon kann sich nun an\n"
	.string "dem besonderen Rang des Rekordhalters\l"
	.string "erfreuen.\p"
	.string "Talentierte Trainer sollten versuchen,\n"
	.string "diesen Rekord zu brechen.\p"
	.string "Das war’s für heute.\n"
	.string "Bis zum nächsten Mal.$"

gTVTodaysRivalTrainerText00::
	.string "Heutiger Rivale!\p"
	.string "Hallo, geschätzte Trainer!\n"
	.string "Wie geht es euch heute?\p"
	.string "Heute wollen wir, wie an jedem Tag,\n"
	.string "einen Blick auf unsere Rivalen werfen.$"

gTVTodaysRivalTrainerText07::
	.string "Unser heutiger Rivale ist\n"
	.string "Trainer {STR_VAR_1}. Er befindet sich\p"
	.string "momentan in der Gegend\n"
	.string "von {STR_VAR_3}.\p"
	.string "{STR_VAR_1} hat bis jetzt {STR_VAR_2} Pokémon\n"
	.string "im Pokédex verzeichnet.$"

gTVTodaysRivalTrainerText08::
	.string "Unser heutiger Rivale ist\n"
	.string "Trainer {STR_VAR_1}. Er befindet sich\l"
	.string "momentan in einer Geheimbasis.\p"
	.string "{STR_VAR_1} hat bis jetzt {STR_VAR_2} Pokémon\n"
	.string "im Pokédex verzeichnet.$"

gTVTodaysRivalTrainerText09::
	.string "Unser heutiger Rivale ist\n"
	.string "Trainer {STR_VAR_1}. \p"
	.string "{STR_VAR_1} hat bis jetzt {STR_VAR_2} Pokémon\n"
	.string "im Pokédex verzeichnet.$"

gTVTodaysRivalTrainerText10::
	.string "Unser heutiger Rivale ist\n"
	.string "Trainer {STR_VAR_1}. Er befindet sich\l"
	.string "gerade auf einer Fähre.\p"
	.string "{STR_VAR_1} hat bis jetzt {STR_VAR_2} Pokémon\n"
	.string "im Pokédex verzeichnet.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "Und wie viele Orden besitzt euer\n"
	.string "Rivale bereits? {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Aber unser Rivale besitzt keinen\n"
	.string "einzigen Orden.$"

gTVTodaysRivalTrainerText03::
	.string "Unser Rivale hat bis jetzt noch kein\n"
	.string "einziges Symbol der Kampfzone\l"
	.string "erhalten.$"

gTVTodaysRivalTrainerText04::
	.string "Schauen wir uns mal an, wie viele\n"
	.string "Symbole der Kampfzone unser\l"
	.string "Rivale bereits besitzt.\p"
	.string "Goldene Symbole: {STR_VAR_1}!\n"
	.string "Silberne Symbole: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Unser Rivale hat sich {STR_VAR_1} Gewinn-\n"
	.string "punkte in der Kampfzone erkämpft.$"

gTVTodaysRivalTrainerText06::
	.string "Und wie schneidest du im Vergleich zu\n"
	.string "{STR_VAR_1} ab?\p"
	.string "Das Abenteuer geht weiter!\p"
	.string "Liebe Trainer!\p"
	.string "Lasst uns alle unseren Weg weitergehen\n"
	.string "und unsere Rivalen überrunden!$"

TrendWatcher_Text_Intro::
	.string "Faustauhaven Trend-show!\p"
	.string "MC: Wie geht’s?\n"
	.string "Wir bringen euch das pralle Leben ins\l"
	.string "Haus und zeigen euch, was in\p"
	.string "Faustauhaven gerade angesagt ist.\n"
	.string "Unser heutiger Gast ist dieser alte\l"
	.string "Freund hier, der von sich behauptet,\p"
	.string "sich in Faustauhaven in allem\n"
	.string "auszukennen.\p"
	.string "Alter Mann: Es freut mich, hier zu sein.\p"
	.string "MC: Kommen wir gleich zur Sache.\p"
	.string "Sag uns, was gerade angesagt ist in\n"
	.string "Faustauhaven.\p"
	.string "Alter Mann: {STR_VAR_1}\n"
	.string "{STR_VAR_2}!\p"
	.string "MC: {STR_VAR_1} {STR_VAR_2}? \p"
	.string "Alter Mann: Nein.\p"
	.string "{STR_VAR_1} {STR_VAR_2} war bei den\n"
	.string "Leuten niemals so richtig angesagt.\p"
	.string "Möchtet ihr etwas darüber hören?\p"
	.string "MC: Äh, nein. Für uns zählt nur, was\n"
	.string "gerade jetzt im Trend liegt und\l"
	.string "angesagt ist…$"

TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Alter Mann: {STR_VAR_3} aus Wurzelheim\n"
	.string "hat mir verraten, dass {STR_VAR_1}\l"
	.string "{STR_VAR_2} angesagt sei…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Alter Mann: {STR_VAR_3} aus Wurzelheim\n"
	.string "hat mir verraten, dass {STR_VAR_1}\l"
	.string "{STR_VAR_2} angesagt sei…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Aber es war aussichtslos:\p"
	.string "Ich organisierte {STR_VAR_1}\n"
	.string "{STR_VAR_2}-Festivals!\l"
	.string "Und auch Wettbewerbe!\p"
	.string "Ich versuchte, es jedem schmackhaft\n"
	.string "zu machen…\p"
	.string "Vielleicht passte {STR_VAR_1}\n"
	.string "einfach nicht…\p"
	.string "MC: Äh, Entschuldigung… Aber wir\n"
	.string "möchten wissen, was jetzt angesagt\l"
	.string "ist…$"

TrendWatcher_Text_MaleTellMeBigger::
	.string "Alter Mann: {STR_VAR_3}!\n"
	.string "Komm mit etwas Besserem um die Ecke\l"
	.string "als {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Alter Mann: {STR_VAR_3}!\n"
	.string "Komm mit etwas Besserem um die Ecke\l"
	.string "als {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "MC: Äh… Ihr habt es gehört, Fans des\n"
	.string "neuesten Trends!\p"
	.string "{STR_VAR_1} {STR_VAR_2}… Äh…\n"
	.string "War in Faustauhaven ein Reinfall.\p"
	.string "Unsere Zeit ist um! Macht’s gut!\p"
	.string "Alter Mann: {STR_VAR_1}\n"
	.string "{STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "Hoenn Schatzsucher!\p"
	.string "Hallo, ihr Suchenden!\n"
	.string "Habt ihr in letzter Zeit verborgene\l"
	.string "Items entdeckt?\p"
	.string "Wie immer sind wir offen für\n"
	.string "Augenzeugen, die uns von den ver-\l"
	.string "borgenen Schätzen berichten.\p"
	.string "Hier haben wir einen Brief!\n"
	.string "Darin steht: “{STR_VAR_1} entdeckt!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "Wow! Den Brief muss ich euch vorlesen!\p"
	.string "Meine lieben Schatzsucher, ich hoffe,\n"
	.string "es geht euch allen gut.\p"
	.string "Vor kurzem habe ich {STR_VAR_2} in der\n"
	.string "Nähe von {STR_VAR_3} getroffen.\p"
	.string "Dieser Trainer hatte das Item\n"
	.string "{STR_VAR_1} gefunden.\p"
	.string "Ich war richtig neidisch!\p"
	.string "Gut gemacht, {STR_VAR_2}!\p"
	.string "Das sollte euch als Ansporn dienen!\n"
	.string "Powert eure Detektoren auf und macht\p"
	.string "euch auf die Suche! Ich warte auf\n"
	.string "interessante Berichte von euch allen!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Wow! Den Brief muss ich euch vorlesen!\p"
	.string "Meine lieben Schatzsucher, ich hoffe,\n"
	.string "es geht euch allen gut.\p"
	.string "Vor kurzem habe ich {STR_VAR_2} auf\n"
	.string "einer Fähre getroffen.\p"
	.string "Dieser Trainer hatte das Item\n"
	.string "{STR_VAR_1} gefunden.\p"
	.string "Ich war richtig neidisch!\p"
	.string "Gut gemacht, {STR_VAR_2}!\p"
	.string "Das sollte euch als Ansporn dienen!\n"
	.string "Powert eure Detektoren auf und macht\p"
	.string "euch auf die Suche! Ich warte auf\n"
	.string "interessante Berichte von euch allen!$"

gTVFindThatGamerText00::
	.string "Wer ist der Beste Spieler!\p"
	.string "Ein dickes Hallo an alle Spieler!\n"
	.string "Wie läuft es beim {STR_VAR_2}?\p"
	.string "Wie immer suchen wir nach einem\n"
	.string "Trainer, der die Spielhalle besucht.\p"
	.string "Unser heutiger Topspieler ist…\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} hat\n"
	.string "{STR_VAR_2} gespielt und\l"
	.string "{STR_VAR_3} Münzen gewonnen.\p"
	.string "“Wenn {STR_VAR_1} hier ist, müssen wir\n"
	.string "darauf achten, genug Münzen vorrätig\l"
	.string "zu haben.”\p"
	.string "Das sagen die Angestellten der\n"
	.string "Spielhalle, wenn unser Trainer im\l"
	.string "Spiel ist!\p"
	.string "Solltet ihr die Spielhalle besuchen\n"
	.string "und {STR_VAR_2} spielen, dann\p"
	.string "achtet so gut auf eure Münzen, wie\n"
	.string "{STR_VAR_1} das tut.\p"
	.string "Das war unser Live-Bericht aus der\n"
	.string "Spielhalle - wo euch vor Spannung der\l"
	.string "Atem stockt!\p"
	.string "Auf Wiedersehen bis zum nächsten Mal!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} hat {STR_VAR_2}\n"
	.string "gespielt und {STR_VAR_3} Münzen verloren.\p"
	.string "“Dank {STR_VAR_1} verkaufen wir viele\n"
	.string "Münzen.”\p"
	.string "Das sagen die Angestellten der\n"
	.string "Spielhalle, wenn dieser Spieler\l"
	.string "sein Glück versucht.$"

gTVFindThatGamerText03::
	.string "Solltet ihr die Spielhalle besuchen\n"
	.string "und {STR_VAR_2} spielen, dann\p"
	.string "achtet so gut auf eure Münzen, wie\n"
	.string "{STR_VAR_1} das tut.\p"
	.string "Das war unser Live-Bericht aus der\n"
	.string "Spielhalle - wo euch vor Spannung der\l"
	.string "Atem stockt!\p"
	.string "Auf Wiedersehen bis zum nächsten Mal!$"

gTVBreakingNewsText00::
	.string "Nachrichten-TV!$"

gTVBreakingNewsText01::
	.string "Seltenes {STR_VAR_2} wurde \n"
	.string "von {STR_VAR_1} gefangen!\p"
	.string "Wir berichten live aus der Gegend\n"
	.string "von {STR_VAR_3}!\p"
	.string "{STR_VAR_1} hat es geschafft, hier ein\n"
	.string "seltenes {STR_VAR_2} zu fangen!$"

gTVBreakingNewsText02::
	.string "Als {STR_VAR_1} das seltene {STR_VAR_2}\n"
	.string "bemerkte, hat der Trainer das Pokémon\l"
	.string "{STR_VAR_3} eingesetzt.$"

gTVBreakingNewsText03::
	.string "Beim Versuch, das seltene Pokémon zu\n"
	.string "fangen, hat der Trainer {STR_VAR_1} Pokébälle\l"
	.string "geworfen.\p"
	.string "Schließlich konnte das Pokémon mit\n"
	.string "einem {STR_VAR_2} gefangen werden!$"

gTVBreakingNewsText04::
	.string "Und in {STR_VAR_2} hallten die\n"
	.string "Freudenschreie von {STR_VAR_1} wider.\p"
	.string "Ich muss gestehen, ich bin ein wenig\n"
	.string "neidisch auf {STR_VAR_1}. Auch ich\l"
	.string "hätte gerne einen Grund für\p"
	.string "Freudenschreie.\n"
	.string "Das war’s für heute!\l"
	.string "Bis zum nächsten Mal!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} hat es nicht geschafft, das\n"
	.string "seltene Pokémon {STR_VAR_2} zu fangen!\p"
	.string "Wir berichten live aus der Region\n"
	.string "um {STR_VAR_3}!\p"
	.string "Hier war es, wo {STR_VAR_1} bei dem\n"
	.string "Versuch gescheitert ist, das seltene\l"
	.string "{STR_VAR_2} zu fangen!$"

gTVBreakingNewsText06::
	.string "Als {STR_VAR_1} auf das seltene\n"
	.string "Pokémon {STR_VAR_2} getroffen ist, hat\l"
	.string "der Trainer {STR_VAR_3} eingesetzt.$"

gTVBreakingNewsText07::
	.string "{STR_VAR_2} sollte die Attacke\n"
	.string "{STR_VAR_1} einsetzen.\p"
	.string "Ohne es zu beabsichtigen, besiegte\n"
	.string "der Trainer damit das seltene Pokémon…$"

gTVBreakingNewsText12::
	.string "Aber {STR_VAR_1} verfiel in Panik, als es\n"
	.string "das seltene {STR_VAR_2} sah.\p"
	.string "Hektisch setzte der Trainer daraufhin\n"
	.string "{STR_VAR_3} ein.\p"
	.string "Doch dadurch wurde das seltene\n"
	.string "Pokémon unabsichtlich besiegt…$"

gTVBreakingNewsText08::
	.string "Und so hallten in der Gegend um\n"
	.string "{STR_VAR_2} die frustrierten\l"
	.string "Schreie von {STR_VAR_1} wider…$"

gTVBreakingNewsText09::
	.string "Aber {STR_VAR_1} schien nicht genug\n"
	.string "Pokébälle zu haben.\p"
	.string "Und so musste der Trainer den Kampf\n"
	.string "mit dem seltenen {STR_VAR_2} abbrechen.\p"
	.string "Und so hallten in der Gegend um\n"
	.string "{STR_VAR_3} die frustrierten\l"
	.string "Schreie von {STR_VAR_1} wider…$"

gTVBreakingNewsText10::
	.string "Aber {STR_VAR_2} floh ohne Vorwarnung\n"
	.string "aus dem Kampf.\p"
	.string "Und so hallten in der Gegend um\n"
	.string "{STR_VAR_3} die frustrierten\l"
	.string "Schreie von {STR_VAR_1} wider…$"

gTVBreakingNewsText11::
	.string "Ich fühle mit {STR_VAR_1}.\n"
	.string "Ich möchte am liebsten auch schreien.\p"
	.string "Das war unser Live-Bericht über eine\n"
	.string "tragische Begebenheit.$"

gTVSecretBaseVisitText00::
	.string "Hallo Leute!!!\n"
	.string "Es ist wieder Zeit für die\l"
	.string "Reportage aus der Geheimbasis.\p"
	.string "Heute besuchen wir die Geheimbasis\n"
	.string "von {STR_VAR_1}.\p"
	.string "Wie hat {STR_VAR_1} sie eingerichtet?\p"
	.string "Lasst uns das herausfinden!\n"
	.string "… … … … …\l"
	.string "…$"

gTVSecretBaseVisitText01::
	.string "Oh…\n"
	.string "Ganz großartig!\p"
	.string "{STR_VAR_2}…\n"
	.string "Dieses Item hätte man hier sicher\l"
	.string "nicht erwartet!$"

gTVSecretBaseVisitText02::
	.string "Oh…\n"
	.string "Einfach bemerkenswert!\p"
	.string "Hier gibt es kein einziges\n"
	.string "Möbelstück!\p"
	.string "Normale Sterbliche werden diese\n"
	.string "Kühnheit der Einrichtung nicht\l"
	.string "nachahmen können!\p"
	.string "Ein einfacher Stil, der aber durch seine\n"
	.string "Wildheit besticht.\p"
	.string "Ich ziehe den Hut vor dir, {STR_VAR_1}.\n"
	.string "So etwas kannst nur du leisten.$"

gTVSecretBaseVisitText03::
	.string "Oh, verstehe!\n"
	.string "Ich habe es klar vor Augen.\p"
	.string "Dieses Item hier - {STR_VAR_2}…\n"
	.string "Es sagt alles!$"

gTVSecretBaseVisitText04::
	.string "Oh, verstehe!\n"
	.string "Ich habe es klar vor Augen.\p"
	.string "Dieser Raum ist ganz bewusst frei\n"
	.string "von allen Gegenständen gehalten!\p"
	.string "Die Interpretation dieses Raumes ist\n"
	.string "eindeutig.$"

gTVSecretBaseVisitText05::
	.string "Wuhuuu!\p"
	.string "{STR_VAR_2} gepaart mit\n"
	.string "{STR_VAR_3}!\p"
	.string "Eine absolute Traumkombination!$"

gTVSecretBaseVisitText06::
	.string "Wuhuuu!\p"
	.string "{STR_VAR_2} - und das an dieser\n"
	.string "Stelle!\p"
	.string "Es prägt das Bild der Geheimbasis.$"

gTVSecretBaseVisitText07::
	.string "Wuhuuu!\p"
	.string "Hier gibt es rein gar nichts!\p"
	.string "Und dieses Nichts prägt diese\n"
	.string "Geheimbasis!$"

gTVSecretBaseVisitText08::
	.string "Oh!\n"
	.string "Da kommt {STR_VAR_1}!\l"
	.string "Stellen wir den Trainer auf die Probe!\p"
	.string "… … … … …\n"
	.string "…\l"
	.string "… … … … …\l"
	.string "…$"

gTVSecretBaseVisitText09::
	.string "Seufz…\n"
	.string "Dies werde ich {STR_VAR_1} geben.\p"
	.string "Die Pokémon dieses Trainers verdienen\n"
	.string "wirklich den Titel Champ.\p"
	.string "Sie beweisen die Stärke von\n"
	.string "{STR_VAR_1}.\p"
	.string "Und dass {STR_VAR_2} die Attacke\n"
	.string "{STR_VAR_3} kennt…\p"
	.string "Das macht deutlich, welche Art von\n"
	.string "Trainer wir bei {STR_VAR_1} vor uns\l"
	.string "haben.\p"
	.string "Nun, das war wirklich interessant!$"

gTVSecretBaseVisitText10::
	.string "Ahaaa…\n"
	.string "Dies werde ich {STR_VAR_1} geben.\p"
	.string "Die Pokémon dieses Trainers sind\n"
	.string "wirklich unglaublich stark!\p"
	.string "Sie beweisen die Hartnäckigkeit\n"
	.string "von {STR_VAR_1}.\p"
	.string "Und dass {STR_VAR_2} die Attacke\n"
	.string "{STR_VAR_3} kennt…\p"
	.string "Das macht deutlich, welche Art von\n"
	.string "Trainer wir bei {STR_VAR_1} vor uns\l"
	.string "haben.\p"
	.string "Nun, das war wirklich interessant!$"

gTVSecretBaseVisitText11::
	.string "Ahaaa…\n"
	.string "Dies werde ich {STR_VAR_1} geben.\p"
	.string "Die Pokémon dieses Trainers sind\n"
	.string "wirklich sehr ausgewogen aufgezogen\l"
	.string "worden!\p"
	.string "Sie beweisen die Reife und Intelligenz\n"
	.string "von {STR_VAR_1}.\p"
	.string "Und dass {STR_VAR_2} die Attacke\n"
	.string "{STR_VAR_3} kennt…\p"
	.string "Das macht deutlich, welche Art von\n"
	.string "Trainer wir bei {STR_VAR_1} vor uns\l"
	.string "haben.\p"
	.string "Nun, das war wirklich interessant!$"

gTVSecretBaseVisitText12::
	.string "Ahaaa…\n"
	.string "Dies werde ich {STR_VAR_1} geben.\p"
	.string "Die Pokémon dieses Trainers\n"
	.string "haben mit Sicherheit eine große\l"
	.string "Zukunft vor sich!\p"
	.string "Sie stehen für die Träume und\n"
	.string "Hoffnungen von {STR_VAR_1}.\p"
	.string "Und dass {STR_VAR_2} die Attacke\n"
	.string "{STR_VAR_3} kennt…\p"
	.string "Das macht deutlich, welche Art von\n"
	.string "Trainer wir bei {STR_VAR_1} vor uns\l"
	.string "haben.\p"
	.string "Nun, das war wirklich interessant!$"

gTVSecretBaseVisitText13::
	.string "Ich muss sagen, das war wirklich eine\n"
	.string "prächtige Geheimbasis!\p"
	.string "Meine lieben Zuschauer, wenn ihr die\n"
	.string "Gelegenheit bekommt, die Geheimbasis\p"
	.string "von {STR_VAR_1} zu besuchen, dann\n"
	.string "macht das unbedingt!\p"
	.string "Bis zum nächsten Mal! Auf Wiedersehen!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Sie ist aufregend!\n"
	.string "Sie ist spannend!\p"
	.string "Die Pokémon-Lotterie Reportage!\p"
	.string "Hallo und herzlich willkommen! Wir\n"
	.string "berichten live über die Pokémon-\l"
	.string "Lotterie im Erdgeschoss des\l"
	.string "Einkaufszentrums von Seegrasulb City!\p"
	.string "Und wie immer treffen wir auch heute\n"
	.string "einen glücklichen Trainer!\p"
	.string "Ein Trainer namens…\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} hat den {STR_VAR_2}\n"
	.string "gewonnen und nimmt\l"
	.string "{STR_VAR_3} mit nach Hause!\p"
	.string "{STR_VAR_1}!\n"
	.string "Herzlichen Glückwunsch!\p"
	.string "Und ihr vor den Fernsehgeräten! Schaut\n"
	.string "euch nicht nur das Glück anderer an!\l"
	.string "Werdet selbst aktiv!\p"
	.string "Wir hier im Einkaufszentrum von\n"
	.string "Seegrasulb City warten auf euch!\p"
	.string "Und das war’s für heute live aus dem\n"
	.string "Einkaufszentrum von Seegrasulb City -\l"
	.string "wo man die größte Auswahl an Waren in\l"
	.string "ganz Hoenn findet!$"

gTVThePokemonBattleSeminarText00::
	.string "Das Seminar für Pokémon-Kämpfe\p"
	.string "Wir analysieren hier Kämpfe, um zu\n"
	.string "schauen, was wir von anderen lernen\l"
	.string "können.\p"
	.string "Heute nehmen wir uns den Kampf von\n"
	.string "{STR_VAR_1} vor.\p"
	.string "{STR_VAR_2} von {STR_VAR_1} hat gegen\n"
	.string "ein {STR_VAR_3} gekämpft…$"

gTVThePokemonBattleSeminarText01::
	.string "Und es hat {STR_VAR_2} mit der Attacke\n"
	.string "{STR_VAR_3} angegriffen…\p"
	.string "Hmm… {STR_VAR_1}!\n"
	.string "Das war völlig falsch.$"

gTVThePokemonBattleSeminarText02::
	.string "Aber das war noch nicht das Schlimmste!\n"
	.string "Das {STR_VAR_1} von diesem Trainer\l"
	.string "setzte außerdem diese Attacke(n) ein:$"

gTVThePokemonBattleSeminarText03::
	.string "{STR_VAR_1}, {STR_VAR_2}\n"
	.string "und {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "{STR_VAR_1} und {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Nun, welche Attacke sollte ein Trainer\n"
	.string "in dieser Situation besser einsetzen?\p"
	.string "… … … … …\n"
	.string "…\l"
	.string "Die Attacke {STR_VAR_1}!\p"
	.string "{STR_VAR_1} wäre viel besser als\n"
	.string "{STR_VAR_2} gewesen!\p"
	.string "Ich bitte euch: Lernt aus diesen\n"
	.string "Fehlern und kämpft mit Intelligenz!\p"
	.string "Bis zum nächsten Mal! Macht’s gut!$"

gTVTrainerFanClubText00::
	.string "Und jetzt alle zusammen!\n"
	.string "Trainer-Fanclub!!!\p"
	.string "MC: Und wie sieht’s bei euch aus?!?\p"
	.string "Heute haben wir die Fans des mega-\n"
	.string "hyper-beliebten Trainers\l"
	.string "{STR_VAR_1} zusammengerufen!\p"
	.string "Fans: Juhuuuuuuuuuuuuuu!\p"
	.string "Fans: {STR_VAR_1}!\p"
	.string "MC: Ich frage euch!\n"
	.string "Wie findet ihr {STR_VAR_1}?!?\p"
	.string "Fans: Wir lieben {STR_VAR_1}!!!\p"
	.string "MC: Und was liebt ihr an dem\n"
	.string "Trainer {STR_VAR_1}?!?$"

gTVTrainerFanClubText01::
	.string "Fans: Dieser Trainer wirft die\n"
	.string "Pokébälle super cool!$"

gTVTrainerFanClubText02::
	.string "Fans: Er rennt anbetungswürdig!$"

gTVTrainerFanClubText03::
	.string "Fans: Dieser Trainer zeigt Stärke,\n"
	.string "wenn es wirklich hart wird!$"

gTVTrainerFanClubText04::
	.string "Fans: Sein Wissen über Pokémon!$"

gTVTrainerFanClubText05::
	.string "Fans: Er ist nett zu allen Pokémon!$"

gTVTrainerFanClubText06::
	.string "Fans: Dieser Trainer ist ein wahrer\n"
	.string "Meister im Fahrrad Fahren.$"

gTVTrainerFanClubText07::
	.string "Fans: Er beeindruckt durch die Art, wie\n"
	.string "er Items kauft.$"

gTVTrainerFanClubText08::
	.string "Fans: Dieser Trainer gibt den Pokémon\n"
	.string "sehr schöne Kosenamen!$"

gTVTrainerFanClubText09::
	.string "Fans: Der Trainer hat seine\n"
	.string "Geheimbasis total schick eingerichtet!$"

gTVTrainerFanClubText10::
	.string "Fans: Der Trainer setzt TMs kühn ein!$"

gTVTrainerFanClubText11::
	.string "MC: Ihr habt es mitbekommen,\n"
	.string "{STR_VAR_1} ist heiß! Man könnte\l"
	.string "sich glatt verbrennen!\p"
	.string "Unter den Fans von {STR_VAR_1}\n"
	.string "gibt es einen Schlachtruf!\p"
	.string "MC: Ich sage {STR_VAR_1},\n"
	.string "ihr sagt…\p"
	.string "Fans: {STR_VAR_2}!\p"
	.string "Fans: {STR_VAR_3}!\p"
	.string "Fans: {STR_VAR_2}!\p"
	.string "Fans: {STR_VAR_3}!\p"
	.string "MC: Richtig! Sagt jemand\n"
	.string "“{STR_VAR_1}”…\p"
	.string "Ruft ihr zurück “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "Das klingt einfach einzigartig!\n"
	.string "Ich kann verstehen, warum jemand\l"
	.string "Fan von {STR_VAR_1} wird!\p"
	.string "Okay, du da, vor dem Fernsehgerät!\n"
	.string "Schließ dich uns an! Alle zusammen!\p"
	.string "MC: Ich sage {STR_VAR_1},\n"
	.string "ihr sagt…\p"
	.string "Fans: {STR_VAR_2}!\p"
	.string "Fans: {STR_VAR_3}!\p"
	.string "Fans: {STR_VAR_2}!\p"
	.string "Fans: {STR_VAR_3}!\p"
	.string "MC: Ich bedanke mich bei euch,\n"
	.string "den rasenden Fans von {STR_VAR_1}!\p"
	.string "Das war unsere Show!\n"
	.string "Bis zum nächsten Mal!\p"
	.string "MC: Ich sage {STR_VAR_1},\n"
	.string "ihr sagt…\p"
	.string "Fans: {STR_VAR_2}!\p"
	.string "Fans: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "Hier sind die Süßen!\n"
	.string "Pokémon und ihre Bänder!\p"
	.string "Hallo, meine Süßen!\p"
	.string "Ich weiß, ihr werdet mir mit Sicherheit\n"
	.string "zustimmen: Pokémon, die Bänder\l"
	.string "tragen, sind wirklich absolut süß!\p"
	.string "Heute möchte ich euch ein süßes\n"
	.string "Pokémon zeigen, das ich entdeckt habe,\l"
	.string "als ich durch die Stadt schlenderte.\p"
	.string "Unser heutiges süßes Pokémon gehört\n"
	.string "zu {STR_VAR_1} und ist ein {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "Die Anzahl der Bänder,\n"
	.string "die {STR_VAR_2} trägt, ist {STR_VAR_3}!\p"
	.string "Und das lässt erkennen, wie sehr\n"
	.string "{STR_VAR_1} das Pokémon mag.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} trägt unglaubliche {STR_VAR_3}\n"
	.string "Bänder!\p"
	.string "Und das spricht Bände! Man erkennt\n"
	.string "die herzliche Bindung zwischen\l"
	.string "{STR_VAR_1} und dem Pokémon.$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} trägt fantastische \n"
	.string "{STR_VAR_3} Bänder!\p"
	.string "{STR_VAR_1} ist ein wahrer Sammler und\n"
	.string "Pokémon-Freund!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Schauen wir uns die Bänder von\n"
	.string "{STR_VAR_2} einmal näher an.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "Das Band des Champs ist besonders\n"
	.string "attraktiv.\p"
	.string "Als {STR_VAR_2} Einzug in die Ruhmes-\n"
	.string "halle hielt, wurde es ihm überreicht.\p"
	.string "Der Mut von {STR_VAR_2} wird damit\n"
	.string "unterstrichen.\p"
	.string "{STR_VAR_2} und das Band des Champs!\n"
	.string "Eine absolut passende Kombination!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "Das Band der Coolness ist besonders\n"
	.string "attraktiv.\p"
	.string "{STR_VAR_2} hat es bekommen, als es den\n"
	.string "Coolness-Wettbewerb gewonnen\l"
	.string "hat.\p"
	.string "Die Coolness von {STR_VAR_2} wird so\n"
	.string "noch mehr hervorgehoben.\p"
	.string "{STR_VAR_2} und das Band der Coolness!\n"
	.string "Eine perfekte Kombination!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "Das Band der Schönheit ist besonders\n"
	.string "attraktiv.\p"
	.string "{STR_VAR_2} hat es bekommen, als es den\n"
	.string "Schönheitswettbewerb gewonnen\l"
	.string "hat.\p"
	.string "Die Schönheit von {STR_VAR_2} wird so\n"
	.string "noch mehr hervorgehoben.\p"
	.string "{STR_VAR_2} und das Band der Schön-\n"
	.string "heit! Eine perfekte Kombination!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "Das Band der Anmut ist besonders\n"
	.string "attraktiv.\p"
	.string "{STR_VAR_2} hat es bekommen, als es den\n"
	.string "Anmutswettbewerb gewonnen\l"
	.string "hat.\p"
	.string "Die Anmut von {STR_VAR_2} wird so\n"
	.string "noch mehr hervorgehoben.\p"
	.string "{STR_VAR_2} und das Band der Anmut!\n"
	.string "Eine perfekte Kombination!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "Das Band der Klugheit ist besonders\n"
	.string "attraktiv.\p"
	.string "{STR_VAR_2} hat es bekommen, als es den\n"
	.string "Klugheits-Wettbewerb gewonnen\l"
	.string "hat.\p"
	.string "Die Klugheit von {STR_VAR_2} wird so\n"
	.string "noch mehr hervorgehoben.\p"
	.string "{STR_VAR_2} und das Band der Klugheit!\n"
	.string "Eine perfekte Kombination!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "Das Band der Stärke ist besonders\n"
	.string "attraktiv.\p"
	.string "{STR_VAR_2} hat es bekommen, als es den\n"
	.string "Stärkewettbewerb gewonnen\l"
	.string "hat.\p"
	.string "Die Stärke von {STR_VAR_2} wird so\n"
	.string "noch mehr hervorgehoben.\p"
	.string "{STR_VAR_2} und das Band der Stärke!\n"
	.string "Eine perfekte Kombination!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "Das Band des Gewinners ist besonders\n"
	.string "attraktiv.\p"
	.string "{STR_VAR_2} hat es bekommen, als\n"
	.string "Anerkennung seiner Leistung im\l"
	.string "Duellturm.\p"
	.string "Das Talent von {STR_VAR_2} wird so\n"
	.string "noch mehr hervorgehoben.\p"
	.string "{STR_VAR_2} und das Band des\n"
	.string "Gewinners! Eine perfekte Kombination!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "Das Band des Sieges ist besonders\n"
	.string "attraktiv.\p"
	.string "{STR_VAR_2} hat es bekommen, als\n"
	.string "Anerkennung seiner Leistung im\l"
	.string "Duellturm.\p"
	.string "Das unglaubliche Talent von\n"
	.string "{STR_VAR_2} wird so noch mehr\l"
	.string "hervorgehoben.\p"
	.string "{STR_VAR_2} und das Band des\n"
	.string "Sieges! Eine perfekte Kombination!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "Das Band des Künstlers ist besonders\n"
	.string "attraktiv.\p"
	.string "{STR_VAR_2} hat es bekommen, als\n"
	.string "Anerkennung seiner Leistung als\l"
	.string "Model für einen Künstler.\p"
	.string "Der Charme von {STR_VAR_2} wird so\n"
	.string "noch mehr hervorgehoben.\p"
	.string "{STR_VAR_2} und das Band des\n"
	.string "Künstlers! Eine perfekte Kombination!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Das Fleiß-Band ist besonders\n"
	.string "attraktiv.\p"
	.string "{STR_VAR_2} hat es bekommen, als\n"
	.string "Anerkennung seiner harten Arbeit.\p"
	.string "Der Fleiß von {STR_VAR_2} wird so\n"
	.string "noch mehr hervorgehoben.\p"
	.string "{STR_VAR_2} und das Fleiß-Band!\n"
	.string "Eine perfekte Kombination!$"

TVSpotTheCuties_Text_Outro::
	.string "Seufz…\p"
	.string "Bänder und Pokémon…\n"
	.string "Was für eine wundervolle Kombination!\p"
	.string "Bevor ich vor Begeisterung in Ohnmacht\n"
	.string "falle, sage ich euch Lebewohl.$"

gTVPokemonNewsBattleFrontierText00::
	.string "Hallo! Es ist wieder Zeit für die\n"
	.string "Pokémon Nachrichten!\p"
	.string "Wir haben unglaubliche Nachrichten von\n"
	.string "der Kampfzone.$"

gTVPokemonNewsBattleFrontierText01::
	.string "Der Trainer {STR_VAR_1} hat den sagen-\n"
	.string "haften Rekord von {STR_VAR_2} Siegen in Folge\l"
	.string "in den Einzelkämpfen des Duellturms\l"
	.string "aufgestellt.\p"
	.string "Ein Hoch auf dich, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "Der Trainer {STR_VAR_1} hat den sagen-\n"
	.string "haften Rekord von {STR_VAR_2} Siegen in Folge\l"
	.string "in den Doppelkämpfen des Duellturms\l"
	.string "aufgestellt.\p"
	.string "Ein Hoch auf dich, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "Der Trainer {STR_VAR_1} hat den sagen-\n"
	.string "haften Rekord von {STR_VAR_2} Siegen in Folge\l"
	.string "in den Multikämpfen des Duellturms\l"
	.string "aufgestellt.\p"
	.string "Ein Hoch auf dich, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "Der Trainer {STR_VAR_1} hat den sagen-\n"
	.string "haften Rekord von {STR_VAR_2} Siegen in Folge\l"
	.string "in den Link-Multikämpfen des\l"
	.string "Duellturms aufgestellt.\p"
	.string "Ein Hoch auf dich, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "Der Trainer {STR_VAR_1} hat den\n"
	.string "meisterhaften Rekord von {STR_VAR_2} Siegen\l"
	.string "in Folge in den Einzelkampf-\l"
	.string "turnieren des Kampfstadions\p"
	.string "aufgestellt. Ein Hoch auf dich,\n"
	.string "{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "Der Trainer {STR_VAR_1} hat den\n"
	.string "meisterhaften Rekord von {STR_VAR_2} Siegen\l"
	.string "in Folge im Doppelkampf-Turnier\l"
	.string "des Kampfstadions aufgestellt.\p"
	.string "Ein Hoch auf dich, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "Der Trainer {STR_VAR_1} hat den sagen-\n"
	.string "haften Rekord von {STR_VAR_2} Siegen in Folge\l"
	.string "in der Einzel-Wechselkampf-Herausfor-\l"
	.string "derung der Kampffabrik aufgestellt.\p"
	.string "Ein Hoch auf dich, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "Der Trainer {STR_VAR_1} hat den sagen-\n"
	.string "haften Rekord von {STR_VAR_2} Siegen in Folge\l"
	.string "in der Doppel-Wechselkampf-Herausfor-\l"
	.string "derung der Kampffabrik aufgestellt.\p"
	.string "Ein Hoch auf dich, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "Der Trainer {STR_VAR_1} hat einen\n"
	.string "neuen Rekord aufgestellt: {STR_VAR_2} Räume\l"
	.string "der Kampfbahn-Herausforderung der\l"
	.string "Kampfipitis wurden erobert.\p"
	.string "Ein Hoch auf dich, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "Der Trainer {STR_VAR_1} hat den sagen-\n"
	.string "haften Rekord von {STR_VAR_2} Siegen in Folge\l"
	.string "in dem K.O.-Teamturnier des\l"
	.string "Kampfrings aufgestellt.\p"
	.string "Ein Hoch auf dich, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "Der Trainer {STR_VAR_1} hat den sagen-\n"
	.string "haften Rekord von {STR_VAR_2} Siegen in Folge\l"
	.string "in den Einzelkampf-Hallen des\l"
	.string "Kampfpalastes aufgestellt.\p"
	.string "Ein Hoch auf dich, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "Der Trainer {STR_VAR_1} hat den sagen-\n"
	.string "haften Rekord von {STR_VAR_2} Siegen in Folge\l"
	.string "in der Doppelkampf-Halle des\l"
	.string "Kampfpalastes aufgestellt.\p"
	.string "Ein Hoch auf dich, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "Der Trainer {STR_VAR_1} hat einen\n"
	.string "neuen Rekord aufgestellt: {STR_VAR_2} Ebenen\l"
	.string "der Kampfforschung-Herausforderung\l"
	.string "in der Kampfpyramide wurden erobert.\p"
	.string "Ein Hoch auf dich, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "Und auf die Pokémon {STR_VAR_1},\n"
	.string "{STR_VAR_2} und {STR_VAR_3}!\p"
	.string "Vielen Dank für eure alle Rekorde\n"
	.string "brechende Vorstellung!$"

gTVPokemonNewsBattleFrontierText15::
	.string "Und auf die Pokémon {STR_VAR_1}\n"
	.string "und {STR_VAR_2}!\p"
	.string "Vielen Dank für eure alle Rekorde\n"
	.string "brechende Vorstellung!$"

gTVPokemonNewsBattleFrontierText16::
	.string "Und auf die vier Pokémon: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "Und {STR_VAR_1}!\p"
	.string "Vielen Dank für eure alle Rekorde\n"
	.string "brechende Vorstellung!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Hoffen wir auf mehr Rekorde von\n"
	.string "{STR_VAR_1} und seinen treuen Pokémon!\p"
	.string "Und das waren die Pokémon Nachrichten!$"

gTVWhatsNo1InHoennTodayText00::
	.string "Wer ist die Nummer Eins In Hoenn?\n"
	.string "Ja, es ist mal wieder so weit!\p"
	.string "Hallo dort draußen vor den Bild-\n"
	.string "schirmen! Strengt ihr euch wirklich an?\p"
	.string "Schauen wir uns einen Trainer an,\n"
	.string "der heute sein Bestes gegeben hat!\p"
	.string "Unsere heutige Nummer eins unter den\n"
	.string "Trainern ist {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "An einem Tag hat {STR_VAR_1} {STR_VAR_2}-mal am\n"
	.string "einarmigen Banditen in der Spielhalle\l"
	.string "gespielt.\p"
	.string "Und währenddessen murmelte\n"
	.string "{STR_VAR_1}: “Irgendwie bewegt sich\l"
	.string "hier gar nichts.”\l"
	.string "Das ist doch wohl wirklich interessant!$"

gTVWhatsNo1InHoennTodayText02::
	.string "An einem Tag hat {STR_VAR_1} {STR_VAR_2}-mal\n"
	.string "Roulette in der Spielhalle\l"
	.string "gespielt.\p"
	.string "Und währenddessen rief\n"
	.string "{STR_VAR_1}: “Überlassen wir es der\l"
	.string "Kugel.”\p"
	.string "Die Augen des Trainers schauten sehr\n"
	.string "konzentriert auf das Spiel.$"

gTVWhatsNo1InHoennTodayText03::
	.string "An einem Tag hat {STR_VAR_1} {STR_VAR_2}-mal\n"
	.string "gegen wilde Pokémon gekämpft.\p"
	.string "Offenbar sind die Pokémon von\n"
	.string "{STR_VAR_1} unvergleichlich stark\l"
	.string "geworden.\p"
	.string "Sie scheinen immer und überall kämpfen\n"
	.string "zu wollen!$"

gTVWhatsNo1InHoennTodayText04::
	.string "An einem Tag hat {STR_VAR_1} {STR_VAR_2}-mal\n"
	.string "den Beerenmixer betätigt.\p"
	.string "Am Ende schien es {STR_VAR_1} ein\n"
	.string "bisschen schwindelig zu sein.\p"
	.string "Der Trainer stolperte herum wie\n"
	.string "ein Pandir.$"

gTVWhatsNo1InHoennTodayText05::
	.string "An nur einem Tag hat {STR_VAR_1} {STR_VAR_2}\n"
	.string "Beeren gepflanzt.\p"
	.string "Und dabei hat sich {STR_VAR_1} die\n"
	.string "Kleidung schmutzig gemacht.\p"
	.string "Dort, wo der Trainer etwas gepflanzt\n"
	.string "hat, blühen nun zahllose Blumen.\p"
	.string "Man sagt, diese würden auf die Menschen\n"
	.string "beruhigend wirken.$"

gTVWhatsNo1InHoennTodayText06::
	.string "An nur einem Tag hat {STR_VAR_1} {STR_VAR_2}\n"
	.string "Beeren gepflückt.\p"
	.string "Der Beutel von {STR_VAR_1} wurde\n"
	.string "dadurch so schwer, dass der Trainer\l"
	.string "Schwierigkeiten hatte, ihn zu tragen.$"

gTVWhatsNo1InHoennTodayText07::
	.string "An nur einem Tag hat {STR_VAR_1} {STR_VAR_2}\n"
	.string "Gewinnpunkte erhalten.\p"
	.string "Später wurde beobachtet, dass\n"
	.string "{STR_VAR_1} Schwierigkeiten hatte,\l"
	.string "sich für einen der Preise zu\l"
	.string "entscheiden, die man für Gewinnpunkte\p"
	.string "eintauschen kann. Ein wirres Grinsen\n"
	.string "lag um den Mund des Trainers, als er\l"
	.string "sich entscheiden musste.$"

gTVWhatsNo1InHoennTodayText08::
	.string "Also, wenn das nicht ausreicht…\p"
	.string "{STR_VAR_1}!\n"
	.string "Du bist heute unser Trainer Nr. 1!\p"
	.string "Nehmt euch ein Beispiel daran! Auch ihr\n"
	.string "könnt zur Nummer eins werden!$"

TVSecretBaseSecrets_Text_Intro::
	.string "Geheimnisse Der Geheimbasis!\p"
	.string "Was machen Trainer in ihrer\n"
	.string "Geheimbasis?\p"
	.string "Heute untersuchen wir die Geheimbasis\n"
	.string "von {STR_VAR_1}.\p"
	.string "Hey! {STR_VAR_2} scheint zu Besuch zu\n"
	.string "sein.\p"
	.string "Dann schauen wir doch noch ein\n"
	.string "bisschen durch das Schlüsselloch.\p"
	.string "Was wird {STR_VAR_2} tun?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Was wird {STR_VAR_2} als Nächstes tun?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "Und was wird {STR_VAR_2} nun machen?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "{STR_VAR_2} hat {STR_VAR_3} Schritte in der\n"
	.string "Geheimbasis von {STR_VAR_1} gemacht,\l"
	.string "bevor es Abschied nehmen hieß.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hmm…\p"
	.string "Scheinbar ist die Geheimbasis von\n"
	.string "{STR_VAR_1} nicht interessant genug\l"
	.string "für {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} scheint sich in der Geheim-\n"
	.string "basis von {STR_VAR_1} wirklich wohl\l"
	.string "gefühlt zu haben.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} scheint ein großer Fan der\n"
	.string "Geheimbasis von {STR_VAR_1} geworden\l"
	.string "zu sein.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Vielleicht möchten sich unsere\n"
	.string "Zuschauer die Geheimbasis von\l"
	.string "{STR_VAR_1} ansehen.\p"
	.string "Schaltet wieder ein, wenn wir uns die\n"
	.string "nächste Geheimbasis anschauen!\l"
	.string "Bis zum nächsten Mal! Auf Wiedersehen.$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "Der Besucher ist stehen geblieben!\p"
	.string "Er bewegt sich nicht einen Millimeter!\p"
	.string "Ist die Geheimbasis von {STR_VAR_1} so\n"
	.string "uninteressant?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "Der Besucher ist stehen geblieben!\p"
	.string "Er bewegt sich nicht einen Millimeter!\p"
	.string "Ist es Müdigkeit?\n"
	.string "Ist der Besucher eingeschlafen?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "Der Besucher setzt sich auf einen\n"
	.string "Stuhl!\p"
	.string "Schaut nur, sein glückliches Gesicht!\p"
	.string "Der Stuhl muss sehr bequem sein, wenn\n"
	.string "er so ein Gefühl hervorruft.$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "Der Besucher hat einen Ballon ins\n"
	.string "Visier genommen!\p"
	.string "Er ist zerplatzt!\n"
	.string "Du meine Güte! Zerplatzt!!!\p"
	.string "Der Besucher scheint darüber sehr\n"
	.string "erschrocken zu sein.$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "Der Besucher hat ein Zelt betreten!\p"
	.string "Der Besucher rennt herum!\p"
	.string "Hui, der Besucher tollt richtig herum!\p"
	.string "Der Besucher scheint überrascht von\n"
	.string "der Größe des Zelts zu sein!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "Der Besucher betrachtet eingehend die\n"
	.string "Pflanze!\p"
	.string "Der Besucher hat einen ausgesprochen\n"
	.string "gereiften Geschmack!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "Der Besucher untersucht das\n"
	.string "Goldschild!\p"
	.string "In den Augen des Besuchers spiegelt\n"
	.string "sich Verwunderung!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "Der Besucher untersucht das\n"
	.string "Silberschild!\p"
	.string "Die Augen des Besuchers werden immer\n"
	.string "größer!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "Der Besucher untersucht das\n"
	.string "Glasornament!\p"
	.string "Oh, nein! Nicht!\p"
	.string "Der Besucher fasst es an!\p"
	.string "Nun ist es übersät mit seinen\n"
	.string "Fingerabdrücken.$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "Der Besucher schaut fern!\p"
	.string "Wir haben hier wohl einen großen\n"
	.string "Fan von Fernsehsendungen vor uns.$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "Der Besucher ist über einen Lehmball\n"
	.string "gestolpert!\p"
	.string "Er sieht erfreut aus.$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "Oh…\p"
	.string "Der Besucher sucht etwas in seinem\n"
	.string "Beutel.\p"
	.string "Er holt etwas heraus. Was ist es?\n"
	.string "Ah! {STR_VAR_2}!\p"
	.string "Schaut euch es euch an. Der Besucher\n"
	.string "lächelt glücklich, während er\l"
	.string "{STR_VAR_2} hochhält!\p"
	.string "Das ist ja fast wie in einem Werbespot!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "Der Besucher nimmt sich ein Kissen und…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "Schlägt darauf ein?!?\p"
	.string "Er scheint unter sehr viel Stress\n"
	.string "zu stehen…$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "Umarmt es innig!\p"
	.string "Der Besucher scheint über irgendetwas\n"
	.string "sehr glücklich zu sein…$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "Der Besucher unterhält sich\n"
	.string "mit {STR_VAR_1}.\p"
	.string "Es sieht so aus, als wollten sie\n"
	.string "gegeneinander antreten!\p"
	.string "Und…\n"
	.string "Und?\p"
	.string "Der Besucher!\n"
	.string "Der Besucher hat den Kampf gewonnen!\p"
	.string "Er führt einen Siegestanz auf!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "Der Besucher unterhält sich\n"
	.string "mit {STR_VAR_1}.\p"
	.string "Es sieht so aus, als wollten sie\n"
	.string "gegeneinander antreten!\p"
	.string "Und…\n"
	.string "Und?\p"
	.string "{STR_VAR_1}!\n"
	.string "{STR_VAR_1} hat den Kampf gewonnen!\p"
	.string "Der Besucher sieht deprimiert aus.$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "Der Besucher unterhält sich\n"
	.string "mit {STR_VAR_1}.\p"
	.string "Es sieht so aus, als wollten sie\n"
	.string "gegeneinander antreten!\p"
	.string "Und…\n"
	.string "Und?\p"
	.string "Nein! Der Besucher hat den Kampf\n"
	.string "abgelehnt. Sie werden nicht kämpfen.\p"
	.string "Ob der Besucher {STR_VAR_1}\n"
	.string "unsympathisch findet?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "Der Besucher schaut sich aufmerksam\n"
	.string "ein Poster an!\p"
	.string "Gefällt ihm das Poster?\n"
	.string "… …\p"
	.string "Irgendetwas an dem Blick des Besuchers\n"
	.string "ist merkwürdig…$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "Der Besucher tritt auf eine Noten-\n"
	.string "matte!\p"
	.string "Hmm…\n"
	.string "Er spielt eine lustige Melodie.$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "Der Besucher unterhält sich\n"
	.string "mit {STR_VAR_1}.\p"
	.string "Es sieht so aus, als wollten sie\n"
	.string "gegeneinander antreten!\p"
	.string "Und…\n"
	.string "Und?\p"
	.string "Oh, ein Unentschieden!\p"
	.string "Beide Trainer scheinen sehr\n"
	.string "enttäuscht zu sein.$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "Der Besucher probiert die Dreh-Matte\n"
	.string "aus!\p"
	.string "Ihm wird offensichtlich schwindelig!\p"
	.string "Er stolpert herum!\n"
	.string "Hey, pass auf!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "Der Besucher zeigt Interesse an dem\n"
	.string "Sandornament!\p"
	.string "Oh, nein!\p"
	.string "Es ist zusammengefallen!\p"
	.string "Dem Besucher ist das mehr als peinlich!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "Der Besucher fährt mit den Fingern\n"
	.string "über den Schreibtisch.\p"
	.string "Er scheint den Staub darauf zu\n"
	.string "missbilligen.\p"
	.string "Ein Besucher, der Sauberkeit\n"
	.string "offensichtlich zu schätzen weiß.$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "Der Besucher starrt fasziniert auf\n"
	.string "einen Backstein.\p"
	.string "Ihn interessiert wohl das Objekt,\n"
	.string "welches darauf steht.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Der Besucher läuft über das Solide\n"
	.string "Brett.\p"
	.string "Er schaut nach unten und setzt\n"
	.string "vorsichtig Fuß vor Fuß.\p"
	.string "Ein vorsichtiger Charakter!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "Der Besucher betrachtet den Zaun.\p"
	.string "Hat er eine neue Idee für eine Falle\n"
	.string "entwickelt?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "Der Besucher tritt auf die Glitzer-\n"
	.string "matte.\p"
	.string "Er stellt sich in verschiedene Posen.\p"
	.string "Er stellt sich offensichtlich vor, er\n"
	.string "wäre ein Fotomodell, das posieren muss.$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "Ein Reifen hat das Interesse des\n"
	.string "Besuchers geweckt.\p"
	.string "Ob er an einen Wagen denkt, zu dem\n"
	.string "dieser Reifen passen würde?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "Der Besucher stellt sich auf das\n"
	.string "Podest.\p"
	.string "Nun kann er sich die Geheimbasis von\n"
	.string "{STR_VAR_1} von oben anschauen.\p"
	.string "Und…\p"
	.string "Er brüllt wie ein Löwe!\n"
	.string "Er brüllt tatsächlich! Unglaublich!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "Kopfüber stürzt sich der Besucher\n"
	.string "durch die Brechbare Tür.\p"
	.string "Und dabei lacht er wie ein Verrückter!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "Der Besucher unterhält sich mit einer\n"
	.string "Puppe.\p"
	.string "Äh…\n"
	.string "Das ist schon ein wenig unheimlich…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "Der Besucher klettert die Leiter der\n"
	.string "Rutsche hinauf.\p"
	.string "Und…\p"
	.string "Rutscht hinunter!\p"
	.string "Er ist unbeschwert und hat ein\n"
	.string "kindliches Vergnügen daran.$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "Der Besucher klettert die Leiter der\n"
	.string "Rutsche hinauf.\p"
	.string "Und…\p"
	.string "Klettert die Leiter wieder hinunter!\p"
	.string "Er wird doch nicht etwa Angst vor\n"
	.string "der Rutsche haben?!?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "Der Besucher tritt auf die Sprung-\n"
	.string "matte.\p"
	.string "Und springt ein Mal!\p"
	.string "Und zwei Mal!\p"
	.string "Was für eine perfekte Landung!\p"
	.string "Er applaudiert sich selbst!\n"
	.string "Was für eine grandiose Vorstellung!$"

gTVSafariFanClubText00::
	.string "Safari-Fanclub!\p"
	.string "Reporter: Also gut, Freunde!\n"
	.string "Ihr werft Pokébälle, nicht wahr?\p"
	.string "Ich stehe hier in der Safari-Zone, die\n"
	.string "vor fantastischer Pokémon nur so\l"
	.string "strotzt.\p"
	.string "Wir sollten uns mal mit einem\n"
	.string "Tutor der Safari-Zone\l"
	.string "unterhalten!\p"
	.string "Hallo, mein Freund. Wie machen sich die\n"
	.string "Trainer, die ihr Glück hier versuchen?$"

gTVSafariFanClubText01::
	.string "Tutor: Nun, jeder scheint sich\n"
	.string "hier wirklich anzustrengen.\p"
	.string "Besonders {STR_VAR_1} beweist großes\n"
	.string "Geschick.\p"
	.string "{STR_VAR_1} hat bereits {STR_VAR_2} Pokémon\n"
	.string "gefangen!$"

gTVSafariFanClubText02::
	.string "Der Trainer setzt seine {POKEBLOCK} sehr\n"
	.string "intelligent ein. Ich glaube, er hat\p"
	.string "bisher {STR_VAR_2} davon verwendet.$"

gTVSafariFanClubText03::
	.string "Der Trainer hat keinen {POKEBLOCK}\n"
	.string "verwendet. Nicht einen einzigen!\p"
	.string "Das ist ein wahrer Profi!$"

gTVSafariFanClubText04::
	.string "Reporter: Kann das stimmen?\p"
	.string "Das hört sich an, als sei unser Freund\n"
	.string "{STR_VAR_1} ein wahrer Safari-Meister!\p"
	.string "Tutor: Ich hoffe, der Trainer\n"
	.string "bringt uns seine Technik bei.$"

gTVSafariFanClubText05::
	.string "Tutor: Heute scheint niemand\n"
	.string "wahres Können zu beweisen.\p"
	.string "Besonders {STR_VAR_1} tut sich schwer.\p"
	.string "Bisher gelang es dem Trainer lediglich\n"
	.string "{STR_VAR_2} Pokémon zu fangen.$"

gTVSafariFanClubText06::
	.string "Tutor: Heute scheint niemand\n"
	.string "wahres Können zu beweisen.\p"
	.string "Besonders {STR_VAR_1} tut sich schwer.\p"
	.string "Bisher konnte der Trainer kein\n"
	.string "einziges Pokémon fangen.$"

gTVSafariFanClubText07::
	.string "Dabei setzt der Trainer {POKEBLOCK} ein.\n"
	.string "Diesmal waren es, glaube ich, {STR_VAR_2}.\p"
	.string "Mann, ich würde mir wirklich wünschen,\n"
	.string "er würde sich geschickter anstellen.$"

gTVSafariFanClubText08::
	.string "Ich glaube, wenn der Trainer {POKEBLOCK}\n"
	.string "verwenden würde, die er bisher noch\p"
	.string "nicht verwendet hat, hätte er gute\n"
	.string "Chancen.$"

gTVSafariFanClubText09::
	.string "Reporter: Kann das stimmen?\p"
	.string "Das klingt, als ob unser Freund\n"
	.string "{STR_VAR_1} noch ein paar Übungs-\l"
	.string "stunden in der Safari-Zone braucht.\p"
	.string "Tutor: Ich hoffe, dieser\n"
	.string "Trainer wird regelmäßig kommen, damit\l"
	.string "er irgendwann den Bogen raus hat.$"

gTVSafariFanClubText10::
	.string "Reporter: Ein wahres Wort! Man muss\n"
	.string "sich den Herausforderungen stellen!\p"
	.string "Also, meine lieben Zuschauer, besucht\n"
	.string "die Safari-Zone und stellt euch dieser\l"
	.string "Herausforderung!\p"
	.string "Bis zum nächsten Mal! Tschüss!$"

ContestLiveUpdates_Text_Intro::
	.string "“Live Von Den Pokémon Wettbewerben”\p"
	.string "MC: Hallo und herzlich willkommen!\p"
	.string "Wir berichten live von dem gerade\n"
	.string "beendeten {STR_VAR_1}-Wettbewerb.\p"
	.string "Die Halle ist immer noch gefüllt mit\n"
	.string "einem Publikum, das sich von den\l"
	.string "Pokémon nicht trennen kann.\p"
	.string "Zuschauer: {STR_VAR_2}!\p"
	.string "Zuschauer: {STR_VAR_3}!\p"
	.string "MC: Da haben wir gerade die Namen der\n"
	.string "Sieger gehört. {STR_VAR_3} hat mit dem\l"
	.string "Pokémon {STR_VAR_2} gewonnen!\p"
	.string "Zuschauer: {STR_VAR_2}! Du bist klasse!\p"
	.string "Zuschauer: {STR_VAR_3}! Weiter so!!!\p"
	.string "MC: Hören wir mal, was die Fans über\n"
	.string "diesen Wettbewerb sagen.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Zuschauer: Das {STR_VAR_2} lag im\n"
	.string "1. und 2. Durchgang ganz vorne!\p"
	.string "Das {STR_VAR_2} wird auch weiter\n"
	.string "gewinnen.$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Zuschauer: Im 1. Durchgang war\n"
	.string "{STR_VAR_2} nicht überzeugend, aber im\l"
	.string "2. Durchgang fegte es alle vom Platz.\p"
	.string "Ein wundervolles Comeback für\n"
	.string "{STR_VAR_2}. Juhuuu!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Zuschauer: Das {STR_VAR_2} blieb im 1.\n"
	.string "und 2. Durchgang gleichbleibend\l"
	.string "erfolgreich.\p"
	.string "{STR_VAR_3} und das {STR_VAR_2} - keine\n"
	.string "gewöhnliche Kombination.$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Zuschauer: {STR_VAR_1} - Unter diesem\n"
	.string "Aspekt war das {STR_VAR_2} einfach\l"
	.string "herausragend!\p"
	.string "Ich hoffe, es strengt sich nächstes Mal\n"
	.string "noch mehr an.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Zuschauer: Als das {STR_VAR_2} nervös\n"
	.string "wurde, konnte ich mich nicht zurück-\l"
	.string "halten und habe es aufgemuntert.\p"
	.string "Ich möchte dem {STR_VAR_2}\n"
	.string "“Glückwunsch!” zurufen.$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Zuschauer: Der Auftritt von {STR_VAR_2}\n"
	.string "hat sogar mich erschreckt!\p"
	.string "{STR_VAR_2}, du warst großartig!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Zuschauer: Der Auftritt von {STR_VAR_2}\n"
	.string "war überwältigend!\p"
	.string "Ich bin immer noch ganz hin und weg.$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Zuschauer: Der Auftritt des Siegers\n"
	.string "{STR_VAR_2} brachte mein Herz zum\l"
	.string "Rasen!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}!\n"
	.string "Du bist cool!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Du bist schön!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "Du bist anmutig!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "Du bist klug!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "Du bist stark!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Zuschauer: Der Auftritt des Siegers\n"
	.string "{STR_VAR_2} lässt mein Herz immer noch\l"
	.string "rasen!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "Cool ist dein zweiter Name!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Schönheit ist dein zweiter Name!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "Anmut ist dein zweiter Name!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "Klugheit ist dein zweiter Name!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "Stärke ist dein zweiter Name!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Zuschauer: Selbst als das {STR_VAR_2}\n"
	.string "eine Pause bei seinem Auftritt\l"
	.string "einlegte, konnte ich den Blick\p"
	.string "nicht abwenden! Ich war von dem\n"
	.string "{STR_VAR_2} wie gefangen.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Zuschauer: Als sich das {STR_VAR_2} vor\n"
	.string "den anderen Pokémon erschreckte,\l"
	.string "wäre ich fast in Tränen ausgebrochen.\p"
	.string "{STR_VAR_2}, du bist unverwüstlich!\n"
	.string "Weiter so!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Zuschauer: Oh…\p"
	.string "Die Attacke {STR_VAR_3} von\n"
	.string "{STR_VAR_2}!\l"
	.string "{STR_VAR_3} von {STR_VAR_2}!\l"
	.string "{STR_VAR_3} von {STR_VAR_2}!\l"
	.string "Wie kann etwas nur so wundervoll sein?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "MC: Nun, da hört ihr es. Hier sind lauter\n"
	.string "Fans von {STR_VAR_1}!\p"
	.string "Ich möchte aber auch erwähnen, dass\n"
	.string "das {STR_VAR_3} von {STR_VAR_2} meine\l"
	.string "Aufmerksamkeit erregt hat.\p"
	.string "{STR_VAR_3} von {STR_VAR_2}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "Es konnte im 2. Durchlauf vor lauter\n"
	.string "Nervosität keinen Auftritt bieten.\p"
	.string "Nächstes Mal möchte ich wenigstens\n"
	.string "einen Auftritt von {STR_VAR_1} sehen!$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "In beiden Durchläufen konnte es\n"
	.string "absolut nicht überzeugen.\l"
	.string "Ich hoffe, dass das {STR_VAR_2} von\p"
	.string "{STR_VAR_1} demnächst besser\n"
	.string "vorbereitet ist und nicht wieder auf\l"
	.string "dem letzten Platz landet.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Es schaffte es nicht, die Begeisterung\n"
	.string "des Publikums für sich zu nutzen und\l"
	.string "einen guten Auftritt zu bieten.\p"
	.string "Hoffen wir, dass {STR_VAR_1} ein Gespür für\n"
	.string "die Stimmung des Publikums bekommt und\l"
	.string "es das nächste Mal richtig anheizt.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Während es im 1. Durchlauf alle schlug,\n"
	.string "versagte es im 2. Durchlauf komplett.\p"
	.string "Es war wirklich erniedrigend.\p"
	.string "{STR_VAR_1} wird sich anstrengen, um\n"
	.string "überzeugende Auftritte hinlegen.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Im 2. Durchlauf konnte es das Publikum\n"
	.string "nicht für sich gewinnen.\l"
	.string "Hoffen wir, dass es sich demnächst\p"
	.string "nicht mehr so viele Gedanken über die\n"
	.string "anderen Pokémon macht und das Publikum\l"
	.string "überzeugen wird.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Es unterlag dem {STR_VAR_2} von\n"
	.string "{STR_VAR_1} um Haaresbreite.\p"
	.string "Es ist erschütternd, so kurz vor dem\n"
	.string "Sieg zu scheitern.\p"
	.string "Ich wäre nicht erstaunt, wenn {STR_VAR_3}\n"
	.string "nun über diese Niederlage weint.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Es hat den Juror enttäuscht, weil es\n"
	.string "eine Attacke zweimal zeigte.\p"
	.string "In einem Wettbewerb ist das wirklich\n"
	.string "ein unverzeihlicher Fehler, für den das\l"
	.string "Pokémon bezahlt hat.\p"
	.string "{STR_VAR_1} sollte ein schlechtes Gewissen\n"
	.string "haben!$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} hat sich zwar tapfer\n"
	.string "geschlagen, aber…\p"
	.string "Es half nichts. Nur der letzte Platz war\n"
	.string "drin.\p"
	.string "{STR_VAR_1} sollte aus dieser Niederlage\n"
	.string "lernen und das Beste daraus machen.$"

ContestLiveUpdates_Text_Outro::
	.string "Jetzt aber sage ich Auf Wiedersehen,\n"
	.string "aber nicht ohne unser übliches Leb wohl\l"
	.string "an unsere Sieger.\p"
	.string "Dieses Mal sind es {STR_VAR_1} und das\n"
	.string "{STR_VAR_2}!\p"
	.string "MC: Seid ihr alle bereit?!?\n"
	.string "Alle zusammen!!!\p"
	.string "Publikum: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "Herzlichen Glückwunsch!\l"
	.string "Ihr seid die Sieger des Wettbewerbs!$"

gTVPokemonBattleUpdateText00::
	.string "“Atemberaubende Pokémon-Kämpfe”\p"
	.string "Wir zeigen euch die Ergebnisse von\n"
	.string "Kämpfen, sobald diese entschieden\l"
	.string "wurden.$"

gTVPokemonBattleUpdateText01::
	.string "Die Trainer {STR_VAR_1} und {STR_VAR_2}\n"
	.string "traten sich in einem {STR_VAR_3}-\l"
	.string "Kampf gegenüber.\p"
	.string "{STR_VAR_1} ging als Sieger daraus\n"
	.string "hervor!$"

gTVPokemonBattleUpdateText02::
	.string "Das {STR_VAR_2} von {STR_VAR_1} zeigte\n"
	.string "mit seiner Attacke {STR_VAR_3} seine\l"
	.string "beeindruckende Kraft.$"

gTVPokemonBattleUpdateText03::
	.string "Das {STR_VAR_2} von {STR_VAR_1}\n"
	.string "dagegen zeigte eine schmerzhafte\l"
	.string "Schwäche.$"

gTVPokemonBattleUpdateText04::
	.string "Herzlichen Glückwunsch, {STR_VAR_1}!\p"
	.string "Und {STR_VAR_2} wünschen wir für den\n"
	.string "nächsten Kampf mehr Erfolg!\p"
	.string "Und damit beenden wir\n"
	.string "“Atemberaubende Pokémon-Kämpfe”$"

gTVPokemonBattleUpdateText05::
	.string "Die Teams der Trainer {STR_VAR_1} und\n"
	.string "{STR_VAR_2} haben sich in einem Multi-\l"
	.string "kampf gemessen.\p"
	.string "Das Team von {STR_VAR_1} ging als\n"
	.string "Sieger daraus hervor.$"

gTVPokemonBattleUpdateText06::
	.string "Das {STR_VAR_2} von {STR_VAR_1} zeigte\n"
	.string "mit seiner Attacke {STR_VAR_3} seine\l"
	.string "beeindruckende Kraft.$"

gTVPokemonBattleUpdateText07::
	.string "{STR_VAR_3} aus dem Team von\n"
	.string "{STR_VAR_2} zeigte eine schmerzliche\l"
	.string "Schwäche.\p"
	.string "Herzlichen Glückwunsch an dein Team,\n"
	.string "{STR_VAR_1}!\p"
	.string "Und dem Team von {STR_VAR_2} wünschen\n"
	.string "wir, dass es bald gewinnen wird!\p"
	.string "Und damit beenden wir\n"
	.string "“Atemberaubende Pokémon-Kämpfe”$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "Pia: Oh! Wir haben hier viele stark\n"
	.string "aussehende Trainer gesehen!\p"
	.string "Okay, Kamera ab!\n"
	.string "Interviewen wir jemanden!$"

GabbyAndTy_Text_GabbyIntro:
	.string "Pia: Oh! Du bist {PLAYER}! Hallo!\n"
	.string "Erinnerst du dich an uns?\p"
	.string "Zeigst du uns, wie stark du geworden\n"
	.string "bist? Okay, das war das Stichwort.$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "Pia: Mein Gefühl hat nicht getrogen.\n"
	.string "Der Trainer ist wirklich erstaunlich.$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "Pia: Erstaunlich! Erstaunlich!\n"
	.string "Wer bist du?!?\p"
	.string "Ich wusste, wir erleben etwas Außerge-\n"
	.string "wöhnliches, als wir dich gesehen haben.\p"
	.string "Oh, ich schulde dir eine Erklärung. Wir\n"
	.string "reisen durch das Land und führen mit\l"
	.string "Trainern Interviews.\p"
	.string "Würdest du uns auch etwas von deiner\n"
	.string "Zeit zur Verfügung stellen?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "Pia: “{STR_VAR_1}!”\p"
	.string "Erinnerst du dich? Das hast du uns das\n"
	.string "letzte Mal nach einem Kampf gesagt.\p"
	.string "So etwas vergesse ich nie!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "Als wir das letzte Mal kämpften, hast du\n"
	.string "uns in den Boden gerammt, bevor wir\l"
	.string "etwas dagegen tun konnten…\p"
	.string "Und wie sieht es heute aus? Dürfen\n"
	.string "wir dich noch einmal interviewen?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "Hast du bei unserem letzten Kampf\n"
	.string "nicht einen Pokéball nach uns\l"
	.string "geworfen?\p"
	.string "Wir waren geschockt! Daher haben wir\n"
	.string "das jedem, wirklich jedem, erzählt!\p"
	.string "Was meinst du? Dürfen wir dich noch\n"
	.string "einmal interviewen?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "Bei unserem letzten Kampf hast du uns\n"
	.string "mit dem Einsatz der Items geschlagen.\p"
	.string "Was meinst du? Dürfen wir dich noch\n"
	.string "einmal interviewen?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "In unserem letzten Kampf haben wir uns\n"
	.string "bemüht, nicht ganz so übel auszusehen.\p"
	.string "Was meinst du? Dürfen wir dich noch\n"
	.string "einmal interviewen?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Was meinst du? Dürfen wir dich noch\n"
	.string "einmal interviewen?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Ja?\n"
	.string "Wunderbar! Danke!\p"
	.string "Okay. Wie würdest du deine Gefühle\n"
	.string "hinsichtlich unseres Kampfes\l"
	.string "beschreiben? Kurz und nett, bitte.$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "Pia: Mmm, yeah!\n"
	.string "Das ist das perfekte Schlagwort!\p"
	.string "Ich bin überzeugt, dass dies eine groß-\n"
	.string "artige TV-Sendung wäre!\p"
	.string "Vielleicht strahlen sie dies im Fern-\n"
	.string "sehen aus, also achte auf das Programm!\p"
	.string "Okay!\n"
	.string "Man sieht sich!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "Pia: Oh…\p"
	.string "Okay, aber gib nicht auf!\n"
	.string "Wir werden dich weiter im Auge behalten!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "Pia: Wir werden dich im Auge behalten!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "Pia: Gibt es irgendwo einen starken\n"
	.string "Trainer mit vielen Pokémon?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "Pia: Wow, das war was!\p"
	.string "Seit unserem letzten Kampf bist du\n"
	.string "stärker geworden - viel stärker.\p"
	.string "Unser Gefühl, du würdest ein heißer\n"
	.string "Trainer werden, hat uns Recht gegeben.\p"
	.string "Was meinst du? Dürfen wir dich noch\n"
	.string "einmal interviewen?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "Pia: Das war aber ein intensiver\n"
	.string "Kampf! Hast du alles aufgezeichnet?!?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "Udo: Hey, guck mal! Ein stark\n"
	.string "aussehender Trainer! Und das hier\l"
	.string "an diesem Ort! Kamera ab!$"

GabbyAndTy_Text_TyIntro:
	.string "Udo: Da schau her!\n"
	.string "Ich erinnere mich an dich!\p"
	.string "Ich werde den ganzen Kampf mit der\n"
	.string "Kamera aufnehmen!$"

GabbyAndTy_Text_TyPostBattle:
	.string "Udo: Du bist ein Naturtalent!\n"
	.string "Du gibst mir erstklassiges Bildmaterial!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "Udo: Du hast nur ein Pokémon?\n"
	.string "Mehr nicht?\p"
	.string "Wenn du mehr Pokémon hättest, wäre\n"
	.string "das Bildmaterial viel, viel besser!$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "Udo: Wir haben tatsächlich einen\n"
	.string "starken Trainer entdeckt.\l"
	.string "Das ist unser Durchbruch.$"

GabbyAndTy_Text_TyDefeat:
	.string "Udo: Ja, alles im Kasten!\n"
	.string "Der ganze Kampf ist auf Band!$"

gTVInSearchOfTrainersText00::
	.string "Auf der Suche nach Trainern…\p"
	.string "Pia: Hallo! Heute besuche ich ein Ge-\n"
	.string "biet in der Nähe von {STR_VAR_1}.\p"
	.string "Wir versuchen, ein neues, großes\n"
	.string "Talent zu finden.\p"
	.string "Unsere Kamera ruht daher auf dem\n"
	.string "Trainer {PLAYER}.\p"
	.string "Etwas an diesem Trainer hat unser\n"
	.string "Interesse geweckt…$"

gTVInSearchOfTrainersText01::
	.string "Wir sind schon früher gegen {PLAYER}\n"
	.string "angetreten, und wir versichern, dass\l"
	.string "der Trainer viel stärker geworden ist!\p"
	.string "Ich wusste sofort, dass wir hier einen\n"
	.string "ganz besonderen Trainer vor uns haben.$"

gTVInSearchOfTrainersText02::
	.string "Die beste Art, das Können eines\n"
	.string "Trainers festzustellen, ist…\p"
	.string "gegen ihn zu kämpfen.\n"
	.string "Und das haben wir gemacht.\p"
	.string "… …\p"
	.string "Und so endete schließlich der Kampf\n"
	.string "gegen {PLAYER}.\p"
	.string "Seine dominierende Vorstellung schlug\n"
	.string "uns vernichtend, zerknüllte uns und\l"
	.string "warf uns weg.\p"
	.string "{PLAYER} ist einfach unglaublich stark…\p"
	.string "Gehen wir etwas näher auf den Kampf\n"
	.string "ein.$"

gTVInSearchOfTrainersText03::
	.string "Die Kombination von {STR_VAR_1} und\n"
	.string "{STR_VAR_3} war einfach göttlich!\p"
	.string "Schon die Ausstrahlung der beiden ließ\n"
	.string "erkennen, dass sie sich gegenseitig un-\l"
	.string "eingeschränkt unterstützen würden.\p"
	.string "Einfach eine unglaubliche Atmosphäre!\p"
	.string "Der Trainer setzte als letzte Attacke\n"
	.string "{STR_VAR_2} ein.\p"
	.string "Die Attacke {STR_VAR_2} ist das\n"
	.string "Zeichen der Freundschaft zwischen\l"
	.string "{STR_VAR_1} und {STR_VAR_3}.$"

gTVInSearchOfTrainersText04::
	.string "So geht mein ganzes Selbstbewusstsein\n"
	.string "dahin… Die Folge unserer Entdeckung.\p"
	.string "Wir wurden geschlagen, bevor wir\n"
	.string "überhaupt eine einzige Attacke ein-\l"
	.string "setzen konnten. Oooh… Schnüff…\p"
	.string "Allein das macht die Kämpfe von\n"
	.string "{PLAYER} schon sehenswert.\p"
	.string "Ich fordere mutige Trainer auf, sich\n"
	.string "mit {PLAYER} zu messen!$"

gTVInSearchOfTrainersText05::
	.string "Dazu gibt es nur eines zu sagen.\n"
	.string "Wage es nicht, während eines Kampfes\l"
	.string "einen Pokéball zu werfen!\p"
	.string "{PLAYER} mag ein starker Kämpfer sein,\n"
	.string "aber die Regeln kennt er nicht.\p"
	.string "Ich gebe unseren Zuschauern\n"
	.string "einen Tipp.\p"
	.string "Wenn ihr {PLAYER} seht, dann weist den\n"
	.string "Trainer zurecht!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} hat ein Talent dafür, das Vor-\n"
	.string "gehen seines Gegners vorherzusehen.\p"
	.string "Das Item wurde erstaunlicherweise \n"
	.string "genau zum richtigen Zeitpunkt benutzt!$"

gTVInSearchOfTrainersText07::
	.string "Ehrlich gesagt, bin ich davon ausge-\n"
	.string "gangen, dass ich sehr gut bin.\p"
	.string "Auch wenn wir verloren haben,\n"
	.string "war es ein heißer Kampf!\p"
	.string "Wenn du es mit uns aufnehmen willst,\n"
	.string "{PLAYER}, musst du noch viel trainieren!$"

gTVInSearchOfTrainersText08::
	.string "Nach dem Kampf baten wir {PLAYER}\n"
	.string "um eine kurze Stellungnahme.\p"
	.string "Der Trainer sagte: “{STR_VAR_1}”.\p"
	.string "Die Pokémon {STR_VAR_2} und\n"
	.string "{STR_VAR_3} von {PLAYER}…\l"
	.string "Und “{STR_VAR_1}”…\p"
	.string "Mmh! Sehr tiefsinnig! Da liegt ein\n"
	.string "tieferer Sinn in dieser Aussage!\p"
	.string "Kein Wunder! Ein bedeutender Trainer\n"
	.string "wird auch bedeutende Worte sagen!\p"
	.string "Das war’s für heute!\n"
	.string "Bis zur nächsten Sendung!$"

ContestLadyShow_Text_Intro::
	.string "“Live Von Den Pokémon- Wettbewerben”\p"
	.string "MC: Wir unterbrechen das aktuelle\n"
	.string "Programm und berichten live von dem\l"
	.string "gerade beendeten {STR_VAR_1}!\p"
	.string "Zuschauer: ?!!\p"
	.string "MC: Oh! Die Teilnehmer des Wettbewerbs\n"
	.string "kommen gerade hier vorbei!\p"
	.string "Ich versuche, spontan ein Interview\n"
	.string "für euch zu Hause zu arrangieren.\p"
	.string "Zuschauer: ?!!\n"
	.string "?!!$"

ContestLadyShow_Text_Won::
	.string "MC: Entschuldige bitte!\n"
	.string "Danke, dass du dich für meine Sendung\l"
	.string "zur Verfügung stellst!\p"
	.string "Darf ich dir zu deinem Sieg gratulieren?\p"
	.string "Was war das ausschlaggebende Moment\n"
	.string "für deinen heutigen atemberaubenden\l"
	.string "Sieg?\p"
	.string "Schönheit: Wir haben heute einfach\n"
	.string "unser Bestes gegeben, mein {STR_VAR_2}\l"
	.string "und ich!\p"
	.string "Aber wir hätten es ohne die\n"
	.string "Unterstützung, die wir vor und im\p"
	.string "Wettbewerb erhalten haben, nicht\n"
	.string "geschafft!\p"
	.string "MC: Gibt es jemand Besonderen, mit dem\n"
	.string "du deine Freude teilen möchtest?\p"
	.string "Schönheit: Hey, da draußen!\p"
	.string "{STR_VAR_3}! Schaust du gerade zu?\n"
	.string "Wir haben es geschafft!!!\l"
	.string "Vielen Dank!$"

ContestLadyShow_Text_Lost::
	.string "MC: Entschuldige bitte!\n"
	.string "Danke, dass du dich für meine Sendung\l"
	.string "zur Verfügung stellst!\p"
	.string "Du bist bestimmt enttäuscht über den\n"
	.string "Ausgang. Willst du uns ein paar Worte\l"
	.string "dazu sagen?\p"
	.string "Schönheit: Es ist herzzerreißend…\n"
	.string "Mein {STR_VAR_2} und ich, wir haben\l"
	.string "unser Bestes gegeben…\p"
	.string "Aber ich habe das Gefühl, jeden, der uns\n"
	.string "bis hierher unterstützt hat,\l"
	.string "enttäuscht zu haben.\p"
	.string "MC: Ich hasse es, das zu sagen, aber die\n"
	.string "Farben des Pokémon wirken ein bisschen\l"
	.string "deplatziert.\p"
	.string "Schönheit: {STR_VAR_3}, es tut mir so\n"
	.string "Leid… Nächstes Mal werde ich besser\l"
	.string "abschneiden, das schwöre ich…\p"
	.string "Schluchz… \p"
	.string "Publikum: Seht mal! Das arme Mädchen!\p"
	.string "MC: Äh… Oh oh…\p"
	.string "Äh… Das war’s für heute!\n"
	.string "Vielen Dank für’s Zuschauen!$"

ContestLadyShow_Text_LostBadly::
	.string "MC: Entschuldige!\n"
	.string "Vielen Dank, dass ihr an meiner Sendung\l"
	.string "teilnehmt.\p"
	.string "Wie lief der Wettbewerb für dich?\p"
	.string "Schönheit: Nichts lief so wie es sein\n"
	.string "sollte… Aus irgendeinem Grund konnte\p"
	.string "mein {STR_VAR_2} das Publikum nicht\n"
	.string "begeistern.\p"
	.string "MC: Ich hasse es, das zu sagen, aber die\n"
	.string "Farbe deines Pokémon wirkt etwas\l"
	.string "deplatziert.\p"
	.string "Schönheit: … … … …\n"
	.string "… …\l"
	.string "Schluchz… Waaaahaaaaa…\p"
	.string "Publikum: Seht mal! Das arme Mädchen!\p"
	.string "MC: Äh… Oh oh…\p"
	.string "Äh… Das war’s von uns für heute!\n"
	.string "Vielen Dank für’s Einschalten.$"
