Route4_Frlg_MapScripts::
	.byte 0

Route4_EventScript_Unused::
	end

Route4_EventScript_Woman::
	msgbox Route4_Text_TrippedOverGeodude, MSGBOX_NPC
	end

Route4_EventScript_MtMoonSign::
	msgbox Route4_Text_MtMoonEntrance, MSGBOX_SIGN
	end

Route4_EventScript_RouteSign::
	msgbox Route4_Text_RouteSign, MSGBOX_SIGN
	end

Route4_Text_TrippedOverGeodude::
	.string "Aua! Ich bin über ein Kleinstein\n"
	.string "gestolpert, ein Stein-Pokémon!$"

Route4_Text_CrissyIntro::
	.string "Ich bin hier, um Pilz-Pokémon zu\n"
	.string "fangen!$"

Route4_Text_CrissyDefeat::
	.string "Ach, Pilz-Pokémon sind ja so süß!$"

Route4_Text_CrissyPostBattle::
	.string "Es dürfte hier keine Pilz-Pokémon\n"
	.string "mehr geben.\p"
	.string "Ich glaube, ich habe alle\n"
	.string "gefangen.$"

Route4_Text_MtMoonEntrance::
	.string "Mondberg\n"
	.string "Tunneleingang$"

Route4_Text_RouteSign::
	.string "Route 4\n"
	.string "Mondberg - Azuria City$"

Text_MegaPunchTeach::
	.string "Ein Schlag von roher Gewalt!\p"
	.string "Mit zerstörerischer, verheerender\n"
	.string "Wirkung.\p"
	.string "Wenn es darauf ankommt, ist\n"
	.string "Megahieb die ultimative Attacke!\l"
	.string "Du stimmst zu, oder?\p"
	.string "Also!\n"
	.string "Soll ein Pokémon diese Attacke\l"
	.string "erlernen?$"

Text_MegaPunchDeclined::
	.string "Du kommst wieder, wenn du die\n"
	.string "Bedeutung von Megahieb\l"
	.string "erkannt hast.$"

Text_MegaPunchWhichMon::
	.string "Schön!\n"
	.string "Welches Pokémon soll Megahieb\l"
	.string "erlernen?$"

Text_MegaPunchTaught::
	.string "Nun sind wir Freunde, was Hiebe\n"
	.string "angeht!\p"
	.string "Du solltest gehen, ehe dich der\n"
	.string "arme, fehlgeleitete Kerl, der dort \l"
	.string "drüben nur Tritte trainiert, sieht.$"

Text_MegaKickTeach::
	.string "Ein Tritt von brutaler Energie!\p"
	.string "Mit zerstörerischer, verheerender\n"
	.string "Wirkung.\p"
	.string "Wenn es darauf ankommt, ist \n"
	.string "Megakick die ultimative Attacke!\p"
	.string "O.K.!\n"
	.string "Ich werde Megakick einem\l"
	.string "Pokémon beibringen.$"

Text_MegaKickDeclined::
	.string "Du kommst angekrochen, wenn du die\n"
	.string "wahre Bedeutung von Megakick\l"
	.string "erkennst.$"

Text_MegaKickWhichMon::
	.string "In Ordnung!\n"
	.string "Welches Pokémon soll Megakick\l"
	.string "erlernen?$"

Text_MegaKickTaught::
	.string "Nun sind wir Freunde, was Tritte\n"
	.string "angeht!\p"
	.string "Du solltest gehen, ehe dich der\n"
	.string "arme, fehlgeleitete Kerl, der dort \l"
	.string "drüben nur Hiebe trainiert, sieht.$"

Route4_Text_PeopleLikeAndRespectBrock::
	.string "Oh, das ist ja der Felsorden!\n"
	.string "Du hast ihn von Rocko bekommen,\l"
	.string "oder?\l"
	.string "Rocko ist cool. Er ist nicht nur\l"
	.string "stark, sondern auch beliebt und\l"
	.string "wird respektiert.\l"
	.string "Ich möchte auch ein Arenaleiter\l"
	.string "wie er werden.$"
