SSAnne_1F_Corridor_Frlg_MapScripts::
	.byte 0

SSAnne_1F_Corridor_EventScript_WorkerM::
	msgbox SSAnne_1F_Corridor_Text_LeStrongSilentType, MSGBOX_NPC
	end

SSAnne_1F_Corridor_EventScript_Sailor::
	msgbox SSAnne_1F_Corridor_Text_PassengersAreRestless, MSGBOX_NPC
	end

SSAnne_1F_Corridor_Text_LeStrongSilentType::
	.string "Oh, was ist das?\n"
	.string "Das ist für mich?\p"
	.string "Woher wusstest du, dass ich seltene\n"
	.string "Gesteine liebe?\p"
	.string "Du weißt, wie man einen Kerl\n"
	.string "glücklich macht!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
	.string "Oh, das ist von BILL!\n"
	.string "Richte ihm meinen Dank aus!\p"
	.string "Du warst einfach fantastisch!\n"
	.string "Das ist für dich!$"

