SSAnne_1F_Corridor_Frlg_MapScripts::
	.byte 0

SSAnne_1F_Corridor_EventScript_WorkerM::
	msgbox SSAnne_1F_Corridor_Text_LeStrongSilentType, MSGBOX_NPC
	end

SSAnne_1F_Corridor_EventScript_Sailor::
	msgbox SSAnne_1F_Corridor_Text_PassengersAreRestless, MSGBOX_NPC
	end

SSAnne_1F_Corridor_Text_LeStrongSilentType::
	.string "Moin, moin, du Landradde!\n"
	.string "Ich bin der Steward auf diesem\l"
	.string "Kahn!\p"
	.string "Ruf mich einfach, wenn du einen\n"
	.string "Wunsch hast!\p"
	.string "Verdammich, gesprächig bist du\n"
	.string "aber nicht!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
	.string "Viele Passagiere sind hyperaktiv!\p"
	.string "Sie langweilen sich und sehnen sich\n"
	.string "nach einem Kampf!$"

