FuchsiaCity_House1_hns_MapScripts::
	.byte 0

FuchsiaCity_House1_EventScript_BillsOlderSister::
	msgbox FuchsiaCity_House1_Text_BillsOlderSister, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_Youngster::
	msgbox FuchsiaCity_House1_Text_Youngster, MSGBOX_NPC
	end

FuchsiaCity_House1_Text_BillsOlderSister:
	.string "Großvater ist gerade zu Besuch\n"
	.string "bei Bill in seinem Haus am Kap\l"
	.string "von Azuria City.$"

FuchsiaCity_House1_Text_Youngster:
	.string "Ich habe vom Radweg aus ein paar\n"
	.string "merkwürdige Pokémon in der Gegend\l"
	.string "herumschleichen sehen!$"

