VermilionCity_House1_hns_MapScripts::
	.byte 0

VermilionCity_House1_EventScript_Fisher::
	msgbox VermilionCity_House1_Text_FishingDude, MSGBOX_NPC
	end
VermilionCity_House1_EventScript_Photo::
	msgbox VermilionCity_House1_Text_Photo, MSGBOX_NPC
	end
VermilionCity_House1_Text_FishingDude:
	.string "Ich bin der Senior-Angler, der ältere\n"
	.string "der beiden Anglerbrüder.\p"
	.string "Hast du schon mal was von diesem\n"
	.string "Profi-Angler am See des Zorns gehört?\p"
	.string "Sein Traum ist es, einmal das größte\n"
	.string "KARPADOR der Welt zu entdecken.\p"
	.string "Wenn's dir nichts ausmacht, dann zeige\n"
	.string "ihm doch alle KARPADOR, die du fängst!\p"
	.string "Wer weiß, vielleicht fängst du ja das\n"
	.string "KARPADOR seiner Träume!$"

VermilionCity_House1_Text_Photo:
	.string "Das ist ein Foto von Leuten,\n"
	.string "die angeln…\p"
	.string "Sie haben eine tolle Zeit…$"
