Route19_Frlg_MapScripts::
	.byte 0

Route19_EventScript_RouteSign::
	msgbox Route19_Text_RouteSign, MSGBOX_SIGN
	end

Route19_Text_RichardIntro::
	.string "Vor dem Schwimmen muss ich mich\n"
	.string "noch aufwärmen!$"

Route19_Text_RichardDefeat::
	.string "Wunderbar, jetzt ist mir warm!$"

Route19_Text_RichardPostBattle::
	.string "Danke!\n"
	.string "Jetzt kann ich schwimmen gehen!$"

Route19_Text_ReeceIntro::
	.string "Warte! Sonst bekommst du einen\n"
	.string "Herzinfarkt!$"

Route19_Text_ReeceDefeat::
	.string "Wuah!\n"
	.string "Mir ist kalt!$"

Route19_Text_ReecePostBattle::
	.string "Nimm dich vor TENTACHA in Acht!$"

Route19_Text_MatthewIntro::
	.string "Ich gehe gerne schwimmen!\n"
	.string "Du auch?$"

Route19_Text_MatthewDefeat::
	.string "Man, war das ein Bauchplatscher!$"

Route19_Text_MatthewPostBattle::
	.string "Ich kann Pokémon besiegen, während\n"
	.string "ich schwimme!$"

Route19_Text_DouglasIntro::
	.string "Was mag sich hinter dem Horizont\n"
	.string "verbergen?$"

Route19_Text_DouglasDefeat::
	.string "Blubber! Gluck!$"

Route19_Text_DouglasPostBattle::
	.string "Ich sehe eine Inselgruppe!$"

Route19_Text_DavidIntro::
	.string "Ich wollte nach Pokémon tauchen,\n"
	.string "doch das war keine gute Idee!$"

Route19_Text_DavidDefeat::
	.string "Hilfe!$"

Route19_Text_DavidPostBattle::
	.string "Nach WASSER-POKéMON sollte man\n"
	.string "lieber angeln!$"

Route19_Text_TonyIntro::
	.string "Ich schaue auf das Meer, um zu\n"
	.string "vergessen!$"

Route19_Text_TonyDefeat::
	.string "Nein!\n"
	.string "Ein traumatisches Erlebnis!$"

Route19_Text_TonyPostBattle::
	.string "Ich schaue auf das Meer, um zu\n"
	.string "vergessen!$"

Route19_Text_AnyaIntro::
	.string "Gibst du mir das Pokémon, auf dem\n"
	.string "du stehst, wenn ich gewinne?$"

Route19_Text_AnyaDefeat::
	.string "Oh! Ich habe verloren!$"

Route19_Text_AnyaPostBattle::
	.string "Bis zu den Seeschauminseln ist es\n"
	.string "noch ein weiter Weg!$"

Route19_Text_AliceIntro::
	.string "Schwimmen macht Spaß, aber man\n"
	.string "holt sich schnell einen\l"
	.string "Sonnenbrand!$"

Route19_Text_AliceDefeat::
	.string "Du bist ein ganz schlimmer Finger!$"

Route19_Text_AlicePostBattle::
	.string "Mein Freund wollte zu den\n"
	.string "Seeschauminseln schwimmen.$"

Route19_Text_AxleIntro::
	.string "Diese Gewässer sind trügerisch!$"

Route19_Text_AxleDefeat::
	.string "Das war gefährlich!$"

Route19_Text_AxlePostBattle::
	.string "Ich habe einen Krampf!\n"
	.string "Blubber, gluck...$"

Route19_Text_ConnieIntro::
	.string "Ich bin hierher geschwommen und\n"
	.string "nun bin ich müde!$"

Route19_Text_ConnieDefeat::
	.string "Ich bin am Ende meiner Kraft...$"

Route19_Text_ConniePostBattle::
	.string "Lapras ist so groß, dass es dich\n"
	.string "trockenen Fußes über das Wasser\l"
	.string "tragen kann!$"

Route19_Text_RouteSign::
	.string "SEE-ROUTE 19\n"
	.string "FUCHSANIA CITY - SEESCHAUMINSELN$"

Route19_Text_LiaIntro::
	.string "Nora: Ich kümmere mich um\n"
	.string "meinen Bruder. Er ist vor\l"
	.string "kurzem ein Trainer geworden.$"

Route19_Text_LiaDefeat::
	.string "Nora: Das ist keine Art meinen\n"
	.string "kleinen Bruder zu behandeln.$"

Route19_Text_LiaPostBattle::
	.string "Nora: Hast du einen kleinen Bruder?\p"
	.string "Ich hoffe, du bringst ihm alles\n"
	.string "Mögliche bei.$"

Route19_Text_LiaNotEnoughMons::
	.string "NORA: Ich möchte mit meinem kleinen\n"
	.string "Bruder zusammen kämpfen.\p"
	.string "Hast du keine zwei POKéMON?$"

Route19_Text_LucIntro::
	.string "Tom: Meine große Schwester hat\n"
	.string "mir das Schwimmen beigebracht\l"
	.string "und mir gezeigt, wie man\l"
	.string "Pokémon trainiert.$"

Route19_Text_LucDefeat::
	.string "Tom: Oh, wow!\n"
	.string "Es gibt jemand, der stärker als\l"
	.string "meine Schwester ist!$"

Route19_Text_LucPostBattle::
	.string "Tom: Meine große Schwester ist\n"
	.string "stark und nett. Sie ist wundervoll.$"

Route19_Text_LucNotEnoughMons::
	.string "TOM: Ich will nicht ohne meine\n"
	.string "Schwester gegen dich kämpfen.\p"
	.string "Hast du keine zwei POKéMON?$"
