SSAnne_Deck_Frlg_MapScripts::
	.byte 0

SSAnne_Deck_EventScript_Youngster::
	msgbox SSAnne_Deck_Text_ShipDepartingSoon, MSGBOX_NPC
	end

SSAnne_Deck_EventScript_BaldingMan::
	msgbox SSAnne_Deck_Text_FeelSeasick, MSGBOX_NPC
	end

SSAnne_Deck_EventScript_Sailor::
	msgbox SSAnne_Deck_Text_ScrubbingDecksHardWork, MSGBOX_NPC
	end

SSAnne_Deck_EventScript_Edmond::
	trainerbattle_single TRAINER_SAILOR_EDMOND, SSAnne_Deck_Text_EdmondIntro, SSAnne_Deck_Text_EdmondDefeat
	msgbox SSAnne_Deck_Text_EdmondPostBattle, MSGBOX_AUTOCLOSE
	end

SSAnne_Deck_EventScript_Trevor::
	trainerbattle_single TRAINER_SAILOR_TREVOR, SSAnne_Deck_Text_TrevorIntro, SSAnne_Deck_Text_TrevorDefeat
	msgbox SSAnne_Deck_Text_TrevorPostBattle, MSGBOX_AUTOCLOSE
	end

SSAnne_Deck_Text_ShipDepartingSoon::
	.string "Sperrstunde! Die Party ist vorbei!\n"
	.string "Das Schiff sticht bald in See!$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
	.string "Puh! Ich werde das Deck wohl nie\n"
	.string "sauber bekommen!$"

SSAnne_Deck_Text_FeelSeasick::
	.string "Brrr, ich fühle mich elend...\p"
	.string "An der frischen Luft fühle ich mich\n"
	.string "besser...$"

SSAnne_Deck_Text_EdmondIntro::
	.string "Heh!\p"
	.string "Wie wäre es mit einem Tänzchen?$"

SSAnne_Deck_Text_EdmondDefeat::
	.string "Ich bin beeindruckt!$"

SSAnne_Deck_Text_EdmondPostBattle::
	.string "Hast du eine Ahnung, wie viele\n"
	.string "unterschiedliche Pokémon es gibt?$"

SSAnne_Deck_Text_TrevorIntro::
	.string "Ahoi!\n"
	.string "Bist du seekrank?$"

SSAnne_Deck_Text_TrevorDefeat::
	.string "Du hast Glück gehabt!$"

SSAnne_Deck_Text_TrevorPostBattle::
	.string "Mein Vater sagt, es gäbe 100\n"
	.string "verschiedene Pokémon. Ich denke,\l"
	.string "es gibt mehr...$"

