Route21_North_Frlg_MapScripts::
	.byte 0

Route21_North_Text_RonaldIntro::
	.string "Möchtest du wissen, ob die Fische\n"
	.string "beißen?$"

Route21_North_Text_RonaldDefeat::
	.string "Mist!$"

Route21_North_Text_RonaldPostBattle::
	.string "Bisher habe ich noch nichts\n"
	.string "gefangen!$"

Route21_North_Text_WadeIntro::
	.string "Ich habe einen guten Fang\n"
	.string "gemacht! Möchtest du ihn sehen?$"

Route21_North_Text_WadeDefeat::
	.string "NEIN!\n"
	.string "KARPADOR!$"

Route21_North_Text_WadePostBattle::
	.string "Oh nein! Ich habe schon wieder\n"
	.string "ein Karpador gefangen!$"

Route21_North_Text_SpencerIntro::
	.string "Die See reinigt Körper und Seele!$"

Route21_North_Text_SpencerDefeat::
	.string "Nein!$"

Route21_North_Text_SpencerPostBattle::
	.string "Aber ich mag die Berge genauso\n"
	.string "gern!$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
	.string "おれだって　たまには\n"
	.string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
	.string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
	.string "うきやすそう　だと？\n"
	.string "うるせー　おおきな　おせわだッ！$"
