SSAnne_2F_Room6_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room6_EventScript_Woman1::
	msgbox SSAnne_2F_Room6_Text_CaptainIsAwfullySick, MSGBOX_NPC
	end

SSAnne_2F_Room6_EventScript_Woman2::
	msgbox SSAnne_2F_Room6_Text_ManyPeopleGetSeasick, MSGBOX_NPC
	end

SSAnne_2F_Room6_Text_CaptainIsAwfullySick::
	.string "Der Kapitän war kreidebleich!\n"
	.string "Er sah schlecht aus!$"

SSAnne_2F_Room6_Text_ManyPeopleGetSeasick::
	.string "Viele Leute werden leicht seekrank!$"

