SevenIsland_SevaultCanyon_Entrance_Frlg_MapScripts::
	.byte 0

SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign::
	msgbox SevenIsland_SevaultCanyon_Entrance_Text_RouteSign, MSGBOX_SIGN
	end

SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
	.string "Hugh!\n"
	.string "Ich besiege dich mit links!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
	.string "Tss!\n"
	.string "Zu stark für mich!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
	.string "Wie war das?\n"
	.string "Ich handle nicht nach meinem\l"
	.string "Aussehen?\l"
	.string "Heh, das ist ein Teil meiner\l"
	.string "Strategie!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
	.string "Servus!\n"
	.string "Bist du in meinem Fanclub?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
	.string "Oh, du bist kein Fan…\p"
	.string "Nun, das kann ich ändern.\n"
	.string "Ich singe nur für dich!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
	.string "Lalala…\n"
	.string "Ich schicke meine Pokémon\l"
	.string "hinaus und die Mädchen schreien!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
	.string "Die Insel ist so weitläufig…\n"
	.string "Es ist schwierig, sie zu bewachen.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
	.string "Uh-uh…$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
	.string "Trainer, die wie du aus Städten\n"
	.string "kommen, sind stark.\p"
	.string "Du bist auf dem Weg zum Turm, \n"
	.string "nicht wahr?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
	.string "Ich bestrafe Leute, die Pokémon\n"
	.string "missbrauchen!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
	.string "Du scheinst kein Problem dar-\n"
	.string "zustellen, Trainer.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
	.string "Behandelst du deine Pokémon\n"
	.string "freundlich, verstehen sie dich.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
	.string "Tizia: Ich bilde ein Team mit Till\n"
	.string "und wir kämpfen gemeinsam.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
	.string "Tizia: Till und ich haben\n"
	.string "verloren. Hehe!$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
	.string "Tizia: Ich muss härter mit Till\n"
	.string "trainieren.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
	.string "Tizia: Ich möchte gemeinsam\n"
	.string "mit Till gegen dich antreten.\p"
	.string "Komme mit zwei Pokémon wieder!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
	.string "Till: Wenn ich an der Seite von\n"
	.string "Tizia bin, fühle ich, dass wir\l"
	.string "nicht verlieren können…$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
	.string "Till: Wenn ich an der Seite von\n"
	.string "Tizia bin, fühle ich, dass wir\l"
	.string "nicht verloren haben…$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
	.string "Till: Wenn ich an der Seite von\n"
	.string "Tizia bin, ist mir schwindelig,\l"
	.string "egal, ob ich gewinne oder verliere.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
	.string "Till: Wenn ich mit Tizia gegen\n"
	.string "dich kämpfe, bin ich glücklich.\p"
	.string "Ich möchte also einen Zwei-gegen-\n"
	.string "Zwei-Kampf mit dir austragen.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
	.string "Eingang zur 7-Schatzschlucht\p"
	.string "Trainer werden gebeten, die\n"
	.string "Pflanzen in der Schlucht\l"
	.string "nicht zu beschädigen!$"

