CeladonCity_House1_Frlg_MapScripts::
	.byte 0

CeladonCity_House1_EventScript_RocketChief::
	msgbox CeladonCity_House1_Text_SlotsReelInTheDough, MSGBOX_NPC
	end

CeladonCity_House1_EventScript_Rocket1::
	msgbox CeladonCity_House1_Text_ShippedMonsAsSlotPrizes, MSGBOX_NPC
	end

CeladonCity_House1_EventScript_Rocket2::
	msgbox CeladonCity_House1_Text_DontTouchGameCornerPoster, MSGBOX_NPC
	end

CeladonCity_House1_Text_SlotsReelInTheDough::
	.string "Haha!\p"
	.string "Mit den Spielautomaten verdienen\n"
	.string "wir uns eine goldene Nase!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
	.string "Boss!\p"
	.string "Wir haben gerade 2000 Pokémon als\n"
	.string "Preise versandt!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
	.string "Schenke dem Poster in der\n"
	.string "Spielhalle keine Beachtung.\p"
	.string "Dahinter ist kein versteckter\n"
	.string "Schalter!$"

