PewterCity_House2_Frlg_MapScripts::
	.byte 0

PewterCity_House2_EventScript_OldMan::
	msgbox PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow, MSGBOX_NPC
	end

PewterCity_House2_EventScript_LittleBoy::
	msgbox PewterCity_House2_Text_MonsEasierCatchIfStatused, MSGBOX_NPC
	end

PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
	.string "Mit wachsender Erfahrung lernen\n"
	.string "Pokémon neue Attacken!\p"
	.string "Manche Attacken kann ihnen jedoch\n"
	.string "nur ein Trainer beibringen!$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
	.string "Pokémon sind einfacher zu fangen,\n"
	.string "wenn sie verletzt sind oder\l"
	.string "schlafen!\p"
	.string "Trotzdem gibt es keine\n"
	.string "Erfolgsgarantie!$"

