Route2_ViridianForest_NorthEntrance_Frlg_MapScripts::
	.byte 0

Route2_ViridianForest_NorthEntrance_EventScript_Youngster::
	msgbox Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_OldMan::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_CooltrainerF::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
	.string "Viele POKéMON leben in Höhlen und\n"
	.string "Wäldern.\p"
	.string "Du solltest dich überall umsehen,\n"
	.string "um verschiedene zu finden!$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
	.string "FLEGMON war hier, aber ich habe\n"
	.string "ihn nicht verstehen können!\p"
	.string "Ich glaube, er hat keine Zähne\n"
	.string "mehr!$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
	.string "FLEGMON hält zur Zeit eine\n"
	.string "Werbekampagne.\p"
	.string "Erreiche die abgelegenste\n"
	.string "Stelle in der SAFARI-ZONE.\p"
	.string "Wenn du das schaffst, erhältst\n"
	.string "du einen praktischen Preis!$"

