Route2_ViridianForest_NorthEntrance_Frlg_MapScripts::
	.byte 0

Route2_ViridianForest_NorthEntrance_EventScript_Youngster::
	msgbox Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_OldMan::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_CooltrainerF::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
	.string "Viele Pokémon leben in Höhlen und\n"
	.string "Wäldern.\p"
	.string "Du solltest dich überall umsehen,\n"
	.string "um verschiedene zu finden!$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
	.string "Achte auf Büsche am Wegesrand.\p"
	.string "Pokémon können sie mit einer\n"
	.string "Spezial-Technik klein hacken.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
	.string "Man kann die Entwicklung eines\n"
	.string "Pokémon stoppen.\p"
	.string "Bricht man sie ab, dann bleibt das\n"
	.string "Pokémon, wie es ist.$"

