TwoIsland_CapeBrink_House_Frlg_MapScripts::
	.byte 0

@ See move_tutors.inc

Text_UltimateMoveThatMon::
	.string "Ich habe die ultimative Attacke\n"
	.string "dieser Elementklasse perfektioniert!\p"
	.string "Aber wird sie in Zukunft von\n"
	.string "niemandem eingesetzt?\p"
	.string "… hm?\p"
	.string "D-du…\n"
	.string "Da-das {VAR}…$"

Text_JustMistaken::
	.string "… nein…\n"
	.string "Ich hatte Unrecht.$"

Text_AllowMeToTeachMonUltimateMove::
	.string "Oh! Das ist es!\n"
	.string "Das ist das POKéMON!\p"
	.string "Dieses {VAR} ist des\n"
	.string "Erlernens meiner Attacke würdig!\p"
	.string "Lässt du es zu?\p"
	.string "Darf dein {VAR} {VAR}\n"
	.string "lernen?$"

Text_YouRejectIt::
	.string "Wie?!? Du lehnst es ab? Nein, ich\n"
	.string "lasse mich davon nicht abbringen!$"

Text_LetMeConferUltimateMove::
	.string "Du lässt es zu?\p"
	.string "Somit lehre ich {VAR}\n"
	.string "deinem {VAR}.\p"
	.string "Cool!$"

Text_TaughtMove::
	.string "Schnauf, schnauf…\p"
	.string "Ich hätte nicht gedacht, dass\n"
	.string "ich diese Attacke noch in meinem\l"
	.string "Leben lehren durfte…$"

Text_MakeBestUseOfMove::
	.string "Ich erwarte, dass du die Attacke\n"
	.string "bestmöglich einsetzt und stärker\l"
	.string "wirst!$"

Text_PassedOnEverythingIKnow::
	.string "Schnauf, schnauf…\p"
	.string "Ich bereue nichts! Ich habe\n"
	.string "all mein Wissen weitergegeben.\p"
	.string "Nun kann ich mit mir Frieden\n"
	.string "schließen und mein Leben\l"
	.string "leben. Meine Aufgabe ist erfüllt.$"

Text_FeelRejuvenated::
	.string "Nachdem ich dir mein Wissen\n"
	.string "übergeben hatte, fühlte ich mich\l"
	.string "so erleichtert.\p"
	.string "Ich fühle mich in der Tat\n"
	.string "jünger, wie neu geboren!$"
