Route25_Frlg_MapScripts::
	.byte 0

Route25_EventScript_SeaCottageSign::
	msgbox Route25_Text_SeaCottageSign, MSGBOX_SIGN
	end

Route25_EventScript_Man::
	msgbox Route25_Text_AreYouHereAlone, MSGBOX_NPC
	end

Route25_Text_JoeyIntro::
	.string "Die Trainer der Gegend kommen zum\n"
	.string "Üben hierher!$"

Route25_Text_JoeyDefeat::
	.string "Du bist richtig gut!$"

Route25_Text_JoeyPostBattle::
	.string "Jedes Pokémon hat seine\n"
	.string "Schwächen!\p"
	.string "Man sollte daher unterschiedliche\n"
	.string "Pokémon trainieren.$"

Route25_Text_DanIntro::
	.string "Ich habe in Orania City mit\n"
	.string "meinem Papa auf der M.s. Anne eine\l"
	.string "Party besucht!$"

Route25_Text_DanDefeat::
	.string "Ich bin nicht sauer!$"

Route25_Text_DanPostBattle::
	.string "Auf der M.s. Anne habe ich\n"
	.string "Trainer aus aller Welt gesehen!$"

Route25_Text_FlintIntro::
	.string "Ich bin richtig cool!\n"
	.string "Ich habe eine Freundin!$"

Route25_Text_FlintDefeat::
	.string "Ach, so ein Mist...$"

Route25_Text_FlintPostBattle::
	.string "Na ja, meine Freundin wird mich\n"
	.string "aufheitern!$"

Route25_Text_KelseyIntro::
	.string "Hallo!\n"
	.string "Mein Freund ist cool!$"

Route25_Text_KelseyDefeat::
	.string "Ich war nicht in Form!$"

Route25_Text_KelseyPostBattle::
	.string "Ach, wäre mein Freund doch auch\n"
	.string "so toll wie du!$"

Route25_Text_ChadIntro::
	.string "Ich wusste, dass wir miteinander\n"
	.string "kämpfen würden!$"

Route25_Text_ChadDefeat::
	.string "Ich wusste auch, dass ich verlieren\n"
	.string "würde!$"

Route25_Text_ChadPostBattle::
	.string "Wenn eines deiner Pokémon verwirrt\n"
	.string "ist, wechsle es aus!\p"
	.string "Das ist eine gute Taktik!$"

Route25_Text_HaleyIntro::
	.string "Meine Freundin hat so ein süßes\n"
	.string "Pokémon! Ich bin furchtbar\l"
	.string "neidisch!$"

Route25_Text_HaleyDefeat::
	.string "Ich bin nicht sauer!$"

Route25_Text_HaleyPostBattle::
	.string "Du warst auf dem Mondberg?\n"
	.string "Hast du ein Piepi gefunden?$"

Route25_Text_FranklinIntro::
	.string "Ich komme gerade vom Mondberg und\n"
	.string "bin topfit!$"

Route25_Text_FranklinDefeat::
	.string "Du hast schwer gekämpft!$"

Route25_Text_FranklinPostBattle::
	.string "Mist!\n"
	.string "Mich hat ein Zubat gebissen!$"

Route25_Text_NobIntro::
	.string "Ich bin auf dem Weg zu einem\n"
	.string "Pokémon-Sammler!$"

Route25_Text_NobDefeat::
	.string "Du hast mich besiegt.$"

Route25_Text_NobPostBattle::
	.string "Dieser Sammler besitzt viele\n"
	.string "seltene Pokémon.$"

Route25_Text_WayneIntro::
	.string "Du möchtest zu Bill?\n"
	.string "Aber erst wird gekämpft!$"

Route25_Text_WayneDefeat::
	.string "Ich gebe auf!$"

Route25_Text_WaynePostBattle::
	.string "Der Pfad dort unten ist eine\n"
	.string "Abkürzung nach Azuria City.$"

Route25_Text_SeaCottageSign::
	.string "Küstenhaus\n"
	.string "Hier wohnt Bill!$"

Route25_Text_MistyHighHopesAboutThisPlace::
	.string "Das Kap ist beliebt bei Pärchen.\p"
	.string "Die Arenaleiterin Misty hat hohe\n"
	.string "Erwartungen an diesen Ort.$"

Route25_Text_AreYouHereAlone::
	.string "Ihre Seele hat Frieden gefunden.\p"
	.string "Sie ist in das Jenseits\n"
	.string "eingekehrt...$"

