Route17_Frlg_MapScripts::
	.byte 0

Route17_EventScript_ItemsNotice::
	msgbox Route17_Text_WatchOutForDiscardedItems, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips1::
	msgbox Route17_Text_SameSpeciesGrowDifferentRates, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips2::
	msgbox Route17_Text_PressBToStayInPlace, MSGBOX_SIGN
	end

Route17_EventScript_RouteSign::
	msgbox Route17_Text_RouteSign, MSGBOX_SIGN
	end

Route17_EventScript_BallsNotice::
	msgbox Route17_Text_DontThrowGameThrowBalls, MSGBOX_SIGN
	end

Route17_EventScript_CyclingRoadSign::
	msgbox Route17_Text_CyclingRoadSign, MSGBOX_SIGN
	end

Route17_Text_RaulIntro::
	.string "Es lohnt sich nicht, Kinder\n"
	.string "auszurauben!$"

Route17_Text_RaulDefeat::
	.string "Die Luft ist raus!$"

Route17_Text_RaulPostBattle::
	.string "Auf dem Radweg liegen nützliche\n"
	.string "Items herum!$"

Route17_Text_IsaiahIntro::
	.string "Was willst du, Tröte?$"

Route17_Text_IsaiahDefeat::
	.string "Hoho!$"

Route17_Text_IsaiahPostBattle::
	.string "Ich könnte dich mit einem\n"
	.string "Bauchplatscher plattmachen!$"

Route17_Text_VirgilIntro::
	.string "Willst du nach Fuchsania City?$"

Route17_Text_VirgilDefeat::
	.string "Ich habe mein Bestes gegeben!$"

Route17_Text_VirgilPostBattle::
	.string "Ich liebe es, bergab Rennen zu\n"
	.string "fahren!$"

Route17_Text_BillyIntro::
	.string "Wir sind Biker, Könige des\n"
	.string "Highways!$"

Route17_Text_BillyDefeat::
	.string "Ich bin voll auf die Nase\n"
	.string "gefallen!$"

Route17_Text_BillyPostBattle::
	.string "Suchst du das Abenteuer?$"

Route17_Text_NikolasIntro::
	.string "Voltobal wird dich unter Strom\n"
	.string "setzen!$"

Route17_Text_NikolasDefeat::
	.string "Du hast mich geerdet!$"

Route17_Text_NikolasPostBattle::
	.string "Ich habe Voltobal im verlassenen\n"
	.string "Kraftwerk gefangen.$"

Route17_Text_ZeekIntro::
	.string "Mein Pokémon entwickelt sich nicht\n"
	.string "weiter!$"

Route17_Text_ZeekDefeat::
	.string "Heh, was sollte das?$"

Route17_Text_ZeekPostBattle::
	.string "Manche Pokémon benötigen\n"
	.string "spezielle Steine, um sich zu\l"
	.string "entwickeln.$"

Route17_Text_JamalIntro::
	.string "Ich muss ein wenig abnehmen!$"

Route17_Text_JamalDefeat::
	.string "Puh!\n"
	.string "Eine gute Übung!$"

Route17_Text_JamalPostBattle::
	.string "Ich habe sicher an Gewicht\n"
	.string "verloren!$"

Route17_Text_CoreyIntro::
	.string "Sei ein Rebell!$"

Route17_Text_CoreyDefeat::
	.string "Arrrgh!$"

Route17_Text_CoreyPostBattle::
	.string "Setze dich für deine Ideale ein!$"

Route17_Text_JaxonIntro::
	.string "Du besitzt ein schickes Fahrrad!\n"
	.string "Fährt es sich gut?$"

Route17_Text_JaxonDefeat::
	.string "Mist!$"

Route17_Text_JaxonPostBattle::
	.string "Das Gefälle macht das Lenken sehr\n"
	.string "schwer!$"

Route17_Text_WilliamIntro::
	.string "Zieh Leine!\n"
	.string "Ich bin erschöpft!$"

Route17_Text_WilliamDefeat::
	.string "Bist du nun zufrieden?$"

Route17_Text_WilliamPostBattle::
	.string "Ich muss mich eine Runde aufs Ohr\n"
	.string "legen!$"

Route17_Text_WatchOutForDiscardedItems::
	.string "Ein Hinweis!\p"
	.string "Achte auf weggeworfene Items!$"

Route17_Text_SameSpeciesGrowDifferentRates::
	.string "Tipps für Trainer\p"
	.string "Jedes Pokémon ist einzigartig.\p"
	.string "Selbst gleiche Pokémon mit\n"
	.string "identischem Level unterscheiden\l"
	.string "sich voneinander.$"

Route17_Text_PressBToStayInPlace::
	.string "Tipps für Trainer\p"
	.string "Drücke den B-Knopf, um auch bei\n"
	.string "Gefälle die Position zu halten.$"

Route17_Text_RouteSign::
	.string "Route 17\n"
	.string "Prismania City - Fuchsania City$"

Route17_Text_DontThrowGameThrowBalls::
	.string "Ein Hinweis!\p"
	.string "Gib niemals auf! Versuche dein\n"
	.string "Glück mit Pokébällen!$"

Route17_Text_CyclingRoadSign::
	.string "Der Radweg endet hier!$"

