Route6_Frlg_MapScripts::
	.byte 0

Route6_EventScript_UndergroundPathSign::
	msgbox Route6_Text_UndergroundPathSign, MSGBOX_SIGN
	end

Route6_Text_RickyIntro::
	.string "Wer da? Heh, hör auf, uns heimlich\n"
	.string "zu belauschen!$"

Route6_Text_RickyDefeat::
	.string "Ich kann einfach nie siegen!$"

Route6_Text_RickyPostBattle::
	.string "Flüster...\n"
	.string "Tuschel...$"

Route6_Text_NancyIntro::
	.string "Entschuldige, aber das hier ist\n"
	.string "Privatsache!$"

Route6_Text_NancyDefeat::
	.string "Grr!\n"
	.string "Ich hasse es, zu verlieren!$"

Route6_Text_NancyPostBattle::
	.string "Flüster...\n"
	.string "Tuschel...$"

Route6_Text_KeigoIntro::
	.string "Man findet hier draußen nicht viele\n"
	.string "Käfer...$"

Route6_Text_KeigoDefeat::
	.string "Du beliebst zu scherzen, oder?$"

Route6_Text_KeigoPostBattle::
	.string "Ich gehe in den Vertania-wald\n"
	.string "zurück. Dort gibt es mehr Käfer!$"

Route6_Text_JeffIntro::
	.string "Hörte ich da jemanden vom Kämpfen\n"
	.string "sprechen?$"

Route6_Text_JeffDefeat::
	.string "Hmm, ich hätte es besser überhört!$"

Route6_Text_JeffPostBattle::
	.string "Zu meiner eigenen Sicherheit sollte\n"
	.string "ich mehr Pokémon bei mir tragen!$"

Route6_Text_IsabelleIntro::
	.string "Kämpfen? Meinst du mich?\n"
	.string "Na gut!$"

Route6_Text_IsabelleDefeat::
	.string "Das hat nicht ganz geklappt!$"

Route6_Text_IsabellePostBattle::
	.string "Verrätst du mir dein Geheimnis?\n"
	.string "Ich möchte auch stärker werden!$"

Route6_Text_ElijahIntro::
	.string "Dich habe ich noch nie gesehen!\n"
	.string "Bist du ein guter Trainer?$"

Route6_Text_ElijahDefeat::
	.string "Du bist ein zu guter Trainer!$"

Route6_Text_ElijahPostBattle::
	.string "Ist mein Pokémon zu schwach,\n"
	.string "oder bin ich etwa nicht gut genug?$"

Route6_Text_UndergroundPathSign::
	.string "TUNNELPFAD\n"
	.string "AZURIA CITY - ORANIA CITY$"

