SixIsland_OutcastIsland_Frlg_MapScripts::
	.byte 0

SixIsland_OutcastIsland_EventScript_Rocket::
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_46, SixIsland_OutcastIsland_Text_RocketIntro, SixIsland_OutcastIsland_Text_RocketDefeat
	msgbox SixIsland_OutcastIsland_Text_RocketPostBattle, MSGBOX_AUTOCLOSE
	end

SixIsland_OutcastIsland_Text_RocketIntro::
	.string "Hier gibt es keine seltenen\n"
	.string "Pokémon! Nicht eines!\p"
	.string "Das ärgert mich, Kiddie! Daher\n"
	.string "kämpfe ich jetzt mit dir!$"

SixIsland_OutcastIsland_Text_RocketDefeat::
	.string "Wie?$"

SixIsland_OutcastIsland_Text_RocketPostBattle::
	.string "Hast du ein seltenes Pokémon\n"
	.string "gesehen? Sag es mir!$"

SixIsland_OutcastIsland_Text_TylorIntro::
	.string "Ich habe kein Glück!\n"
	.string "Ein Kampf wäre ein willkommener\l"
	.string "Rhythmuswechsel.$"

SixIsland_OutcastIsland_Text_TylorDefeat::
	.string "Nein, überhaupt kein Glück…$"

SixIsland_OutcastIsland_Text_TylorPostBattle::
	.string "Ich kann nicht nach Hause, ohne\n"
	.string "etwas gefangen zu haben!$"

SixIsland_OutcastIsland_Text_MymoIntro::
	.string "Schnauf… schnauf…\p"
	.string "Ich bin hier auf einmal vom\n"
	.string "Hafen auf Eiland Sechs\l"
	.string "her geschwommen.$"

SixIsland_OutcastIsland_Text_MymoDefeat::
	.string "Schnauf…\n"
	.string "Schnauf…$"

SixIsland_OutcastIsland_Text_MymoPostBattle::
	.string "Ich bin erst bei der Hälfte…\n"
	.string "Ich wurde besiegt…$"

SixIsland_OutcastIsland_Text_NicoleIntro::
	.string "Es ist nicht leicht, beim Schwimmen\n"
	.string "Pokémon in den Kampf zu\l"
	.string "schicken.$"

SixIsland_OutcastIsland_Text_NicoleDefeat::
	.string "Du hast mich nicht im Schwimmen\n"
	.string "geschlagen. Der Rest ist egal.$"

SixIsland_OutcastIsland_Text_NicolePostBattle::
	.string "Bist du auf dem Weg zu der Insel\n"
	.string "dort oben?\p"
	.string "Ich habe dort nichts Interessantes\n"
	.string "gesehen!$"

SixIsland_OutcastIsland_Text_AvaIntro::
	.string "Tina: Lass uns einen Zwei-gegen-\n"
	.string "Zwei Marinekampf bestreiten!$"

SixIsland_OutcastIsland_Text_AvaDefeat::
	.string "Tina: Oh, du überraschst mich!\n"
	.string "Noch besser, du bist allein!$"

SixIsland_OutcastIsland_Text_AvaPostBattle::
	.string "Tina: Ich bevorzuge das Meer\n"
	.string "gegenüber jedem Pool.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
	.string "TINA: Du forderst uns zu einem\n"
	.string "Kampf heraus?\p"
	.string "Du benötigst dafür allerdings\n"
	.string "mindestens zwei POKéMON.$"

SixIsland_OutcastIsland_Text_GebIntro::
	.string "Tino: Hilf mir, große Schwester!\n"
	.string "Bitte kämpfe mit mir!$"

SixIsland_OutcastIsland_Text_GebDefeat::
	.string "Tino: Wow, große Schwester, diese\n"
	.string "Person ist richtig gut!$"

SixIsland_OutcastIsland_Text_GebPostBattle::
	.string "Tino: Ich bin auf meine Schwester\n"
	.string "angewiesen, da ich den Boden\l"
	.string "nicht berühren kann.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
	.string "TINO: Bitte kämpfe gegen mich und\n"
	.string "meine Schwester!\p"
	.string "… oh, du hast keine zwei POKéMON?$"
