SaffronCity_Dojo_Frlg_MapScripts::
	.byte 0

SaffronCity_Dojo_EventScript_TriggerMasterBattleLeft::
	lockall
	setvar VAR_MAP_SCENE_SAFFRON_CITY_DOJO, 1
	applymovement LOCALID_KARATE_MASTER, Common_Movement_WalkInPlaceFasterLeft
	waitmovement 0
	releaseall
	end

SaffronCity_Dojo_EventScript_TriggerMasterBattleRight::
	lockall
	setvar VAR_MAP_SCENE_SAFFRON_CITY_DOJO, 1
	applymovement LOCALID_KARATE_MASTER, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	releaseall
	end

SaffronCity_Dojo_EventScript_HitmonleeBall::
	lock
	faceplayer
	goto_if_set FLAG_GOT_HITMON_FROM_DOJO, SaffronCity_Dojo_EventScript_AlreadyGotHitmon
	showmonpic SPECIES_HITMONLEE, 10, 3
	setvar VAR_TEMP_1, SPECIES_HITMONLEE
	applymovement LOCALID_KARATE_MASTER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	textcolor NPC_TEXT_COLOR_MALE
	msgbox SaffronCity_Dojo_Text_YouWantHitmonlee, MSGBOX_YESNO
	call EventScript_RestorePrevTextColor
	goto_if_eq VAR_RESULT, YES, SaffronCity_Dojo_EventScript_GiveHitmon
	hidemonpic
	release
	end

SaffronCity_Dojo_EventScript_AlreadyGotHitmon::
	msgbox SaffronCity_Dojo_Text_BetterNotGetGreedy
	release
	end

SaffronCity_Dojo_EventScript_HitmonchanBall::
	lock
	faceplayer
	goto_if_set FLAG_GOT_HITMON_FROM_DOJO, SaffronCity_Dojo_EventScript_AlreadyGotHitmon
	showmonpic SPECIES_HITMONCHAN, 10, 3
	setvar VAR_TEMP_1, SPECIES_HITMONCHAN
	applymovement LOCALID_KARATE_MASTER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	textcolor NPC_TEXT_COLOR_MALE
	msgbox SaffronCity_Dojo_Text_YouWantHitmonchan, MSGBOX_YESNO
	call EventScript_RestorePrevTextColor
	goto_if_eq VAR_RESULT, YES, SaffronCity_Dojo_EventScript_GiveHitmon
	hidemonpic
	release
	end

SaffronCity_Dojo_EventScript_GiveHitmon::
	hidemonpic
	givemon VAR_TEMP_1, 25
	goto_if_eq VAR_RESULT, 0, SaffronCity_Dojo_EventScript_ReceivedHitmonParty
	goto_if_eq VAR_RESULT, 1, SaffronCity_Dojo_EventScript_ReceivedHitmonPC
	goto_if_eq VAR_RESULT, 2, Common_EventScript_NoMoreRoomForPokemon
	release
	end

SaffronCity_Dojo_EventScript_ReceivedHitmonParty::
	removeobject VAR_LAST_TALKED
	bufferspeciesname STR_VAR_1, VAR_TEMP_1
	playfanfare MUS_LEVEL_UP
	message SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster
	waitmessage
	waitfanfare
	setflag FLAG_GOT_HITMON_FROM_DOJO
	msgbox gText_NicknameThisPokemon, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, SaffronCity_Dojo_EventScript_EndGiveMon
	call Common_EventScript_GetGiftMonPartySlot
	call Common_EventScript_NameReceivedPartyMon
	goto SaffronCity_Dojo_EventScript_EndGiveMon
	end

SaffronCity_Dojo_EventScript_ReceivedHitmonPC::
	removeobject VAR_LAST_TALKED
	bufferspeciesname STR_VAR_1, VAR_TEMP_1
	playfanfare MUS_LEVEL_UP
	message SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster
	waitmessage
	waitfanfare
	setflag FLAG_GOT_HITMON_FROM_DOJO
	msgbox gText_NicknameThisPokemon, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, SaffronCity_Dojo_EventScript_TransferredHitmonToPC
	call Common_EventScript_NameReceivedBoxMon
	goto SaffronCity_Dojo_EventScript_TransferredHitmonToPC
	end

SaffronCity_Dojo_EventScript_TransferredHitmonToPC::
	call Common_EventScript_TransferredToPC
	goto SaffronCity_Dojo_EventScript_EndGiveMon
	end

SaffronCity_Dojo_EventScript_EndGiveMon::
	release
	end

SaffronCity_Dojo_EventScript_Statue::
	msgbox SaffronCity_Dojo_Text_FightingDojo, MSGBOX_SIGN
	end

SaffronCity_Dojo_EventScript_LeftScroll::
	msgbox SaffronCity_Dojo_Text_EnemiesOnEverySide, MSGBOX_SIGN
	end

SaffronCity_Dojo_EventScript_RightScroll::
	msgbox SaffronCity_Dojo_Text_GoesAroundComesAround, MSGBOX_SIGN
	end

SaffronCity_Dojo_EventScript_Hitoshi::
	trainerbattle_single TRAINER_BLACK_BELT_HITOSHI, SaffronCity_Dojo_Text_HitoshiIntro, SaffronCity_Dojo_Text_HitoshiDefeat
	msgbox SaffronCity_Dojo_Text_HitoshiPostBattle, MSGBOX_AUTOCLOSE
	end

SaffronCity_Dojo_EventScript_Hideki::
	trainerbattle_single TRAINER_BLACK_BELT_HIDEKI, SaffronCity_Dojo_Text_HidekiIntro, SaffronCity_Dojo_Text_HidekiDefeat
	msgbox SaffronCity_Dojo_Text_HidekiPostBattle, MSGBOX_AUTOCLOSE
	end

SaffronCity_Dojo_EventScript_Aaron::
	trainerbattle_single TRAINER_BLACK_BELT_AARON, SaffronCity_Dojo_Text_AaronIntro, SaffronCity_Dojo_Text_AaronDefeat
	msgbox SaffronCity_Dojo_Text_AaronPostBattle, MSGBOX_AUTOCLOSE
	end

SaffronCity_Dojo_EventScript_Mike::
	trainerbattle_single TRAINER_BLACK_BELT_MIKE, SaffronCity_Dojo_Text_MikeIntro, SaffronCity_Dojo_Text_MikeDefeat
	msgbox SaffronCity_Dojo_Text_MikePostBattle, MSGBOX_AUTOCLOSE
	end

SaffronCity_Dojo_EventScript_MasterKoichi::
	trainerbattle_single TRAINER_BLACK_BELT_KOICHI, SaffronCity_Dojo_Text_MasterKoichiIntro, SaffronCity_Dojo_Text_MasterKoichiDefeat, SaffronCity_Dojo_EventScript_DefeatedMasterKoichi
	goto_if_set FLAG_GOT_HITMON_FROM_DOJO, SaffronCity_Dojo_EventScript_MasterKoichiAlreadyGotHitmon
	msgbox SaffronCity_Dojo_Text_ChoosePrizedFightingMon, MSGBOX_AUTOCLOSE
	end

SaffronCity_Dojo_EventScript_MasterKoichiAlreadyGotHitmon::
	msgbox SaffronCity_Dojo_Text_StayAndTrainWithUs
	release
	end

SaffronCity_Dojo_EventScript_DefeatedMasterKoichi::
	setvar VAR_MAP_SCENE_SAFFRON_CITY_DOJO, 1
	release
	end

SaffronCity_Dojo_Text_MasterKoichiIntro::
	.string "Willkommen!\p"
	.string "Ich bin der Karate-meister!\n"
	.string "Ich leite diese Pokémon-Arena!\p"
	.string "Du forderst mich heraus? Also gut!\n"
	.string "Ich kenne keine Gnade!\p"
	.string "Los!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
	.string "Arrgh!\n"
	.string "Ich wurde geschlagen!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
	.string "Ich bin deiner Gnade unwürdig!\p"
	.string "Trotzdem flehe ich dich an, unser\n"
	.string "Emblem nicht als Trophäe\l"
	.string "mitzunehmen!\p"
	.string "Zum Ersatz gebe ich dir ein\n"
	.string "preisgekröntes Kampf-Pokémon!\p"
	.string "Wähle eines von beiden aus!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
	.string "Hi!\p"
	.string "Bleibe doch hier und trainiere\n"
	.string "Karate mit uns!$"

SaffronCity_Dojo_Text_MikeIntro::
	.string "Stopp!\n"
	.string "Ziehe deine Schuhe aus!$"

SaffronCity_Dojo_Text_MikeDefeat::
	.string "Ich gebe auf!$"

SaffronCity_Dojo_Text_MikePostBattle::
	.string "Warte nur, bis du unseren Meister\n"
	.string "triffst!\p"
	.string "Verglichen mit ihm bin ich ein\n"
	.string "kleiner Fisch!$"

SaffronCity_Dojo_Text_HidekiIntro::
	.string "Du sollst sehr gut sein!\n"
	.string "Beweise es mir!$"

SaffronCity_Dojo_Text_HidekiDefeat::
	.string "Schiedsrichter!\n"
	.string "1 Punkt!$"

SaffronCity_Dojo_Text_HidekiPostBattle::
	.string "Unser Meister ist ein echter Profi!$"

SaffronCity_Dojo_Text_AaronIntro::
	.string "Keine Herausforderung ist mir zu\n"
	.string "hart!\p"
	.string "Ich zertrümmere Steine mit bloßen\n"
	.string "Händen!$"

SaffronCity_Dojo_Text_AaronDefeat::
	.string "Autsch!\n"
	.string "Ich habe eine Prellung!$"

SaffronCity_Dojo_Text_AaronPostBattle::
	.string "Die einzige Sache, vor der wir uns\n"
	.string "fürchten, ist Psychokinese!$"

SaffronCity_Dojo_Text_HitoshiIntro::
	.string "Haii-ia!\p"
	.string "Unbefugten ist der Zutritt zu\n"
	.string "unserem Kampf-dojo verboten!$"

SaffronCity_Dojo_Text_HitoshiDefeat::
	.string "Uff!\n"
	.string "Ich gebe auf!$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
	.string "Die allerbesten Kämpfer des Landes\n"
	.string "trainieren hier!$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
	.string "Möchtest du Kicklee, das\n"
	.string "trittstarke Pokémon?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
	.string "{PLAYER} erhält\n"
	.string "{STR_VAR_1}.$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
	.string "Möchtest du Nockchan, den Meister\n"
	.string "des Boxkampfs?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
	.string "{PLAYER}は　カラテ　だいおう　から\n"
	.string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
	.string "Er sagte ein Pokémon...$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
	.string "Überall Gegner!$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
	.string "Wie die Saat, so die Ernte!$"

SaffronCity_Dojo_Text_FightingDojo::
	.string "Kampfarena$"

