SafariZone_Center_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_Center_RestHouse_EventScript_Sara::
	msgbox SafariZone_Center_Text_WhereDidErikGo, MSGBOX_NPC
	end

SafariZone_Center_RestHouse_EventScript_Scientist::
	msgbox SafariZone_Center_Text_CatchingMonsAsGifts, MSGBOX_NPC
	end

SafariZone_Center_Text_WhereDidErikGo::
	.string "SARAH: Wo ist bloß mein Freund\n"
	.string "ERIK hingegangen?$"

SafariZone_Center_Text_CatchingMonsAsGifts::
	.string "Die POKéMON von unserem BOSS\n"
	.string "werden dich fertig machen!$"

