SafariZone_Center_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_Center_RestHouse_EventScript_Sara::
	msgbox SafariZone_Center_Text_WhereDidErikGo, MSGBOX_NPC
	end

SafariZone_Center_RestHouse_EventScript_Scientist::
	msgbox SafariZone_Center_Text_CatchingMonsAsGifts, MSGBOX_NPC
	end

SafariZone_Center_Text_WhereDidErikGo::
	.string "Sarah: Wo ist bloß mein Freund\n"
	.string "Erik hingegangen?$"

SafariZone_Center_Text_CatchingMonsAsGifts::
	.string "Die Pokémon von unserem Boss\n"
	.string "werden dich fertig machen!$"

