@ Flavor text for interacting with various background objects

EventScript_Bookshelf::
	msgbox Text_Bookshelf, MSGBOX_SIGN
	end

EventScript_PokeMartShelf::
	msgbox Text_PokeMartShelf, MSGBOX_SIGN
	end

EventScript_Food::
	msgbox Text_Food, MSGBOX_SIGN
	end

EventScript_VideoGame::
	msgbox Text_VideoGame, MSGBOX_SIGN
	end

EventScript_Computer::
	msgbox Text_Computer, MSGBOX_SIGN
	end

EventScript_ImpressiveMachine::
	msgbox Text_ImpressiveMachine, MSGBOX_SIGN
	end

EventScript_Blueprints::
	msgbox Text_Blueprints, MSGBOX_SIGN
	end

EventScript_Burglary::
	msgbox Text_Burglary, MSGBOX_SIGN
	end

EventScript_PlayerFacingTVScreen::
	msgbox Text_PlayerFacingTVScreen, MSGBOX_SIGN
	end

EventScript_Cabinet::
	msgbox Text_DishesPlatesNeatlyLinedUp, MSGBOX_SIGN
	end

EventScript_Kitchen::
	msgbox Text_Kitchen, MSGBOX_SIGN
	end

EventScript_Dresser::
	msgbox Text_Dresser, MSGBOX_SIGN
	end

EventScript_Snacks::
	msgbox Text_Snacks, MSGBOX_SIGN
	end

EventScript_Painting::
	msgbox Text_Painting, MSGBOX_SIGN
	end

EventScript_PowerPlantMachine::
	msgbox Text_PowerPlantMachine, MSGBOX_SIGN
	end

EventScript_Telephone::
	msgbox Text_Telephone, MSGBOX_SIGN
	end

EventScript_AdvertisingPoster::
	msgbox Text_AdvertisingPoster, MSGBOX_SIGN
	end

EventScript_TastyFood::
	msgbox Text_TastyFood, MSGBOX_SIGN
	end

EventScript_TrashBin::
	msgbox Text_TrashBin, MSGBOX_SIGN
	end

EventScript_Cup::
	msgbox Text_Cup, MSGBOX_SIGN
	end

EventScript_PolishedWindow::
	msgbox Text_PolishedWindow, MSGBOX_SIGN
	end

EventScript_BeautifulSkyWindow::
	msgbox Text_BeautifulSkyWindow, MSGBOX_SIGN
	end

EventScript_BlinkingLights::
	msgbox Text_BlinkingLights, MSGBOX_SIGN
	end

EventScript_NeatlyLinedUpTools::
	msgbox Text_NeatlyLinedUpTools, MSGBOX_SIGN
	end

EventScript_PokemartSign::
	msgbox Text_PokemartSign, MSGBOX_SIGN
	end

EventScript_PokecenterSign::
	msgbox Text_PokecenterSign, MSGBOX_SIGN
	end

EventScript_Indigo_UltimateGoal::
	msgbox Text_Indigo_UltimateGoal, MSGBOX_SIGN
	end

EventScript_Indigo_HighestAuthority::
	msgbox Text_Indigo_HighestAuthority, MSGBOX_SIGN
	end

@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "Vollgestopft mit Büchern\n"
	.string "über POKéMON.$"

Text_NothingButPokemonBooks::
	.string "Nichts als Bücher\n"
	.string "über POKéMON$"

Text_ATownMap::
	.string "Eine Karte.$"

Text_PokeMartShelf::
	.string "Wow!\n"
	.string "Allerlei POKéMON-Kram!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Gerichte und Teller sind\n"
	.string "sauber in einer Reihe.$"

Text_Kitchen::
	.string "Es riecht wunderbar!\n"
	.string "Jemand hat hier gekocht.$"

Text_Dresser::
	.string "Ein solider Schrank.\n"
	.string "Hat Platz für viele Dinge.$"

Text_Snacks::
	.string "Hier ist ein Haufen Snacks.$"

Text_PokemartSign::
	.string "All deine Itemwünsche erfüllt!\n"
	.string "POKéMON MARKT$"

Text_PokecenterSign::
	.string "Heile deine POKéMON!\n"
	.string "POKéMONCENTER$"

Text_Indigo_UltimateGoal::
	.string "INDIGO PLATEAU\p"
	.string "Das ultimative Ziel der Trainer!\n"
	.string "POKéMON LIGA HQ$"

Text_Indigo_HighestAuthority::
	.string "INDIGO PLATEAU\p"
	.string "Die höchste POKéMON Autorität!\n"
	.string "POKéMON LIGA HQ$"

Text_Food::
	.string "Hier gibt es bestimmt jede Menge\n"
	.string "leckere Sachen zu essen.$"

Text_Blueprints::
	.string "Das scheint eine Art Bauplan\n"
	.string "zu sein.\p"
	.string "Er ist voller Skizzen und Text.$"

Text_Painting::
	.string "Es ist ein schönes Bild eines\n"
	.string "POKéMON.\p"
	.string "Es sieht sehr zufrieden aus.$"

Text_PowerPlantMachine::
	.string "Was diese Maschine wohl macht?\n"
	.string "Ich lasse sie lieber in Ruhe!$"

Text_Telephone::
	.string "Es ist ein Telefon.\n"
	.string "Ich benutze es lieber nicht.$"

Text_Computer::
	.string "Nur komplizierte Wörter und\n"
	.string "Zahlen ohne jeden Sinn…$"

Text_AdvertisingPoster::
	.string "Ein Werbeplakat für allerlei\n"
	.string "verschiedene Produkte.$"

Text_TastyFood::
	.string "Oh, das riecht köstlich!\n"
	.string "Da knurrt gleich der Magen!$"

Text_TrashBin::
	.string "In diesem Mülleimer…\n"
	.string "……\p"
	.string "ist überhaupt nichts drin!$"

Text_Cup::
	.string "Es ist eine Tasse mit einem\n"
	.string "POKéMON-Zeichen darauf.$"

Text_PolishedWindow::
	.string "Das Fenster ist blitzblank\n"
	.string "geputzt.$"

Text_BeautifulSkyWindow::
	.string "Draußen vor dem Fenster…\p"
	.string "Der Himmel sieht einfach\n"
	.string "wunderschön aus.$"

Text_BlinkingLights::
	.string "Lichter in vielen Farben\n"
	.string "blinken ständig.$"

Text_NeatlyLinedUpTools::
	.string "Alle möglichen Werkzeuge\n"
	.string "sind ordentlich aufgereiht.$"

Text_ImpressiveMachine::
	.string "Das ist wohl eine Maschine.\n"
	.string "Sie wirkt ziemlich beeindruckend.$"

Text_VideoGame::
	.string "Das neueste Videospiel!\n"
	.string "Es sieht richtig spaßig aus!$"

Text_Burglary::
	.string "Hier sind deutliche Spuren\n"
	.string "eines Einbruchs zu sehen…$"

Text_PlayerFacingTVScreen::
	.string "Im Fernsehen läuft ein POKéMON!\n"
	.string "Es scheint viel Spaß zu haben.$"
