ThreeIsland_House4_Frlg_MapScripts::
	.byte 0

ThreeIsland_House4_EventScript_BaldingMan::
	msgbox ThreeIsland_House4_Text_GhostsInBerryForest, MSGBOX_NPC
	end

ThreeIsland_House4_EventScript_LittleBoy::
	msgbox ThreeIsland_House4_Text_PapaKeepsLyingToMe, MSGBOX_NPC
	end

ThreeIsland_House4_Text_GhostsInBerryForest::
	.string "Wenn du den ZERSCHNEIDER einsetzt,\n"
	.string "kannst du kleine Bäume fällen.\p"
	.string "Probiere es doch bei den Bäumen\n"
	.string "um ORANIA CITY aus!$"

ThreeIsland_House4_Text_PapaKeepsLyingToMe::
	.string "Oh, nein! Du hast keinen Platz für\n"
	.string "weitere Items!$"

