ThreeIsland_House4_Frlg_MapScripts::
	.byte 0

ThreeIsland_House4_EventScript_BaldingMan::
	msgbox ThreeIsland_House4_Text_GhostsInBerryForest, MSGBOX_NPC
	end

ThreeIsland_House4_EventScript_LittleBoy::
	msgbox ThreeIsland_House4_Text_PapaKeepsLyingToMe, MSGBOX_NPC
	end

ThreeIsland_House4_Text_GhostsInBerryForest::
	.string "Du solltest nie alleine in den\n"
	.string "Beerenforst gehen!\p"
	.string "Warum?\n"
	.string "Es spukt dort!$"

ThreeIsland_House4_Text_PapaKeepsLyingToMe::
	.string "Papa lügt mich ständig an und\n"
	.string "lässt mich nicht hinaus zum\l"
	.string "Spielen!$"

