CeruleanCity_Gym_Frlg_MapScripts::
	.byte 0

CeruleanCity_Gym_EventScript_Misty::
	famechecker FAMECHECKER_MISTY, FCPICKSTATE_COLORED, UpdatePickStateFromSpecialVar8005
	trainerbattle_single TRAINER_LEADER_MISTY, CeruleanCity_Gym_Text_MistyIntro, CeruleanCity_Gym_Text_MistyDefeat, CeruleanCity_Gym_EventScript_MistyDefeated, NO_MUSIC
	goto_if_unset FLAG_GOT_TM03_FROM_MISTY, CeruleanCity_Gym_EventScript_GiveTM03
	msgbox CeruleanCity_Gym_Text_ExplainTM03
	release
	end

CeruleanCity_Gym_EventScript_MistyDefeated::
	famechecker FAMECHECKER_MISTY, 1
	setflag FLAG_DEFEATED_MISTY
	setflag FLAG_BADGE02_GET
	setrespawn HEAL_LOCATION_CERULEAN_CITY
	set_gym_trainers_frlg 2
	goto CeruleanCity_Gym_EventScript_GiveTM03
	end

CeruleanCity_Gym_EventScript_GiveTM03::
	msgbox CeruleanCity_Gym_Text_ExplainCascadeBadge
	checkitemspace ITEM_TM03
	goto_if_eq VAR_RESULT, FALSE, CeruleanCity_Gym_EventScript_NoRoomForTM03
	giveitem_msg CeruleanCity_Gym_Text_ReceivedTM03FromMisty, ITEM_TM03
	setflag FLAG_GOT_TM03_FROM_MISTY
	msgbox CeruleanCity_Gym_Text_ExplainTM03
	release
	end

CeruleanCity_Gym_EventScript_NoRoomForTM03::
	msgbox CeruleanCity_Gym_Text_BetterMakeRoomForThis
	release
	end

CeruleanCity_Gym_EventScript_Diana::
	trainerbattle_single TRAINER_PICNICKER_DIANA, CeruleanCity_Gym_Text_DianaIntro, CeruleanCity_Gym_Text_DianaDefeat
	msgbox CeruleanCity_Gym_Text_DianaPostBattle, MSGBOX_AUTOCLOSE
	end

CeruleanCity_Gym_EventScript_Luis::
	trainerbattle_single TRAINER_SWIMMER_MALE_LUIS, CeruleanCity_Gym_Text_LuisIntro, CeruleanCity_Gym_Text_LuisDefeat
	famechecker FAMECHECKER_MISTY, 2
	msgbox CeruleanCity_Gym_Text_LuisPostBattle, MSGBOX_AUTOCLOSE
	end

CeruleanCity_Gym_EventScript_GymGuy::
	lock
	faceplayer
	goto_if_set FLAG_DEFEATED_MISTY, CeruleanCity_Gym_EventScript_GymGuyPostVictory
	msgbox CeruleanCity_Gym_Text_GymGuyAdvice
	release
	end

CeruleanCity_Gym_EventScript_GymGuyPostVictory::
	msgbox CeruleanCity_Gym_Text_WeMakePrettyGoodTeam
	release
	end

CeruleanCity_Gym_EventScript_GymStatue::
	lockall
	goto_if_set FLAG_BADGE02_GET, CeruleanCity_Gym_EventScript_GymStatuePostVictory
	msgbox CeruleanCity_Gym_Text_GymStatue
	releaseall
	end

CeruleanCity_Gym_EventScript_GymStatuePostVictory::
	msgbox CeruleanCity_Gym_Text_GymStatuePlayerWon
	releaseall
	end

CeruleanCity_Gym_Text_MistyIntro::
	.string "{PLAY_BGM}{MUS_RG_ENCOUNTER_GYM_LEADER}Du musst neu sein, ich habe dich\n"
	.string "noch nie gesehen!\p"
	.string "Wenn ein Trainer zum Profi werden\n"
	.string "möchte, muss er sich eine Pokémon-\l"
	.string "Taktik erarbeiten!\p"
	.string "Auf welche Weise fängst du deine\n"
	.string "Pokémon?\p"
	.string "Meine Strategie basiert auf dem\n"
	.string "gnadenlosen Offensiv-Einsatz von\l"
	.string "Wasser-pokémon!{PLAY_BGM}?À$"

CeruleanCity_Gym_Text_ExplainTM03::
	.string "TM03 ist die AQUAWELLE!\p"
	.string "WASSER-POKéMON können diese\n"
	.string "Attacke erlernen!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
	.string "Der QUELLORDEN lässt alle POKéMON\n"
	.string "bis Level 30 deinen Befehlen\l"
	.string "gehorchen!\p"
	.string "Sogar Außenseiter gehorchen dir!\p"
	.string "Deine POKéMON können den\n"
	.string "ZERSCHNEIDER nun jederzeit \l"
	.string "einsetzen!\p"
	.string "Du kannst kleine Büsche zerhacken\n"
	.string "und so neue Wege freilegen!\p"
	.string "Zu guter Letzt schenke ich dir\n"
	.string "noch meine Lieblings-TM!$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
	.string "{PLAYER} received TM03\n"
	.string "from MISTY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
	.string "Du hast momentan keinen Platz für\n"
	.string "mein Geschenk!$"

CeruleanCity_Gym_Text_MistyDefeat::
	.string "Wow!\n"
	.string "Du bist sehr gut!\p"
	.string "Alles klar!\p"
	.string "Ich überlasse dir den Quellorden\n"
	.string "als Zeichen deines Triumphes!$"

CeruleanCity_Gym_Text_DianaIntro::
	.string "Wie? Du?\n"
	.string "Ich bin schon zu gut für dich!\p"
	.string "Misty muss sich nicht mit dir\n"
	.string "abgeben!$"

CeruleanCity_Gym_Text_DianaDefeat::
	.string "Ich bin überwältigt!$"

CeruleanCity_Gym_Text_DianaPostBattle::
	.string "Du musst dich anderen Trainern\n"
	.string "stellen, um herauszufinden, wie gut\l"
	.string "du bist.$"

CeruleanCity_Gym_Text_LuisIntro::
	.string "Platsch!\p"
	.string "Ich bin dein erster Gegner!\n"
	.string "Es geht los!$"

CeruleanCity_Gym_Text_LuisDefeat::
	.string "Das darf nicht wahr sein!$"

CeruleanCity_Gym_Text_LuisPostBattle::
	.string "MISTY verbessert stets ihr Können!\p"
	.string "Jemand wie du hat keine Chance,\n"
	.string "sie zu besiegen!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
	.string "Heh!\n"
	.string "Warte, du Champion in spe!\p"
	.string "Ich habe einen Tipp für dich!\p"
	.string "MISTY, die ARENALEITERIN, kämpft\n"
	.string "mit WASSER-POKéMON!\p"
	.string "Du kannst ihnen das Wasser mit\n"
	.string "PFLANZEN-POKéMON entziehen!\p"
	.string "ELEKTRO-POKéMON dürften sich auch\n"
	.string "als nützlich erweisen!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
	.string "Du hast MISTY besiegt! Habe ich es\n"
	.string "nicht gesagt?\p"
	.string "Glaub mir, wir beide bilden ein\n"
	.string "sehr gutes Team!$"

CeruleanCity_Gym_Text_GymStatue::
	.string "AZURIA POKéMON-ARENA\n"
	.string "LEITUNG: MISTY\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
	.string "AZURIA POKéMON-ARENA\n"
	.string "LEITUNG: MISTY\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}, {PLAYER}$"

