PewterCity_Museum_2F_Frlg_MapScripts::
	.byte 0

PewterCity_Museum_2F_EventScript_Man::
	msgbox PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_OldMan::
	msgbox PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_Scientist::
	msgbox PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_LittleGirl::
	msgbox PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_BaldingMan::
	msgbox PewterCity_Museum_1F_Text_PikachuSoonIPromise, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_SpaceShuttle::
	msgbox PewterCity_Museum_1F_Text_SpaceShuttle, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_MoonStone::
	msgbox PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon, MSGBOX_SIGN
	end

Text_SeismicTossTeach::
	.string "Das Geheimnis des Raumes…\n"
	.string "Die Rätsel des Planeten…\p"
	.string "Es gibt so vieles, worüber wir so\n"
	.string "wenig wissen!\p"
	.string "Aber was treibt uns an, noch mehr\n"
	.string "zu hinterfragen und nicht das\l"
	.string "Handtuch zu werfen?\l"
	.string "Der einzige erlaubte Wurf…\p"
	.string "Wie wäre es mit Geowurf?\n"
	.string "Soll ich das einem Pokémon\l"
	.string "beibringen?$"

Text_SeismicTossDeclined::
	.string "So ist das also!\n"
	.string "Ich bin sicher, du kommst zurück!$"

Text_SeismicTossWhichMon::
	.string "Welches Pokémon soll die\n"
	.string "Attacke erlernen?$"

Text_SeismicTossTaught::
	.string "Ich hoffe, du wirfst nicht das\n"
	.string "Handtuch! Mach weiter so!$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
	.string "Mondstein?\p"
	.string "Was ist daran so einzigartig?$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
	.string "Der 20. Juli 1969!\p"
	.string "Die erste Mondlandung!\p"
	.string "Für die Fernsehübertragung hatte\n"
	.string "ich extra einen Farbfernseher\l"
	.string "gekauft!$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
	.string "Momentan haben wir eine\n"
	.string "Raumfahrt-Ausstellung.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
	.string "Ich hätte gerne ein Pikachu!\n"
	.string "Es ist so furchtbar süß!\p"
	.string "Mein Papa soll mir eines fangen!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
	.string "Ja, ein Pikachu!\n"
	.string "Ich verspreche, ich fange eins!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
	.string "Space Shuttle$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
	.string "Auf dem Mondberg gefundenes\n"
	.string "Meteoritengestein “Mondstein?”$"

