SSAnne_2F_Room3_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room3_EventScript_Gentleman::
	msgbox SSAnne_2F_Room3_Text_SeenMonsFerryPeople, MSGBOX_NPC
	end

SSAnne_2F_Room3_EventScript_OldMan::
	msgbox SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown, MSGBOX_NPC
	end

SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
	.string "Ich habe schon Leute auf Pokémon\n"
	.string "übers Wasser gleiten sehen!$"

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
	.string "Pokémon können Büsche mit dem\n"
	.string "Zerschneider klein hacken.\p"
	.string "Aber vergiss nicht, Zerschneider\n"
	.string "ist eine VM!\p"
	.string "Wer sie einmal gelernt hat, kann\n"
	.string "sie nicht so einfach vergessen!$"

