SafariZone_North_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_North_RestHouse_EventScript_Fisher::
	msgbox SafariZone_East_Text_PrizeInDeepestPartOfSafariZone, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Scientist::
	msgbox SafariZone_East_Text_KeepAnyItemFoundOnSafari, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Gentleman::
	msgbox SafariZone_East_Text_MyEeveeEvolvedIntoFlareon, MSGBOX_NPC
	end

SafariZone_East_Text_KeepAnyItemFoundOnSafari::
	.string "Die komischen Muster auf dem\n"
	.string "Boden…\p"
	.string "Sie ähneln den Mustern auf der\n"
	.string "Kleidung meines Großvaters.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
	.string "Beim nächsten Mal nehme ich\n"
	.string "meinen kleinen Bruder mit.$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
	.string "Ihr Stadtmenschen kommt immer so\n"
	.string "hip daher mit euren trendy Hüten…\p"
	.string "Wie wärs, wenn du ihn mir gibst?$"

