SafariZone_North_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_North_RestHouse_EventScript_Fisher::
	msgbox SafariZone_East_Text_PrizeInDeepestPartOfSafariZone, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Scientist::
	msgbox SafariZone_East_Text_KeepAnyItemFoundOnSafari, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Gentleman::
	msgbox SafariZone_East_Text_MyEeveeEvolvedIntoFlareon, MSGBOX_NPC
	end

SafariZone_East_Text_KeepAnyItemFoundOnSafari::
	.string "Alle Items, die du findest, gehören\n"
	.string "dir!\p"
	.string "Aber dir wird die Zeit davonlaufen,\n"
	.string "wenn du alle auf einmal einsammeln\l"
	.string "möchtest!$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
	.string "Gehe in die Safari-Zone! Du kannst\n"
	.string "dort einen Preis gewinnen!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
	.string "Mein Evoli hat sich zu Flamara\n"
	.string "entwickelt!\p"
	.string "Aber bei einem Freund hat sich\n"
	.string "Evoli zu Aquana entwickelt!$"

