ViridianCity_Mart_hns_MapScripts::
	.byte 0

ViridianCity_Mart_EventScript_Lass::
	msgbox ViridianMart_Text_Lass, MSGBOX_NPC
	end

ViridianCity_Mart_EventScript_Cooltrainer::
	msgbox ViridianMart_Text_CooltrainerM, MSGBOX_NPC
	end

ViridianMart_Text_Lass:
	.string "Der Arenaleiter dieser Stadt\n"
	.string "ist extrem cool!$"

ViridianMart_Text_CooltrainerM:
	.string "Warst du schon auf der Zinnoberinsel?\p"
	.string "Sie liegt tief im Süden.$"

