Route2_ViridianForest_SouthEntrance_Frlg_MapScripts::
	.byte 0

Route2_ViridianForest_SouthEntrance_EventScript_Woman1::
	msgbox Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze, MSGBOX_NPC
	end

Route2_ViridianForest_SouthEntrance_EventScript_Woman2::
	msgbox Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite, MSGBOX_NPC
	end

Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze::
	.string "Du gehst in den Vertania-Wald?\n"
	.string "Sei auf der Hut, dort verläuft man\l"
	.string "sich leicht!$"

Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite::
	.string "Hast du schon ein Rattfratz\n"
	.string "gefangen?\p"
	.string "Es ist klein, aber sein Biss ist\n"
	.string "heftig!$"

