Akala_House_hns_MapScripts::
	.byte 0


Alola_Akala_House_OldWoman::
	lock
	faceplayer
	msgbox Alola_Akala_House_OldWoman_Text_0, MSGBOX_AUTOCLOSE
	release
	end


Alola_Akala_House_OldWoman_Text_0:
	.string "Ich sage meinem Mann jeden Tag, er\n"
	.string "soll die Natu nicht füttern, aber\l"
	.string "er hört einfach nicht!\p"
	.string "Eines Tages bringt er mir noch so\n"
	.string "ein Ding mit nach Hause, das weiß\l"
	.string "ich genau!$"
