@ Handled by data/scripts/day_care.inc

Route5_PokemonDayCare_Frlg_MapScripts::
	.byte 0

Route5_PokemonDayCare_Text_WantMeToRaiseMon::
	.string "Ich leite diese Pension.\p"
	.string "Soll ich eines deiner Pokémon\n"
	.string "großziehen?$"

Route5_PokemonDayCare_Text_ComeAgain::
	.string "Dann bis später.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
	.string "Welches Pokémon soll hier bleiben?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
	.string "Ich verstehe.\n"
	.string "Komm mich wieder besuchen.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
	.string "O.K., ich kümmere mich eine Weile\n"
	.string "um {STR_VAR_1}.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
	.string "Komm später wieder vorbei, um es\n"
	.string "abzuholen.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
	.string "Du bist schon wieder zurück?\p"
	.string "{STR_VAR_1} sollte noch ein\n"
	.string "bisschen bei mir bleiben.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
	.string "Bevor du dein Pokémon wieder\n"
	.string "mitnimmst, bekomme ich noch\l"
	.string "{STR_VAR_2}¥ von dir!$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
	.string "Vielen Dank!\n"
	.string "Hier ist dein Pokémon!$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
	.string "{PLAYER} erhält\n"
	.string "{STR_VAR_1} zurück!$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
	.string "Du hast nur ein Pokémon dabei!$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
	.string "Wenn du mir dieses Pokémon\n"
	.string "überlässt, womit willst du kämpfen?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
	.string "{STR_VAR_1} hat sich toll \n"
	.string "entwickelt!\p"
	.string "Es ist um {STR_VAR_2} Level gestiegen!\p"
	.string "Das habe ich gut gemacht, oder?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
	.string "Du kannst kein weiteres Pokémon\n"
	.string "mehr tragen!$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
	.string "Du hast nicht genug Geld…$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
	.string "きみの\n"
	.string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
	.string "わるいけど　ひでんのわざを　もった\n"
	.string "ポケモンは　あずかれないなぁ$"
