Melemele_House_6_hns_MapScripts::
	.byte 0


Melemele_House6_Hiker::
	lock
	faceplayer
	msgbox Melemele_House6_Hiker_Text_0, MSGBOX_AUTOCLOSE
	release
	end


Melemele_House6_GameboyKid::
	lock
	faceplayer
	msgbox Melemele_House6_GameboyKid_Text_0, MSGBOX_AUTOCLOSE
	release
	end


Melemele_House6_Hiker_Text_0:
	.string "Ich habe dieses Haus gekauft, damit\n"
	.string "mein Sohn und ich die Natur\l"
	.string "erkunden können…\p"
	.string "Aber er will nur an diesem Game Boy\n"
	.string "spielen.$"

Melemele_House6_GameboyKid_Text_0:
	.string "Auf meinem Game Boy habe ich ein\n"
	.string "Spiel, mit dem ich die Alola-Region\l"
	.string "erkunden kann!\p"
	.string "Es ist wie in echt.\p"
	.string "Es heißt Ultra Eclipse,\n"
	.string "von Phantonomy!\p"
	.string "Haha, sieh mal!\n"
	.string "Ich reite ein eisiges UHaFnir!$"


