Route3_Frlg_MapScripts::
	.byte 0

Route3_EventScript_Youngster::
	msgbox Route3_Text_TunnelFromCeruleanTiring, MSGBOX_NPC
	end

Route3_EventScript_RouteSign::
	msgbox Route3_Text_RouteSign, MSGBOX_SIGN
	end

Route3_Text_TunnelFromCeruleanTiring::
	.string "Puh! Ich muss eine Pause machen!\p"
	.string "Der Weg durch den Tunnel aus\n"
	.string "Azuria City ist sehr beschwerlich!$"

Route3_Text_ColtonIntro::
	.string "Heh! Ich kenne dich aus dem\n"
	.string "Vertania-wald!$"

Route3_Text_ColtonDefeat::
	.string "Du hast mich wieder besiegt!$"

Route3_Text_ColtonPostBattle::
	.string "Neben den Pokémon hier im Wald,\n"
	.string "gibt es noch Unmengen anderer\l"
	.string "Pokémon zu entdecken!$"

Route3_Text_BenIntro::
	.string "Überall sind Brennnesseln! Und ich\n"
	.string "trage Shorts! So ein Mist!$"

Route3_Text_BenDefeat::
	.string "Wäre ich heute doch nur daheim\n"
	.string "geblieben!$"

Route3_Text_BenPostBattle::
	.string "Du kannst Pokémon via PC in Boxen\n"
	.string "ablegen.\p"
	.string "Jede Box fasst 30 Pokémon!$"

Route3_Text_JaniceIntro::
	.string "Was starrst du mich so an?$"

Route3_Text_JaniceDefeat::
	.string "Du bist gefährlich!$"

Route3_Text_JanicePostBattle::
	.string "Hör auf, Leute anzustarren!\n"
	.string "Dann musst du auch nicht kämpfen!$"

Route3_Text_GregIntro::
	.string "Bist du auch ein Trainer?\n"
	.string "Lass uns kämpfen!$"

Route3_Text_GregDefeat::
	.string "Mit diesen Pokémon hätte ich auch\n"
	.string "leicht gewonnen!$"

Route3_Text_GregPostBattle::
	.string "Wenn auf dem PC eine Pokémon-Box\n"
	.string "voll ist, wechsle einfach zu einer\l"
	.string "anderen Box!$"

Route3_Text_SallyIntro::
	.string "Warum schaust du mich so fasziniert\n"
	.string "an?$"

Route3_Text_SallyDefeat::
	.string "Bleib immer nett!$"

Route3_Text_SallyPostBattle::
	.string "Vermeide Kämpfe, indem du anderen\n"
	.string "Trainern aus dem Weg gehst!$"

Route3_Text_CalvinIntro::
	.string "Hehe! Ich habe meinem Bruder\n"
	.string "gesagt, er soll Shorts anziehen!$"

Route3_Text_CalvinDefeat::
	.string "Nein!\n"
	.string "Verloren!$"

Route3_Text_CalvinPostBattle::
	.string "Man sollte nicht alles machen, was\n"
	.string "der große Bruder verlangt! Hehe!$"

Route3_Text_JamesIntro::
	.string "Meine neuen Pokémon wollen\n"
	.string "kämpfen!$"

Route3_Text_JamesDefeat::
	.string "Du hast meine Pokémon besiegt!$"

Route3_Text_JamesPostBattle::
	.string "Die Pokémon eines Trainers sind\n"
	.string "stärker als wildlebende!$"

Route3_Text_RobinIntro::
	.string "Huch! Sollen das etwa\n"
	.string "Annäherungsversuche sein?$"

Route3_Text_RobinDefeat::
	.string "Bleib mir fern!$"

Route3_Text_RobinPostBattle::
	.string "Die Route 4 liegt am Fuße des\n"
	.string "Mondberges.$"

Route3_Text_RouteSign::
	.string "Route 3\n"
	.string "Zum Mondberg$"

