OneIsland_TreasureBeach_Frlg_MapScripts::
	.byte 0

OneIsland_TreasureBeach_EventScript_Boy::
	msgbox OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach, MSGBOX_NPC
	end

OneIsland_TreasureBeach_Text_AmaraIntro::
	.string "Sich zurücklehnen und von den\n"
	.string "Wellen treiben lassen…\l"
	.string "Das ist wunderbar!$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
	.string "Ich habe verloren…\n"
	.string "Es tut so weh!$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
	.string "Das Wasser ist hier angenehm\n"
	.string "warm.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
	.string "Die Strömung spült einige brauch-\n"
	.string "bare Dinge hier an den Strand.\p"
	.string "Daher durchkämme ich den Strand\n"
	.string "hier regelmäßig.$"

