Route15_Frlg_MapScripts::
	.byte 0

Route15_EventScript_RouteSign::
	msgbox Route15_Text_RouteSign, MSGBOX_SIGN
	end

Route15_Text_KindraIntro::
	.string "Wunderbar! Dann kann ich gleich\n"
	.string "ausprobieren, wie gut die Pokémon\l"
	.string "sind, die ich getauscht habe!$"

Route15_Text_KindraDefeat::
	.string "Nicht gut genug!$"

Route15_Text_KindraPostBattle::
	.string "Man kann den Spitznamen eines\n"
	.string "Pokémon, das man getauscht hat,\l"
	.string "nicht ändern.\p"
	.string "Nur der Original-Trainer kann den\n"
	.string "Namen verändern.$"

Route15_Text_BeckyIntro::
	.string "Du siehst lammfromm aus!\n"
	.string "Dann habe ich eine Chance!$"

Route15_Text_BeckyDefeat::
	.string "Du bist ein Wolf im Schafspelz!$"

Route15_Text_BeckyPostBattle::
	.string "Ich habe Angst vor Bikern, sie\n"
	.string "sind so hässlich und brutal!$"

Route15_Text_EdwinIntro::
	.string "Wenn ich pfeife, kann ich Vogel-\n"
	.string "Pokémon herbeirufen!$"

Route15_Text_EdwinDefeat::
	.string "Au!\n"
	.string "Das ist tragisch!$"

Route15_Text_EdwinPostBattle::
	.string "Vielleicht bin ich keine\n"
	.string "Kämpfernatur...$"

Route15_Text_ChesterIntro::
	.string "Hmm? Meine Vögel erschaudern?\n"
	.string "Du musst wirklich sehr gut sein!$"

Route15_Text_ChesterDefeat::
	.string "Ich lag also richtig!$"

Route15_Text_ChesterPostBattle::
	.string "Wusstest du, dass manche Attacken,\n"
	.string "wie Erdbeben, keine Wirkung auf\l"
	.string "Vögel haben?$"

Route15_Text_GraceIntro::
	.string "Du bist ein schlaues Kind!$"

Route15_Text_GraceDefeat::
	.string "Und du siehst so süß aus!$"

Route15_Text_GracePostBattle::
	.string "O.k., du hast mich besiegt.\n"
	.string "Es macht mir nichts aus!$"

Route15_Text_OliviaIntro::
	.string "Ich trainiere Pokémon, weil ich\n"
	.string "alleine lebe!$"

Route15_Text_OliviaDefeat::
	.string "So habe ich es mir aber nicht\n"
	.string "vorgestellt!$"

Route15_Text_OliviaPostBattle::
	.string "Ich verbringe zu Hause sehr viel\n"
	.string "Zeit mit meinen Pokémon!$"

Route15_Text_ErnestIntro::
	.string "Heh, Kiddie!\n"
	.string "Lass uns kämpfen!$"

Route15_Text_ErnestDefeat::
	.string "Voll\n"
	.string "erwischt!$"

Route15_Text_ErnestPostBattle::
	.string "Man lebt nur einmal!\n"
	.string "Daher bin ich ein Bandit!\l"
	.string "Das Team Rocket ist cool!$"

Route15_Text_AlexIntro::
	.string "Her mit deinen Moneten! Wenn du\n"
	.string "verlierst, gibst du mir dein Geld!$"

Route15_Text_AlexDefeat::
	.string "Das darf nicht wahr sein!$"

Route15_Text_AlexPostBattle::
	.string "Vergiss die Sache mit dem Geld,\n"
	.string "das war ein Scherz!$"

Route15_Text_CeliaIntro::
	.string "Pokémon zu tauschen, ist wirklich\n"
	.string "cool!$"

Route15_Text_CeliaDefeat::
	.string "Ich sagte tauschen!$"

Route15_Text_CeliaPostBattle::
	.string "Ich tausche mit meinen Freunden\n"
	.string "Pokémon!$"

Route15_Text_YazminIntro::
	.string "Möchtest du mit meinen Pokémon\n"
	.string "spielen?$"

Route15_Text_YazminDefeat::
	.string "Ich war zu ungestüm!$"

Route15_Text_YazminPostBattle::
	.string "Ich muss ein wenig mit schwächeren\n"
	.string "Trainern üben...$"

Route15_Text_RouteSign::
	.string "ROUTE 15\n"
	.string "WESTEN: FUCHSANIA CITY$"

Route15_Text_MyaIntro::
	.string "Eva: Du bist perfekt!\n"
	.string "Hilfst du mir, meinen kleinen\l"
	.string "Bruder zu trainieren?$"

Route15_Text_MyaDefeat::
	.string "Eva: Konzentriere dich, Sergio!\n"
	.string "Achte auf deine Taten!$"

Route15_Text_MyaPostBattle::
	.string "Eva: O.k.! Wir haben es vergeigt!\n"
	.string "Ich füge unserem Trainingsprogramm\l"
	.string "einige Lektionen hinzu.$"

Route15_Text_MyaNotEnoughMons::
	.string "EVA: Möchtest du uns\n"
	.string "herausfordern? Du brauchst\l"
	.string "allerdings zwei POKéMON!$"

Route15_Text_RonIntro::
	.string "Sergio: Meine Schwester bekommt\n"
	.string "Angst, wenn wir verlieren.$"

Route15_Text_RonDefeat::
	.string "Sergio: Oh, nein…\n"
	.string "Es tut mir Leid, Schwesterherz!$"

Route15_Text_RonPostBattle::
	.string "Sergio: Oh, Mist…\n"
	.string "Ich wünschte, ich hätte eine\l"
	.string "nette Schwester…$"

Route15_Text_RonNotEnoughMons::
	.string "SERGIO: Wolltest du gegen meine\n"
	.string "Schwester und mich antreten?\p"
	.string "Dann brauchst du zwei POKéMON!$"
