CeruleanCity_Mart_hns_MapScripts::
	.byte 0

CeruleanCity_Mart_EventScript_Juggler::
	msgbox CeruleanMart_Text_CooltrainerM, MSGBOX_NPC
	end

CeruleanCity_Mart_EventScript_CooltrainerF::
	msgbox CeruleanMart_Text_CooltrainerF, MSGBOX_NPC
	end

CeruleanMart_Text_CooltrainerM:
	.string "Auf dem Weg zum Kap bei Azuria City\n"
	.string "wirst du vielen Trainern begegnen.\p"
	.string "Sie stellen dort das Können anderer\n"
	.string "Trainer auf die Probe.$"

CeruleanMart_Text_CooltrainerF:
	.string "In dieser Stadt ist Misty wahrscheinlich\n"
	.string "die Einzige, die es mit den Trainern\l"
	.string "am Kap von Azuria City aufnehmen kann.$"
