Route10_Frlg_MapScripts::
	.byte 0

Route10_EventScript_Unused::
	end

Route10_EventScript_NorthRockTunnelSign::
	msgbox Route10_Text_RockTunnelDetourToLavender, MSGBOX_SIGN
	end

Route10_EventScript_SouthRockTunnelSign::
	msgbox Route10_Text_RockTunnel, MSGBOX_SIGN
	end

Route10_EventScript_PowerPlantSign::
	msgbox Route10_Text_PowerPlant, MSGBOX_SIGN
	end

Route10_Text_MarkIntro::
	.string "Bist du auch ein Pokémaniac?\n"
	.string "Möchtest du meine Sammlung sehen?$"

Route10_Text_MarkDefeat::
	.string "Na ja, macht nichts!$"

Route10_Text_MarkPostBattle::
	.string "Zu Hause habe ich noch mehr\n"
	.string "seltene Pokémon!$"

Route10_Text_ClarkIntro::
	.string "Ha-ha-ha-ha!$"

Route10_Text_ClarkDefeat::
	.string "Ha-ha!\n"
	.string "Haha-ha-tschi!$"

Route10_Text_ClarkPostBattle::
	.string "Schnief...\n"
	.string "Diese verdammte Erkältung!$"

Route10_Text_HermanIntro::
	.string "Heh du, möchtest du meine Pokémon\n"
	.string "sehen?$"

Route10_Text_HermanDefeat::
	.string "Nein!\n"
	.string "Meine Pokémon!$"

Route10_Text_HermanPostBattle::
	.string "Ich nehme dir übel, dass du mich\n"
	.string "besiegt hast!$"

Route10_Text_HeidiIntro::
	.string "Jedes Mal, wenn ich in einer\n"
	.string "Pokémon-Arena gekämpft habe,\l"
	.string "wurde ich besiegt!$"

Route10_Text_HeidiDefeat::
	.string "Nein!\n"
	.string "Nicht schon wieder!$"

Route10_Text_HeidiPostBattle::
	.string "Ich habe einige PokémaniacS in\n"
	.string "dieser Gegend gesehen.$"

Route10_Text_TrentIntro::
	.string "Ahh! Die Bergluft ist so wunderbar\n"
	.string "erfrischend!$"

Route10_Text_TrentDefeat::
	.string "Ich kann wieder klar denken!$"

Route10_Text_TrentPostBattle::
	.string "Ich habe von Bergluft die Nase\n"
	.string "gestrichen voll!$"

Route10_Text_CarolIntro::
	.string "Ich fühle mich vom vielen Wandern\n"
	.string "erschöpft...$"

Route10_Text_CarolDefeat::
	.string "Ich bin nicht fit!$"

Route10_Text_CarolPostBattle::
	.string "Viele Pokémon in dieser Gegend\n"
	.string "sind grob!\p"
	.string "Ich wünschte, eines wäre rosa mit\n"
	.string "einem Blumenmuster!$"

Route10_Text_RockTunnelDetourToLavender::
	.string "Felstunnel\n"
	.string "Umleitung nach Lavandia$"

Route10_Text_RockTunnel::
	.string "Felstunnel$"

Route10_Text_PowerPlant::
	.string "Kraftwerk$"

