LavenderTown_Mart_hns_MapScripts::
	.byte 0

LavenderTown_Mart_EventScript_Pokefan::
	msgbox LavenderMart_Text_PokefanM, MSGBOX_NPC
	end

LavenderTown_Mart_EventScript_Rocker::
	msgbox LavenderMart_Text_Rocker, MSGBOX_NPC
	end

LavenderMart_Text_PokefanM:
	.string "Es ist unabdingbar, SCHUTZ bei\n"
	.string "sich zu haben,\l"
	.string "wenn man Höhlen erkundet.\p"
	.string "Obwohl ich Höhlen sehr gerne\n"
	.string "erforsche, habe ich noch\l"
	.string "nicht alle erforscht.$"

LavenderMart_Text_Rocker:
	.string "Ich habe von einem Kunstschmied\p"
	.string "gehört, der maßgefertigte\n"
	.string "Pokébälle in AZALEA\l"
	.string "in JOHTO herstellt.\p"
	.string "Ich wünschte, ich hätte auch\n"
	.string "welche.$"
