FuchsiaCity_SafariZone_Office_Frlg_MapScripts::
	.byte 0

FuchsiaCity_SafariZone_Office_EventScript_Worker1::
	msgbox FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker2::
	msgbox FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker3::
	msgbox FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker4::
	msgbox FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
	.string "Der Wärter trägt den Spitznamen\n"
	.string "Flegmon.\p"
	.string "Er und Flegmon ähneln sich sehr!$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
	.string "Flegmon weiß eine Menge über\n"
	.string "Pokémon!\p"
	.string "Er besitzt sogar einige Fossilien\n"
	.string "ausgestorbener Urzeit-Pokémon!$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
	.string "Flegmon war hier, aber ich habe\n"
	.string "ihn nicht verstehen können!\p"
	.string "Ich glaube, er hat keine Zähne\n"
	.string "mehr!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
	.string "Flegmon hält zur Zeit eine\n"
	.string "Werbekampagne.\p"
	.string "Erreiche die abgelegenste\n"
	.string "Stelle in der Safari-Zone.\p"
	.string "Wenn du das schaffst, erhältst\n"
	.string "du einen praktischen Preis!$"

