FuchsiaCity_SafariZone_Office_Frlg_MapScripts::
	.byte 0

FuchsiaCity_SafariZone_Office_EventScript_Worker1::
	msgbox FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker2::
	msgbox FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker3::
	msgbox FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker4::
	msgbox FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
	.string "Der Wärter trägt den Spitznamen\n"
	.string "Flegmon.\p"
	.string "Er und Flegmon ähneln sich sehr!$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
	.string "Mein Mann tauscht für sein Leben\n"
	.string "gern Pokémon.\p"
	.string "Bist du auch ein Sammler? Würdest\n"
	.string "du bitte Pokémon mit ihm tauschen?$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
	.string "Hallo!\p"
	.string "Willst du dein {PLAYER} nicht\n"
	.string "gegen ein {PLAYER} tauschen?$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
	.string "Flegmon hält zur Zeit eine\n"
	.string "Werbekampagne.\p"
	.string "Erreiche die abgelegenste\n"
	.string "Stelle in der Safari-Zone.\p"
	.string "Wenn du das schaffst, erhältst\n"
	.string "du einen praktischen Preis!$"

