SixIsland_House_Frlg_MapScripts::
	.byte 0

SixIsland_House_EventScript_OldMan::
	msgbox SixIsland_House_Text_GoodPlaceForNatureAndHistory, MSGBOX_NPC
	end

SixIsland_House_Text_GoodPlaceForNatureAndHistory::
	.string "Auf dieser Insel gibt es nichts,\n"
	.string "was junge Leute aufregend finden.\p"
	.string "Aber in punkto Natur und\n"
	.string "Geschichte ist dies ein\l"
	.string "interessanter Ort.\l"
	.string "Entspann dich und genieße\l"
	.string "deinen Aufenthalt.$"

