SixIsland_GreenPath_Frlg_MapScripts::
	.byte 0

SixIsland_GreenPath_EventScript_RightRouteSign::
	msgbox SixIsland_GreenPath_Text_LeftRouteSign, MSGBOX_SIGN
	end

SixIsland_GreenPath_EventScript_LeftRouteSign::
	msgbox SixIsland_GreenPath_Text_RightRouteSign, MSGBOX_SIGN
	end

SixIsland_GreenPath_Text_JaclynIntro::
	.string "… häh?\p"
	.string "Ich sah mein Haus, aber Teleport\n"
	.string "brachte mich hierher?$"

SixIsland_GreenPath_Text_JaclynDefeat::
	.string "Jippie!$"

SixIsland_GreenPath_Text_JaclynPostBattle::
	.string "Ich bin so kopflos!\p"
	.string "Ich muss mich konzentrieren, um\n"
	.string "mit Teleport zu meinem\l"
	.string "Haus zu gelangen!$"

SixIsland_GreenPath_Text_LeftRouteSign::
	.string "Auf diesen Moment hat der Boss\n"
	.string "sehr lange gewartet!$"

SixIsland_GreenPath_Text_RightRouteSign::
	.string "Grüner Pfad\n"
	.string "Sei umweltbewusst!$"

