#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("");
const u8 gText_ExpandedPlaceholder_Chan[] = _("");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("Saphir");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("Rubin");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("Smaragd");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("Aqua");
const u8 gText_ExpandedPlaceholder_Magma[] = _("Magma");
const u8 gText_ExpandedPlaceholder_Archie[] = _("Adrian");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("Marc");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("Kyogre");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("Groudon");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("Brix");
const u8 gText_ExpandedPlaceholder_May[] = _("Maike");
const u8 gText_ExpandedPlaceholder_Red[] = _("Rot");
const u8 gText_ExpandedPlaceholder_Green[] = _("Grün");
const u8 gText_ExpandedPlaceholder_Silver[] = _("Silber");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("Ei");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("Pokémon");
const u8 gText_Player[] = _("Player"); // Unused
const u8 gText_Pokedex[] = _("Pokédex"); // Unused
const u8 gText_Time[] = _("Spielzeit");
const u8 gText_Badges[] = _("Badges"); // Unused
const u8 gText_AButton[] = _("A Button"); // Unused
const u8 gText_BButton[] = _("B Button"); // Unused
const u8 gText_RButton[] = _("R Button"); // Unused
const u8 gText_LButton[] = _("L Button"); // Unused
const u8 gText_Start[] = _("Start"); // Unused
const u8 gText_Select[] = _("SELECT"); // Unused
const u8 gText_ControlPad[] = _("+ Control Pad"); // Unused
const u8 gText_LButtonRButton[] = _("L Button  R Button"); // Unused
const u8 gText_Controls[] = _("Controls"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}Info {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}Weiter");
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}Weiter {B_BUTTON}Zurück");
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}Info{A_BUTTON}Weiter {B_BUTTON}Zur.");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}Info{A_BUTTON}{B_BUTTON}Zurück");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}Zurück");
const u8 gText_Boy[] = _("Junge");
const u8 gText_Girl[] = _("Mädel");
const u8 gText_ThisIsAPokemon[] = _("Dies ist ein sogenanntes\n“Pokémon.”{PAUSE 96}\p");
const u8 gText_5MarksPokemon[] = _("?????");
const u8 gText_UnkHeight[] = _("{CLEAR_TO 0x0C}??'??”");
const u8 gText_UnkHeightMetric[] = _("???.? m");
const u8 gText_UnkWeight[] = _("????.? lbs.");
const u8 gText_UnkWeightMetric[] = _("???.? kg");
const u8 gText_EmptyPkmnCategory[] = _("                       Pokémon"); // Unused
const u8 gText_EmptyHeight[] = _("{CLEAR_TO 0x0C}    '    ”"); // Unused
const u8 gText_EmptyWeight[] = _("        .   lbs."); // Unused
const u8 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u8 gText_CryOf[] = _("Ruf von");
const u8 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u8 gText_SizeComparedTo[] = _("Größe im Vergleich zu ");
const u8 gText_PokedexRegistration[] = _("Neuer Eintrag aufgenommen.");
const u8 gText_HTHeight[] = _("Gr.");
const u8 gText_WTWeight[] = _("Gew.");
const u8 gText_SearchingPleaseWait[] = _("Suche läuft.\nBitte warten…");
const u8 gText_SearchCompleted[] = _("Suche beendet.");
const u8 gText_NoMatchingPkmnWereFound[] = _("Es wurde keine Übereinstimmung ermittelt.");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("Suche nach Pokémon anhand\nausgewählter Parameter.");
const u8 gText_SwitchPokedexListings[] = _("Ordnungssystem des Pokédex ändern.");
const u8 gText_ReturnToPokedex[] = _("Kehre zurück zum Pokédex.");
const u8 gText_SelectPokedexMode[] = _("Wähle einen Pokédex.");
const u8 gText_SelectPokedexListingMode[] = _("Wähle ein Ordnungssystem des Pokédex.");
const u8 gText_ListByFirstLetter[] = _("Nach Anfangsbuchstaben suchen.\n(Alle gesehenen Pokémon.)");
const u8 gText_ListByBodyColor[] = _("Nach Körperfarbe suchen.\n(Alle gesehenen Pokémon.)");
const u8 gText_ListByType[] = _("Nach Elementklasse suchen.\n(Nur gefangene Pokémon.)");
const u8 gText_ExecuteSearchSwitch[] = _("Suche/Änderung ausführen.");
#if IS_HNS
const u8 gText_DexHoennTitle[] = _("Johto Dex");
#else
const u8 gText_DexHoennTitle[] = _("Hoenn Dex");
#endif
const u8 gText_DexNatTitle[] = _("Nationaler Dex");
const u8 gText_DexSortNumericalTitle[] = _("Numerisch");
const u8 gText_DexSortAtoZTitle[] = _("Von A bis Z");
const u8 gText_DexSortHeaviestTitle[] = _("Nach Gewicht >");
const u8 gText_DexSortLightestTitle[] = _("Nach Gewicht <");
const u8 gText_DexSortTallestTitle[] = _("Nach Größe >");
const u8 gText_DexSortSmallestTitle[] = _("Nach Größe <");
const u8 gText_DexSearchAlphaABC[] = _("ABC");
const u8 gText_DexSearchAlphaDEF[] = _("DEF");
const u8 gText_DexSearchAlphaGHI[] = _("GHI");
const u8 gText_DexSearchAlphaJKL[] = _("JKL");
const u8 gText_DexSearchAlphaMNO[] = _("MNO");
const u8 gText_DexSearchAlphaPQR[] = _("PQR");
const u8 gText_DexSearchAlphaSTU[] = _("STU");
const u8 gText_DexSearchAlphaVWX[] = _("VWX");
const u8 gText_DexSearchAlphaYZ[] = _("YZ");
const u8 gText_DexSearchColorRed[] = _("Rot");
const u8 gText_DexSearchColorBlue[] = _("Blau");
const u8 gText_DexSearchColorYellow[] = _("Gelb");
const u8 gText_DexSearchColorGreen[] = _("Grün");
const u8 gText_DexSearchColorBlack[] = _("Schwarz");
const u8 gText_DexSearchColorBrown[] = _("Braun");
const u8 gText_DexSearchColorPurple[] = _("Lila");
const u8 gText_DexSearchColorGray[] = _("Grau");
const u8 gText_DexSearchColorWhite[] = _("Weiß");
const u8 gText_DexSearchColorPink[] = _("Rosa");
#if IS_HNS
const u8 gText_DexHoennDescription[] = _("Johto Pokédex");
#else
const u8 gText_DexHoennDescription[] = _("Hoenn Pokédex");
#endif
const u8 gText_DexNatDescription[] = _("Nationaler Pokédex");
const u8 gText_DexSortNumericalDescription[] = _("Pokémon werden anhand ihrer\nNummer sortiert.");
const u8 gText_DexSortAtoZDescription[] = _("Gesehene und gefangene Pokémon\nwerden alphabetisch geordnet.");
const u8 gText_DexSortHeaviestDescription[] = _("Gefangene Pokémon werden nach Gewicht\nsortiert, beginnend mit dem schwersten.");
const u8 gText_DexSortLightestDescription[] = _("Gefangene Pokémon werden nach Gewicht\nsortiert, beginnend mit dem leichtesten.");
const u8 gText_DexSortTallestDescription[] = _("Gefangene Pokémon werden nach Größe\nsortiert, beginnend mit dem größten.");
const u8 gText_DexSortSmallestDescription[] = _("Gefangene Pokémon werden nach Größe\nsortiert, beginnend mit dem kleinsten.");
const u8 gText_DexEmptyString[] = _("");
const u8 gText_DexSearchDontSpecify[] = _("Keine Angabe");
const u8 gText_DexSearchTypeNone[] = _("Keiner");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(" "); // Unused
const u8 gText_WelcomeToHOF[] = _("Willkommen in der Ruhmeshalle!");
const u8 gText_HOFDexRating[] = _("Gesichtete Pokémon: {STR_VAR_1}!\nBesitz an Pokémon: {STR_VAR_2}!\pProf. Birks Pokédex-Bewertung!\pProf. Birk: Mal sehen…\p");
const u8 gText_HOFDexSaving[] = _("Sichern…\nGerät Nicht Ausschalten!");
const u8 gText_HOFCorrupted[] = _("Die RH-Daten sind beschädigt.");
const u8 gText_HOFNumber[] = _("Ruhmeshalle, Nr. {STR_VAR_1}");
const u8 gText_LeagueChamp[] = _("Champ der Pokémon Liga!\nHerzlichen Glückwunsch!");
const u8 gText_Number[] = _("Nr. ");
const u8 gText_Level[] = _("Lv.");
const u8 gText_IdNumberSlash[] = _("Idno. /"); // Unused
const u8 gText_Name[] = _("Trainer");
const u8 gText_IDNumber[] = _("ID.Nr.");
const u8 gText_BirchInTrouble[] = _("Prof. Birk ist in Schwierigkeiten!\nSchnapp’ dir ein Pokémon und hilf ihm!");
const u8 gText_ConfirmStarterChoice[] = _("Wählst du dieses Pokémon?");
const u8 gText_Pokemon4[] = _("Pokémon"); // Unused
const u8 gText_FlyToWhere[] = _("Wohin Fliegen?");
const u8 gMenuText_Use[] = _("Benutzen");
const u8 gMenuText_Toss[] = _("Werfen");
const u8 gMenuText_Register[] = _("Regist.");
const u8 gMenuText_Give[] = _("Geben");
const u8 gMenuText_Confirm[] = _("O.K.");
const u8 gText_Cancel[] = _("Zurück");
const u8 gText_Cancel2[] = _("Zurück");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("Keines");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("-");
const u8 gText_TwoDashes[] = _("--");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("Lv.");
const u8 gText_NumberClear01[] = _("{NO} {CLEAR 0x01}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("Kehre zurück zum\nvorherigen Menü.");
const u8 gText_WhatWouldYouLike[] = _("Was möchtest du tun?");
const u8 gMenuText_Give2[] = _("Geben");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _(" Beere"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1} Münz.");
const u8 gText_CloseBag[] = _("Beutel Schliessen");
const u8 gText_Var1IsSelected[] = _("Was möchtest\ndu tun?");
const u8 gText_CantWriteMail[] = _("Du kannst keinen\nBrief schreiben.");
const u8 gText_NoPokemon[] = _("Hier ist kein\nPokémon.");
const u8 gText_MoveVar1Where[] = _("Gegen welches Item\naustauschen?");
const u8 gText_Var1CantBeHeld[] = _("{STR_VAR_1} ist nicht zu geben.");
const u8 gText_TossHowManyVar1s[] = _("Wie viel in den Müll?");
const u8 gText_ThrewAwayVar2Var1s[] = _("{STR_VAR_2} × {STR_VAR_1}\nweggeworfen.");
const u8 gText_ConfirmTossItems[] = _("Willst du wirklich\n{STR_VAR_2} × {STR_VAR_1}\nwegwerfen?");
#if IS_HNS
    const u8 gText_DadsAdvice[] = _("Lind sagt immer…\n{PLAYER}, dies ist weder der rechte\lOrt noch der rechte Zeitpunkt dafür!{PAUSE_UNTIL_PRESS}");
#else
    const u8 gText_DadsAdvice[] = _("Vati sagt immer……\n{PLAYER}, dies ist weder der rechte\lOrt noch der rechte Zeitpunkt dafür!{PAUSE_UNTIL_PRESS}");
#endif
const u8 gText_PlayerUsedVar2[] = _("{PLAYER} setzt\n{STR_VAR_2} ein.{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("Aber Schutz wirkt doch\nnoch!{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("Doch die Wirkung eines Lockmittels\nhielt noch an.{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("Die Boxen sind voll.{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("zum Hauptmenü");
const u8 gText_TheBattle[] = _("zum Kampf");
const u8 gText_ThePokemonList[] = _("zur Pokémon-Liste");
const u8 gText_TheShop[] = _("zum Geschäft");
const u8 gText_ThePC[] = _("zum PC");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("Zurück\n{STR_VAR_1}.");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS] =        COMPOUND_STRING("Items"),
    [POCKET_POKE_BALLS] =   COMPOUND_STRING("Pokébälle"),
    [POCKET_TM_HM]  =       COMPOUND_STRING("TMs & VMs"),
    [POCKET_BERRIES] =      COMPOUND_STRING("Beeren"),
    [POCKET_KEY_ITEMS] =    COMPOUND_STRING("Basis Items"),
    [POCKET_MEDICINE] =     COMPOUND_STRING("Medizin"),
#if I_COMBINE_BAG_POCKETS == FALSE
    [POCKET_BATTLE_ITEMS] = COMPOUND_STRING("Kampf"),
    [POCKET_TREASURES] =    COMPOUND_STRING("Schätze"),
#endif
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 0x03}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 0x11}{STR_VAR_1}{CLEAR 0x05}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("Kaufen");
const u8 gText_ShopSell[] = _("Verkaufen");
const u8 gText_ShopQuit[] = _("Tschüss!");
const u8 gText_ThatItemIsSoldOut[] = _("Tut mir leid, dieses Item ist\nausverkauft.{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("Ausverkauft");
const u8 gText_InBagVar1[] = _("Besitz: {STR_VAR_1}");
const u8 gText_QuitShopping[] = _("Einkauf beenden.");
const u8 gText_Var1CertainlyHowMany[] = _("{STR_VAR_1}? Aber gerne.\nWie viele möchtest du?");
const u8 gText_Var1CertainlyHowMany2[] = _("{STR_VAR_1} ist {STR_VAR_2}!\nGerne. Wie viele möchtest du?");
const u8 gText_Var1AndYouWantedVar2[] = _("{STR_VAR_1}? Und du möchtest {STR_VAR_2}?\nDas macht dann ¥{STR_VAR_3}.");
const u8 gText_Var1AndYouWantedVar2BP[] = _("{STR_VAR_1}? Und du möchtest {STR_VAR_2}?\nDas macht dann {STR_VAR_3}GP.");
const u8 gText_Var1IsItThatllBeVar2[] = _("{STR_VAR_1} soll es sein?\nDas kostet ¥{STR_VAR_2}. Einverstanden?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("Du wolltest {STR_VAR_1}?\nDas kostet ¥{STR_VAR_2}. Einverstanden?");
const u8 gText_YouWantedVar1ThatllBeVar2BP[] = _("Du möchtest {STR_VAR_1}?\nDas macht {STR_VAR_2}GP. Ist das in Ordnung?");
const u8 gText_HereYouGoThankYou[] = _("Bitte sehr!\nUnd vielen Dank.");
const u8 gText_ThankYouIllSendItHome[] = _("Vielen Dank!\nEs wird auf deinen PC übertragen.");
const u8 gText_ThanksIllSendItHome[] = _("Danke!\nEs wird auf deinen PC übertragen.");
const u8 gText_YouDontHaveMoney[] = _("Du hast nicht genug Geld.{PAUSE_UNTIL_PRESS}");
const u8 gText_YouDontHaveEnoughBP[] = _("Du hast nicht genug\nGP.{PAUSE_UNTIL_PRESS}");
const u8 gText_DontHaveEnoughVar1[] = _("Du hast nicht genug\n{STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_Var1SureHowMany[] = _("{STR_VAR_1}? Sicher.\nWie viele möchtest du?");
const u8 gText_xOne[] = _("x1");
const u8 gText_xFive[] = _("x5");
const u8 gText_KurtVar1AndYouWantedVar2Plural[] = _("Du möchtest {STR_VAR_2} davon?\nDas macht {STR_VAR_3} Beeren.");
const u8 gText_KurtVar1AndYouWantedVar2Singular[] = _("Du möchtest {STR_VAR_2} davon?\nDas macht {STR_VAR_3} Beeren.");
const u8 gText_KurtGettingStarted[] = _("Kurt: Ich fange sofort an!");
const u8 gText_ExitMenu[] = _("Menü Verlassen");
const u8 gText_NoMoreRoomForThis[] = _("Du hast keinen Platz für weitere Items.{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("Es ist kein Platz für {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("Gibt es noch etwas, womit\nich dienen kann?");
const u8 gText_CanIHelpWithAnythingElse[] = _("Kann ich dir sonst noch dienlich sein?");
const u8 gText_ThrowInPremierBall[] = _("Ich gebe dir noch einen Premierball.{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("Ich gebe dir noch {STR_VAR_1} Premierbälle.{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{STR_VAR_2}? Es tut mir Leid, aber\ndas kann ich nicht kaufen.{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("{STR_VAR_2}?\nWie viele möchtest du verkaufen?");
const u8 gText_ICanPayVar1[] = _("Ich gebe dir ¥{STR_VAR_1}.\nBist du damit einverstanden?");
const u8 gText_TurnedOverVar1ForVar2[] = _("{STR_VAR_2} wurde übergeben\nim Tausch gegen ¥{STR_VAR_1}.");
const u8 gText_PokedollarVar1[] = _("¥{STR_VAR_1}");
const u8 gText_HP3[] = _("KP");
const u8 gText_SpAtk3[] = _("Sp. Ang.");
const u8 gText_SpDef3[] = _("Sp. Ver.");
const u8 gText_WontHaveEffect[] = _("Es wird keine Wirkung haben.{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("Wähle das {PKMN} zum Fusionieren.");
const u8 gText_CantBeUsedOnPkmn[] = _("Das kann nicht bei diesem\nPokémon eingesetzt werden.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("{STR_VAR_1} kann nicht ausge-\ntauscht werden!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1}\nkämpft bereits!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1} ist\nbereits ausgewählt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1} kann\nnicht kämpfen!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("Ein Pokémon von {STR_VAR_1} ist\nnicht gegen deins eintauschbar!{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("Ein Ei kann nicht kämpfen!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("Das ist erst einsetzbar, wenn\nein neuer Orden errungen wurde.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("Es können nicht mehr als\n{STR_VAR_1} Pokémon teilnehmen.{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("Den abgenommenen Brief\nauf deinen PC übertragen?");
const u8 gText_MailSentToPC[] = _("Der Brief wurde auf deinen\nPC übertragen.{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("Du kannst keine weiteren Briefe\nauf deinen PC übertragen.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("Wird der Brief entfernt, geht\nder Inhalt verloren, okay?");
const u8 gText_RemoveMailBeforeItem[] = _("Der Brief muss entfernt werden,\num ein Item tragen zu können.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("{STR_VAR_1} erhält\n{STR_VAR_2} zum Tragen.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1} trägt bereits\n{STR_VAR_2}.\pSollen die Items ausge-\ntauscht werden?");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1} trägt\nkein Item.{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("{STR_VAR_2} von\n{STR_VAR_1} erhalten.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("Der Brief wurde dem\nPokémon abgenommen.{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("{STR_VAR_2} wurde gegen\n{STR_VAR_1} ausgetauscht.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("Dieses Pokémon trägt ein Item.\nEs kann keinen Brief tragen.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("Der Brief wurde von deinem\nPC heruntergeladen.{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("Der Beutel ist voll. Das Item\ndes Pokémon wurde nicht entfernt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{STR_VAR_1} erlernt\n{STR_VAR_2}!");
const u8 gText_PkmnLearnedMove4[] = _("{STR_VAR_1} erlernt\n{STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1} und {STR_VAR_2}\nsind nicht kompatibel.\p{STR_VAR_2} kann nicht \nerlernt werden.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1} versucht,\n{STR_VAR_2} zu erlernen.\pAber {STR_VAR_1} kann maximal\nvier Attacken erlernen.\pSoll eine andere Attacke durch\n{STR_VAR_2} ersetzt werden?");
const u8 gText_StopLearningMove2[] = _("{STR_VAR_2} nicht\nerlernen?");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1} hat {STR_VAR_2}\nnicht erlernt.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("Welche Attacke soll vergessen\nwerden?{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("1, {PAUSE 15}2 und{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1} Schwupp!\p{STR_VAR_1} hat\n{STR_VAR_2} vergessen.\pUnd…{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1} kennt\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("Die KP von {STR_VAR_1} wurden\num {STR_VAR_2} Punkt(e) aufgefüllt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("Die Vergiftung von {STR_VAR_1}\nwurde geheilt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("Die Paralyse von {STR_VAR_1}\nwurde aufgehoben.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1} ist aufgewacht.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("Verbrennung von {STR_VAR_1}\nwurde geheilt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1}s Erfrierung wurde geheilt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1} wurde aufgetaut.{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("AP wurden aufgefüllt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1} regained health.{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1} erholte sich.{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("AP von {STR_VAR_1}\nwurden angehoben.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1} erreicht\nLv. {STR_VAR_2}.");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1} gained {STR_VAR_2} Exp. Points!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1} erreicht\nLv. {STR_VAR_3}.");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_2} von\n{STR_VAR_1} wurde angehoben.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1} wird zahm.\nDer Grundwert {STR_VAR_2} sinkt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1} vergöttert dich!\nDer Grundwert {STR_VAR_2} sinkt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1} wird zahm. Grund-\nwert {STR_VAR_2} sinkt nicht mehr.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1} ist nicht\nmehr verwirrt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1} fühlt sich nicht\nmehr angezogen.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1} transformed!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("{STR_VAR_1}\nwegwerfen?");
const u8 gText_ItemThrownAway[] = _("{STR_VAR_1}\nwurde weggeworfen.{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("Teach which Pokémon?"); // Unused
const u8 gText_ChoosePokemon[] = _("Wähle ein Pokémon.");
const u8 gText_MoveToWhere[] = _("An wessen Stelle setzen?");
const u8 gText_TeachWhichPokemon[] = _("Welches Pokémon lehren?");
const u8 gText_UseOnWhichPokemon[] = _("Welches Pokémon?");
const u8 gText_GiveToWhichPokemon[] = _("Welchem Pokémon geben?");
const u8 gText_DoWhatWithPokemon[] = _("Was tun mit {STR_VAR_1}?");
const u8 gText_NothingToCut[] = _("Hier nicht einsetzbar.");
const u8 gText_CantSurfHere[] = _("Surfer nicht einsetzbar.");
const u8 gText_AlreadySurfing[] = _("Surfer ist eingesetzt.");
const u8 gText_CantUseHere[] = _("Hier nicht einsetzbar.");
const u8 gText_RestoreWhichMove[] = _("Welche Att. auffüllen?");
const u8 gText_BoostPp[] = _("AP welcher Att. heben?");
const u8 gText_DoWhatWithItem[] = _("Was willst du mit dem Item?");
const u8 gText_NoPokemonForBattle[] = _("Kein Pokémon kampfbereit!");
const u8 gText_ChoosePokemon2[] = _("Wähle ein Pokémon.");
const u8 gText_NotEnoughHp[] = _("Nicht genügend KP…");
const u8 gText_PokemonAreNeeded[] = _("{STR_VAR_1} Pokémon sind nötig.");
const u8 gText_PokemonCantBeSame[] = _("Nicht dieselben Pokémon!");
const u8 gText_NoIdenticalHoldItems[] = _("Nicht dieselben Items!");
const u8 gText_CurrentIsTooFast[] = _("Die Strömung ist zu stark!");
const u8 gText_DoWhatWithMail[] = _("Was ist mit dem Brief?");
const u8 gText_ChoosePokemonCancel[] = _("Wähle Pkmn oder Zurück.");
const u8 gText_ChoosePokemonConfirm[] = _("Wähle ein Pkmn und bestätige.");
const u8 gText_SendWhichMonToPC[] = _("Welches Pokémon zum PC senden?");
const u8 gText_MoveItemWhere[] = _("Item wohin bewegen?");
const u8 gText_XsYAnd[] = _("{STR_VAR_1}'s {STR_VAR_2} und\n");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_1}'s {STR_VAR_2} wurden getauscht!{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("Lass uns Rad fahren!");
const u8 gText_InUseAlready_PM[] = _("Das wird bereits benutzt.");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1} trägt bereits\n{STR_VAR_2}.");
const u8 gText_WhichAppliance[] = _("Welches Haushaltsgerät\nmöchtest du bestellen?");
const u8 gText_NoUse[] = _("Unnütz!");
const u8 gText_Able[] = _("O.K.");
const u8 gText_First_PM[] = _("Erstes");
const u8 gText_Second_PM[] = _("Zweites");
const u8 gText_Third_PM[] = _("Drittes");
const u8 gText_Able2[] = _("O.K.");
const u8 gText_NotAble[] = _("Nein");
const u8 gText_Able3[] = _("O.K.");
const u8 gText_NotAble2[] = _("Nein");
const u8 gText_Learned[] = _("Kennt Att.");
const u8 gText_Have[] = _("Haben");
const u8 gText_DontHave[] = _("Nix Haben");
const u8 gText_Fourth[] = _("Viertes");
const u8 gText_PkmnCantParticipate[] = _("Dieses Pkmn kann nicht teilnehmen.{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("Teilnahme absagen?");
const u8 gText_CancelBattle[] = _("Kampf absagen?");
const u8 gText_ReturnToWaitingRoom[] = _("Zurück ins Wartezimmer?");
const u8 gText_CancelChallenge[] = _("Herausforderung widerrufen?");
const u8 gText_EscapeFromHere[] = _("Von hier fliehen und nach\n{STR_VAR_1} zurückkehren?");
const u8 gText_ReturnToHealingSpot[] = _("Zum heilenden Ort in {STR_VAR_1}\nzurückkehren?");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{STR_VAR_1}を ぐるぐるこうかんに\nだして よろしいですか？");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("Das ist das einzige\nPokémon zum Kampf.");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("Dieses Pokémon kann jetzt\nnicht getauscht werden.");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("Dieses Pokémon kann nicht\ngetauscht werden.");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("Ei jetzt nicht tauschbar.");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("Pkmn des anderen Trainers kann\njetzt nicht getauscht werden.");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("Der andere Trainer kann das\nPkmn jetzt nicht akzeptieren.");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("Du kannst mit diesem Trainer\njetzt keine Pkmn tauschen.");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("Diese Art von Pokémon möchte\nder andere Trainer nicht.");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("Dies ist kein Ei!");
const u8 gText_Register[] = _("Wählen");
const u8 gText_Attack3[] = _("Angriff");
const u8 gText_Defense3[] = _("Vert.");
const u8 gText_SpAtk4[] = _("Sp.Ang.");
const u8 gText_SpDef4[] = _("Sp.Ver.");
const u8 gText_Speed2[] = _("Init.");
const u8 gText_HP4[] = _("KP");
const u8 gText_EmptyString8[] = _(""); // Unused
const u8 gText_OTSlash[] = _("OT:");
const u8 gText_RentalPkmn[] = _("Leih-Pokémon");
const u8 gText_TypeSlash[] = _("Typ:");
const u8 gText_Power[] = _("Stärke");
const u8 gText_Accuracy2[] = _("Genau.");
const u8 gText_Appeal[] = _("Ausdr.");
const u8 gText_Jam[] = _("Eindr.");
const u8 gText_Status[] = _("Status");
const u8 gText_ExpPoints[] = _("E.-Punkte");
const u8 gText_NextLv[] = _("Nächst. Lv.");
const u8 gText_RibbonsVar1[] = _("Bänder: {STR_VAR_1}");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("Events"); // Unused
const u8 gText_Switch[] = _("Tausch");
const u8 gText_PkmnInfo[] = _("Pokémon-Info");
const u8 gText_PkmnSkills[] = _("Pokémon-Fähig.");
const u8 gText_BattleMoves[] = _("Attacken");
const u8 gText_ContestMoves[] = _("Wett.-Attacken");
const u8 gText_Info[] = _("Info");
const u8 gText_EggWillTakeALongTime[] = _("Dieses Ei braucht sicher\nnoch sehr viel Zeit.");
const u8 gText_EggWillTakeSomeTime[] = _("Was da wohl schlüpfen wird?\nEs wird sicher lange dauern.");
const u8 gText_EggWillHatchSoon[] = _("Bewegungen… Da wird\nwohl bald etwas schlüpfen.");
const u8 gText_EggAboutToHatch[] = _("Geräusche! Da schlüpft\nsicher bald etwas!");
const u8 gText_EggReadyToHatch_Nuzlocke[] = _("Würde schlüpfen, aber\nvon Nuzlocke blockiert!");
const u8 gText_HMMovesCantBeForgotten2[] = _("VM-Attacken können jetzt\nnicht vergessen werden.");
const u8 gText_XNatureMetAtYZ[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\n{LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedAtYZ[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\ngeschlüpft mit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureObtainedInTrade[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nin einem Tausch erhalten.");
const u8 gText_XNatureFatefulEncounter[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nin schicksalhafter Begeg-\nnung mit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1} erhalten.");
const u8 gText_XNatureProbablyMetAt[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}, gefangen\nvermutlich mit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNature[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}");
const u8 gText_XNatureMetSomewhereAt[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nirgendwo getroffen\nmit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedSomewhereAt[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}, irgendwo\ngeschlüpft mit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_OddEggFoundByCouple[] = _("Seltsames Pokémon-Ei, das\ndie Pensionsleitung fand.");
const u8 gText_PeculiarEggNicePlace[] = _("Kurioses Pokémon-Ei, an\nhübschem Ort erhalten.");
const u8 gText_PeculiarEggTrade[] = _("Kurioses Pokémon-Ei, im\nTausch erhalten.");
const u8 gText_EggFromHotSprings[] = _("Ein Pokémon-Ei, an den\nHeißen Quellen erhalten.");
const u8 gText_OddEggFromDaycare[] = _("Ein seltsames Pokémon-Ei\nvon der Pension.");
const u8 gText_EggFromTraveler[] = _("Ein seltsames Pokémon-Ei\nvon einem Reisenden.");
const u8 gText_ApostropheSBase[] = _("Basis v. {STR_VAR_1}");
const u8 gText_OkayToDeleteFromRegistry[] = _("Soll {STR_VAR_1} aus dem Grundbuch\ngelöscht werden?");
const u8 gText_RegisteredDataDeleted[] = _("Eingetragene Daten wurden gelöscht.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("Es gibt kein Grundbuch.{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("Eintr. Löschen");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("Dekorieren");
const u8 gText_PutAway[] = _("Wegnehmen");
const u8 gText_Toss2[] = _("Wegwerfen");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("Wähle eine Dekoration \nund stelle sie auf.");
const u8 gText_StoreChosenDecorInPC[] = _("Wähle eine Dekoration und \nübertrage sie auf deinen PC.");
const u8 gText_ThrowAwayUnwantedDecors[] = _("Wähle eine Dekoration\nund wirf sie weg.");
const u8 gText_NoDecorations[] = _("Es gibt keine Dekoration.{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("Tisch");
const u8 gText_Chair[] = _("Stuhl");
const u8 gText_Plant[] = _("Pflanze");
const u8 gText_Ornament[] = _("Ornament");
const u8 gText_Mat[] = _("Matte");
const u8 gText_Poster[] = _("Poster");
const u8 gText_Doll[] = _("Puppe");
const u8 gText_Cushion[] = _("Kissen");
const u8 gText_Gold[] = _("Gold");
const u8 gText_Silver[] = _("Silber");
const u8 gText_PlaceItHere[] = _("Hierhin platzieren?");
const u8 gText_CantBePlacedHere[] = _("Kann hier nicht platziert werden.");
const u8 gText_CancelDecorating[] = _("Dekorieren beenden?");
const u8 gText_InUseAlready[] = _("Das wurde bereits platziert.");
const u8 gText_NoMoreDecorations[] = _("Mehr kann nicht dekoriert werden. Es\nist nur Platz für {STR_VAR_1} Dekorationen.");
const u8 gText_NoMoreDecorations2[] = _("Mehr kann nicht dekoriert werden. Es\nist nur Platz für {STR_VAR_1} Dekorationen.");
const u8 gText_MustBePlacedOnDesk[] = _("Das kann hier nicht stehen.\nEs muss auf einem Tisch o. Ä. stehen."); // Unused
const u8 gText_CantPlaceInRoom[] = _("Die Dekoration kann nicht in deinem\neigenen Zimmer aufgestellt werden.");
const u8 gText_CantThrowAwayInUse[] = _("Diese Dekoration wurde platziert.\nDu kannst sie nicht wegwerfen.");
const u8 gText_DecorationWillBeDiscarded[] = _("{STR_VAR_1} wird weggeworfen.\nEinverstanden?");
const u8 gText_DecorationThrownAway[] = _("Die Dekoration wurde weggeworfen.");
const u8 gText_StopPuttingAwayDecorations[] = _("Wegnehmen von Dekoration beenden?");
const u8 gText_NoDecorationHere[] = _("Hier ist keine Dekoration.");
const u8 gText_ReturnDecorationToPC[] = _("Diese Dekoration auf \nden PC übertragen?");
const u8 gText_DecorationReturnedToPC[] = _("Die Dekoration wurde auf\nden PC übertragen.");
const u8 gText_NoDecorationsInUse[] = _("Es sind keine Dekorationen platziert.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("Es gibt keine Items.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("Hier ist kein Brief.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("Was soll mit dem Brief von\n{STR_VAR_1} geschehen?");
const u8 gText_MessageWillBeLost[] = _("Der Inhalt geht verloren.\nIst das in Ordnung für dich?");
const u8 gText_BagIsFull[] = _("Der Beutel ist voll.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("Der Brief, dessen Inhalt gelöscht\nist, wurde im Beutel gelagert.{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("Vati");
const u8 gText_Mom[] = _("Mutti");
const u8 gText_MomHowMuchDeposit[] = _("Wieviel möchtest du\nbei Mutti einzahlen?");
const u8 gText_MomHowMuchWithdraw[] = _("Wieviel möchtest du\nbei Mutti entnehmen?");
const u8 gText_MomMatchCallDesc[] = _("Ruhig & Nett");
const u8 gText_MomMatchCallName[] = _("Mutti");
const u8 gText_MomMenuCheckSavings[] = _("Konto");
const u8 gText_MomMenuDeposit[] = _("Einzahlen");
const u8 gText_MomMenuWithdraw[] = _("Nehmen");
const u8 gText_MomMenuToggleSaving[] = _("Sparen");
const u8 gText_MomMenuExit[] = _("Verlassen");
const u8 gText_Info2[] = _("Info");
const u8 gText_CoolnessContest[] = _("Cool.");
const u8 gText_BeautyContest[] = _("Schön.");
const u8 gText_CutenessContest[] = _("Anmut");
const u8 gText_SmartnessContest[] = _("Klug.");
const u8 gText_ToughnessContest[] = _("Stärke");
const u8 gText_Decoration2[] = _("Dekoration");
const u8 gText_PackUp[] = _("Einpacken");
const u8 gText_Registry[] = _("Register");
const u8 gText_Information[] = _("Information");
const u8 gText_Yes[] = _("Ja");
const u8 gText_No[] = _("Nein");
const u8 gText_Lv50[] = _("LV. 50");
const u8 gText_OpenLevel[] = _("Offene Kämpfe");
const u8 gText_RedShard[] = _("Purpurstück");
const u8 gText_YellowShard[] = _("Gelbstück");
const u8 gText_BlueShard[] = _("Indigostück");
const u8 gText_GreenShard[] = _("Grünstück");
const u8 gText_BattleFrontier[] = _("Kampfzone");
const u8 gText_Cool[] = _("Cool.");
const u8 gText_Beauty[] = _("Schön.");
const u8 gText_Cute[] = _("Anmut");
const u8 gText_Smart[] = _("Klug.");
const u8 gText_Tough[] = _("Stärke");
const u8 gText_Normal[] = _("Normal");
const u8 gText_Super[] = _("Super");
const u8 gText_Hyper[] = _("Hyper");
const u8 gText_Master[] = _("Master");
const u8 gText_Cool2[] = _("Cool.");
const u8 gText_Beauty2[] = _("Schön.");
const u8 gText_Cute2[] = _("Anmut");
const u8 gText_Smart2[] = _("Klug.");
const u8 gText_Tough2[] = _("Stärke");
const u8 gText_Items[] = _("Item");
const u8 gText_Key_Items[] = _("Basis-Item");
const u8 gText_Poke_Balls[] = _("Ball");
const u8 gText_TMs_Hms[] = _("TM/VM");
const u8 gText_Berries2[] = _("Beeren");
const u8 gText_Medicine[] = _("Medizin");
#if I_COMBINE_BAG_POCKETS == FALSE
const u8 gText_BattleItems[] = _("Kampfitems");
const u8 gText_Treasures[] = _("Schätze");
#endif
const u8 gText_SomeonesPC[] = _("Jemandes PC");
const u8 gText_LanettesPC[] = _("Lanettes PC");
const u8 gText_BillsPc[] = _("Bills PC");
const u8 gText_PlayersPC[] = _("PC von {PLAYER}");
const u8 gText_HallOfFame[] = _("Ruhmeshalle");
const u8 gText_LogOff[] = _("Ausloggen");
const u8 gText_Challenges[] = _("Einstellung");
const u8 gText_Opponent[] = _("Gegner");
const u8 gText_Tourney_Tree[] = _("Turniertafel");
const u8 gText_ReadyToStart[] = _("Bereit");
const u8 gText_Single2[] = _("Einzel");
const u8 gText_Double2[] = _("Doppel");
const u8 gText_Multi[] = _("Multi");
const u8 gText_MultiLink[] = _("Multi-Link");
const u8 gText_MenuOptionPokedex[] = _("Pokédex");
const u8 gText_MenuOptionPokemon[] = _("Pokémon");
const u8 gText_MenuOptionBag[] = _("Beutel");
#if IS_HNS
const u8 gText_MenuOptionPokenav[] = _("Pokécom");
#else
const u8 gText_MenuOptionPokenav[] = _("Pokécom");
#endif
const u8 gText_Blank[] = _("");
const u8 gText_MenuOptionSave[] = _("Sichern");
const u8 gText_MenuOptionOption[] = _("Option.");
const u8 gText_MenuOptionExit[] = _("Beenden");
const u8 gText_SouthernIsland[] = _("Insel im Süden");
const u8 gText_BirthIsland[] = _("Entstehungsinsel");
const u8 gText_FarawayIsland[] = _("Ferneiland");
const u8 gText_NavelRock[] = _("Nabelfels");
const u8 gText_NormalTagMatch[] = _("Basisteamkampf");
const u8 gText_VarietyTagMatch[] = _("Hürdenteamkampf");
const u8 gText_UniqueTagMatch[] = _("Unikatteamkampf");
const u8 gText_ExpertTagMatch[] = _("Profiteamkampf");
const u8 gText_TradeCenter[] = _("Handelscenter");
const u8 gText_Colosseum[] = _("Kolosseum");
const u8 gText_RecordCorner[] = _("Statistiktausch");
const u8 gText_BerryCrush3[] = _("Beerenmühle");
const u8 gText_BattleRules[] = _("Kampfregeln");
const u8 gText_JudgeMind[] = _("Jury: Verstand");
const u8 gText_JudgeSkill[] = _("Jury: Geschick");
const u8 gText_JudgeBody[] = _("Jury: Körper");
const u8 gText_BasicRules[] = _("Grundregeln");
const u8 gText_SwapPartners[] = _("Tausch: Team");
const u8 gText_SwapNumber[] = _("Tausch: Nr.");
const u8 gText_SwapNotes[] = _("Tausch: Tipp");
const u8 gText_BattleBasics[] = _("Kampftipps");
const u8 gText_PokemonNature[] = _("Pokémon Wesen");
const u8 gText_PokemonMoves[] = _("Pkmn Attacken");
const u8 gText_Underpowered[] = _("Wesen&Attacken");
const u8 gText_WhenInDanger[] = _("Bei Gefahr");
const u8 gText_BattlePokemon[] = _("Kampfpokémon");
const u8 gText_BattleTrainers[] = _("Kampftrainer");
const u8 gText_GoOn[] = _("Weiter");
const u8 gText_Record2[] = _("Sichern");
const u8 gText_Rest[] = _("Ausruhen");
const u8 gText_Retire[] = _("Schluss");
const u8 gText_1F[] = _("EG");
const u8 gText_2F[] = _("1S");
const u8 gText_3F[] = _("2S");
const u8 gText_4F[] = _("3S");
const u8 gText_5F[] = _("4S");
const u8 gText_6F[] = _("5S");
const u8 gText_7F[] = _("6S");
const u8 gText_8F[] = _("7S");
const u8 gText_9F[] = _("8S");
const u8 gText_10F[] = _("9S");
const u8 gText_11F[] = _("10S");
const u8 gText_B1F[] = _("U1S");
const u8 gText_B2F[] = _("U2S");
const u8 gText_B3F[] = _("U3S");
const u8 gText_B4F[] = _("U4S");
const u8 gText_Rooftop[] = _("Dach");
const u8 gText_ElevatorNowOn[] = _("Momentan im");
const u8 gText_BP[] = _("GP");
const u8 gText_RankingHall[] = _("Ergebnishalle");
const u8 gText_ExchangeService[] = _("Austauschservice");
const u8 gText_LilycoveCity[] = _("Seegrasulb City");
const u8 gText_SlateportCity[] = _("Graphitport City");
const u8 gText_Exit[] = _("Zurück");
const u8 gText_YourPartysFull[] = _("Dein Team ist voll!");
const u8 gText_InParty[] = _("Im Team");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_RED WHITE GREEN}♂{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_GREEN WHITE BLUE}♀{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_RED WHITE GREEN}♂{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_GREEN WHITE BLUE}♀{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("Erstelle dein eigenes Profil!");
const u8 gText_AndMakeYourProfile[] = _("Kombiniere 4 Wörter/Ausdrücke.");
const u8 gText_CombineSixWordsOrPhrases[] = _("Verwende 6 Ausdrücke,");
const u8 gText_AndMakeAMessage[] = _("um einen Satz zu bilden.");
const u8 gText_FindWordsThatDescribeYour[] = _("Finde Worte, die deine momentanen");
const u8 gText_FeelingsRightNow[] = _("Empfindungen beschreiben.");
const u8 gText_WithFourPhrases[] = _("With four phrases,"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("Kombiniere 9 Ausdrücke und");
const u8 gText_AndMakeAMessage2[] = _("erstelle eine Nachricht.");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("Ändere nur 1 Wort/Ausdruck");
const u8 gText_AndImproveTheBardsSong[] = _("und verbessere das Barden-Lied.");
const u8 gText_YourProfile[] = _("Dein Profil");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("Dein Gefühl zum Kampfbeginn");
const u8 gText_WhatYouSayIfYouWin[] = _("Dein Ausspruch im Fall des Sieges");
const u8 gText_WhatYouSayIfYouLose[] = _("Dein Ausspruch bei einer Niederl.");
const u8 gText_TheAnswer[] = _("Die Antwort");
const u8 gText_TheMailMessage[] = _("Der Inhalt des Briefes");
const u8 gText_TheMailSalutation[] = _("Die Brief-Anrede"); // Unused
const u8 gText_TheBardsSong2[] = _("Das neue Lied");
const u8 gText_CombineTwoWordsOrPhrases[] = _("Kombiniere 2 Ausdrücke und");
const u8 gText_AndMakeATrendySaying[] = _("schaffe einen hippen Spruch.");
const u8 gText_TheTrendySaying[] = _("Der hippe Spruch");
const u8 gText_IsAsShownOkay[] = _("lautet also so. O.K.?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("Kombiniere 2 Ausdrücke und");
const u8 gText_ToTeachHerAGoodSaying[] = _("bringe ihr einen guten Spruch bei.");
const u8 gText_FindWordsWhichFit[] = _("Finde die passenden Worte");
const u8 gText_TheTrainersImage[] = _("für diesen Trainer.");
const u8 gText_TheImage[] = _("Darstellung");
const u8 gText_OutOfTheListedChoices[] = _("Wähle eine der vorgegebenen");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("Antworten als Lösung aus");
const u8 gText_AndCreateAQuiz[] = _("und erstelle ein Quiz!");
const u8 gText_PickAWordOrPhraseAnd[] = _("Wähle ein(en) Wort/Ausdruck aus");
const u8 gText_SetTheQuizAnswer[] = _("und lege die Antwort fest.");
const u8 gText_TheAnswerColon[] = _("Die Antwort:");
const u8 gText_TheQuizColon[] = _("Das Quiz:"); // Unused
const u8 gText_ApprenticePhrase[] = _("Aussage des Lehrlings:");
const u8 gText_QuitEditing[] = _("Das Textverfassen beenden?");
const u8 gText_StopGivingPkmnMail[] = _("Pokémon keinen Brief geben?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("Fülle den Fragebogen aus.");
const u8 gText_LetsReplyToTheInterview[] = _("Lass uns das Interview beenden!");
const u8 gText_AllTextBeingEditedWill[] = _("Der gesamte verfasste Text wird");
const u8 gText_BeDeletedThatOkay[] = _("gelöscht. Einverstanden?");
const u8 gText_QuitEditing2[] = _("Quit editing?"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("Der geänderte Text wird nicht gesichert."); // Unused
const u8 gText_IsThatOkay[] = _("Ist das in Ordnung?"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("Gib bitte ein Wort oder einen Satz ein."); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("Der gesamte Text kann nicht\ngelöscht werden.");
const u8 gText_OnlyOnePhrase[] = _("Nur ein Ausdruck ist änderbar.");
const u8 gText_OriginalSongWillBeUsed[] = _("Das Lied wird wiederhergestellt.");
const u8 gText_ThatsTrendyAlready[] = _("That's trendy already!"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("Kombiniere 2 Wörter/Ausdrücke.");
const u8 gText_QuitGivingInfo[] = _("Quit giving information?"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("Pokémon keinen Brief geben?"); // Unused
const u8 gText_CreateAQuiz2[] = _("Erstelle ein Quiz!"); // Unused
const u8 gText_SetTheAnswer[] = _("Lege die Antwort fest!"); // Unused
const u8 gText_CancelSelection[] = _("Auswahl abbrechen?"); // Unused
const u8 gText_Profile[] = _("Profil");
const u8 gText_AtTheBattlesStart[] = _("Zum Kampfbeginn");
const u8 gText_UponWinningABattle[] = _("Über den Sieg");
const u8 gText_UponLosingABattle[] = _("Über die Niederlage");
const u8 gText_TheBardsSong[] = _("Das Barden-Lied");
const u8 gText_WhatsHipAndHappening[] = _("Was ist hip? Was ist top?");
const u8 gText_Interview[] = _("Interview");
const u8 gText_GoodSaying[] = _("Guter Spruch");
const u8 gText_FansQuestion[] = _("Frage eines Fans");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは？"); // Unused
const u8 gText_ApprenticesPhrase[] = _("Worte des Lehrlings");
const u8 gText_Questionnaire[] = _("Fragebogen");
const u8 gText_YouCannotQuitHere[] = _("Beenden hier nicht möglich.");
const u8 gText_SectionMustBeCompleted[] = _("Abschnitt noch abschließen.");
const u8 gText_F700sQuiz[] = _("Quiz von {DYNAMIC 0}");
const u8 gText_Lady[] = _("Lady");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("Drücke den A-Knopf, nachdem");
const u8 gText_QuestionPressTheAButton[] = _("du die Quizfrage gelesen hast.");
const u8 gText_TheQuizAnswerIs[] = _("Wie lautet die Antwort?");
const u8 gText_LikeToQuitQuiz[] = _("Möchtest du dieses Quiz");
const u8 gText_ChallengeQuestionMark[] = _("beenden?");
const u8 gText_IsThisQuizOK[] = _("Ist dieses Quiz o.k.?");
const u8 gText_CreateAQuiz[] = _("Quiz erstellen!");
const u8 gText_SelectTheAnswer[] = _("Wähle die Antwort!");
const u8 gText_LyricsCantBeDeleted[] = _("Phrasenlöschen ist unmöglich!");
const u8 gText_PokemonLeague[] = _("Pokémon Liga");
const u8 gText_PokemonCenter[] = _("Pokémon-Center");
const u8 gText_Coolness[] = _("Coolness ");
const u8 gText_Beauty3[] = _("Schönheit ");
const u8 gText_Cuteness[] = _("Anmut ");
const u8 gText_Smartness[] = _("Klugheit ");
const u8 gText_Toughness[] = _("Stärke ");
const u8 gText_SaveFailedCheckingBackup[] = _("Speicherfehler! Backup Memory\nwird geprüft. Bitte warten…\n{COLOR RED}“Benötigte Zeit: 1 Minute”");
const u8 gText_BackupMemoryDamaged[] = _("Backup Memory defekt oder interne\nBatterie verbraucht! Weiterspielen\nmöglich, speichern nicht!");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}“Spiel fortsetzen nicht möglich.\nZurück zum Titelbildschirm…”");
const u8 gText_CheckCompleted[] = _("Überprüfung beendet.\nNeuer Speicherversuch erfolgt.\nBitte warten…");
const u8 gText_SaveCompleteGameCannotContinue[] = _("Speichern beendet.\n{COLOR RED}“Spiel fortsetzen nicht möglich.\nZurück zum Titelbildschirm.”");
const u8 gText_SaveCompletePressA[] = _("Speichern beendet.\n{COLOR RED}“Bitte A-Knopf drücken.”");
const u8 gText_Ferry[] = _("Fähre");
const u8 gText_SecretBase[] = _("Geheimbasis");
const u8 gText_Hideout[] = _("Versteck");
const u8 gText_ResetRTCConfirmCancel[] = _("Echtzeituhr zurücksetzen?\nA: Bestätigen, B: Zurück");
const u8 gText_PresentTime[] = _("Aktuelle Uhrzeit im Spiel");
const u8 gText_PreviousTime[] = _("Vorherige Uhrzeit im Spiel");
const u8 gText_PleaseResetTime[] = _("Bitte die Zeit zurückstellen.");
const u8 gText_ClockHasBeenReset[] = _("Die Uhr wurde zurückgestellt. Daten\nwerden gesichert. Bitte warten…");
const u8 gText_SaveCompleted[] = _("Speichern beendet.");
const u8 gText_SaveFailed[] = _("Speichern fehlgeschlagen.");
const u8 gText_NoSaveFileCantSetTime[] = _("Es existiert kein Speicherstand. Uhr-\nzeit kann nicht eingestellt werden.");
const u8 gText_InGameClockUsable[] = _("Das spielinterne Zeiteingabe-\nSystem ist jetzt verfügbar.");
const u8 gText_Spicy2[] = _("scharf");
const u8 gText_Dry2[] = _("trocken");
const u8 gText_Sweet2[] = _("süß");
const u8 gText_Bitter2[] = _("bitter");
const u8 gText_Sour2[] = _("sauer");
const u8 gText_Single[] = _("Einzel");
const u8 gText_Double[] = _("Doppel");
const u8 gText_Knockout[] = _("Knockout");
const u8 gText_Mixed[] = _("Gemischt");
const u8 gText_First[] = _("ersten Preis");
const u8 gText_Second[] = _("zweiten Preis");
const u8 gText_Third[] = _("dritten Preis");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} wurde besiegt…\p\n");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} überlebt das Gift.\nDas Gift ist verschwunden!\p");
#endif
const u8 gText_PkmnSurvived_FldPsn[] = _("{STR_VAR_1} überlebt das Gift.\nDas Gift ist verschwunden!\p");
const u8 gText_Marco[] = _("Marco");
const u8 gText_TrainerCardName[] = _("Name ");
const u8 gText_TrainerCardIDNo[] = _("Idnr.");
const u8 gText_TrainerCardMoney[] = _("Geld");
const u8 gText_PokeDollar[] = _("¥"); // Unused
const u8 gText_TrainerCardPokedex[] = _("Pokédex");
const u8 gText_EmptyString6[] = _("");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _(" points"); // Unused
const u8 gText_TrainerCardTime[] = _("Spielzeit");
const u8 gJPText_BattlePoints[] = _("ゲ-ムポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("Trainerpass von {STR_VAR_1}");
const u8 gText_HallOfFameDebut[] = _("Erste Ruhmeshalle:");
const u8 gText_LinkBattles[] = _("Kämpfe via Link");
const u8 gText_LinkCableBattles[] = _("Kämpfe gg. Freund/E");
const u8 gText_WinsLosses[] = _("S.: {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  N.: {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("Pokémon-Tausch:");
const u8 gText_UnionTradesAndBattles[] = _("Konnex-Tausche & -Kämpfe:");
const u8 gText_BerryCrush[] = _("Beerenmühle:");
const u8 gText_WaitingTrainerFinishReading[] = _("Der andere Trainer hat deinen\nTrainerpass noch nicht gelesen.");
const u8 gText_PokeblocksWithFriends[] = _("{POKEBLOCK} mit Freund/En:");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("Gew. Wettbewerbe mit Freunden:");
const u8 gText_BattlePtsWon[] = _("Erhaltene Gewinnpunkte:");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}GP");
const u8 gText_BattleTower[] = _("Duellturm");
const u8 gText_WinsStraight[] = _("S.:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} in Folge:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("Duellturm");
const u8 gText_BattleDome[] = _("Kampfstadion");
const u8 gText_BattlePalace[] = _("Kampfpalast");
const u8 gText_BattleFactory[] = _("Kampffabrik");
const u8 gText_BattleArena[] = _("Kampfring");
const u8 gText_BattlePike[] = _("Kampfipitis");
const u8 gText_BattlePyramid[] = _("Kampfpyramide");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} Einzel");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} Doppel");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} Multi");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} Link");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("Geben");
const u8 gText_NoNeed[] = _("Nein");
const u8 gText_AnnouncingResults[] = _("Bekanntgabe der Ergebnisse!");
const u8 gText_PreliminaryResults[] = _("Ergebnisse 1. Durchlauf!");
const u8 gText_Round2Results[] = _("Ergebnisse 2. Durchlauf!");
const u8 gText_ContestantsMonWon[] = _("Sieger ist: {STR_VAR_2} von {STR_VAR_1}!");
const u8 gText_CommunicationStandby[] = _("Verbindung…");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{COLOR_HIGHLIGHT_SHADOW DYNAMIC_COLOR6 WHITE DYNAMIC_COLOR5}"); // Unused
const u8 gText_HealthboxNickname[] = _("{HIGHLIGHT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("Groß");
const u8 gText_Lower[] = _("klein");
const u8 gText_Others[] = _("Others");
const u8 gText_Symbols[] = _("Symbole");
const u8 gText_Register2[] = _("Wählen");
const u8 gText_Exit2[] = _("Beenden");
const u8 gText_QuitChatting[] = _("Chat beenden?");
const u8 gText_RegisterTextWhere[] = _("Wo in Liste schreiben?");
const u8 gText_RegisterTextHere[] = _("Hier in Liste schreiben?");
const u8 gText_InputText[] = _("Text schreiben.");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0} ist im Chat!");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0} verließ den Chat.");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("Chat wird verlassen…");
const u8 gText_LeaderLeftEndingChat[] = _("Leiter {DYNAMIC 0} verlässt und\nbeendet somit den Chat.");
const u8 gText_RegisteredTextChangedOKToSave[] = _("Der Text in der Liste wurde geändert.\nSoll gespeichert werden?");
const u8 gText_AlreadySavedFile_Chat[] = _("Es gibt bereits einen Spielstand.\nSpielstand überschreiben?");
const u8 gText_SavingDontTurnOff_Chat[] = _("Speichervorgang…\nGerät Nicht Ausschalten!");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0} hat das Spiel gespeichert.");
const u8 gText_IfLeaderLeavesChatEnds[] = _("Falls der Leiter den Chat\nverlässt, ist er vorüber, O.K.?");
const u8 gText_Hello[] = _("Hallo");
const u8 gText_Pokemon2[] = _("Pokémon");
const u8 gText_Trade[] = _("Tausch");
const u8 gText_Battle[] = _("Kampf");
const u8 gText_Lets[] = _("Auf");
const u8 gText_Ok[] = _("O.K.!");
const u8 gText_Sorry[] = _("Sorry");
const u8 gText_YaySmileEmoji[] = _("Yo{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("Danke");
const u8 gText_ByeBye[] = _("Tschüss!");
const u8 gText_HatchedFromEgg[] = _("{STR_VAR_1} schlüpfte aus dem Ei!");
const u8 gText_NicknameHatchPrompt[] = _("Möchtest du dem geschlüpften\n{STR_VAR_1} einen Kosenamen geben?");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("Die Beerenmühle starten?\nBitte wähle eine Beere aus!\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("Bitte warte, bis alle Mitspieler\nBeeren ausgewählt haben.");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}Du hast {STR_VAR_1} Einheiten seiden-\nweichen Beerenpuder erhalten.{RESUME_MUSIC}\pDein Bestand an Beerenpuder ist\n{STR_VAR_2} Einheiten.\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("Das Resultat wird gespeichert.\nBitte warten!");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("Möchtest du erneut die\nBeerenmühle betreiben?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("Du hast keine Beeren!\nDas Spiel wird abgebrochen.");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("Ein Mitspieler hat abgebrochen.\nDas Spiel wird beendet.");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("Die Zeit ist abgelaufen!\pEs konnte kein guter Beerenpuder\nhergestellt werden…\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("Verbindung…");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _("-mal");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("{STR_VAR_1}Beere");
ALIGNED(4) const u8 gText_TimeColon[] = _("Zeit:");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("Mahltempo:");
ALIGNED(4) const u8 gText_Silkiness[] = _("Feinheit:");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _("Min. ");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _("Sek.");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _("-mal/Sek.");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1} %");
ALIGNED(4) const u8 gText_PressesRankings[] = _("Platz nach Druckvorgängen");
ALIGNED(4) const u8 gText_CrushingResults[] = _("Mahlresultat");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("Beschaffenheits-Platzierung");
ALIGNED(4) const u8 gText_CoopRankings[] = _("Kooperations-Platzierung");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("Druckkraft-Platzierung");
const u8 gText_BerryCrush2[] = _("Beerenmühle");
const u8 gText_PressingSpeedRankings[] = _("Drucktempo-Platzierung");
const u8 gText_Var1Players[] = _("{STR_VAR_1} Spieler");
const u8 gText_SymbolsEarned[] = _("Gew. Symbole");
const u8 gText_BattleRecord[] = _("Video");
const u8 gText_BattlePoints[] = _("Gewinnpunkte");
const u8 gText_UnusedCancel[] = _("Cancel"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("Kampfzonenkarte ansehen");
const u8 gText_CheckTrainerCard[] = _("Trainerpass ansehen");
const u8 gText_ViewRecordedBattle[] = _("Kampfaufzeichnung ansehen");
const u8 gText_PutAwayFrontierPass[] = _("Kampfzonenpass wegstecken");
const u8 gText_CurrentBattlePoints[] = _("Aktuelle Anzahl der Gewinnpunkte");
const u8 gText_CollectedSymbols[] = _("Die erhaltenen Symbole");
const u8 gText_BattleTowerAbilitySymbol[] = _("Duellturm - Anlagesymbol");
const u8 gText_BattleDomeTacticsSymbol[] = _("Kampfstadion - Taktiksymbol");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("Kampfpalast - Seelensymbol");
const u8 gText_BattleArenaGutsSymbol[] = _("Kampfring - Grobsymbol");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("Kampffabrik - Kenntnissymbol");
const u8 gText_BattlePikeLuckSymbol[] = _("Kampfipitis - Lossymbol");
const u8 gText_BattlePyramidBraveSymbol[] = _("Kampfpyramide - Bravursymbol");
const u8 gText_ThereIsNoBattleRecord[] = _("Es gibt keine Kampfaufzeichnung.");
const u8 gText_BattleTower3[] = _("Duellturm");
const u8 gText_BattleDome2[] = _("Kampfstadion");
const u8 gText_BattlePalace2[] = _("Kampfpalast");
const u8 gText_BattleArena2[] = _("Kampfring");
const u8 gText_BattleFactory2[] = _("Kampffabrik");
const u8 gText_BattlePike2[] = _("Kampfipitis");
const u8 gText_BattlePyramid2[] = _("Kampfpyramide");
const u8 gText_BattleTowerDesc[] = _("Kämpfe, bis du die Spitze erreichst!\nDeine Anlagen werden geprüft.");
const u8 gText_BattleDomeDesc[] = _("Gewinne das Turnier!\nDeine Taktik wird geprüft.");
const u8 gText_BattlePalaceDesc[] = _("Achte auf deine Pokémon!\nDeine Seele wird geprüft.");
const u8 gText_BattleArenaDesc[] = _("Gewinne im Team!\nDeine Grobheit wird geprüft.");
const u8 gText_BattleFactoryDesc[] = _("Gewinne mit Leih-Pokémon!\nDeine Kenntnisse werden geprüft.");
const u8 gText_BattlePikeDesc[] = _("Wähle einen der drei Pfade aus!\nDein Los wird geprüft.");
const u8 gText_BattlePyramidDesc[] = _("Forsche dich ganz nach oben!\nDeine Bravur wird geprüft.");
const u8 gText_Powder[] = _("Puder");
const u8 gText_BerryPickingRecords[] = _("Rekorde für Beerenernte mit Dodri");
const u8 gText_BerriesPicked[] = _("Geerntete Beeren:");
const u8 gText_BestScore[] = _("Höchstpunktzahl:");
const u8 gText_BerriesInRowFivePlayers[] = _("Geerntete Beeren in Folge bei\nfünf Spielern:");
const u8 gText_BerryPickingResults[] = _("Resultat der Beerenernte!");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 0x03}10Pkt.{CLEAR_TO 0x2B}30Pkt.{CLEAR_TO 0x53}50Pkt.{CLEAR_TO 0x77}{EMOJI_MINUS}50Pkt.");
const u8 gText_AnnouncingRankings[] = _("Die Platzierungen!");
const u8 gText_AnnouncingPrizes[] = _("Die Preise!");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("Der Erstplatzierte erhält:\n{DYNAMIC 0}!");
const u8 gText_CantHoldAnyMore[] = _("Mehr tragen unmöglich.");
const u8 gText_FilledStorageSpace[] = _("Der Lagerplatz wurde aufgebraucht.");
const u8 gText_WantToPlayAgain[] = _("Erneut spielen?");
const u8 gText_SomeoneDroppedOut[] = _("Irgendjemand hat abgebrochen!\nVerbindung wird abgebrochen!");
const u8 gText_SpacePoints[] = _(" Punkte");
const u8 gText_CommunicationStandby3[] = _("Verbindung…");
const u8 gText_SpacePoints2[] = _(" Punkte");
const u8 gText_SpaceTimes3[] = _("-mal");
const u8 gText_PkmnJumpRecords[] = _("Rekorde für Pokémon-Sprung");
const u8 gText_JumpsInARow[] = _("Sprünge in Folge:");
const u8 gText_BestScore2[] = _("Höchstpunktzahl:");
const u8 gText_ExcellentsInARow[] = _("Famos in Folge:");
const u8 gText_AwesomeWonF701F700[] = _("Tolle Leistung! Du hast\n{DYNAMIC 1} {DYNAMIC 0} gewonnen!");
const u8 gText_FilledStorageSpace2[] = _("Kein Platz mehr!");
const u8 gText_CantHoldMore[] = _("Mehr tragen unmöglich.");
const u8 gText_WantToPlayAgain2[] = _("Erneut spielen?");
const u8 gText_SomeoneDroppedOut2[] = _("Irgendjemand hat abgebrochen!\nVerbindung wird abgebrochen!");
const u8 gText_CommunicationStandby4[] = _("Verbindung…");
const u8 gText_LinkContestResults[] = _("Linkwettbewerbsergebnis v. {PLAYER}");
const u8 gText_1st[] = _("1. ");
const u8 gText_2nd[] = _("2. ");
const u8 gText_3rd[] = _("3. ");
const u8 gText_4th[] = _("4. ");
const u8 gText_Friend[] = _("Friend");
const u8 gText_Pokemon3[] = _("Pokémon"); // Unused
const u8 gJPText_MysteryGift[] = _("ふしぎなもらいもの");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}けってい {B_BUTTON}やめる");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("カードeリーダー{PLUS}　で\nふしぎなもらいものを　よみこみます");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の　メニューから\n‘つうしん'を　えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("‘ゲームボーイアドバンスとつうしん'\nを　せんたく　してください");
const u8 gJPText_SelectConnectAndPressA[] = _("カードeリーダー{PLUS}の　‘つうしん'を\nえらんで　Aボタンを　おしてください"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("せつぞくが　まちがっています");
const u8 gJPText_CardReadingHasBeenHalted[] = _("カードの　よみこみを\nちゅうし　しました");
const u8 gJPText_UnableConnectWithEReader[] = _("カードeリーダー{PLUS}と\nつうしん　できません"); // Unused
const u8 gJPText_Connecting[] = _("つうしん　ちゅう　です");
const u8 gJPText_ConnectionErrorCheckLink[] = _("つうしん　エラーです\nせつぞくを　たしかめて　ください");
const u8 gJPText_ConnectionErrorTryAgain[] = _("つうしん　エラーです\nはじめから　やりなおして　ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS}　に\nカードを　よみこませて　ください");
const u8 gJPText_ConnectionComplete[] = _("つうしん　しゅうりょう！");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな　トレーナーが\nホウエンに　やってきた！");
const u8 gJPText_PleaseWaitAMoment[] = _("しばらく　おまちください");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ　エラー　です\nデータが　ほぞん　できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("Einzelkampfraumergebnis von {PLAYER}");
const u8 gText_DoubleBattleRoomResults[] = _("Doppelkampfraumergebnis von {PLAYER}");
const u8 gText_MultiBattleRoomResults[] = _("Multikampfraumergebnis von {PLAYER}");
const u8 gText_LinkMultiBattleRoomResults[] = _("Linkmultikampfraumergebnis von {PLAYER}");
const u8 gText_SingleBattleTourneyResults[] = _("Einzelturnierkampfergebnis von {PLAYER}");
const u8 gText_DoubleBattleTourneyResults[] = _("Doppelturnierkampfergebnis von {PLAYER}");
const u8 gText_SingleBattleHallResults[] = _("Einzelaufsichtshallenergebnis v. {PLAYER}");
const u8 gText_DoubleBattleHallResults[] = _("Doppelaufsichtshallenergebnis v. {PLAYER}");
const u8 gText_BattleChoiceResults[] = _("Kampfbahnergebnis von {PLAYER}");
const u8 gText_SetKOTourneyResults[] = _("K.O.-Teamturnierergebnis von {PLAYER}");
const u8 gText_BattleSwapSingleResults[] = _("Wechselkampfeinzelergebnis von {PLAYER}");
const u8 gText_BattleSwapDoubleResults[] = _("Wechselkampfdoppelergebnis von {PLAYER}");
const u8 gText_BattleQuestResults[] = _("Kampfforschungsergebnis von {PLAYER}");
const u8 gText_Lv502[] = _("LV. 50");
const u8 gText_OpenLv[] = _("Freies Lv.");
const u8 gText_WinStreak[] = _("Siegesserie: {STR_VAR_1}");
const u8 gText_Current[] = _("Moment.");
const u8 gText_Record[] = _("Rekord");
const u8 gText_Prev[] = _("Vorher");
const u8 gText_RentalSwap[] = _("Leih/Wechsel");
const u8 gText_Total[] = _("Gesamt");
const u8 gText_ClearStreak[] = _("Erfolgsserie: {STR_VAR_1}");
const u8 gText_Championships[] = _("Gesamtgewinne: {STR_VAR_1}");
const u8 gText_RoomsCleared[] = _("Absolv. Räume: {STR_VAR_1}");
const u8 gText_TimesCleared[] = _("Erf. Teilnahmen: {STR_VAR_1}");
const u8 gText_KOsInARow[] = _("K.O.-Serie: {STR_VAR_1}");
const u8 gText_TimesVar1[] = _("Anzahl: {STR_VAR_1}");
const u8 gText_FloorsCleared[] = _("Abs. Eb.: {STR_VAR_1}");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("LV. 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("Offene Kämpfe");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("Siegesserie: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("Erfolgsserie: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("Absolv. Räume: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("K.O.-Serie: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("Abs. Eb.: {STR_VAR_2}");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _(" und {STR_VAR_2} der gefangenen\nPokémon-Arten sind nicht zugelassen");
const u8 gText_FrontierFacilityIncluding[] = _(".\pThese include ");
const u8 gText_FrontierFacilityAreInelegible[] = _(" sind nicht zugelassen");

const u8 gText_YesNo[] = _("Ja\nNein");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("Prüfblick");
const u8 gText_CommErrorCheckConnections[] = _("Verbindungsfehler…\nÜberprüfe bitte alle Verbindungen\nund schalte das Gerät aus und wieder ein.");
const u8 gText_CommErrorEllipsis[] = _("Verbindungsfehler…");
const u8 gText_MoveCloserToLinkPartner[] = _("Verkürze die Distanz zum Mitspieler.\nVermeide Hindernisse zum Mitspieler.");
const u8 gText_ABtnRegistrationCounter[] = _("A-Knopf: Rezeption");
const u8 gText_ABtnTitleScreen[] = _("A-Knopf: Titelbildschirm");
const u8 gText_NumPlayerLink[] = _("{STR_VAR_1}Sp-Link");
const u8 gText_BronzeCard[] = _("Bronze");
const u8 gText_CopperCard[] = _("Kupferrot");
const u8 gText_SilverCard[] = _("Silber");
const u8 gText_GoldCard[] = _("Gold");
const u8 gText_Day[] = _("Tag");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("O.K.");
const u8 gText_Days[] = _("Tage"); // Unused
const u8 gText_TimeColon2[] = _("Zeit"); // Unused
const u8 gText_GameTime[] = _("Spielzeit"); // Unused
const u8 gText_RTCTime[] = _("Echtzeituhr"); // Unused
const u8 gText_UpdatedTime[] = _("Aktualisierte Zeit"); // Unused
const u8 gText_MenuPokedex[] = _("Pokédex");
const u8 gText_MenuPokemon[] = _("Pokémon");
const u8 gText_MenuBag[] = _("Beutel");
#if IS_HNS
const u8 gText_MenuPokenav[] = _("{POKE}Com");
#else
const u8 gText_MenuPokenav[] = _("Pokénav");
#endif
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("Sichern");
const u8 gText_MenuOption[] = _("Option.");
const u8 gText_MenuExit[] = _("Beenden");
const u8 gText_MenuRetire[] = _("Schluss");
const u8 gText_MenuRest[] = _("Ausruhen");
const u8 gText_MenuDexNav[] = _("Dexnav");
const u8 gText_SafariBallStock[] = _("Safaribälle\nVorrat: {STR_VAR_1}");
const u8 gText_MenuSafariStats[] = _("{STR_VAR_1}/{STR_VAR_2}\nBälle  {STR_VAR_3}");
const u8 gText_BattlePyramidFloor[] = _("Kampfpyramide\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("Erdgeschoss");
const u8 gText_Floor2[] = _("Ebene 2");
const u8 gText_Floor3[] = _("Ebene 3");
const u8 gText_Floor4[] = _("Ebene 4");
const u8 gText_Floor5[] = _("Ebene 5");
const u8 gText_Floor6[] = _("Ebene 6");
const u8 gText_Floor7[] = _("Ebene 7");
const u8 gText_Peak[] = _("Spitze");
const u8 gText_LinkStandby2[] = _("Verbindung…\n… … B-Knopf: Abbrechen");
const u8 gText_PressAToLoadEvent[] = _("Lade Geschehen mit A-Knopf.\n… … B-Knopf: Abbrechen");
const u8 gText_LoadingEvent[] = _("Geschehen wird geladen.");
const u8 gText_DontRemoveCableTurnOff[] = _("Verbindungskabel nicht entfernen!\nDie Geräte nicht ausschalten!");
const u8 gText_EventSafelyLoaded[] = _("Geschehen ist erfolgreich geladen.");
const u8 gText_LoadErrorEndingSession[] = _("Fehler beim Laden!\nVorgang wird abgebrochen.");
const u8 gJPText_Player[] = _("プレイヤー"); // Unused
const u8 gJPText_Sama[] = _("さま"); // Unused
const u8 gText_DexHoenn[] = _("Hoenn");
const u8 gText_DexNational[] = _("Nationaler");
const u8 gText_PokedexDiploma[] = _("Spieler: {CLEAR 0x10}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\n{STR_VAR_1} Pokédex\nDieses Dokument bescheinigt\ndie erfolgreiche Vervoll-\nständigung des Pokédex.\n\n{CLEAR_TO 0x42}{COLOR RED}{SHADOW LIGHT_RED}Game Freak");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}ゲ-ムフリ-ク"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("Hoenn");
const u8 gText_Kanto[] = _("Kanto");
const u8 gText_Johto[] = _("Johto");
const u8 gText_JohtoKanto[] = _("Johto & Kanto");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_2} wird\n{STR_VAR_1} zugesandt.");
const u8 gText_ByeByeVar1[] = _("Tschüss, {STR_VAR_2}!");
const u8 gText_XSentOverY[] = _("{STR_VAR_1} versandte {STR_VAR_3}.");
const u8 gText_TakeGoodCareOfX[] = _("Kümmere dich gut um {STR_VAR_3}!");

const u8 gText_ThreeQuestionMarks[] = _("???");
const u8 gText_FourQuestionMarks[] = _("????");
const u8 gText_MaxHP[] = _("Max. KP");
const u8 gText_Attack[] = _("Angriff");
const u8 gText_Defense[] = _("Vert.");
const u8 gText_Speed[] = _("Init.");
const u8 gText_SpAtk[] = _("Sp. Ang.");
const u8 gText_SpDef[] = _("Sp. Ver.");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("-");
const u8 gText_MixingRecords[] = _("Rekorddaten-Austausch…");
const u8 gText_RecordMixingComplete[] = _("Rekorddaten-Austausch beendet.\nVielen Dank für deine Geduld.");
const u8 gText_RentalPkmn2[] = _("Leih-Pokémon");
const u8 gText_SelectFirstPkmn[] = _("Wähle das erste Pokémon!");
const u8 gText_SelectSecondPkmn[] = _("Wähle das zweite Pokémon!");
const u8 gText_SelectThirdPkmn[] = _("Wähle das dritte Pokémon!");
const u8 gText_Rent[] = _("Verleih");
const u8 gText_Summary[] = _("Bericht");
const u8 gText_Others2[] = _("Andere");
const u8 gText_Deselect[] = _("Entfernen");
const u8 gText_TheseThreePkmnOkay[] = _("Diese drei Pkmn auswählen?");
const u8 gText_Yes2[] = _("Ja");
const u8 gText_No2[] = _("Nein");
const u8 gText_CantSelectSamePkmn[] = _("Wahl desselben {PKMN} unmögl.");
const u8 gText_PkmnSwap[] = _("Pokémon-Wechsel");
const u8 gText_SelectPkmnToSwap[] = _("Wähle das zu wechselnde {PKMN}.");
const u8 gText_SelectPkmnToAccept[] = _("Bestätige das gewählte {PKMN}.");
const u8 gText_Swap[] = _("Wechsel");
const u8 gText_Summary2[] = _("Bericht");
const u8 gText_Rechoose[] = _("Neuwahl");
const u8 gText_QuitSwapping[] = _("Wechseln beenden?");
const u8 gText_Yes3[] = _("Ja");
const u8 gText_No3[] = _("Nein");
const u8 gText_PkmnForSwap[] = _("Wechselpkmn");
const u8 gText_Cancel3[] = _("Abbruch");
const u8 gText_Swap2[] = _("Swap"); // Unused
const u8 gText_Accept[] = _("Accept"); // Unused
const u8 gText_AcceptThisPkmn[] = _("Dieses {PKMN} annehmen?");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("Selbes {PKMN} bereits im Team.");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("Spieler");
const u8 gText_SavingBadges[] = _("Orden");
const u8 gText_SavingPokedex[] = _("Pokédex");
const u8 gText_SavingTime[] = _("Spielzeit");
const u8 gText_WirelessCommStatus[] = _("Drahtlose Verbindungen:");
const u8 gText_PeopleTrading[] = _("Tauscher:");
const u8 gText_PeopleBattling[] = _("Kämpfer:");
const u8 gText_PeopleInUnionRoom[] = _("Begegnungen im Konnex-Klub:");
const u8 gText_PeopleCommunicating[] = _("Eingegangene Verbindungen:");
const u8 gText_F700Players[] = _("{DYNAMIC 0} Spieler");
const u8 gText_F701Players[] = _("{DYNAMIC 1} Spieler");
const u8 gText_F702Players[] = _("{DYNAMIC 2} Spieler");
const u8 gText_F703Players[] = _("{DYNAMIC 3} Spieler");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("Wunderkarten");
ALIGNED(4) const u8 gText_WonderNews[] = _("Wundernews");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("Drahtlose Verbindungen");
ALIGNED(4) const u8 gText_Friend2[] = _("Freund");
ALIGNED(4) const u8 gText_Exit3[] = _("Zurück");
ALIGNED(4) const u8 gText_Receive[] = _("Erhalten");
ALIGNED(4) const u8 gText_Send[] = _("Senden");
ALIGNED(4) const u8 gText_Toss[] = _("Müll");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("Einige Geschehen werden über die\nDrahtlose Verbindung importiert.");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("Lies die Wunderkarten in\ndeinem Besitz.");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("Lies die News!");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("Zurück zum Titelbildschirm.");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("Du hast keine Wunderkarte,\nalso wird eine neue Karte angelegt.");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("Du hast keine Wundernews,\nalso werden neue News angelegt.");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("Wo soll auf die Wunderkarte\nzugegriffen werden?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("Wo soll auf die Wundernews\nzugegriffen werden?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("Verbindung…\n… … B-Knopf: Abbrechen"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("Übertragung… ");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("Verbindung vollständig.");
ALIGNED(4) const u8 gText_CommunicationError[] = _("Übertragungsfehler.");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("Die Verbindung wurde abgebrochen.");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("Soll die Wunderkarte weggeworfen\nund die neue Karte benutzt werden?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("Geschenk dieser Karte noch nicht\nerhalten! Neue Karte benutzen?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("Eine Wunderkarte von {STR_VAR_1}\nerhalten.");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("Ein Wundernews-Item von {STR_VAR_1}\nerhalten.");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("Eine neue Wunderkarte erhalten.");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("Ein neues Wundernews-Item erhalten.");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("Einen neuen Stempel erhalten.");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("Ein neuer Trainer ist eingetroffen.");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("Diese Wunderkarte hattest\ndu bereits!");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("Dieses Wundernews-Item\nhattest du bereits.");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("Diesen Stempel hattest\ndu bereits.");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("Es gibt keinen Platz mehr, um\nStempel hinzuzufügen.");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("Dein Rekord wurde Drahtlos\nübertragen.");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("Du kannst von diesem Trainer\nkeine Wunderkarte annehmen.");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("Du kannst von diesem Trainer\nkeine Wundernews annehmen.");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("Es wurde nichts übertragen…");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("Was möchtest du mit den\nWunderkarten anstellen?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("Was möchtest du mit den\nWundernews anstellen?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("Wunderkarte wird übertragen…");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("Wundernews werden übertragen…");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("Deine Wunderkarte wurde zu\n{STR_VAR_1} übertragen.");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("Deine Wundernews wurden zu\n{STR_VAR_1} übertragen.");
ALIGNED(4) const u8 gText_StampSentTo[] = _("{STR_VAR_1} erhält einen Stempel.");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("{STR_VAR_1} erhält Geschehen.");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("Der andere Trainer hat diese\nWunderkarte bereits.");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("Der andere Trainer hat diese\nWundernews bereits.");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("Der andere Trainer hat diesen\nStempel bereits.");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("Der andere Trainer hat die\nVerbindung abgebrochen.");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("Du kannst diesem Trainer kein\nGeheimgeschehen übertragen.");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("Wenn du die Karte weg-\nwirfst, passiert nichts! O.K.?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("Soll dieses News-Item weg-\ngeworfen werden?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("Kein Geheimgeschehen!\nTrotzdem wegwerfen?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("Daten werden gesichert.\nBitte warten…");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("Speichern beendet.\nBitte A-Knopf drücken.");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("Wunderkarte weggeworfen!");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("Wundernews weggeworfen!");
ALIGNED(4) const u8 gText_MysteryGift[] = _("Geheimgeschehen");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}Wahl {A_BUTTON}O.K. {B_BUTTON}Beenden");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}Wahl {A_BUTTON}O.K. {B_BUTTON}Zurück");
const u8 gText_PlayersBattleResults[] = _("Kampfergebnisse von {PLAYER}");
const u8 gText_TotalRecordWLD[] = _("Gesamt-Rekord S.:{STR_VAR_1} N.:{STR_VAR_2} P.:{STR_VAR_3}");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 0x50}Sieg{CLEAR_TO 0x79}Nieder.{CLEAR_TO 0xB0}Patt");
const u8 gText_CommunicationStandby5[] = _("Verbindung…");
const u8 gDaycareText_GetAlongVeryWell[] = _("Die beiden scheinen sich sehr zu\nmögen.");
const u8 gDaycareText_GetAlong[] = _("Die beiden scheinen sich zu\nvertragen.");
const u8 gDaycareText_DontLikeOther[] = _("Die beiden mögen sich nicht sehr.");
const u8 gDaycareText_PlayOther[] = _("Die beiden spielen lieber mit\nanderen Pokémon als miteinander.");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("Keines");
const u8 gText_Lv[] = _("{LV}");
const u8 gText_TimeBoard[] = _("Zeittafel");
const u8 gText_TimeCleared[] = _("Benötigte Zeit ");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1} Min. {STR_VAR_2},{STR_VAR_3} Sek.");
const u8 gText_TrainerHill1F[] = _("EG");
const u8 gText_TrainerHill2F[] = _("1S");
const u8 gText_TrainerHill3F[] = _("2S");
const u8 gText_TrainerHill4F[] = _("3S");
const u8 gText_TeachWhichMoveToPkmn[] = _("{STR_VAR_1} welche Att. beibr.?");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("{STR_VAR_2} beibringen?");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1} lernte\n{STR_VAR_2}.");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1} versucht,\n{STR_VAR_2} zu erlernen.\pAber {STR_VAR_1} kann nicht mehr\nals vier Attacken erlernen.\pSoll eine Attacke zu Gunsten von\n{STR_VAR_2} vergessen werden?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("{STR_VAR_2} nicht erlernen?");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1, {PAUSE 15}2 {PAUSE 15}…{PAUSE 15}…{PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Schwupp!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1} vergaß\n{STR_VAR_3}.\pUnd…\p{STR_VAR_1} lernt {STR_VAR_2}.");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1} hat die Attacke\n{STR_VAR_2} nicht erlernt."); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("Soll {STR_VAR_1} keine neue\nAttacke erlernen?");
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("Welche Attacke soll vergessen\nwerden?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("Attacken");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("Wett.-Attacken");
const u8 gText_MoveRelearnerType[] = _("Type/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("AP/");
const u8 gText_MoveRelearnerPower[] = _("Stärke/");
const u8 gText_MoveRelearnerAccuracy[] = _("Genau./");
const u8 gText_MoveRelearnerAppeal[] = _("Ausdruck");
const u8 gText_MoveRelearnerJam[] = _("Eindruck");
const u8 gText_ClearAllSaveData[] = _("Alle gesich. Datenber. löschen?");
const u8 gText_ClearingData[] = _("Daten werden gelöscht…\nBitte warten…");
const u8 gText_IsThisTheCorrectTime[] = _("Ist die Uhrzeit korrekt?");
const u8 gText_Confirm3[] = _("O.K.");
const u8 gText_Cancel4[] = _("Zurück");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("Verbindungsaufbau…\nMitspieler wird erwartet.");
const u8 gText_BattleWasRefused[] = _("Der Kampf wurde abgesagt.{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("Kampfabsage.{PAUSE 60}");
const u8 gText_NoWeather[] = _("Wetterlos"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("Sonnig"); // Unused
const u8 gText_Sunny2[] = _("Sonnig 2"); // Unused
const u8 gText_Rain[] = _("Regen"); // Unused
const u8 gText_Snow[] = _("Schnee"); // Unused
const u8 gText_Lightning[] = _("Gewitter"); // Unused
const u8 gText_Fog[] = _("Nebel"); // Unused
const u8 gText_VolcanoAsh[] = _("Vulkanasche"); // Unused
const u8 gText_Sandstorm[] = _("Sandsturm"); // Unused
const u8 gText_Fog2[] = _("Nebel 2"); // Unused
const u8 gText_Seafloor[] = _("Tiefsee"); // Unused
const u8 gText_Cloudy[] = _("Wolkig"); // Unused
const u8 gText_Sunny3[] = _("Sonnig 3"); // Unused
const u8 gText_HeavyRain[] = _("Wolkenbruch"); // Unused
const u8 gText_Seafloor2[] = _("Tiefsee2"); // Unused
const u8 gText_DelAll[] = _("Löschen");
const u8 gText_Cancel5[] = _("Abbruch");
const u8 gText_Ok2[] = _("O.K.");
const u8 gText_Quiz[] = _("Quiz");
const u8 gText_Answer[] = _("Antwort");
const u8 gText_PokeBalls[] = _("Pokébälle");
const u8 gText_Berry[] = _("Beere");
const u8 gText_Berries[] = _("Beeren");
const u8 gText_Obtained999RareCandies[] = _("Du hast 999 Sonderbonbons\nerhalten!{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOn[] = _("Der EP-Teiler wurde aktiviert.{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("Der EP-Teiler wurde deaktiviert.{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("Geist");
const u8 gText_Boulderbadge[] = _("Felsorden");
const u8 gText_Cascadebadge[] = _("Quellorden");
const u8 gText_Thunderbadge[] = _("Donnerorden");
const u8 gText_Rainbowbadge[] = _("Farborden");
const u8 gText_Soulbadge[] = _("Seelenorden");
const u8 gText_Marshbadge[] = _("Sumpforden");
const u8 gText_Volcanobadge[] = _("Vulkanorden");
const u8 gText_Earthbadge[] = _("Erdorden");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("Eich: Es ist wichtig deine\nPokémon gut kennenzulernen.\p");
const u8 gText_OakThisIsListOfPokemon[] = _("Dies ist eine Liste deiner Pokémon,\n{PLAYER}.\pÖffne dies um die Attacken und\nFähigkeiten zu sehen.\pDu kannst sie hier auch auswählen\num ihnen ein Item zu geben.{PAUSE_UNTIL_PRESS}");

const u8 gText_GBPlayerOn[] = _("Der GB geht an.\nNostalgie füllt die Luft.{PAUSE_UNTIL_PRESS}");
const u8 gText_GBPlayerOff[] = _("GB ausgeschaltet.{PAUSE_UNTIL_PRESS}");

const u8 gText_Sunday[] = _("Sonntag");
const u8 gText_Monday[] = _("Montag");
const u8 gText_Tuesday[] = _("Dienstag");
const u8 gText_Wednesday[] = _("Mittwoch");
const u8 gText_Thursday[] = _("Donnerstag");
const u8 gText_Friday[] = _("Freitag");
const u8 gText_Saturday[] = _("Samstag");
const u8 gText_LoveBall[] =     _("Sympaball / Pirsifbeere / (FEE/PSY)");
const u8 gText_Lure[] =         _("Köderball / Fragiabeere / (WAS/DRA)");
const u8 gText_FriendBall[] =   _("Freundesball / Amrenabeere / (KÄF/PFL)");
const u8 gText_Heavy[] =        _("Schwerball / Sinelbeere / (GES/BOD/STA)");
const u8 gText_Moon[] =         _("Mondball / Maronbeere / (UNL/GEI/GIF)");
const u8 gText_Fast[] =         _("Turboball / Wilbirbeere / (ELE/KAM/FEU)");
const u8 gText_LevelBall[] =    _("Levelball / Persimbeere / (NOR/FLU/EIS)");
const u8 gText_Vermilion[] = _("Orania-City");
const u8 gText_Olivine[] = _("Oliviana-City");
const u8 gText_Abra[] = _("Abra{CLEAR_TO 0x58}120");
const u8 gText_Clefairy[] = _("Piepi{CLEAR_TO 0x58}500");
const u8 gText_Munchlax[] = _("Mampfaxo{CLEAR_TO 0x58}2800");
const u8 gText_Dratini[] = _("Dratini{CLEAR_TO 0x58}5500");
const u8 gText_Porygon[] = _("Porygon{CLEAR_TO 0x58}6500");
const u8 gText_Floor0[] = _("Keller");
const u8 gText_Pal[] = _("Kumpel");
const u8 gText_Underling[] = _("Untergebener");
const u8 gText_Strategy[] = _("Strategie");
const u8 gText_Training[] = _("Training");
const u8 gText_Cheating[] = _("Schummeln");
const u8 gText_WeakPerson[] = _("Schwache Person");
const u8 gText_ToughPerson[] = _("Starke Person");
const u8 gText_Anybody[] = _("Irgendjemand");
const u8 gText_Love2[] = _("Liebe");
const u8 gText_Violence[] = _("Gewalt");
const u8 gText_Knowledge[] = _("Wissen");
const u8 gText_Tough3[] = _("Zäh");
const u8 gText_Weak[] = _("Schwach");
const u8 gText_Both[] = _("Beides");
const u8 gText_GreenStone[] = _("Grüner Stein");
const u8 gText_RedStone[] = _("Roter Stein");
const u8 gText_BlueStone[] = _("Blauer Stein");
