#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("");
const u8 gText_ExpandedPlaceholder_Chan[] = _("");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("SAPHIR");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("RUBIN");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("SMARAGD");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("AQUA");
const u8 gText_ExpandedPlaceholder_Magma[] = _("MAGMA");
const u8 gText_ExpandedPlaceholder_Archie[] = _("ADRIAN");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("MARC");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("KYOGRE");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("GROUDON");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("BRIX");
const u8 gText_ExpandedPlaceholder_May[] = _("MAIKE");
const u8 gText_ExpandedPlaceholder_Red[] = _("ROT");
const u8 gText_ExpandedPlaceholder_Green[] = _("GRÜN");
const u8 gText_ExpandedPlaceholder_Silver[] = _("SILBER");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("EI");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("POKéMON");
const u8 gText_Player[] = _("PLAYER"); // Unused
const u8 gText_Pokedex[] = _("POKéDEX"); // Unused
const u8 gText_Time[] = _("TIME");
const u8 gText_Badges[] = _("BADGES"); // Unused
const u8 gText_AButton[] = _("A Button"); // Unused
const u8 gText_BButton[] = _("B Button"); // Unused
const u8 gText_RButton[] = _("R Button"); // Unused
const u8 gText_LButton[] = _("L Button"); // Unused
const u8 gText_Start[] = _("START"); // Unused
const u8 gText_Select[] = _("SELECT"); // Unused
const u8 gText_ControlPad[] = _("+ Control Pad"); // Unused
const u8 gText_LButtonRButton[] = _("L Button  R Button"); // Unused
const u8 gText_Controls[] = _("CONTROLS"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}WEITER");
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}WEITER {B_BUTTON}BACK");
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}WÄHLE {A_BUTTON}WEITER {B_BUTTON}ABBRUCH");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}PICK {A_BUTTON}{B_BUTTON}ABBRUCH");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}ZURÜCK");
const u8 gText_Boy[] = _("JUNGE");
const u8 gText_Girl[] = _("MÄDEL");
const u8 gText_ThisIsAPokemon[] = _("Dies ist ein sogenanntes\n“POKéMON.”{PAUSE 96}\p");
const u8 gText_5MarksPokemon[] = _("????? POKéMON");
const u8 gText_UnkHeight[] = _("{CLEAR_TO 0x0C}??'??”");
const u8 gText_UnkHeightMetric[] = _("???.? m");
const u8 gText_UnkWeight[] = _("????.? lbs.");
const u8 gText_UnkWeightMetric[] = _("???.? kg.");
const u8 gText_EmptyPkmnCategory[] = _("                       POKéMON"); // Unused
const u8 gText_EmptyHeight[] = _("{CLEAR_TO 0x0C}    '    ”"); // Unused
const u8 gText_EmptyWeight[] = _("        .   lbs."); // Unused
const u8 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u8 gText_CryOf[] = _("RUF VON");
const u8 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u8 gText_SizeComparedTo[] = _("GRÖSSE IM VERGLEICH ZU ");
const u8 gText_PokedexRegistration[] = _("Neuer Eintrag aufgenommen.");
const u8 gText_HTHeight[] = _("GR.");
const u8 gText_WTWeight[] = _("GEW.");
const u8 gText_SearchingPleaseWait[] = _("Suche läuft.\nBitte warten…");
const u8 gText_SearchCompleted[] = _("Suche beendet.");
const u8 gText_NoMatchingPkmnWereFound[] = _("Es wurde keine Übereinstimmung ermittelt.");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("Suche nach POKéMON anhand\nausgewählter Parameter.");
const u8 gText_SwitchPokedexListings[] = _("Ordnungssystem des POKéDEX ändern.");
const u8 gText_ReturnToPokedex[] = _("Kehre zurück zum POKéDEX.");
const u8 gText_SelectPokedexMode[] = _("Wähle einen POKéDEX.");
const u8 gText_SelectPokedexListingMode[] = _("Wähle ein Ordnungssystem des POKéDEX.");
const u8 gText_ListByFirstLetter[] = _("Nach Anfangsbuchstaben suchen.\n(Alle gesehenen POKéMON.)");
const u8 gText_ListByBodyColor[] = _("Nach Körperfarbe suchen.\n(Alle gesehenen POKéMON.)");
const u8 gText_ListByType[] = _("Nach Elementklasse suchen.\n(Nur gefangene POKéMON.)");
const u8 gText_ExecuteSearchSwitch[] = _("Suche/Änderung ausführen.");
#if IS_HNS
const u8 gText_DexHoennTitle[] = _("JOHTO DEX");
#else
const u8 gText_DexHoennTitle[] = _("HOENN DEX");
#endif
const u8 gText_DexNatTitle[] = _("NATIONALER DEX");
const u8 gText_DexSortNumericalTitle[] = _("NUMERISCH");
const u8 gText_DexSortAtoZTitle[] = _("VON A BIS Z");
const u8 gText_DexSortHeaviestTitle[] = _("NACH GEWICHT >");
const u8 gText_DexSortLightestTitle[] = _("NACH GEWICHT <");
const u8 gText_DexSortTallestTitle[] = _("NACH GRÖSSE >");
const u8 gText_DexSortSmallestTitle[] = _("NACH GRÖSSE <");
const u8 gText_DexSearchAlphaABC[] = _("ABC");
const u8 gText_DexSearchAlphaDEF[] = _("DEF");
const u8 gText_DexSearchAlphaGHI[] = _("GHI");
const u8 gText_DexSearchAlphaJKL[] = _("JKL");
const u8 gText_DexSearchAlphaMNO[] = _("MNO");
const u8 gText_DexSearchAlphaPQR[] = _("PQR");
const u8 gText_DexSearchAlphaSTU[] = _("STU");
const u8 gText_DexSearchAlphaVWX[] = _("VWX");
const u8 gText_DexSearchAlphaYZ[] = _("YZ");
const u8 gText_DexSearchColorRed[] = _("ROT");
const u8 gText_DexSearchColorBlue[] = _("BLAU");
const u8 gText_DexSearchColorYellow[] = _("GELB");
const u8 gText_DexSearchColorGreen[] = _("GRÜN");
const u8 gText_DexSearchColorBlack[] = _("SCHWARZ");
const u8 gText_DexSearchColorBrown[] = _("BRAUN");
const u8 gText_DexSearchColorPurple[] = _("LILA");
const u8 gText_DexSearchColorGray[] = _("GRAU");
const u8 gText_DexSearchColorWhite[] = _("WEISS");
const u8 gText_DexSearchColorPink[] = _("ROSA");
#if IS_HNS
const u8 gText_DexHoennDescription[] = _("JOHTO POKéDEX");
#else
const u8 gText_DexHoennDescription[] = _("HOENN POKéDEX");
#endif
const u8 gText_DexNatDescription[] = _("Nationaler POKéDEX");
const u8 gText_DexSortNumericalDescription[] = _("POKéMON werden anhand ihrer\nNummer sortiert.");
const u8 gText_DexSortAtoZDescription[] = _("Gesehene und gefangene POKéMON\nwerden alphabetisch geordnet.");
const u8 gText_DexSortHeaviestDescription[] = _("Gefangene POKéMON werden nach Gewicht\nsortiert, beginnend mit dem schwersten.");
const u8 gText_DexSortLightestDescription[] = _("Gefangene POKéMON werden nach Gewicht\nsortiert, beginnend mit dem leichtesten.");
const u8 gText_DexSortTallestDescription[] = _("Gefangene POKéMON werden nach Größe\nsortiert, beginnend mit dem größten.");
const u8 gText_DexSortSmallestDescription[] = _("Gefangene POKéMON werden nach Größe\nsortiert, beginnend mit dem kleinsten.");
const u8 gText_DexEmptyString[] = _("");
const u8 gText_DexSearchDontSpecify[] = _("KEINE ANGABE");
const u8 gText_DexSearchTypeNone[] = _("KEINER");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(" "); // Unused
const u8 gText_WelcomeToHOF[] = _("Willkommen in der RUHMESHALLE!");
const u8 gText_HOFDexRating[] = _("Spotted POKéMON: {STR_VAR_1}!\nOwned POKéMON: {STR_VAR_2}!\pPROF. BIRCH's POKéDEX rating!\pPROF. BIRCH: Let's see…\p");
const u8 gText_HOFDexSaving[] = _("SAVING…\nDON'T TURN OFF THE POWER.");
const u8 gText_HOFCorrupted[] = _("Die RH-Daten sind beschädigt.");
const u8 gText_HOFNumber[] = _("RUHMESHALLE, Nr. {STR_VAR_1}");
const u8 gText_LeagueChamp[] = _("CHAMP der POKéMON LIGA!\nHerzlichen Glückwunsch!");
const u8 gText_Number[] = _("Nr. ");
const u8 gText_Level[] = _("Lv.");
const u8 gText_IdNumberSlash[] = _("IDNo. /"); // Unused
const u8 gText_Name[] = _("TRAINER");
const u8 gText_IDNumber[] = _("ID.Nr.");
const u8 gText_BirchInTrouble[] = _("PROF. BIRK ist in Schwierigkeiten!\nSchnapp’ dir ein PKMN und hilf ihm!");
const u8 gText_ConfirmStarterChoice[] = _("Wählst du dieses POKéMON?");
const u8 gText_Pokemon4[] = _("POKéMON"); // Unused
const u8 gText_FlyToWhere[] = _("Wohin FLIEGEN?");
const u8 gMenuText_Use[] = _("BENUTZEN");
const u8 gMenuText_Toss[] = _("WERFEN");
const u8 gMenuText_Register[] = _("REGIST.");
const u8 gMenuText_Give[] = _("GEBEN");
const u8 gMenuText_Confirm[] = _("CONFIRM");
const u8 gText_Cancel[] = _("ZURÜCK");
const u8 gText_Cancel2[] = _("ZURÜCK");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("KEINES");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("-");
const u8 gText_TwoDashes[] = _("--");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("Lv.");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 0x01}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("Kehre zurück zum\nvorherigen Menü.");
const u8 gText_WhatWouldYouLike[] = _("Was möchtest du tun?");
const u8 gMenuText_Give2[] = _("GIVE");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _(" BERRY"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1} MÜNZ.");
const u8 gText_CloseBag[] = _("BEUTEL SCHLIESSEN");
const u8 gText_Var1IsSelected[] = _("Was möchtest\ndu tun?");
const u8 gText_CantWriteMail[] = _("Du kannst keinen\nBRIEF schreiben.");
const u8 gText_NoPokemon[] = _("Hier ist kein\nPOKéMON.");
const u8 gText_MoveVar1Where[] = _("Gegen welches Item\naustauschen?");
const u8 gText_Var1CantBeHeld[] = _("{STR_VAR_1} ist nicht zu geben.");
const u8 gText_TossHowManyVar1s[] = _("Wie viel in den Müll?");
const u8 gText_ThrewAwayVar2Var1s[] = _("{STR_VAR_2} × {STR_VAR_1}\nweggeworfen.");
const u8 gText_ConfirmTossItems[] = _("Willst du wirklich\n{STR_VAR_2} × {STR_VAR_1}\nwegwerfen?");
#if IS_HNS
    const u8 gText_DadsAdvice[] = _("LIND sagt immer…\n{PLAYER}, dies ist weder der rechte\lOrt noch der rechte Zeitpunkt dafür!{PAUSE_UNTIL_PRESS}");
#else
    const u8 gText_DadsAdvice[] = _("VATI sagt immer……\n{PLAYER}, dies ist weder der rechte\lOrt noch der rechte Zeitpunkt dafür!{PAUSE_UNTIL_PRESS}");
#endif
const u8 gText_PlayerUsedVar2[] = _("{PLAYER} setzt\n{STR_VAR_2} ein.{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("Aber SCHUTZ wirkt doch\nnoch!{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("But the effects of a Lure\nlingered from earlier.{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("Die BOXen sind voll.{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("zum Hauptmenü");
const u8 gText_TheBattle[] = _("zum Kampf");
const u8 gText_ThePokemonList[] = _("zur POKéMON-LISTE");
const u8 gText_TheShop[] = _("zum Geschäft");
const u8 gText_ThePC[] = _("zum PC");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("Zurück\n{STR_VAR_1}.");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS] =        COMPOUND_STRING("Items"),
    [POCKET_POKE_BALLS] =   COMPOUND_STRING("Pokébälle"),
    [POCKET_TM_HM]  =       COMPOUND_STRING("TMs & VMs"),
    [POCKET_BERRIES] =      COMPOUND_STRING("Beeren"),
    [POCKET_KEY_ITEMS] =    COMPOUND_STRING("Basis Items"),
    [POCKET_MEDICINE] =     COMPOUND_STRING("Medizin"),
#if I_COMBINE_BAG_POCKETS == FALSE
    [POCKET_BATTLE_ITEMS] = COMPOUND_STRING("Kampf"),
    [POCKET_TREASURES] =    COMPOUND_STRING("Schätze"),
#endif
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 0x03}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 0x11}{STR_VAR_1}{CLEAR 0x05}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("KAUFEN");
const u8 gText_ShopSell[] = _("VERKAUFEN");
const u8 gText_ShopQuit[] = _("TSCHÜSS!");
const u8 gText_ThatItemIsSoldOut[] = _("I'm sorry, but that item is sold out.{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("AUSVERKAUFT");
const u8 gText_InBagVar1[] = _("BESITZ: {STR_VAR_1}");
const u8 gText_QuitShopping[] = _("Einkauf beenden.");
const u8 gText_Var1CertainlyHowMany[] = _("{STR_VAR_1}? Aber gerne.\nWie viele möchtest du?");
const u8 gText_Var1CertainlyHowMany2[] = _("{STR_VAR_1} ist {STR_VAR_2}!\nGerne. Wie viele möchtest du?");
const u8 gText_Var1AndYouWantedVar2[] = _("{STR_VAR_1}? Und du möchtest {STR_VAR_2}?\nDas macht dann ¥{STR_VAR_3}.");
const u8 gText_Var1AndYouWantedVar2BP[] = _("{STR_VAR_1}? Und du möchtest {STR_VAR_2}?\nDas macht dann {STR_VAR_3}KP.");
const u8 gText_Var1IsItThatllBeVar2[] = _("{STR_VAR_1} soll es sein?\nDas kostet ¥{STR_VAR_2}. Einverstanden?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("Du wolltest {STR_VAR_1}?\nDas kostet ¥{STR_VAR_2}. Einverstanden?");
const u8 gText_YouWantedVar1ThatllBeVar2BP[] = _("You wanted {STR_VAR_1}?\nThat'll be {STR_VAR_2}BP. Will that be okay?");
const u8 gText_HereYouGoThankYou[] = _("Bitte sehr!\nUnd vielen Dank.");
const u8 gText_ThankYouIllSendItHome[] = _("Vielen Dank!\nEs wird auf deinen PC übertragen.");
const u8 gText_ThanksIllSendItHome[] = _("Danke!\nEs wird auf deinen PC übertragen.");
const u8 gText_YouDontHaveMoney[] = _("Du hast nicht genug Geld.{PAUSE_UNTIL_PRESS}");
const u8 gText_YouDontHaveEnoughBP[] = _("Du hast nicht genug\nKP.{PAUSE_UNTIL_PRESS}");
const u8 gText_DontHaveEnoughVar1[] = _("Du hast nicht genug\n{STR_VAR_1}s.{PAUSE_UNTIL_PRESS}");
const u8 gText_Var1SureHowMany[] = _("{STR_VAR_1}s? Sicher.\nWieviele möchtest du?");
const u8 gText_xOne[] = _("x1");
const u8 gText_KurtVar1AndYouWantedVar2Plural[] = _("Du möchtest {STR_VAR_2} davon?\nDas macht {STR_VAR_3} Beeren.");
const u8 gText_KurtVar1AndYouWantedVar2Singular[] = _("Du möchtest {STR_VAR_2} davon?\nDas macht {STR_VAR_3} Beeren.");
const u8 gText_KurtGettingStarted[] = _("KURT: Ich fange sofort an!");
const u8 gText_ExitMenu[] = _("MENÜ VERLASSEN");
const u8 gText_NoMoreRoomForThis[] = _("Du hast keinen Platz für weitere Items.{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("Es ist kein Platz für {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("Gibt es noch etwas, womit\nich dienen kann?");
const u8 gText_CanIHelpWithAnythingElse[] = _("Kann ich dir sonst noch dienlich sein?");
const u8 gText_ThrowInPremierBall[] = _("Ich gebe dir noch einen PREMIERBALL.{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("I'll throw in {STR_VAR_1} PREMIER BALLS, too.{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{STR_VAR_2}? Es tut mir Leid, aber\ndas kann ich nicht kaufen.{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("{STR_VAR_2}?\nWie viele möchtest du verkaufen?");
const u8 gText_ICanPayVar1[] = _("Ich gebe dir ¥{STR_VAR_1}.\nBist du damit einverstanden?");
const u8 gText_TurnedOverVar1ForVar2[] = _("{STR_VAR_2} wurde übergeben\nim Tausch gegen ¥{STR_VAR_1}.");
const u8 gText_PokedollarVar1[] = _("¥{STR_VAR_1}");
const u8 gText_HP3[] = _("KP");
const u8 gText_SpAtk3[] = _("SP. ANG.");
const u8 gText_SpDef3[] = _("SP. VER.");
const u8 gText_WontHaveEffect[] = _("Es wird keine Wirkung haben.{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("Choose {PKMN} to fuse with.");
const u8 gText_CantBeUsedOnPkmn[] = _("Das kann nicht bei diesem\nPOKéMON eingesetzt werden.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("{STR_VAR_1} kann nicht ausge-\ntauscht werden!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1}\nkämpft bereits!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1} ist\nbereits ausgewählt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1} kann\nnicht kämpfen!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("Ein POKéMON von {STR_VAR_1} ist\nnicht gegen deins eintauschbar!{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("Ein EI kann nicht kämpfen!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("Das ist erst einsetzbar, wenn\nein neuer ORDEN errungen wurde.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("Es können nicht mehr als\n{STR_VAR_1} POKéMON teilnehmen.{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("Den abgenommenen BRIEF\nauf deinen PC übertragen?");
const u8 gText_MailSentToPC[] = _("Der BRIEF wurde auf deinen\nPC übertragen.{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("Du kannst keine weiteren BRIEFE\nauf deinen PC übertragen.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("Wird der BRIEF entfernt, geht\nder Inhalt verloren, okay?");
const u8 gText_RemoveMailBeforeItem[] = _("Der BRIEF muss entfernt werden,\num ein Item tragen zu können.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("{STR_VAR_1} erhält\n{STR_VAR_2} zum Tragen.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1} trägt bereits\n{STR_VAR_2}.\pSollen die Items ausge-\ntauscht werden?");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1} trägt\nkein Item.{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("{STR_VAR_2} von\n{STR_VAR_1} erhalten.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("Der BRIEF wurde dem\nPOKéMON abgenommen.{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("{STR_VAR_2} wurde gegen\n{STR_VAR_1} ausgetauscht.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("Dieses POKéMON trägt ein Item.\nEs kann keinen BRIEF tragen.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("Der BRIEF wurde von deinem\nPC heruntergeladen.{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("Der BEUTEL ist voll. Das Item\ndes PKMN wurde nicht entfernt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{STR_VAR_1} erlernt\n{STR_VAR_2}!");
const u8 gText_PkmnLearnedMove4[] = _("{STR_VAR_1} erlernt\n{STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1} und {STR_VAR_2}\nsind nicht kompatibel.\p{STR_VAR_2} kann nicht \nerlernt werden.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1} versucht,\n{STR_VAR_2} zu erlernen.\pAber {STR_VAR_1} kann maximal\nvier Attacken erlernen.\pSoll eine andere Attacke durch\n{STR_VAR_2} ersetzt werden?");
const u8 gText_StopLearningMove2[] = _("{STR_VAR_2} nicht\nerlernen?");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1} hat {STR_VAR_2}\nnicht erlernt.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("Welche Attacke soll vergessen\nwerden?{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("1, {PAUSE 15}2 und{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1} Schwupp!\p{STR_VAR_1} hat\n{STR_VAR_2} vergessen.\pUnd…{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1} kennt\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("Die KP von {STR_VAR_1} wurden\num {STR_VAR_2} Punkt(e) aufgefüllt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("Die Vergiftung von {STR_VAR_1}\nwurde geheilt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("Die Paralyse von {STR_VAR_1}\nwurde aufgehoben.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1} ist aufgewacht.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("Verbrennung von {STR_VAR_1}\nwurde geheilt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1}'s frostbite was healed.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1} wurde aufgetaut.{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("AP wurden aufgefüllt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1} regained health.{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1} erholte sich.{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("AP von {STR_VAR_1}\nwurden angehoben.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1} erreicht\nLv. {STR_VAR_2}.");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1} gained {STR_VAR_2} Exp. Points!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1} gained {STR_VAR_2} Exp. Points\nand was elevated to Lv. {STR_VAR_3}!");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_2} von\n{STR_VAR_1} wurde angehoben.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1} wird zahm.\nDer Grundwert {STR_VAR_2} sinkt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1} vergöttert dich!\nDer Grundwert {STR_VAR_2} sinkt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1} wird zahm. Grund-\nwert {STR_VAR_2} sinkt nicht mehr.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1} ist nicht\nmehr verwirrt.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1} fühlt sich nicht\nmehr angezogen.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1} transformed!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("{STR_VAR_1}\nwegwerfen?");
const u8 gText_ItemThrownAway[] = _("{STR_VAR_1}\nwurde weggeworfen.{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("Teach which POKéMON?"); // Unused
const u8 gText_ChoosePokemon[] = _("Wähle ein POKéMON.");
const u8 gText_MoveToWhere[] = _("An wessen Stelle setzen?");
const u8 gText_TeachWhichPokemon[] = _("Welches POKéMON lehren?");
const u8 gText_UseOnWhichPokemon[] = _("Welches POKéMON?");
const u8 gText_GiveToWhichPokemon[] = _("Welchem POKéMON geben?");
const u8 gText_DoWhatWithPokemon[] = _("Was tun mit {STR_VAR_1}?");
const u8 gText_NothingToCut[] = _("Hier nicht einsetzbar.");
const u8 gText_CantSurfHere[] = _("SURFER nicht einsetzbar.");
const u8 gText_AlreadySurfing[] = _("SURFER ist eingesetzt.");
const u8 gText_CantUseHere[] = _("Hier nicht einsetzbar.");
const u8 gText_RestoreWhichMove[] = _("Welche Att. auffüllen?");
const u8 gText_BoostPp[] = _("AP welcher Att. heben?");
const u8 gText_DoWhatWithItem[] = _("Was willst du mit dem Item?");
const u8 gText_NoPokemonForBattle[] = _("Kein POKéMON kampfbereit!");
const u8 gText_ChoosePokemon2[] = _("Wähle ein POKéMON.");
const u8 gText_NotEnoughHp[] = _("Nicht genügend KP…");
const u8 gText_PokemonAreNeeded[] = _("{STR_VAR_1} POKéMON sind nötig.");
const u8 gText_PokemonCantBeSame[] = _("Nicht dieselben POKéMON!");
const u8 gText_NoIdenticalHoldItems[] = _("Nicht dieselben Items!");
const u8 gText_CurrentIsTooFast[] = _("Die Strömung ist zu stark!");
const u8 gText_DoWhatWithMail[] = _("Was ist mit dem BRIEF?");
const u8 gText_ChoosePokemonCancel[] = _("Wähle PKMN oder ZURÜCK.");
const u8 gText_ChoosePokemonConfirm[] = _("Wähle ein PKMN und bestätige.");
const u8 gText_SendWhichMonToPC[] = _("Welches POKéMON zum PC senden?");
const u8 gText_MoveItemWhere[] = _("Item wohin bewegen?");
const u8 gText_XsYAnd[] = _("{STR_VAR_1}'s {STR_VAR_2} und\n");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_1}'s {STR_VAR_2} wurden getauscht!{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("Lass uns Rad fahren!");
const u8 gText_InUseAlready_PM[] = _("Das wird bereits benutzt.");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1} trägt bereits\n{STR_VAR_2}.");
const u8 gText_WhichAppliance[] = _("Order which\nappliance?");
const u8 gText_NoUse[] = _("Unnütz!");
const u8 gText_Able[] = _("O.K.");
const u8 gText_First_PM[] = _("ERSTES");
const u8 gText_Second_PM[] = _("ZWEITES");
const u8 gText_Third_PM[] = _("DRITTES");
const u8 gText_Able2[] = _("O.K.");
const u8 gText_NotAble[] = _("NEIN");
const u8 gText_Able3[] = _("O.K.");
const u8 gText_NotAble2[] = _("NEIN");
const u8 gText_Learned[] = _("KENNT ATT.");
const u8 gText_Have[] = _("HABEN");
const u8 gText_DontHave[] = _("NIX HABEN");
const u8 gText_Fourth[] = _("VIERTES");
const u8 gText_PkmnCantParticipate[] = _("Dieses PKMN kann nicht teilnehmen.{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("Teilnahme absagen?");
const u8 gText_CancelBattle[] = _("Kampf absagen?");
const u8 gText_ReturnToWaitingRoom[] = _("Zurück ins WARTEZIMMER?");
const u8 gText_CancelChallenge[] = _("Herausforderung widerrufen?");
const u8 gText_EscapeFromHere[] = _("Von hier fliehen und nach\n{STR_VAR_1} zurückkehren?");
const u8 gText_ReturnToHealingSpot[] = _("Zum heilenden Ort in {STR_VAR_1}\nzurückkehren?");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{STR_VAR_1}を ぐるぐるこうかんに\nだして よろしいですか？");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("Das ist das einzige\nPOKéMON zum Kampf.");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("Dieses POKéMON kann jetzt\nnicht getauscht werden.");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("That POKéMON can't be traded.");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("EI jetzt nicht tauschbar.");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("PKMN des anderen TRAINERs kann\njetzt nicht getauscht werden.");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("Der andere TRAINER kann das\nPKMN jetzt nicht akzeptieren.");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("Du kannst mit diesem TRAINER\njetzt keine PKMN tauschen.");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("Diese Art von POKéMON möchte\nder andere TRAINER nicht.");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("Dies ist kein EI!");
const u8 gText_Register[] = _("WÄHLEN");
const u8 gText_Attack3[] = _("ANGRIFF");
const u8 gText_Defense3[] = _("VERT.");
const u8 gText_SpAtk4[] = _("SP.ANG.");
const u8 gText_SpDef4[] = _("SP.VER.");
const u8 gText_Speed2[] = _("INIT.");
const u8 gText_HP4[] = _("KP");
const u8 gText_EmptyString8[] = _(""); // Unused
const u8 gText_OTSlash[] = _("OT:");
const u8 gText_RentalPkmn[] = _("LEIH-POKéMON");
const u8 gText_TypeSlash[] = _("TYP:");
const u8 gText_Power[] = _("STÄRKE");
const u8 gText_Accuracy2[] = _("GENAU.");
const u8 gText_Appeal[] = _("AUSDR.");
const u8 gText_Jam[] = _("EINDR.");
const u8 gText_Status[] = _("STATUS");
const u8 gText_ExpPoints[] = _("E.-PUNKTE");
const u8 gText_NextLv[] = _("NÄCHST. Lv.");
const u8 gText_RibbonsVar1[] = _("BÄNDER: {STR_VAR_1}");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("EVENTS"); // Unused
const u8 gText_Switch[] = _("TAUSCH");
const u8 gText_PkmnInfo[] = _("POKéMON-INFO");
const u8 gText_PkmnSkills[] = _("POKéMON-FÄHIG.");
const u8 gText_BattleMoves[] = _("ATTACKEN");
const u8 gText_ContestMoves[] = _("WETT.-ATTACKEN");
const u8 gText_Info[] = _("INFO");
const u8 gText_EggWillTakeALongTime[] = _("Dieses EI braucht sicher\nnoch sehr viel Zeit.");
const u8 gText_EggWillTakeSomeTime[] = _("Was da wohl schlüpfen wird?\nEs wird sicher lange dauern.");
const u8 gText_EggWillHatchSoon[] = _("Bewegungen… Da wird\nwohl bald etwas schlüpfen.");
const u8 gText_EggAboutToHatch[] = _("Geräusche! Da schlüpft\nsicher bald etwas!");
const u8 gText_EggReadyToHatch_Nuzlocke[] = _("Würde schlüpfen, aber\nvon Nuzlocke blockiert!");
const u8 gText_HMMovesCantBeForgotten2[] = _("VM-Attacken können jetzt\nnicht vergessen werden.");
const u8 gText_XNatureMetAtYZ[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\n{LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedAtYZ[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\ngeschlüpft mit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureObtainedInTrade[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nin einem Tausch erhalten.");
const u8 gText_XNatureFatefulEncounter[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nin schicksalhafter Begeg-\nnung mit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1} erhalten.");
const u8 gText_XNatureProbablyMetAt[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}, gefangen\nvermutlich mit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNature[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}");
const u8 gText_XNatureMetSomewhereAt[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nirgendwo getroffen\nmit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedSomewhereAt[] = _("Wesen: {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}, irgendwo\ngeschlüpft mit {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_OddEggFoundByCouple[] = _("Seltsames POKéMON-EI, das\ndie PENSIONSLEITUNG fand.");
const u8 gText_PeculiarEggNicePlace[] = _("Kurioses POKéMON-EI, an\nhübschem Ort erhalten.");
const u8 gText_PeculiarEggTrade[] = _("Kurioses POKéMON-EI, im\nTausch erhalten.");
const u8 gText_EggFromHotSprings[] = _("Ein POKéMON-EI, an den\nHeißen Quellen erhalten.");
const u8 gText_EggFromTraveler[] = _("Ein seltsames POKéMON-EI\nvon einem Reisenden.");
const u8 gText_ApostropheSBase[] = _("BASIS v. {STR_VAR_1}");
const u8 gText_OkayToDeleteFromRegistry[] = _("Soll {STR_VAR_1} aus dem GRUNDBUCH\ngelöscht werden?");
const u8 gText_RegisteredDataDeleted[] = _("Eingetragene Daten wurden gelöscht.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("Es gibt kein GRUNDBUCH.{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("EINTR. LÖSCHEN");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("DEKORIEREN");
const u8 gText_PutAway[] = _("WEGNEHMEN");
const u8 gText_Toss2[] = _("WEGWERFEN");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("Wähle eine Dekoration \nund stelle sie auf.");
const u8 gText_StoreChosenDecorInPC[] = _("Wähle eine Dekoration und \nübertrage sie auf deinen PC.");
const u8 gText_ThrowAwayUnwantedDecors[] = _("Wähle eine Dekoration\nund wirf sie weg.");
const u8 gText_NoDecorations[] = _("Es gibt keine Dekoration.{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("TISCH");
const u8 gText_Chair[] = _("STUHL");
const u8 gText_Plant[] = _("PFLANZE");
const u8 gText_Ornament[] = _("ORNAMENT");
const u8 gText_Mat[] = _("MATTE");
const u8 gText_Poster[] = _("POSTER");
const u8 gText_Doll[] = _("PUPPE");
const u8 gText_Cushion[] = _("KISSEN");
const u8 gText_Gold[] = _("GOLD");
const u8 gText_Silver[] = _("SILBER");
const u8 gText_PlaceItHere[] = _("Hierhin platzieren?");
const u8 gText_CantBePlacedHere[] = _("Kann hier nicht platziert werden.");
const u8 gText_CancelDecorating[] = _("Dekorieren beenden?");
const u8 gText_InUseAlready[] = _("Das wurde bereits platziert.");
const u8 gText_NoMoreDecorations[] = _("Mehr kann nicht dekoriert werden. Es\nist nur Platz für {STR_VAR_1} Dekorationen.");
const u8 gText_NoMoreDecorations2[] = _("Mehr kann nicht dekoriert werden. Es\nist nur Platz für {STR_VAR_1} Dekorationen.");
const u8 gText_MustBePlacedOnDesk[] = _("This can't be placed here.\nIt must be on a DESK, etc."); // Unused
const u8 gText_CantPlaceInRoom[] = _("Die Dekoration kann nicht in deinem\neigenen Zimmer aufgestellt werden.");
const u8 gText_CantThrowAwayInUse[] = _("Diese Dekoration wurde platziert.\nDu kannst sie nicht wegwerfen.");
const u8 gText_DecorationWillBeDiscarded[] = _("{STR_VAR_1} wird weggeworfen.\nEinverstanden?");
const u8 gText_DecorationThrownAway[] = _("Die Dekoration wurde weggeworfen.");
const u8 gText_StopPuttingAwayDecorations[] = _("Wegnehmen von Dekoration beenden?");
const u8 gText_NoDecorationHere[] = _("Hier ist keine Dekoration.");
const u8 gText_ReturnDecorationToPC[] = _("Diese Dekoration auf \nden PC übertragen?");
const u8 gText_DecorationReturnedToPC[] = _("Die Dekoration wurde auf\nden PC übertragen.");
const u8 gText_NoDecorationsInUse[] = _("Es sind keine Dekorationen platziert.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("Es gibt keine Items.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("Hier ist kein BRIEF.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("Was soll mit dem BRIEF von\n{STR_VAR_1} geschehen?");
const u8 gText_MessageWillBeLost[] = _("Der Inhalt geht verloren.\nIst das in Ordnung für dich?");
const u8 gText_BagIsFull[] = _("Der BEUTEL ist voll.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("Der BRIEF, dessen Inhalt gelöscht\nist, wurde im BEUTEL gelagert.{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("VATI");
const u8 gText_Mom[] = _("MUTTI");
const u8 gText_MomHowMuchDeposit[] = _("Wieviel möchtest du\nbei Mutti einzahlen?");
const u8 gText_MomHowMuchWithdraw[] = _("Wieviel möchtest du\nbei Mutti entnehmen?");
const u8 gText_MomMatchCallDesc[] = _("RUHIG & NETT");
const u8 gText_MomMatchCallName[] = _("MUTTI");
const u8 gText_MomMenuCheckSavings[] = _("KONTO");
const u8 gText_MomMenuDeposit[] = _("EINZAHLEN");
const u8 gText_MomMenuWithdraw[] = _("NEHMEN");
const u8 gText_MomMenuToggleSaving[] = _("SPAREN");
const u8 gText_MomMenuExit[] = _("VERLASSEN");
const u8 gText_Info2[] = _("INFO");
const u8 gText_CoolnessContest[] = _("COOL.");
const u8 gText_BeautyContest[] = _("SCHÖN.");
const u8 gText_CutenessContest[] = _("ANMUT");
const u8 gText_SmartnessContest[] = _("KLUG.");
const u8 gText_ToughnessContest[] = _("STÄRKE");
const u8 gText_Decoration2[] = _("DEKORATION");
const u8 gText_PackUp[] = _("EINPACKEN");
const u8 gText_Registry[] = _("REGISTER");
const u8 gText_Information[] = _("INFORMATION");
const u8 gText_Yes[] = _("JA");
const u8 gText_No[] = _("NEIN");
const u8 gText_Lv50[] = _("LV. 50");
const u8 gText_OpenLevel[] = _("OFFENE KÄMPFE");
const u8 gText_RedShard[] = _("PURPURSTÜCK");
const u8 gText_YellowShard[] = _("GELBSTÜCK");
const u8 gText_BlueShard[] = _("INDIGOSTÜCK");
const u8 gText_GreenShard[] = _("GRÜNSTÜCK");
const u8 gText_BattleFrontier[] = _("KAMPFZONE");
const u8 gText_Cool[] = _("COOL.");
const u8 gText_Beauty[] = _("SCHÖN.");
const u8 gText_Cute[] = _("ANMUT");
const u8 gText_Smart[] = _("KLUG.");
const u8 gText_Tough[] = _("STÄRKE");
const u8 gText_Normal[] = _("NORMAL");
const u8 gText_Super[] = _("SUPER");
const u8 gText_Hyper[] = _("HYPER");
const u8 gText_Master[] = _("MASTER");
const u8 gText_Cool2[] = _("COOL.");
const u8 gText_Beauty2[] = _("SCHÖN.");
const u8 gText_Cute2[] = _("ANMUT");
const u8 gText_Smart2[] = _("KLUG.");
const u8 gText_Tough2[] = _("STÄRKE");
const u8 gText_Items[] = _("ITEM");
const u8 gText_Key_Items[] = _("BASIS-ITEM");
const u8 gText_Poke_Balls[] = _("BALL");
const u8 gText_TMs_Hms[] = _("TM/VM");
const u8 gText_Berries2[] = _("BEEREn");
const u8 gText_Medicine[] = _("MEDIZIN");
#if I_COMBINE_BAG_POCKETS == FALSE
const u8 gText_BattleItems[] = _("KAMPFITEMS");
const u8 gText_Treasures[] = _("SCHÄTZE");
#endif
const u8 gText_SomeonesPC[] = _("JEMANDES PC");
const u8 gText_LanettesPC[] = _("BILL'S PC");
const u8 gText_BillsPc[] = _("BILL'S PC");
const u8 gText_PlayersPC[] = _("PC von {PLAYER}");
const u8 gText_HallOfFame[] = _("RUHMESHALLE");
const u8 gText_LogOff[] = _("AUSLOGGEN");
const u8 gText_Challenges[] = _("EINSTELLUNG");
const u8 gText_Opponent[] = _("GEGNER");
const u8 gText_Tourney_Tree[] = _("TURNIERTAFEL");
const u8 gText_ReadyToStart[] = _("BEREIT");
const u8 gText_Single2[] = _("EINZEL");
const u8 gText_Double2[] = _("DOPPEL");
const u8 gText_Multi[] = _("MULTI");
const u8 gText_MultiLink[] = _("MULTI-LINK");
const u8 gText_MenuOptionPokedex[] = _("POKéDEX");
const u8 gText_MenuOptionPokemon[] = _("POKéMON");
const u8 gText_MenuOptionBag[] = _("BEUTEL");
#if IS_HNS
const u8 gText_MenuOptionPokenav[] = _("POKéCOM");
#else
const u8 gText_MenuOptionPokenav[] = _("POKéCOM");
#endif
const u8 gText_Blank[] = _("");
const u8 gText_MenuOptionSave[] = _("SICHERN");
const u8 gText_MenuOptionOption[] = _("OPTION.");
const u8 gText_MenuOptionExit[] = _("BEENDEN");
const u8 gText_SouthernIsland[] = _("INSEL IM SÜDEN");
const u8 gText_BirthIsland[] = _("ENTSTEHUNGSINSEL");
const u8 gText_FarawayIsland[] = _("FERNEILAND");
const u8 gText_NavelRock[] = _("NABELFELS");
const u8 gText_NormalTagMatch[] = _("BASISTEAMKAMPF");
const u8 gText_VarietyTagMatch[] = _("HÜRDENTEAMKAMPF");
const u8 gText_UniqueTagMatch[] = _("UNIKATTEAMKAMPF");
const u8 gText_ExpertTagMatch[] = _("PROFITEAMKAMPF");
const u8 gText_TradeCenter[] = _("HANDELSCENTER");
const u8 gText_Colosseum[] = _("KOLOSSEUM");
const u8 gText_RecordCorner[] = _("STATISTIKTAUSCH");
const u8 gText_BerryCrush3[] = _("BEERENMÜHLE");
const u8 gText_BattleRules[] = _("KAMPFREGELN");
const u8 gText_JudgeMind[] = _("JURY: VERSTAND");
const u8 gText_JudgeSkill[] = _("JURY: GESCHICK");
const u8 gText_JudgeBody[] = _("JURY: KÖRPER");
const u8 gText_BasicRules[] = _("GRUNDREGELN");
const u8 gText_SwapPartners[] = _("TAUSCH: TEAM");
const u8 gText_SwapNumber[] = _("TAUSCH: NR.");
const u8 gText_SwapNotes[] = _("TAUSCH: TIPP");
const u8 gText_BattleBasics[] = _("KAMPFTIPPS");
const u8 gText_PokemonNature[] = _("POKéMON WESEN");
const u8 gText_PokemonMoves[] = _("PKMN ATTACKEN");
const u8 gText_Underpowered[] = _("WESEN&ATTACKEN");
const u8 gText_WhenInDanger[] = _("BEI GEFAHR");
const u8 gText_BattlePokemon[] = _("KAMPFPOKéMON");
const u8 gText_BattleTrainers[] = _("KAMPFTRAINER");
const u8 gText_GoOn[] = _("WEITER");
const u8 gText_Record2[] = _("SICHERN");
const u8 gText_Rest[] = _("AUSRUHEN");
const u8 gText_Retire[] = _("SCHLUSS");
const u8 gText_1F[] = _("EG");
const u8 gText_2F[] = _("1S");
const u8 gText_3F[] = _("2S");
const u8 gText_4F[] = _("3S");
const u8 gText_5F[] = _("4S");
const u8 gText_6F[] = _("5S");
const u8 gText_7F[] = _("6S");
const u8 gText_8F[] = _("7S");
const u8 gText_9F[] = _("8S");
const u8 gText_10F[] = _("9S");
const u8 gText_11F[] = _("10S");
const u8 gText_B1F[] = _("U1S");
const u8 gText_B2F[] = _("U2S");
const u8 gText_B3F[] = _("U3S");
const u8 gText_B4F[] = _("U4S");
const u8 gText_Rooftop[] = _("DACH");
const u8 gText_ElevatorNowOn[] = _("Momentan im");
const u8 gText_BP[] = _("GP");
const u8 gText_RankingHall[] = _("ERGEBNISHALLE");
const u8 gText_ExchangeService[] = _("AUSTAUSCHSERVICE");
const u8 gText_LilycoveCity[] = _("SEEGRASULB CITY");
const u8 gText_SlateportCity[] = _("GRAPHITPORT CITY");
const u8 gText_Exit[] = _("ZURÜCK");
const u8 gText_YourPartysFull[] = _("Dein Team ist voll!");
const u8 gText_InParty[] = _("IM TEAM");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_RED WHITE GREEN}♂{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_GREEN WHITE BLUE}♀{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_RED WHITE GREEN}♂{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_GREEN WHITE BLUE}♀{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("Erstelle dein eigenes Profil!");
const u8 gText_AndMakeYourProfile[] = _("Kombiniere 4 Wörter/Ausdrücke.");
const u8 gText_CombineSixWordsOrPhrases[] = _("Verwende 6 Ausdrücke,");
const u8 gText_AndMakeAMessage[] = _("um einen Satz zu bilden.");
const u8 gText_FindWordsThatDescribeYour[] = _("Finde Worte, die deine momentanen");
const u8 gText_FeelingsRightNow[] = _("Empfindungen beschreiben.");
const u8 gText_WithFourPhrases[] = _("With four phrases,"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("Kombiniere 9 Ausdrücke und");
const u8 gText_AndMakeAMessage2[] = _("erstelle eine Nachricht.");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("Ändere nur 1 Wort/Ausdruck");
const u8 gText_AndImproveTheBardsSong[] = _("und verbessere das BARDEN-Lied.");
const u8 gText_YourProfile[] = _("Dein Profil");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("Dein Gefühl zum Kampfbeginn");
const u8 gText_WhatYouSayIfYouWin[] = _("Dein Ausspruch im Fall des Sieges");
const u8 gText_WhatYouSayIfYouLose[] = _("Dein Ausspruch bei einer Niederl.");
const u8 gText_TheAnswer[] = _("Die Antwort");
const u8 gText_TheMailMessage[] = _("Der Inhalt des BRIEFes");
const u8 gText_TheMailSalutation[] = _("The MAIL salutation"); // Unused
const u8 gText_TheBardsSong2[] = _("Das neue Lied");
const u8 gText_CombineTwoWordsOrPhrases[] = _("Kombiniere 2 Ausdrücke und");
const u8 gText_AndMakeATrendySaying[] = _("schaffe einen hippen Spruch.");
const u8 gText_TheTrendySaying[] = _("Der hippe Spruch");
const u8 gText_IsAsShownOkay[] = _("lautet also so. O.K.?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("Kombiniere 2 Ausdrücke und");
const u8 gText_ToTeachHerAGoodSaying[] = _("bringe ihr einen guten Spruch bei.");
const u8 gText_FindWordsWhichFit[] = _("Finde die passenden Worte");
const u8 gText_TheTrainersImage[] = _("für diesen TRAINER.");
const u8 gText_TheImage[] = _("Darstellung");
const u8 gText_OutOfTheListedChoices[] = _("Wähle eine der vorgegebenen");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("Antworten als Lösung aus");
const u8 gText_AndCreateAQuiz[] = _("und erstelle ein Quiz!");
const u8 gText_PickAWordOrPhraseAnd[] = _("Wähle ein(en) Wort/Ausdruck aus");
const u8 gText_SetTheQuizAnswer[] = _("und lege die Antwort fest.");
const u8 gText_TheAnswerColon[] = _("Die Antwort:");
const u8 gText_TheQuizColon[] = _("The quiz:"); // Unused
const u8 gText_ApprenticePhrase[] = _("Aussage des Lehrlings:");
const u8 gText_QuitEditing[] = _("Das Textverfassen beenden?");
const u8 gText_StopGivingPkmnMail[] = _("POKéMON keinen BRIEF geben?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("Fülle den Fragebogen aus.");
const u8 gText_LetsReplyToTheInterview[] = _("Lass uns das Interview beenden!");
const u8 gText_AllTextBeingEditedWill[] = _("Der gesamte verfasste Text wird");
const u8 gText_BeDeletedThatOkay[] = _("gelöscht. Einverstanden?");
const u8 gText_QuitEditing2[] = _("Quit editing?"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("The edited text will not be saved."); // Unused
const u8 gText_IsThatOkay[] = _("Is that okay?"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("Please enter a phrase or word."); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("The entire text can't be deleted.");
const u8 gText_OnlyOnePhrase[] = _("Nur ein Ausdruck ist änderbar.");
const u8 gText_OriginalSongWillBeUsed[] = _("Das Lied wird wiederhergestellt.");
const u8 gText_ThatsTrendyAlready[] = _("That's trendy already!"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("Kombiniere 2 Wörter/Ausdrücke.");
const u8 gText_QuitGivingInfo[] = _("Quit giving information?"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("Stop giving the POKéMON MAIL?"); // Unused
const u8 gText_CreateAQuiz2[] = _("Create a quiz!"); // Unused
const u8 gText_SetTheAnswer[] = _("Set the answer!"); // Unused
const u8 gText_CancelSelection[] = _("Cancel the selection?"); // Unused
const u8 gText_Profile[] = _("PROFIL");
const u8 gText_AtTheBattlesStart[] = _("Zum Kampfbeginn");
const u8 gText_UponWinningABattle[] = _("Über den Sieg");
const u8 gText_UponLosingABattle[] = _("Über die Niederlage");
const u8 gText_TheBardsSong[] = _("Das BARDEN-Lied");
const u8 gText_WhatsHipAndHappening[] = _("Was ist hip? Was ist top?");
const u8 gText_Interview[] = _("Interview");
const u8 gText_GoodSaying[] = _("Guter Spruch");
const u8 gText_FansQuestion[] = _("Frage eines Fans");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは？"); // Unused
const u8 gText_ApprenticesPhrase[] = _("Worte des Lehrlings");
const u8 gText_Questionnaire[] = _("FRAGEBOGEN");
const u8 gText_YouCannotQuitHere[] = _("Beenden hier nicht möglich.");
const u8 gText_SectionMustBeCompleted[] = _("Abschnitt noch abschließen.");
const u8 gText_F700sQuiz[] = _("Quiz von {DYNAMIC 0}");
const u8 gText_Lady[] = _("Lady");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("Drücke den A-Knopf, nachdem");
const u8 gText_QuestionPressTheAButton[] = _("du die Quizfrage gelesen hast.");
const u8 gText_TheQuizAnswerIs[] = _("Wie lautet die Antwort?");
const u8 gText_LikeToQuitQuiz[] = _("Möchtest du dieses Quiz");
const u8 gText_ChallengeQuestionMark[] = _("beenden?");
const u8 gText_IsThisQuizOK[] = _("Ist dieses Quiz o.k.?");
const u8 gText_CreateAQuiz[] = _("Quiz erstellen!");
const u8 gText_SelectTheAnswer[] = _("Wähle die Antwort!");
const u8 gText_LyricsCantBeDeleted[] = _("Phrasenlöschen ist unmöglich!");
const u8 gText_PokemonLeague[] = _("POKéMON LIGA");
const u8 gText_PokemonCenter[] = _("POKéMON-CENTER");
const u8 gText_Coolness[] = _("Coolness ");
const u8 gText_Beauty3[] = _("Schönheit ");
const u8 gText_Cuteness[] = _("Anmut ");
const u8 gText_Smartness[] = _("Klugheit ");
const u8 gText_Toughness[] = _("Stärke ");
const u8 gText_SaveFailedCheckingBackup[] = _("Speicherfehler! Backup Memory\nwird geprüft. Bitte warten…\n{COLOR RED}“Benötigte Zeit: 1 Minute”");
const u8 gText_BackupMemoryDamaged[] = _("Backup Memory defekt oder interne\nBatterie verbraucht! Weiterspielen\nmöglich, speichern nicht!");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}“Spiel fortsetzen nicht möglich.\nZurück zum Titelbildschirm…”");
const u8 gText_CheckCompleted[] = _("Überprüfung beendet.\nNeuer Speicherversuch erfolgt.\nBitte warten…");
const u8 gText_SaveCompleteGameCannotContinue[] = _("Speichern beendet.\n{COLOR RED}“Spiel fortsetzen nicht möglich.\nZurück zum Titelbildschirm.”");
const u8 gText_SaveCompletePressA[] = _("Speichern beendet.\n{COLOR RED}“Bitte A-Knopf drücken.”");
const u8 gText_Ferry[] = _("FÄHRE");
const u8 gText_SecretBase[] = _("GEHEIMBASIS");
const u8 gText_Hideout[] = _("VERSTECK");
const u8 gText_ResetRTCConfirmCancel[] = _("Echtzeituhr zurücksetzen?\nA: Bestätigen, B: Zurück");
const u8 gText_PresentTime[] = _("Aktuelle Uhrzeit im Spiel");
const u8 gText_PreviousTime[] = _("Vorherige Uhrzeit im Spiel");
const u8 gText_PleaseResetTime[] = _("Bitte die Zeit zurückstellen.");
const u8 gText_ClockHasBeenReset[] = _("Die Uhr wurde zurückgestellt. Daten\nwerden gesichert. Bitte warten…");
const u8 gText_SaveCompleted[] = _("Speichern beendet.");
const u8 gText_SaveFailed[] = _("Speichern fehlgeschlagen.");
const u8 gText_NoSaveFileCantSetTime[] = _("Es existiert kein Speicherstand. Uhr-\nzeit kann nicht eingestellt werden.");
const u8 gText_InGameClockUsable[] = _("Das spielinterne Zeiteingabe-\nSystem ist jetzt verfügbar.");
const u8 gText_Spicy2[] = _("scharf");
const u8 gText_Dry2[] = _("trocken");
const u8 gText_Sweet2[] = _("süß");
const u8 gText_Bitter2[] = _("bitter");
const u8 gText_Sour2[] = _("sauer");
const u8 gText_Single[] = _("EINZEL");
const u8 gText_Double[] = _("DOPPEL");
const u8 gText_Knockout[] = _("KNOCKOUT");
const u8 gText_Mixed[] = _("GEMISCHT");
const u8 gText_First[] = _("ersten Preis");
const u8 gText_Second[] = _("zweiten Preis");
const u8 gText_Third[] = _("dritten Preis");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} wurde besiegt…\p\n");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} überlebt das Gift.\nDas Gift ist verschwunden!\p");
#endif
const u8 gText_PkmnSurvived_FldPsn[] = _("{STR_VAR_1} überlebt das Gift.\nDas Gift ist verschwunden!\p");
const u8 gText_Marco[] = _("MARCO");
const u8 gText_TrainerCardName[] = _("NAME ");
const u8 gText_TrainerCardIDNo[] = _("IDNr.");
const u8 gText_TrainerCardMoney[] = _("GELD");
const u8 gText_PokeDollar[] = _("¥"); // Unused
const u8 gText_TrainerCardPokedex[] = _("POKéDEX");
const u8 gText_EmptyString6[] = _("");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _(" points"); // Unused
const u8 gText_TrainerCardTime[] = _("SPIELZEIT");
const u8 gJPText_BattlePoints[] = _("ゲ-ムポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("TRAINERPASS von {STR_VAR_1}");
const u8 gText_HallOfFameDebut[] = _("ERSTE RUHMESHALLE:");
const u8 gText_LinkBattles[] = _("KÄMPFE via LINK");
const u8 gText_LinkCableBattles[] = _("KÄMPFE GG. FREUND/E");
const u8 gText_WinsLosses[] = _("S.: {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  N.: {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("POKéMON-TAUSCH:");
const u8 gText_UnionTradesAndBattles[] = _("KONNEX-TAUSCHE & -KÄMP.:");
const u8 gText_BerryCrush[] = _("BEERENMÜHLE:");
const u8 gText_WaitingTrainerFinishReading[] = _("Der andere TRAINER hat deinen\nTRAINERPASS noch nicht gelesen.");
const u8 gText_PokeblocksWithFriends[] = _("{POKEBLOCK} MIT FREUND/EN:");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("GEW. WETTBEWERBE M. FREUND/EN:");
const u8 gText_BattlePtsWon[] = _("ERHALTENE GEWINNPUNKTE:");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}GP");
const u8 gText_BattleTower[] = _("DUELLTURM");
const u8 gText_WinsStraight[] = _("S.:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} IN FOLGE:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("DUELLTURM");
const u8 gText_BattleDome[] = _("KAMPFSTADION");
const u8 gText_BattlePalace[] = _("KAMPFPALAST");
const u8 gText_BattleFactory[] = _("KAMPFFABRIK");
const u8 gText_BattleArena[] = _("KAMPFRING");
const u8 gText_BattlePike[] = _("KAMPFIPITIS");
const u8 gText_BattlePyramid[] = _("KAMPFPYRAMIDE");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} EINZEL");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} DOPPEL");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} MULTI");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} LINK");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("Geben");
const u8 gText_NoNeed[] = _("Nein");
const u8 gText_AnnouncingResults[] = _("Bekanntgabe der Ergebnisse!");
const u8 gText_PreliminaryResults[] = _("Ergebnisse 1. Durchlauf!");
const u8 gText_Round2Results[] = _("Ergebnisse 2. Durchlauf!");
const u8 gText_ContestantsMonWon[] = _("Sieger ist: {STR_VAR_2} von {STR_VAR_1}!");
const u8 gText_CommunicationStandby[] = _("Verbindung…");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{COLOR_HIGHLIGHT_SHADOW DYNAMIC_COLOR6 WHITE DYNAMIC_COLOR5}"); // Unused
const u8 gText_HealthboxNickname[] = _("{HIGHLIGHT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("GROSS");
const u8 gText_Lower[] = _("klein");
const u8 gText_Others[] = _("OTHERS");
const u8 gText_Symbols[] = _("SYMBOLE");
const u8 gText_Register2[] = _("WÄHLEN");
const u8 gText_Exit2[] = _("BEENDEN");
const u8 gText_QuitChatting[] = _("Chat beenden?");
const u8 gText_RegisterTextWhere[] = _("Wo in Liste schreiben?");
const u8 gText_RegisterTextHere[] = _("Hier in Liste schreiben?");
const u8 gText_InputText[] = _("Text schreiben.");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0} ist im Chat!");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0} verließ den Chat.");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("Chat wird verlassen…");
const u8 gText_LeaderLeftEndingChat[] = _("LEITER {DYNAMIC 0} verlässt und\nbeendet somit den Chat.");
const u8 gText_RegisteredTextChangedOKToSave[] = _("Der Text in der Liste wurde geändert.\nSoll gespeichert werden?");
const u8 gText_AlreadySavedFile_Chat[] = _("Es gibt bereits einen Spielstand.\nSpielstand überschreiben?");
const u8 gText_SavingDontTurnOff_Chat[] = _("SPEICHERVORGANG…\nGERÄT NICHT AUSSCHALTEN!");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0} hat das Spiel gespeichert.");
const u8 gText_IfLeaderLeavesChatEnds[] = _("Falls der Leiter den Chat\nverlässt, ist er vorüber, O.K.?");
const u8 gText_Hello[] = _("HALLO");
const u8 gText_Pokemon2[] = _("POKéMON");
const u8 gText_Trade[] = _("TAUSCH");
const u8 gText_Battle[] = _("KAMPF");
const u8 gText_Lets[] = _("AUF");
const u8 gText_Ok[] = _("O.K.!");
const u8 gText_Sorry[] = _("SORRY");
const u8 gText_YaySmileEmoji[] = _("YO{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("DANKE");
const u8 gText_ByeBye[] = _("TSCHÜSS!");
const u8 gText_HatchedFromEgg[] = _("{STR_VAR_1} schlüpfte aus dem EI!");
const u8 gText_NicknameHatchPrompt[] = _("Möchtest du dem geschlüpften\n{STR_VAR_1} einen Kosenamen geben?");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("Die BEERENMÜHLE starten?\nBitte wähle eine BEERE aus!\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("Bitte warte, bis alle Mitspieler\nBEEREn ausgewählt haben.");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}Du hast {STR_VAR_1} Einheiten seiden-\nweichen BEERENPUDER erhalten.{RESUME_MUSIC}\pDein Bestand an BEERENPUDER ist\n{STR_VAR_2} Einheiten.\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("Das Resultat wird gespeichert.\nBitte warten!");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("Möchtest du erneut die\nBEERENMÜHLE betreiben?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("Du hast keine BEEREN!\nDas Spiel wird abgebrochen.");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("Ein Mitspieler hat abgebrochen.\nDas Spiel wird beendet.");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("Die Zeit ist abgelaufen!\pEs konnte kein guter BEERENPUDER\nhergestellt werden…\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("Verbindung…");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _("-mal");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("{STR_VAR_1}BEERE");
ALIGNED(4) const u8 gText_TimeColon[] = _("Zeit:");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("Mahltempo:");
ALIGNED(4) const u8 gText_Silkiness[] = _("Feinheit:");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _("MIN. ");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _("SEK.");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _("-mal/SEK.");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1} %");
ALIGNED(4) const u8 gText_PressesRankings[] = _("Platz nach Druckvorgängen");
ALIGNED(4) const u8 gText_CrushingResults[] = _("Mahlresultat");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("Beschaffenheits-Platzierung");
ALIGNED(4) const u8 gText_CoopRankings[] = _("Kooperations-Platzierung");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("Druckkraft-Platzierung");
const u8 gText_BerryCrush2[] = _("BEERENMÜHLE");
const u8 gText_PressingSpeedRankings[] = _("Drucktempo-Platzierung");
const u8 gText_Var1Players[] = _("{STR_VAR_1} SPIELER");
const u8 gText_SymbolsEarned[] = _("Gew. Symbole");
const u8 gText_BattleRecord[] = _("Video");
const u8 gText_BattlePoints[] = _("Gewinnpunkte");
const u8 gText_UnusedCancel[] = _("CANCEL"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("KAMPFZONENKARTE ansehen");
const u8 gText_CheckTrainerCard[] = _("TRAINERPASS ansehen");
const u8 gText_ViewRecordedBattle[] = _("Kampfaufzeichnung ansehen");
const u8 gText_PutAwayFrontierPass[] = _("KAMPFZONENPASS wegstecken");
const u8 gText_CurrentBattlePoints[] = _("Aktuelle Anzahl der Gewinnpunkte");
const u8 gText_CollectedSymbols[] = _("Die erhaltenen Symbole");
const u8 gText_BattleTowerAbilitySymbol[] = _("Duellturm - Anlagesymbol");
const u8 gText_BattleDomeTacticsSymbol[] = _("Kampfstadion - Taktiksymbol");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("Kampfpalast - Seelensymbol");
const u8 gText_BattleArenaGutsSymbol[] = _("Kampfring - Grobsymbol");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("Kampffabrik - Kenntnissymbol");
const u8 gText_BattlePikeLuckSymbol[] = _("Kampfipitis - Lossymbol");
const u8 gText_BattlePyramidBraveSymbol[] = _("Kampfpyramide - Bravursymbol");
const u8 gText_ThereIsNoBattleRecord[] = _("Es gibt keine Kampfaufzeichnung.");
const u8 gText_BattleTower3[] = _("DUELLTURM");
const u8 gText_BattleDome2[] = _("KAMPFSTADION");
const u8 gText_BattlePalace2[] = _("KAMPFPALAST");
const u8 gText_BattleArena2[] = _("KAMPFRING");
const u8 gText_BattleFactory2[] = _("KAMPFFABRIK");
const u8 gText_BattlePike2[] = _("KAMPFIPITIS");
const u8 gText_BattlePyramid2[] = _("KAMPFPYRAMIDE");
const u8 gText_BattleTowerDesc[] = _("Kämpfe, bis du die Spitze erreichst!\nDeine Anlagen werden geprüft.");
const u8 gText_BattleDomeDesc[] = _("Gewinne das Turnier!\nDeine Taktik wird geprüft.");
const u8 gText_BattlePalaceDesc[] = _("Achte auf deine POKéMON!\nDeine Seele wird geprüft.");
const u8 gText_BattleArenaDesc[] = _("Gewinne im Team!\nDeine Grobheit wird geprüft.");
const u8 gText_BattleFactoryDesc[] = _("Gewinne mit Leih-POKéMON!\nDeine Kenntnisse werden geprüft.");
const u8 gText_BattlePikeDesc[] = _("Wähle einen der drei Pfade aus!\nDein Los wird geprüft.");
const u8 gText_BattlePyramidDesc[] = _("Forsche dich ganz nach oben!\nDeine Bravur wird geprüft.");
const u8 gText_Powder[] = _("PUDER");
const u8 gText_BerryPickingRecords[] = _("REKORDE für BEERENERNTE mit DODRI");
const u8 gText_BerriesPicked[] = _("Geerntete BEEREn:");
const u8 gText_BestScore[] = _("Höchstpunktzahl:");
const u8 gText_BerriesInRowFivePlayers[] = _("Geerntete BEEREn in Folge bei\nfünf Spielern:");
const u8 gText_BerryPickingResults[] = _("Resultat der BEERENERNTE!");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 0x03}10Pkt.{CLEAR_TO 0x2B}30Pkt.{CLEAR_TO 0x53}50Pkt.{CLEAR_TO 0x77}{EMOJI_MINUS}50Pkt.");
const u8 gText_AnnouncingRankings[] = _("Die Platzierungen!");
const u8 gText_AnnouncingPrizes[] = _("Die Preise!");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("Der Erstplatzierte erhält:\n{DYNAMIC 0}!");
const u8 gText_CantHoldAnyMore[] = _("Mehr tragen unmöglich.");
const u8 gText_FilledStorageSpace[] = _("Der Lagerplatz wurde aufgebraucht.");
const u8 gText_WantToPlayAgain[] = _("Erneut spielen?");
const u8 gText_SomeoneDroppedOut[] = _("Irgendjemand hat abgebrochen!\nVerbindung wird abgebrochen!");
const u8 gText_SpacePoints[] = _(" Punkte");
const u8 gText_CommunicationStandby3[] = _("Verbindung…");
const u8 gText_SpacePoints2[] = _(" Punkte");
const u8 gText_SpaceTimes3[] = _("-mal");
const u8 gText_PkmnJumpRecords[] = _("REKORDE für POKéMON-SPRUNG");
const u8 gText_JumpsInARow[] = _("Sprünge in Folge:");
const u8 gText_BestScore2[] = _("Höchstpunktzahl:");
const u8 gText_ExcellentsInARow[] = _("FAMOS in Folge:");
const u8 gText_AwesomeWonF701F700[] = _("Tolle Leistung! Du hast\n{DYNAMIC 1} {DYNAMIC 0} gewonnen!");
const u8 gText_FilledStorageSpace2[] = _("Kein Platz mehr!");
const u8 gText_CantHoldMore[] = _("Mehr tragen unmöglich.");
const u8 gText_WantToPlayAgain2[] = _("Erneut spielen?");
const u8 gText_SomeoneDroppedOut2[] = _("Irgendjemand hat abgebrochen!\nVerbindung wird abgebrochen!");
const u8 gText_CommunicationStandby4[] = _("Verbindung…");
const u8 gText_LinkContestResults[] = _("Linkwettbewerbsergebnis v. {PLAYER}");
const u8 gText_1st[] = _("1. ");
const u8 gText_2nd[] = _("2. ");
const u8 gText_3rd[] = _("3. ");
const u8 gText_4th[] = _("4. ");
const u8 gText_Friend[] = _("Friend");
const u8 gText_Pokemon3[] = _("POKeMON"); // Unused
const u8 gJPText_MysteryGift[] = _("ふしぎなもらいもの");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}けってい {B_BUTTON}やめる");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("カードeリーダー{PLUS}　で\nふしぎなもらいものを　よみこみます");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の　メニューから\n‘つうしん'を　えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("‘ゲームボーイアドバンスとつうしん'\nを　せんたく　してください");
const u8 gJPText_SelectConnectAndPressA[] = _("カードeリーダー{PLUS}の　‘つうしん'を\nえらんで　Aボタンを　おしてください"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("せつぞくが　まちがっています");
const u8 gJPText_CardReadingHasBeenHalted[] = _("カードの　よみこみを\nちゅうし　しました");
const u8 gJPText_UnableConnectWithEReader[] = _("カードeリーダー{PLUS}と\nつうしん　できません"); // Unused
const u8 gJPText_Connecting[] = _("つうしん　ちゅう　です");
const u8 gJPText_ConnectionErrorCheckLink[] = _("つうしん　エラーです\nせつぞくを　たしかめて　ください");
const u8 gJPText_ConnectionErrorTryAgain[] = _("つうしん　エラーです\nはじめから　やりなおして　ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS}　に\nカードを　よみこませて　ください");
const u8 gJPText_ConnectionComplete[] = _("つうしん　しゅうりょう！");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな　トレーナーが\nホウエンに　やってきた！");
const u8 gJPText_PleaseWaitAMoment[] = _("しばらく　おまちください");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ　エラー　です\nデータが　ほぞん　できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("Einzelkampfraumergebnis von {PLAYER}");
const u8 gText_DoubleBattleRoomResults[] = _("Doppelkampfraumergebnis von {PLAYER}");
const u8 gText_MultiBattleRoomResults[] = _("Multikampfraumergebnis von {PLAYER}");
const u8 gText_LinkMultiBattleRoomResults[] = _("Linkmultikampfraumergebnis von {PLAYER}");
const u8 gText_SingleBattleTourneyResults[] = _("Einzelturnierkampfergebnis von {PLAYER}");
const u8 gText_DoubleBattleTourneyResults[] = _("Doppelturnierkampfergebnis von {PLAYER}");
const u8 gText_SingleBattleHallResults[] = _("Einzelaufsichtshallenergebnis v. {PLAYER}");
const u8 gText_DoubleBattleHallResults[] = _("Doppelaufsichtshallenergebnis v. {PLAYER}");
const u8 gText_BattleChoiceResults[] = _("Kampfbahnergebnis von {PLAYER}");
const u8 gText_SetKOTourneyResults[] = _("K.O.-Teamturnierergebnis von {PLAYER}");
const u8 gText_BattleSwapSingleResults[] = _("Wechselkampfeinzelergebnis von {PLAYER}");
const u8 gText_BattleSwapDoubleResults[] = _("Wechselkampfdoppelergebnis von {PLAYER}");
const u8 gText_BattleQuestResults[] = _("Kampfforschungsergebnis von {PLAYER}");
const u8 gText_Lv502[] = _("LV. 50");
const u8 gText_OpenLv[] = _("FREIES LV.");
const u8 gText_WinStreak[] = _("Siegesserie: {STR_VAR_1}");
const u8 gText_Current[] = _("MOMENT.");
const u8 gText_Record[] = _("REKORD");
const u8 gText_Prev[] = _("VORHER");
const u8 gText_RentalSwap[] = _("Leih/Wechsel");
const u8 gText_Total[] = _("Gesamt");
const u8 gText_ClearStreak[] = _("Erfolgsserie: {STR_VAR_1}");
const u8 gText_Championships[] = _("Gesamtgewinne: {STR_VAR_1}");
const u8 gText_RoomsCleared[] = _("Absolv. Räume: {STR_VAR_1}");
const u8 gText_TimesCleared[] = _("Erf. Teilnahmen: {STR_VAR_1}");
const u8 gText_KOsInARow[] = _("K.O.-Serie: {STR_VAR_1}");
const u8 gText_TimesVar1[] = _("Anzahl: {STR_VAR_1}");
const u8 gText_FloorsCleared[] = _("Abs. Eb.: {STR_VAR_1}");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("LV. 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("OFFENE KÄMPFE");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("Siegesserie: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("Erfolgsserie: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("Absolv. Räume: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("K.O.-Serie: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("Abs. Eb.: {STR_VAR_2}");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _(" and {STR_VAR_2} of the POKéMON species\nyou caught are inelegible");
const u8 gText_FrontierFacilityIncluding[] = _(".\pThese include ");
const u8 gText_FrontierFacilityAreInelegible[] = _(" are inelegible");

const u8 gText_YesNo[] = _("JA\nNEIN");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("PRÜFBLICK");
const u8 gText_CommErrorCheckConnections[] = _("Verbindungsfehler…\nÜberprüfe bitte alle Verbindungen\nund schalte das Gerät AUS und wieder EIN.");
const u8 gText_CommErrorEllipsis[] = _("Verbindungsfehler…");
const u8 gText_MoveCloserToLinkPartner[] = _("Verkürze die Distanz zum Mitspieler.\nVermeide Hindernisse zum Mitspieler.");
const u8 gText_ABtnRegistrationCounter[] = _("A-Knopf: Rezeption");
const u8 gText_ABtnTitleScreen[] = _("A-Knopf: Titelbildschirm");
const u8 gText_NumPlayerLink[] = _("{STR_VAR_1}SP-LINK");
const u8 gText_BronzeCard[] = _("BRONZE");
const u8 gText_CopperCard[] = _("KUPFERROT");
const u8 gText_SilverCard[] = _("SILBER");
const u8 gText_GoldCard[] = _("GOLD");
const u8 gText_Day[] = _("TAG");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("O.K.");
const u8 gText_Days[] = _("Tage"); // Unused
const u8 gText_TimeColon2[] = _("ZEIT"); // Unused
const u8 gText_GameTime[] = _("Spielzeit"); // Unused
const u8 gText_RTCTime[] = _("Echtzeituhr"); // Unused
const u8 gText_UpdatedTime[] = _("Aktualisierte Zeit"); // Unused
const u8 gText_MenuPokedex[] = _("POKéDEX");
const u8 gText_MenuPokemon[] = _("POKéMON");
const u8 gText_MenuBag[] = _("BEUTEL");
#if IS_HNS
const u8 gText_MenuPokenav[] = _("{POKE}COM");
#else
const u8 gText_MenuPokenav[] = _("POKéNAV");
#endif
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("SICHERN");
const u8 gText_MenuOption[] = _("OPTION.");
const u8 gText_MenuExit[] = _("BEENDEN");
const u8 gText_MenuRetire[] = _("SCHLUSS");
const u8 gText_MenuRest[] = _("AUSRUHEN");
const u8 gText_MenuDexNav[] = _("DEXNAV");
const u8 gText_SafariBallStock[] = _("SAFARIBÄLLE\nVorrat: {STR_VAR_1}");
const u8 gText_MenuSafariStats[] = _("{STR_VAR_1}/{STR_VAR_2}\nBÄLLE  {STR_VAR_3}");
const u8 gText_BattlePyramidFloor[] = _("Kampfpyramide\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("Erdgeschoss");
const u8 gText_Floor2[] = _("Ebene 2");
const u8 gText_Floor3[] = _("Ebene 3");
const u8 gText_Floor4[] = _("Ebene 4");
const u8 gText_Floor5[] = _("Ebene 5");
const u8 gText_Floor6[] = _("Ebene 6");
const u8 gText_Floor7[] = _("Ebene 7");
const u8 gText_Peak[] = _("Spitze");
const u8 gText_LinkStandby2[] = _("Verbindung…\n… … B-Knopf: Abbrechen");
const u8 gText_PressAToLoadEvent[] = _("Lade Geschehen mit A-Knopf.\n… … B-Knopf: Abbrechen");
const u8 gText_LoadingEvent[] = _("Geschehen wird geladen.");
const u8 gText_DontRemoveCableTurnOff[] = _("Verbindungskabel nicht entfernen!\nDie Geräte nicht ausschalten!");
const u8 gText_EventSafelyLoaded[] = _("Geschehen ist erfolgreich geladen.");
const u8 gText_LoadErrorEndingSession[] = _("Fehler beim Laden!\nVorgang wird abgebrochen.");
const u8 gJPText_Player[] = _("プレイヤー"); // Unused
const u8 gJPText_Sama[] = _("さま"); // Unused
const u8 gText_DexHoenn[] = _("HOENN");
const u8 gText_DexNational[] = _("NATIONALER");
const u8 gText_PokedexDiploma[] = _("Spieler: {CLEAR 0x10}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\n{STR_VAR_1} POKéDEX\nDieses Dokument bescheinigt\ndie erfolgreiche Vervoll-\nständigung des POKéDEX.\n\n{CLEAR_TO 0x42}{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}ゲ-ムフリ-ク"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("HOENN");
const u8 gText_Kanto[] = _("KANTO");
const u8 gText_Johto[] = _("JOHTO");
const u8 gText_JohtoKanto[] = _("JOHTO & KANTO");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_2} wird\n{STR_VAR_1} zugesandt.");
const u8 gText_ByeByeVar1[] = _("Tschüss, {STR_VAR_2}!");
const u8 gText_XSentOverY[] = _("{STR_VAR_1} versandte {STR_VAR_3}.");
const u8 gText_TakeGoodCareOfX[] = _("Kümmere dich gut um {STR_VAR_3}!");

const u8 gText_ThreeQuestionMarks[] = _("???");
const u8 gText_FourQuestionMarks[] = _("????");
const u8 gText_MaxHP[] = _("MAX. KP");
const u8 gText_Attack[] = _("ANGRIFF");
const u8 gText_Defense[] = _("VERT.");
const u8 gText_Speed[] = _("INIT.");
const u8 gText_SpAtk[] = _("SP. ANG.");
const u8 gText_SpDef[] = _("SP. VER.");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("-");
const u8 gText_MixingRecords[] = _("Rekorddaten-Austausch…");
const u8 gText_RecordMixingComplete[] = _("Rekorddaten-Austausch beendet.\nVielen Dank für deine Geduld.");
const u8 gText_RentalPkmn2[] = _("LEIH-POKéMON");
const u8 gText_SelectFirstPkmn[] = _("Wähle das erste POKéMON!");
const u8 gText_SelectSecondPkmn[] = _("Wähle das zweite POKéMON!");
const u8 gText_SelectThirdPkmn[] = _("Wähle das dritte POKéMON!");
const u8 gText_Rent[] = _("VERLEIH");
const u8 gText_Summary[] = _("BERICHT");
const u8 gText_Others2[] = _("ANDERE");
const u8 gText_Deselect[] = _("ENTFERNEN");
const u8 gText_TheseThreePkmnOkay[] = _("Diese drei PKMN auswählen?");
const u8 gText_Yes2[] = _("JA");
const u8 gText_No2[] = _("NEIN");
const u8 gText_CantSelectSamePkmn[] = _("Wahl desselben {PKMN} unmögl.");
const u8 gText_PkmnSwap[] = _("POKéMON-WECHSEL");
const u8 gText_SelectPkmnToSwap[] = _("Wähle das zu wechselnde {PKMN}.");
const u8 gText_SelectPkmnToAccept[] = _("Bestätige das gewählte {PKMN}.");
const u8 gText_Swap[] = _("WECHSEL");
const u8 gText_Summary2[] = _("BERICHT");
const u8 gText_Rechoose[] = _("NEUWAHL");
const u8 gText_QuitSwapping[] = _("Wechseln beenden?");
const u8 gText_Yes3[] = _("JA");
const u8 gText_No3[] = _("NEIN");
const u8 gText_PkmnForSwap[] = _("WECHSELPKMN");
const u8 gText_Cancel3[] = _("ABBRUCH");
const u8 gText_Swap2[] = _("SWAP"); // Unused
const u8 gText_Accept[] = _("ACCEPT"); // Unused
const u8 gText_AcceptThisPkmn[] = _("Dieses {PKMN} annehmen?");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("Selbes {PKMN} bereits im Team.");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("SPIELER");
const u8 gText_SavingBadges[] = _("ORDEN");
const u8 gText_SavingPokedex[] = _("POKéDEX");
const u8 gText_SavingTime[] = _("SPIELZEIT");
const u8 gText_WirelessCommStatus[] = _("Drahtlose Verbindungen:");
const u8 gText_PeopleTrading[] = _("Tauscher:");
const u8 gText_PeopleBattling[] = _("Kämpfer:");
const u8 gText_PeopleInUnionRoom[] = _("Begegnungen im KONNEX-KLUB:");
const u8 gText_PeopleCommunicating[] = _("Eingegangene Verbindungen:");
const u8 gText_F700Players[] = _("{DYNAMIC 0} SPIELER");
const u8 gText_F701Players[] = _("{DYNAMIC 1} SPIELER");
const u8 gText_F702Players[] = _("{DYNAMIC 2} SPIELER");
const u8 gText_F703Players[] = _("{DYNAMIC 3} SPIELER");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("WUNDERKARTEn");
ALIGNED(4) const u8 gText_WonderNews[] = _("WUNDERNEWS");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("DRAHTLOSE VERBINDUNGEN");
ALIGNED(4) const u8 gText_Friend2[] = _("FREUND");
ALIGNED(4) const u8 gText_Exit3[] = _("ZURÜCK");
ALIGNED(4) const u8 gText_Receive[] = _("ERHALTEN");
ALIGNED(4) const u8 gText_Send[] = _("SENDEN");
ALIGNED(4) const u8 gText_Toss[] = _("MÜLL");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("Einige Geschehen werden über die\nDrahtlose Verbindung importiert.");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("Lies die WUNDERKARTEn in\ndeinem Besitz.");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("Lies die NEWS!");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("Zurück zum Titelbildschirm.");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("Du hast keine WUNDERKARTE,\nalso wird eine neue KARTE angelegt.");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("Du hast keine WUNDERNEWS,\nalso werden neue NEWS angelegt.");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("Wo soll auf die WUNDERKARTE\nzugegriffen werden?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("Wo soll auf die WUNDERNEWS\nzugegriffen werden?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("Communication standby…\nB Button: Cancel"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("Übertragung… ");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("Verbindung vollständig.");
ALIGNED(4) const u8 gText_CommunicationError[] = _("Übertragungsfehler.");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("Die Verbindung wurde abgebrochen.");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("Soll die WUNDERKARTE weggeworfen\nund die neue Karte benutzt werden?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("Geschenk dieser Karte noch nicht\nerhalten! Neue Karte benutzen?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("Eine WUNDERKARTE von {STR_VAR_1}\nerhalten.");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("Ein WUNDERNEWS-Item von {STR_VAR_1}\nerhalten.");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("Eine neue WUNDERKARTE erhalten.");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("Ein neues WUNDERNEWS-Item erhalten.");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("Einen neuen STEMPEL erhalten.");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("Ein neuer TRAINER ist eingetroffen.");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("Diese WUNDERKARTE hattest\ndu bereits!");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("Dieses WUNDERNEWS-Item\nhattest du bereits.");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("Diesen STEMPEL hattest\ndu bereits.");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("Es gibt keinen Platz mehr, um\nSTEMPEL hinzuzufügen.");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("Dein Rekord wurde DRAHTLOS\nübertragen.");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("Du kannst von diesem TRAINER\nkeine WUNDERKARTE annehmen.");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("Du kannst von diesem TRAINER\nkeine WUNDERNEWS annehmen.");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("Es wurde nichts übertragen…");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("Was möchtest du mit den\nWUNDERKARTEn anstellen?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("Was möchtest du mit den\nWUNDERNEWS anstellen?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("WUNDERKARTE wird übertragen…");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("WUNDERNEWS werden übertragen…");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("Deine WUNDERKARTE wurde zu\n{STR_VAR_1} übertragen.");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("Deine WUNDERNEWS wurden zu\n{STR_VAR_1} übertragen.");
ALIGNED(4) const u8 gText_StampSentTo[] = _("{STR_VAR_1} erhält einen STEMPEL.");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("{STR_VAR_1} erhält GESCHEHEN.");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("Der andere TRAINER hat diese\nWUNDERKARTE bereits.");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("Der andere TRAINER hat diese\nWUNDERNEWS bereits.");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("Der andere TRAINER hat diesen\nSTEMPEL bereits.");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("Der andere TRAINER hat die\nVerbindung abgebrochen.");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("Du kannst diesem TRAINER kein\nGEHEIMGESCHEHEN übertragen.");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("Wenn du die KARTE weg-\nwirfst, passiert nichts! O.K.?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("Soll dieses NEWS-Item weg-\ngeworfen werden?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("Kein GEHEIMGESCHEHEN!\nTrotzdem wegwerfen?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("Daten werden gesichert.\nBitte warten…");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("Speichern beendet.\nBitte A-Knopf drücken.");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("WUNDERKARTE weggeworfen!");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("WUNDERNEWS weggeworfen!");
ALIGNED(4) const u8 gText_MysteryGift[] = _("GEHEIMGESCHEHEN");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}WAHL {A_BUTTON}O.K. {B_BUTTON}BEENDEN");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}WAHL {A_BUTTON}O.K. {B_BUTTON}ZURÜCK");
const u8 gText_PlayersBattleResults[] = _("KAMPFERGEBNISSE von {PLAYER}");
const u8 gText_TotalRecordWLD[] = _("GESAMT-REKORD S.:{STR_VAR_1} N.:{STR_VAR_2} P.:{STR_VAR_3}");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 0x50}SIEG{CLEAR_TO 0x79}NIEDER.{CLEAR_TO 0xB0}PATT");
const u8 gText_CommunicationStandby5[] = _("Verbindung…");
const u8 gDaycareText_GetAlongVeryWell[] = _("The two seem to get along\nvery well.");
const u8 gDaycareText_GetAlong[] = _("The two seem to get along.");
const u8 gDaycareText_DontLikeOther[] = _("The two don't seem to like\neach other much.");
const u8 gDaycareText_PlayOther[] = _("The two prefer to play with other\nPOKéMON than each other.");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("KEINES");
const u8 gText_Lv[] = _("{LV}");
const u8 gText_TimeBoard[] = _("ZEITTAFEL");
const u8 gText_TimeCleared[] = _("BENÖTIGTE ZEIT ");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1} Min. {STR_VAR_2},{STR_VAR_3} Sek.");
const u8 gText_TrainerHill1F[] = _("EG");
const u8 gText_TrainerHill2F[] = _("1S");
const u8 gText_TrainerHill3F[] = _("2S");
const u8 gText_TrainerHill4F[] = _("3S");
const u8 gText_TeachWhichMoveToPkmn[] = _("{STR_VAR_1} welche Att. beibr.?");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("{STR_VAR_2} beibringen?");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1} lernte\n{STR_VAR_2}.");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1} versucht,\n{STR_VAR_2} zu erlernen.\pAber {STR_VAR_1} kann nicht mehr\nals vier Attacken erlernen.\pSoll eine Attacke zu Gunsten von\n{STR_VAR_2} vergessen werden?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("{STR_VAR_2} nicht erlernen?");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1, {PAUSE 15}2 {PAUSE 15}…{PAUSE 15}…{PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Schwupp!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1} vergaß\n{STR_VAR_3}.\pUnd…\p{STR_VAR_1} lernt {STR_VAR_2}.");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1} did not learn the\nmove {STR_VAR_2}."); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("Soll {STR_VAR_1} keine neue\nAttacke erlernen?");
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("Welche Attacke soll vergessen\nwerden?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("ATTACKEN");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("WETT.-ATTACKEN");
const u8 gText_MoveRelearnerType[] = _("TYPE/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("AP/");
const u8 gText_MoveRelearnerPower[] = _("STÄRKE/");
const u8 gText_MoveRelearnerAccuracy[] = _("GENAU./");
const u8 gText_MoveRelearnerAppeal[] = _("AUSDRUCK");
const u8 gText_MoveRelearnerJam[] = _("EINDRUCK");
const u8 gText_ClearAllSaveData[] = _("Alle gesich. Datenber. löschen?");
const u8 gText_ClearingData[] = _("Daten werden gelöscht…\nBitte warten…");
const u8 gText_IsThisTheCorrectTime[] = _("Ist die Uhrzeit korrekt?");
const u8 gText_Confirm3[] = _("O.K.");
const u8 gText_Cancel4[] = _("ZURÜCK");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("Verbindungsaufbau…\nMitspieler wird erwartet.");
const u8 gText_BattleWasRefused[] = _("Der Kampf wurde abgesagt.{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("Kampfabsage.{PAUSE 60}");
const u8 gText_NoWeather[] = _("WETTERLOS"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("SONNIG"); // Unused
const u8 gText_Sunny2[] = _("SONNIG 2"); // Unused
const u8 gText_Rain[] = _("REGEN"); // Unused
const u8 gText_Snow[] = _("SCHNEE"); // Unused
const u8 gText_Lightning[] = _("GEWITTER"); // Unused
const u8 gText_Fog[] = _("NEBEL"); // Unused
const u8 gText_VolcanoAsh[] = _("VULKANASCHE"); // Unused
const u8 gText_Sandstorm[] = _("SANDSTURM"); // Unused
const u8 gText_Fog2[] = _("NEBEL 2"); // Unused
const u8 gText_Seafloor[] = _("TIEFSEE"); // Unused
const u8 gText_Cloudy[] = _("WOLKIG"); // Unused
const u8 gText_Sunny3[] = _("SONNIG 3"); // Unused
const u8 gText_HeavyRain[] = _("WOLKENBRUCH"); // Unused
const u8 gText_Seafloor2[] = _("TIEFSEE2"); // Unused
const u8 gText_DelAll[] = _("LÖSCHEN");
const u8 gText_Cancel5[] = _("ABBRUCH");
const u8 gText_Ok2[] = _("O.K.");
const u8 gText_Quiz[] = _("QUIZ");
const u8 gText_Answer[] = _("ANTWORT");
const u8 gText_PokeBalls[] = _("POKéBÄLLe");
const u8 gText_Berry[] = _("BEERE");
const u8 gText_Berries[] = _("BEEREn");
const u8 gText_Obtained999RareCandies[] = _("Du hast 999 Sonderbonbons\nerhalten!{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOn[] = _("Der EP-Teiler wurde aktiviert.{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("Der EP-Teiler wurde deaktiviert.{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("GEIST");
const u8 gText_Boulderbadge[] = _("Felsorden");
const u8 gText_Cascadebadge[] = _("Quellorden");
const u8 gText_Thunderbadge[] = _("Donnerorden");
const u8 gText_Rainbowbadge[] = _("Farborden");
const u8 gText_Soulbadge[] = _("Seelenorden");
const u8 gText_Marshbadge[] = _("Sumpforden");
const u8 gText_Volcanobadge[] = _("Vulkanorden");
const u8 gText_Earthbadge[] = _("Erdorden");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("EICH: Es ist wichtig deine\nPOKéMON gut kennenzulernen.\p");
const u8 gText_OakThisIsListOfPokemon[] = _("Dies ist eine Liste deiner POKéMON,\n{PLAYER}.\pÖffne dies um die Attacken und\nFähigkeiten zu sehen.\pDu kannst sie hier auch auswählen\num ihnen ein Item zu geben.{PAUSE_UNTIL_PRESS}");

const u8 gText_GBPlayerOn[] = _("Der GB geht an.\nNostalgie füllt die Luft.{PAUSE_UNTIL_PRESS}");
const u8 gText_GBPlayerOff[] = _("GB ausgeschaltet.{PAUSE_UNTIL_PRESS}");

const u8 gText_Sunday[] = _("SONNTAG");
const u8 gText_Monday[] = _("MONTAG");
const u8 gText_Tuesday[] = _("DIENSTAG");
const u8 gText_Wednesday[] = _("MITTWOCH");
const u8 gText_Thursday[] = _("DONNERSTAG");
const u8 gText_Friday[] = _("FREITAG");
const u8 gText_Saturday[] = _("SAMSTAG");
const u8 gText_LoveBall[] =     _("LIEBE    / PIRSIF  / (FRY/PSY)");
const u8 gText_Lure[] =         _("LOCK    / FRAGIA  / (WTR/DRG)");
const u8 gText_FriendBall[] =   _("FREUND / AMREN  / (KÄF/GRS)");
const u8 gText_Heavy[] =        _("SCHWER   / SINEL   / (GST/BOD/STL)");
const u8 gText_Moon[] =         _("MOND    / MARON / (UNL/GST/GIF)");
const u8 gText_Fast[] =         _("SCHNELL    / WILBI / (ELC/FIG/FEU)");
const u8 gText_LevelBall[] =    _("LEVEL  / PERSIM / (NRM/FLY/EIS)");
const u8 gText_Vermilion[] = _("ORANIA-CITY");
const u8 gText_Olivine[] = _("OLIVIANA-CITY");
const u8 gText_Abra[] = _("ABRA{CLEAR_TO 0x40}120 COINS");
const u8 gText_Clefairy[] = _("PIEPI{CLEAR_TO 0x40}500 COINS");
const u8 gText_Munchlax[] = _("MAMPFAXO{CLEAR_TO 0x40}2,800 COINS");
const u8 gText_Dratini[] = _("DRATINI{CLEAR_TO 0x40}5,500 COINS");
const u8 gText_Porygon[] = _("PORYGON{CLEAR_TO 0x40}6,500 COINS");
const u8 gText_Floor0[] = _("Keller");
const u8 gText_Pal[] = _("Kumpel");
const u8 gText_Underling[] = _("Untergebener");
const u8 gText_Strategy[] = _("Strategie");
const u8 gText_Training[] = _("Training");
const u8 gText_Cheating[] = _("Schummeln");
const u8 gText_WeakPerson[] = _("Schwache Person");
const u8 gText_ToughPerson[] = _("Starke Person");
const u8 gText_Anybody[] = _("Irgendjemand");
const u8 gText_Love2[] = _("Liebe");
const u8 gText_Violence[] = _("Gewalt");
const u8 gText_Knowledge[] = _("Wissen");
const u8 gText_Tough3[] = _("Zäh");
const u8 gText_Weak[] = _("Schwach");
const u8 gText_Both[] = _("Beides");
const u8 gText_GreenStone[] = _("GRÜNER STEIN");
const u8 gText_RedStone[] = _("ROTER STEIN");
const u8 gText_BlueStone[] = _("BLAUER STEIN");
