FiveIsland_House1_Frlg_MapScripts::
	.byte 0

FiveIsland_House1_EventScript_Woman::
	msgbox FiveIsland_House1_Text_HusbandWentOffFishing, MSGBOX_NPC
	end

FiveIsland_House1_Text_HusbandWentOffFishing::
	.string "Du brauchst für das Abendessen\n"
	.string "heute nichts einkaufen!\p"
	.string "… das hat mein Gatte gesagt,\n"
	.string "als er heute zum Angeln ging.\p"
	.string "Ich weiß nicht, ob ich mich auf\n"
	.string "seine große Ankündigung\l"
	.string "verlassen kann.$"

