OneIsland_KindleRoad_Frlg_MapScripts::
	.byte 0

OneIsland_KindleRoad_EventScript_RouteSign::
	msgbox OneIsland_KindleRoad_Text_RouteSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_EventScript_EmberSpaSign::
	msgbox OneIsland_KindleRoad_Text_EmberSpaSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_Text_MariaIntro::
	.string "Das Wetter ist wunderbar!\n"
	.string "Perfekt für einen Kampf!$"

OneIsland_KindleRoad_Text_MariaDefeat::
	.string "Uhhhhhhhhh!$"

OneIsland_KindleRoad_Text_MariaPostBattle::
	.string "Bitte bespritze nicht mein Gesicht!\n"
	.string "Du ruinierst mein Makeup!$"

OneIsland_KindleRoad_Text_AbigailIntro::
	.string "Ich bekomme langsam einen\n"
	.string "Sonnenbrand…$"

OneIsland_KindleRoad_Text_AbigailDefeat::
	.string "Oh, du bist schrecklich!$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
	.string "Ich mag deinen Hut. Vielleicht\n"
	.string "sollte ich auch einen tragen…$"

OneIsland_KindleRoad_Text_FinnIntro::
	.string "Von hier kann man den Glutberg\n"
	.string "in den Himmel ragen sehen.$"

OneIsland_KindleRoad_Text_FinnDefeat::
	.string "Hm, du bist stark, oder?$"

OneIsland_KindleRoad_Text_FinnPostBattle::
	.string "Der Himmel ist hier immens!$"

OneIsland_KindleRoad_Text_GarrettIntro::
	.string "Habe ich beim Schwimmen nur eine\n"
	.string "Pause gemacht, um von dir\l"
	.string "herausgefordert zu werden?$"

OneIsland_KindleRoad_Text_GarrettDefeat::
	.string "Heh, was…\n"
	.string "Du bist wirklich gut!$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
	.string "Anstatt Surfer ständig ein-\n"
	.string "zusetzen, solltest du ein wenig\l"
	.string "schwimmen.$"

OneIsland_KindleRoad_Text_TommyIntro::
	.string "Warte! Warte einen Moment!\n"
	.string "Ich habe einen Großen am Haken!$"

OneIsland_KindleRoad_Text_TommyDefeat::
	.string "Ich habe erneut verloren…$"

OneIsland_KindleRoad_Text_TommyPostBattle::
	.string "Ich habe nicht nur den Kampf,\n"
	.string "sondern auch den Fisch\l"
	.string "verloren!$"

OneIsland_KindleRoad_Text_SharonIntro::
	.string "Könntest du mir beim\n"
	.string "Training aushelfen?$"

OneIsland_KindleRoad_Text_SharonDefeat::
	.string "Du bist mir eine Nummer zu groß!$"

OneIsland_KindleRoad_Text_SharonPostBattle::
	.string "Es ist offensichtlich, dass du\n"
	.string "Talent hast! Ich mag dich!$"

OneIsland_KindleRoad_Text_TanyaIntro::
	.string "Es gibt keinen Tag, an dem\n"
	.string "wir nicht trainieren!$"

OneIsland_KindleRoad_Text_TanyaDefeat::
	.string "Ich bin so doof!$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
	.string "Von jetzt an werde ich noch\n"
	.string "härter trainieren.$"

OneIsland_KindleRoad_Text_SheaIntro::
	.string "Jeden Morgen vorm Frühstück\n"
	.string "schwimme ich um diese Insel.$"

OneIsland_KindleRoad_Text_SheaDefeat::
	.string "Schnauf…\n"
	.string "Schnauf…$"

OneIsland_KindleRoad_Text_SheaPostBattle::
	.string "Ich habe verloren, weil ich\n"
	.string "wegen der Rennerei außer\l"
	.string "Puste war…$"

OneIsland_KindleRoad_Text_HughIntro::
	.string "Kleide dich für einen Kampf!\n"
	.string "Wechsle dieses unwürdige Outfit!$"

OneIsland_KindleRoad_Text_HughDefeat::
	.string "Warum gerade ich?!?$"

OneIsland_KindleRoad_Text_HughPostBattle::
	.string "Sogar Kampfsportler sind heut-\n"
	.string "zutage modebewusst…$"

OneIsland_KindleRoad_Text_BryceIntro::
	.string "Alles schmeckt großartig, wenn\n"
	.string "du in der Natur bist!$"

OneIsland_KindleRoad_Text_BryceDefeat::
	.string "Ugh! Vergeigt!$"

OneIsland_KindleRoad_Text_BrycePostBattle::
	.string "Das Wasser in Gebieten mit\n"
	.string "Vulkanen ist köstlich!$"

OneIsland_KindleRoad_Text_ClaireIntro::
	.string "Mein Mittagessen hat uns gesättigt!\n"
	.string "Kämpfst du gegen uns, damit wir\l"
	.string "ein wenig Bewegung bekommen?$"

OneIsland_KindleRoad_Text_ClaireDefeat::
	.string "Das brachte mich ins Schwitzen!$"

OneIsland_KindleRoad_Text_ClairePostBattle::
	.string "Was soll ich tun?\n"
	.string "Ich sterbe vor Hunger!$"

OneIsland_KindleRoad_Text_KiaIntro::
	.string "Heidi: Mein großer Bruder und ich\n"
	.string "sind ein grandioses Gespann!$"

OneIsland_KindleRoad_Text_KiaDefeat::
	.string "Heidi: Häh!?!\n"
	.string "Ich kann es nicht glauben!$"

OneIsland_KindleRoad_Text_KiaPostBattle::
	.string "Heidi: Wie kann jemand besser\n"
	.string "als mein Bruder sein?$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
	.string "HEIDI: Wenn du gegen uns kämpfen\n"
	.string "möchtest, musst du mindestens\l"
	.string "zwei POKéMON mitbringen!$"

OneIsland_KindleRoad_Text_MikIntro::
	.string "Dirk: An der Seite von Heidi\n"
	.string "habe ich vor nichts Angst!$"

OneIsland_KindleRoad_Text_MikDefeat::
	.string "Dirk: Wow!\n"
	.string "Das ist zu viel!$"

OneIsland_KindleRoad_Text_MikPostBattle::
	.string "Dirk: Wie kann ich an der\n"
	.string "Seite von Heidi verlieren?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
	.string "DIRK: Möchtest du gegen uns beide\n"
	.string "kämpfen?$"

OneIsland_KindleRoad_Text_RouteSign::
	.string "Ich habe ein CHANEIRA gefangen!\p"
	.string "Die Mühe hat sich gelohnt!$"

OneIsland_KindleRoad_Text_EmberSpaSign::
	.string "Wie viele hast du gefangen?\n"
	.string "Ich bin total erschöpft!$"

